// Binary property table generator.
//
// Generates two files in lockstep from PropList.txt,
// DerivedCoreProperties.txt, and emoji/emoji-data.txt:
//
//   unicode/binary_property.pony  — closed-union `BinaryProperty`
//     type, one primitive per UCD binary property, plus the
//     `BinaryProperties` helper (from_iso, byte codecs).
//
//   unicode/_ucd_binary_props.pony — one cp-range table per
//     property, plus a shared range-search helper.
//
// Each property's table is 8 bytes raw (LE U32 lo + LE U32 hi)
// per range record, ASCII-hex-pair encoded like the rest.

primitive BinaryPropsTableEmitter
  fun emit_both(
    proplist_lines: ReadSeq[String val] box,
    dcp_lines: ReadSeq[String val] box,
    emoji_lines: ReadSeq[String val] box)
    : (String iso^, String iso^) ?
  =>
    """
    Parse all three sources, collect distinct property names, and
    return (binary_property_runtime, ucd_binary_props_table).
    """
    let working = recover ref Array[PropertyEntry val] end
    _push_entries(working, proplist_lines)?
    _push_entries(working, dcp_lines)?
    _push_entries(working, emoji_lines)?
    let dest = recover trn Array[PropertyEntry val](working.size()) end
    var k: USize = 0
    while k < working.size() do
      try dest.push(working(k)?) end
      k = k + 1
    end
    let immutable: Array[PropertyEntry val] val = consume dest
    let names = _collect_names(immutable)
    let per_prop = _group_by_property(immutable, names)
    let runtime = _emit_runtime(names)
    let table = _emit_table(names, per_prop)
    (consume runtime, consume table)

  fun _push_entries(
    dest: Array[PropertyEntry val] ref,
    lines: ReadSeq[String val] box) ?
  =>
    for line in lines.values() do
      match PropertyFileParser.parse_line(line)?
      | let e: PropertyEntry val => dest.push(e)
      | None => None
      end
    end

  fun _collect_names(
    entries: ReadSeq[PropertyEntry val] box)
    : Array[String val] val
  =>
    let seen = recover trn Array[String val] end
    for e in entries.values() do
      var found: Bool = false
      for n in seen.values() do
        if n == e.property then found = true; break end
      end
      if not found then seen.push(e.property) end
    end
    // alphabetical sort
    let n = seen.size()
    var i: USize = 1
    while i < n do
      try
        var j = i
        let cur = seen(j)?
        while (j > 0) and (seen(j - 1)? > cur) do
          seen(j)? = seen(j - 1)?
          j = j - 1
        end
        seen(j)? = cur
      end
      i = i + 1
    end
    let out = recover trn Array[String val](seen.size()) end
    for n2 in seen.values() do out.push(n2) end
    consume out

  fun _group_by_property(
    entries: ReadSeq[PropertyEntry val] box,
    names: Array[String val] val)
    : Array[Array[(U32, U32)] val] val
  =>
    """
    For each property in `names`, return its sorted, coalesced
    cp-range list.
    """
    let out = recover trn Array[Array[(U32, U32)] val] end
    for name in names.values() do
      var bucket = recover ref Array[(U32, U32)] end
      for e in entries.values() do
        if e.property == name then
          bucket.push((e.range_lo, e.range_hi))
        end
      end
      _sort_pairs(bucket)
      out.push(_coalesce(bucket))
    end
    consume out

  fun _sort_pairs(buf: Array[(U32, U32)] ref) =>
    let n = buf.size()
    var i: USize = 1
    while i < n do
      try
        var j = i
        let cur = buf(j)?
        while (j > 0) and (buf(j - 1)?._1 > cur._1) do
          buf(j)? = buf(j - 1)?
          j = j - 1
        end
        buf(j)? = cur
      end
      i = i + 1
    end

  fun _coalesce(buf: Array[(U32, U32)] box): Array[(U32, U32)] val =>
    let out = recover trn Array[(U32, U32)] end
    var have: Bool = false
    var cur_lo: U32 = 0
    var cur_hi: U32 = 0
    for r in buf.values() do
      if have and (r._1 == (cur_hi + 1)) then
        cur_hi = r._2
      else
        if have then out.push((cur_lo, cur_hi)) end
        cur_lo = r._1
        cur_hi = r._2
        have = true
      end
    end
    if have then out.push((cur_lo, cur_hi)) end
    consume out

  fun _type_name(name: String val): String val =>
    """
    Convert "ID_Start" → "PropIDStart" (strip underscores; primitives
    can't have underscores in Pony).
    """
    let out = recover trn String(name.size() + 6) end
    out.append("Prop")
    for c in name.values() do
      if c != '_' then out.push(c) end
    end
    consume out

  fun _emit_runtime(names: Array[String val] val): String iso^ =>
    recover iso
      let out = String(32 * 1024)
      out.append("// Auto-generated by unicode-build. Do not edit by hand.\n")
      out.append("// Regenerate via:\n")
      out.append("//   make ucd-generate\n")
      out.append("//\n")
      out.append("// Source: PropList.txt + DerivedCoreProperties.txt +\n")
      out.append("// emoji/emoji-data.txt. The `BinaryProperty` type is a\n")
      out.append("// closed union — exhaustive `match` is compile-checked.\n\n")

      for n in names.values() do
        let tn = _type_name(n)
        out.append("primitive " + tn + "\n")
        out.append("  fun code(): String val => \"" + n + "\"\n")
        out.append("  fun string(): String val => \"" + n + "\"\n\n")
      end

      out.append("type BinaryProperty is\n  ( ")
      var first: Bool = true
      for n in names.values() do
        if first then first = false
        else out.append("\n  | ")
        end
        out.append(_type_name(n))
      end
      out.append("\n  )\n\n")

      out.append("primitive BinaryProperties\n")
      out.append("  fun from_iso(s: String box): (BinaryProperty | None) =>\n")
      out.append("    match s\n")
      for n in names.values() do
        out.append("    | \"" + n + "\" => " + _type_name(n) + "\n")
      end
      out.append("    else None\n")
      out.append("    end\n")
      out
    end

  fun _emit_table(
    names: Array[String val] val,
    per_prop: Array[Array[(U32, U32)] val] val)
    : String iso^
  =>
    recover iso
      let out = String(1024 * 1024)
      out.append("// Auto-generated by unicode-build. Do not edit by hand.\n")
      out.append("// Regenerate via:\n")
      out.append("//   make ucd-generate\n")
      out.append("//\n")
      out.append("// One code-generated nested `match` per binary property\n")
      out.append("// (see `_RangeMatchEmitter` in unicode_build/). Top-level\n")
      out.append("// dispatches on `cp >> 12` (4096-cp bucket — LLVM lowers\n")
      out.append("// this to a switch), inner is an upper-bound chain over\n")
      out.append("// the ranges inside that bucket.\n\n")

      out.append("primitive _UcdBinaryProps\n")
      out.append("  fun has(cp: U32, p: BinaryProperty): Bool =>\n")
      out.append("    match p\n")
      for n in names.values() do
        out.append("    | " + _type_name(n) + " => _p_"
          + _underscore_safe(n) + "(cp)\n")
      end
      out.append("    end\n\n")

      let to_variant: {(U8): String val} val =
        {(b: U8): String val => "true"}
      var idx: USize = 0
      for n in names.values() do
        try
          let ranges = per_prop(idx)?
          out.append("  fun _p_" + _underscore_safe(n)
            + "(cp: U32): Bool =>\n")
          let tagged = _tag_ranges(ranges)
          _RangeMatchEmitter.emit(out, tagged, to_variant, "false")
          out.append("\n")
        end
        idx = idx + 1
      end
      out
    end

  fun _tag_ranges(
    ranges: Array[(U32, U32)] val): Array[(U32, U32, U8)] val
  =>
    """
    `_RangeMatchEmitter.emit` takes (lo, hi, byte) triples — for the
    binary properties there is no per-range byte (presence is the
    answer), so we tag every range with `U8(1)` and let the
    `byte_to_variant` lambda map any byte to the string `"true"`.
    """
    recover val
      let out = Array[(U32, U32, U8)]
      for r in ranges.values() do
        out.push((r._1, r._2, U8(1)))
      end
      out
    end

  fun _underscore_safe(name: String val): String val =>
    """
    Pony function names CAN contain underscores; keep the UCD name's
    underscores as-is for the table getter so different properties
    don't collide (e.g., "ID_Start" vs "IDStart" — both could exist
    in theory; using the original name with underscores is
    unambiguous). Convert to lowercase to avoid PascalCase collisions
    with the primitive names.
    """
    let out = recover trn String(name.size()) end
    for c in name.values() do
      if (c >= 'A') and (c <= 'Z') then out.push(c + 32)
      else out.push(c)
      end
    end
    consume out

  fun _emit_le_u32(out: String ref, value: U32) =>
    _emit_byte(out, U8.from[U32](value and 0xFF))
    _emit_byte(out, U8.from[U32]((value >> 8) and 0xFF))
    _emit_byte(out, U8.from[U32]((value >> 16) and 0xFF))
    _emit_byte(out, U8.from[U32]((value >> 24) and 0xFF))

  fun _emit_byte(out: String ref, b: U8) =>
    let digits = "0123456789ABCDEF"
    try out.push(digits(USize.from[U8](b >> 4))?) end
    try out.push(digits(USize.from[U8](b and 0xF))?) end
