// Simple case-mapping tables.
//
// UnicodeData.txt fields 12/13/14 carry "simple" (single-codepoint to
// single-codepoint) Uppercase / Lowercase / Titlecase mappings. Per
// UAX #44, a codepoint maps to itself if no entry is given.
//
// Three tables, ASCII-hex-pair encoded; only non-identity mappings are
// stored. Record layout (per entry): 8 bytes raw / 16 hex chars
//   chars 0..7   : cp (LE U32)
//   chars 8..15  : mapped cp (LE U32)
//
// `Codepoints.simple_upper(cp)` returns `cp` when no entry exists, so
// the runtime API is identity-preserving — but the table only stores
// the non-trivial mappings, which keeps it ~12KB instead of 1MB+.

primitive CaseTableEmitter
  fun emit_simple_upper(
    entries: ReadSeq[UnicodeDataEntry val] box)
    : String iso^
  =>
    _emit_simple(entries, "_UcdSimpleUpper", "simple_upper",
      "Simple_Uppercase_Mapping")

  fun emit_simple_lower(
    entries: ReadSeq[UnicodeDataEntry val] box)
    : String iso^
  =>
    _emit_simple(entries, "_UcdSimpleLower", "simple_lower",
      "Simple_Lowercase_Mapping")

  fun emit_simple_title(
    entries: ReadSeq[UnicodeDataEntry val] box)
    : String iso^
  =>
    _emit_simple(entries, "_UcdSimpleTitle", "simple_title",
      "Simple_Titlecase_Mapping")

  fun _emit_simple(
    entries: ReadSeq[UnicodeDataEntry val] box,
    primitive_name: String val,
    kind: String val,
    ucd_property: String val)
    : String iso^
  =>
    let pairs = _collect(entries, kind)
    recover iso
      let out = String(32 * 1024)
      out.append("// Auto-generated by unicode-build. Do not edit by hand.\n")
      out.append("// Regenerate via:\n")
      out.append("//   make ucd-generate\n")
      out.append("//\n")
      out.append("// Source: UnicodeData.txt " + ucd_property + ".\n")
      out.append("// Only non-identity mappings are stored.\n\n")

      out.append("primitive " + primitive_name + "\n")
      out.append("  fun of(cp: U32): U32 =>\n")
      out.append("    let t = _table()\n")
      out.append("    var lo: USize = 0\n")
      out.append("    var hi: USize = t.size() / 16\n")
      out.append("    while lo < hi do\n")
      out.append("      let mid = lo + ((hi - lo) / 2)\n")
      out.append("      let base = mid * 16\n")
      out.append("      try\n")
      out.append("        let key: U32 =\n")
      out.append("          _UcdHex.byte(t, base)?\n")
      out.append("            or (_UcdHex.byte(t, base + 2)? << 8)\n")
      out.append("            or (_UcdHex.byte(t, base + 4)? << 16)\n")
      out.append("            or (_UcdHex.byte(t, base + 6)? << 24)\n")
      out.append("        if cp < key then hi = mid\n")
      out.append("        elseif cp > key then lo = mid + 1\n")
      out.append("        else\n")
      out.append("          let mapped: U32 =\n")
      out.append("            _UcdHex.byte(t, base + 8)?\n")
      out.append("              or (_UcdHex.byte(t, base + 10)? << 8)\n")
      out.append("              or (_UcdHex.byte(t, base + 12)? << 16)\n")
      out.append("              or (_UcdHex.byte(t, base + 14)? << 24)\n")
      out.append("          return mapped\n")
      out.append("        end\n")
      out.append("      else return cp\n")
      out.append("      end\n")
      out.append("    end\n")
      out.append("    cp\n\n")

      out.append("  fun _table(): String val =>\n")
      out.append("    \"")
      for p in pairs.values() do
        _emit_le_u32(out, p._1)
        _emit_le_u32(out, p._2)
      end
      out.append("\"\n")
      out
    end

  fun _collect(
    entries: ReadSeq[UnicodeDataEntry val] box,
    kind: String val)
    : Array[(U32, U32)] val
  =>
    let out = recover trn Array[(U32, U32)] end
    for e in entries.values() do
      let mapped: (U32 | None) =
        if kind == "simple_upper" then e.simple_upper
        elseif kind == "simple_lower" then e.simple_lower
        else e.simple_title
        end
      match mapped
      | let m: U32 if m != e.codepoint => out.push((e.codepoint, m))
      | let _: U32 => None
      | None => None
      end
    end
    consume out

  fun _emit_le_u32(out: String ref, value: U32) =>
    _emit_byte(out, U8.from[U32](value and 0xFF))
    _emit_byte(out, U8.from[U32]((value >> 8) and 0xFF))
    _emit_byte(out, U8.from[U32]((value >> 16) and 0xFF))
    _emit_byte(out, U8.from[U32]((value >> 24) and 0xFF))

  fun _emit_byte(out: String ref, b: U8) =>
    let digits = "0123456789ABCDEF"
    try out.push(digits(USize.from[U8](b >> 4))?) end
    try out.push(digits(USize.from[U8](b and 0xF))?) end


primitive SimpleCaseFoldEmitter
  fun emit(pairs: Array[(U32, U32)] val): String iso^ =>
    """
    Emit `_ucd_simple_casefold.pony` — cp → folded cp, defaulting to
    identity. Pairs must be sorted ascending by cp.
    """
    recover iso
      let out = String(64 * 1024)
      out.append("// Auto-generated by unicode-build. Do not edit by hand.\n")
      out.append("// Regenerate via:\n")
      out.append("//   make ucd-generate\n")
      out.append("//\n")
      out.append("// Source: CaseFolding.txt status C + S entries.\n")
      out.append("// Only non-identity mappings are stored.\n\n")

      out.append("primitive _UcdSimpleCaseFold\n")
      out.append("  fun of(cp: U32): U32 =>\n")
      out.append("    let t = _table()\n")
      out.append("    var lo: USize = 0\n")
      out.append("    var hi: USize = t.size() / 16\n")
      out.append("    while lo < hi do\n")
      out.append("      let mid = lo + ((hi - lo) / 2)\n")
      out.append("      let base = mid * 16\n")
      out.append("      try\n")
      out.append("        let key: U32 =\n")
      out.append("          _UcdHex.byte(t, base)?\n")
      out.append("            or (_UcdHex.byte(t, base + 2)? << 8)\n")
      out.append("            or (_UcdHex.byte(t, base + 4)? << 16)\n")
      out.append("            or (_UcdHex.byte(t, base + 6)? << 24)\n")
      out.append("        if cp < key then hi = mid\n")
      out.append("        elseif cp > key then lo = mid + 1\n")
      out.append("        else\n")
      out.append("          let mapped: U32 =\n")
      out.append("            _UcdHex.byte(t, base + 8)?\n")
      out.append("              or (_UcdHex.byte(t, base + 10)? << 8)\n")
      out.append("              or (_UcdHex.byte(t, base + 12)? << 16)\n")
      out.append("              or (_UcdHex.byte(t, base + 14)? << 24)\n")
      out.append("          return mapped\n")
      out.append("        end\n")
      out.append("      else return cp\n")
      out.append("      end\n")
      out.append("    end\n")
      out.append("    cp\n\n")

      out.append("  fun _table(): String val =>\n")
      out.append("    \"")
      for p in pairs.values() do
        CaseTableEmitter._emit_le_u32(out, p._1)
        CaseTableEmitter._emit_le_u32(out, p._2)
      end
      out.append("\"\n")
      out
    end
