// Simple case-mapping tables.
//
// UnicodeData.txt fields 12/13/14 carry "simple" (single-codepoint to
// single-codepoint) Uppercase / Lowercase / Titlecase mappings. Per
// UAX #44, a codepoint maps to itself if no entry is given.
//
// Three tables, all emitted as a two-level `match cp >> 12` dispatch
// (see range_match_emitter.pony for the rationale). The default arm
// returns `cp` so the runtime API remains identity-preserving.

primitive CaseTableEmitter
  fun emit_simple_upper(
    entries: ReadSeq[UnicodeDataEntry val] box)
    : String iso^
  =>
    _emit_simple(entries, "_UcdSimpleUpper", "simple_upper",
      "Simple_Uppercase_Mapping")

  fun emit_simple_lower(
    entries: ReadSeq[UnicodeDataEntry val] box)
    : String iso^
  =>
    _emit_simple(entries, "_UcdSimpleLower", "simple_lower",
      "Simple_Lowercase_Mapping")

  fun emit_simple_title(
    entries: ReadSeq[UnicodeDataEntry val] box)
    : String iso^
  =>
    _emit_simple(entries, "_UcdSimpleTitle", "simple_title",
      "Simple_Titlecase_Mapping")

  fun _emit_simple(
    entries: ReadSeq[UnicodeDataEntry val] box,
    primitive_name: String val,
    kind: String val,
    ucd_property: String val)
    : String iso^
  =>
    let pairs = _collect(entries, kind)
    recover iso
      let out = String(64 * 1024)
      out.append("// Auto-generated by unicode-build. Do not edit by hand.\n")
      out.append("// Regenerate via:\n")
      out.append("//   make ucd-generate\n")
      out.append("//\n")
      out.append("// Source: UnicodeData.txt " + ucd_property + ".\n")
      out.append("// Only non-identity mappings are stored; the default arm\n")
      out.append("// returns `cp` so the runtime API is identity-preserving.\n\n")

      out.append("primitive " + primitive_name + "\n")
      out.append("  fun of(cp: U32): U32 =>\n")
      emit_simple_match(out, pairs)
      out
    end

  fun emit_simple_match(
    out: String ref,
    pairs: Array[(U32, U32)] val)
  =>
    """
    Two-level dispatch for simple cp → cp tables. Top-level
    `match cp >> 12` picks a 4096-cp bucket; inner `match cp` selects
    the exact codepoint and returns its mapped value. The default arm
    at every level returns `cp` (identity).
    """
    out.append("    match cp >> 12\n")
    var prev_bucket: U32 = 0xFFFFFFFF
    var bucket_open: Bool = false
    for p in pairs.values() do
      let bucket = p._1 >> 12
      if bucket != prev_bucket then
        if bucket_open then
          out.append("      else cp\n")
          out.append("      end\n")
        end
        out.append("    | 0x")
        _RangeMatchEmitter.emit_hex_u32(out, bucket)
        out.append(" =>\n")
        out.append("      match cp\n")
        bucket_open = true
        prev_bucket = bucket
      end
      out.append("      | 0x")
      _RangeMatchEmitter.emit_hex_u32(out, p._1)
      out.append(" => 0x")
      _RangeMatchEmitter.emit_hex_u32(out, p._2)
      out.append("\n")
    end
    if bucket_open then
      out.append("      else cp\n")
      out.append("      end\n")
    end
    out.append("    else\n")
    out.append("      cp\n")
    out.append("    end\n")

  fun _collect(
    entries: ReadSeq[UnicodeDataEntry val] box,
    kind: String val)
    : Array[(U32, U32)] val
  =>
    let out = recover trn Array[(U32, U32)] end
    for e in entries.values() do
      let mapped: (U32 | None) =
        if kind == "simple_upper" then e.simple_upper
        elseif kind == "simple_lower" then e.simple_lower
        else e.simple_title
        end
      match mapped
      | let m: U32 if m != e.codepoint => out.push((e.codepoint, m))
      | let _: U32 => None
      | None => None
      end
    end
    consume out


primitive SimpleCaseFoldEmitter
  fun emit(pairs: Array[(U32, U32)] val): String iso^ =>
    """
    Emit `_ucd_simple_casefold.pony` — cp → folded cp, defaulting to
    identity. Pairs must be sorted ascending by cp.
    """
    recover iso
      let out = String(64 * 1024)
      out.append("// Auto-generated by unicode-build. Do not edit by hand.\n")
      out.append("// Regenerate via:\n")
      out.append("//   make ucd-generate\n")
      out.append("//\n")
      out.append("// Source: CaseFolding.txt status C + S entries.\n")
      out.append("// Only non-identity mappings are stored; the default arm\n")
      out.append("// returns `cp` so the runtime API is identity-preserving.\n\n")

      out.append("primitive _UcdSimpleCaseFold\n")
      out.append("  fun of(cp: U32): U32 =>\n")
      CaseTableEmitter.emit_simple_match(out, pairs)
      out
    end
