// General Category table generator.
//
// Layout:
//   The table is a single `String val` literal of ASCII hex pairs —
//   each byte of underlying data is two ASCII hex characters. Each
//   9-byte record (18 ASCII chars) is:
//     chars 0..7   : range_lo (little-endian U32, 8 hex chars = 4 bytes)
//     chars 8..15  : range_hi (little-endian U32, 8 hex chars = 4 bytes)
//     chars 16..17 : category index (2 hex chars = 1 byte)
//
// Why ASCII hex pairs (not `\xNN` escapes, not `Array[U8]` literal):
//
//   * `\xNN` in Pony String literals is a Unicode codepoint escape — values
//     above 0x7F get UTF-8 encoded (e.g., `\x80` becomes the two bytes
//     `0xC2 0x80`). This corrupts a raw-byte table.
//
//   * `Array[U8]` literals create one AST node per element. For a
//     ~3000-entry × 9-byte = 27000-byte table that means ~27000 AST
//     nodes, which sends ponyc into a multi-hour typechecking spin.
//
//   ASCII hex pairs sidestep both problems: the string contains only
//   printable ASCII (no UTF-8 encoding), and it's a single literal
//   (one AST node). Compile is fast; runtime decodes pairs on the fly.
//
// Lookup:
//   Binary search over the implicit record array, with each iteration
//   reading the relevant hex pairs and parsing them. O(log n).

primitive CategoryTableEmitter
  fun emit(entries: ReadSeq[UnicodeDataEntry val] box)
    : (String iso^, String iso^)
  =>
    """
    Generate (pony_source, c_source) for
    `unicode/_ucd_general_category.pony` and its co-located blob.
    """
    let ranges = _coalesce_ranges(entries)
    let header =
      "// Auto-generated by unicode-build. Do not edit by hand.\n"
      + "// Regenerate via:\n"
      + "//   make ucd-generate\n"
      + "//\n"
      + "// Source: UnicodeData.txt General_Category field.\n"
      + "// Codepoints outside any range default to Cn."
    let default_byte = try CategoryCodes.to_byte("Cn") as U8 else U8(29) end
    _TrieEmitter.emit(header, "_UcdCategory", "Category",
      "Categories._from_byte(", ")", "ucd_cat", ranges, default_byte)

  fun _emit_le_u32(out: String ref, value: U32) =>
    _emit_byte(out, U8.from[U32](value and 0xFF))
    _emit_byte(out, U8.from[U32]((value >> 8) and 0xFF))
    _emit_byte(out, U8.from[U32]((value >> 16) and 0xFF))
    _emit_byte(out, U8.from[U32]((value >> 24) and 0xFF))

  fun _emit_byte(out: String ref, b: U8) =>
    """
    Append two ASCII hex digits for `b`. The string literal stays in
    printable ASCII so it sidesteps Pony's UTF-8-encoding `\xNN` rule.
    """
    let digits = "0123456789ABCDEF"
    try out.push(digits(USize.from[U8](b >> 4))?) end
    try out.push(digits(USize.from[U8](b and 0xF))?) end

  fun _coalesce_ranges(
    entries: ReadSeq[UnicodeDataEntry val] box)
    : Array[(U32, U32, U8)] val
  =>
    """
    Collapse consecutive single-codepoint entries with the same category
    into ranges. Multi-codepoint range entries (CJK Ideograph blocks, etc.)
    pass through unchanged. Returns (range_lo, range_hi, category_byte).
    """
    let out = recover trn Array[(U32, U32, U8)] end
    var cur_lo: U32 = 0
    var cur_hi: U32 = 0
    var cur_cat: U8 = 29  // Cn
    var have_cur: Bool = false

    for e in entries.values() do
      if have_cur and (e.codepoint == (cur_hi + 1)) and (e.category == cur_cat)
        and (e.codepoint == e.range_end)
      then
        cur_hi = e.codepoint
      else
        if have_cur then
          out.push((cur_lo, cur_hi, cur_cat))
        end
        cur_lo = e.codepoint
        cur_hi = e.range_end
        cur_cat = e.category
        have_cur = true
      end
    end
    if have_cur then
      out.push((cur_lo, cur_hi, cur_cat))
    end
    consume out
