use "../unicode"

// General Category table generator.
//
// Emits a sorted array of (range_start, range_end, category) entries plus
// a binary-search lookup function. This is the simplest layout that still
// performs well: the table for Unicode 16 is ~3000 ranges, so binary
// search costs ~12 comparisons per lookup with predictable branches.
//
// A more compact two-stage radix layout is in scope for a later
// optimization pass; the API is `_UcdCategory.of(cp)` regardless of
// storage shape, so callers don't see the difference.

primitive CategoryTableEmitter
  fun emit(entries: ReadSeq[UnicodeDataEntry val] box): String iso^ =>
    """
    Generate the contents of `unicode/_ucd_general_category.pony`.
    """
    let ranges = _coalesce_ranges(entries)
    recover iso
      let out = String(64 * 1024)
      out.append("// Auto-generated by unicode-build. Do not edit by hand.\n")
      out.append("// Regenerate via:\n")
      out.append("//   make ucd-generate\n")
      out.append("//\n")
      out.append("// Source: UnicodeData.txt General_Category field.\n")
      out.append("// Format: sorted Array[(U32, U32, Category) val] val —\n")
      out.append("// (range_lo, range_hi inclusive, category). Lookup is binary\n")
      out.append("// search. Codepoints outside any range default to Cn.\n\n")

      out.append("primitive _UcdCategory\n")
      out.append("  fun of(cp: U32): Category =>\n")
      out.append("    let t = _table()\n")
      out.append("    var lo: USize = 0\n")
      out.append("    var hi: USize = t.size()\n")
      out.append("    while lo < hi do\n")
      out.append("      let mid = lo + ((hi - lo) / 2)\n")
      out.append("      try\n")
      out.append("        (let range_lo, let range_hi, let cat) = t(mid)?\n")
      out.append("        if cp < range_lo then\n")
      out.append("          hi = mid\n")
      out.append("        elseif cp > range_hi then\n")
      out.append("          lo = mid + 1\n")
      out.append("        else\n")
      out.append("          return cat\n")
      out.append("        end\n")
      out.append("      else\n")
      out.append("        return Cn\n")
      out.append("      end\n")
      out.append("    end\n")
      out.append("    Cn\n\n")

      out.append("  fun _table(): Array[(U32, U32, Category)] val =>\n")
      out.append("    [as (U32, U32, Category):\n")
      for entry in ranges.values() do
        out.append("      (0x")
        out.append(_hex(entry._1))
        out.append(", 0x")
        out.append(_hex(entry._2))
        out.append(", ")
        out.append(_category_code(entry._3))
        out.append(")\n")
      end
      out.append("    ]\n")

      out
    end

  fun _coalesce_ranges(
    entries: ReadSeq[UnicodeDataEntry val] box)
    : Array[(U32, U32, Category)] val
  =>
    """
    Collapse consecutive single-codepoint entries with the same category
    into ranges. Multi-codepoint range entries (CJK Ideograph blocks, etc.)
    pass through unchanged.
    """
    let out = recover trn Array[(U32, U32, Category)] end
    var cur_lo: U32 = 0
    var cur_hi: U32 = 0
    var cur_cat: Category = Cn
    var have_cur: Bool = false

    for e in entries.values() do
      if have_cur and (e.codepoint == (cur_hi + 1)) and (e.category is cur_cat)
        and (e.codepoint == e.range_end)
      then
        cur_hi = e.codepoint
      else
        if have_cur then
          out.push((cur_lo, cur_hi, cur_cat))
        end
        cur_lo = e.codepoint
        cur_hi = e.range_end
        cur_cat = e.category
        have_cur = true
      end
    end
    if have_cur then
      out.push((cur_lo, cur_hi, cur_cat))
    end
    consume out

  fun _hex(value: U32): String iso^ =>
    """
    Format `value` as uppercase hex (no `0x` prefix, no padding).
    """
    if value == 0 then return "0".clone() end
    let digits = "0123456789ABCDEF"
    var v = value
    let tmp = recover ref Array[U8](8) end
    while v > 0 do
      try tmp.push(digits(USize.from[U32](v and 0xF))?) end
      v = v >> 4
    end
    let out = recover iso String(tmp.size()) end
    var i = tmp.size()
    while i > 0 do
      try out.push(tmp(i - 1)?) end
      i = i - 1
    end
    consume out

  fun _category_code(c: Category): String val =>
    match c
    | Lu => "Lu" | Ll => "Ll" | Lt => "Lt" | Lm => "Lm" | Lo => "Lo"
    | Mn => "Mn" | Mc => "Mc" | Me => "Me"
    | Nd => "Nd" | Nl => "Nl" | No => "No"
    | Pc => "Pc" | Pd => "Pd" | Ps => "Ps" | Pe => "Pe"
    | Pi => "Pi" | Pf => "Pf" | Po => "Po"
    | Sm => "Sm" | Sc => "Sc" | Sk => "Sk" | So => "So"
    | Zs => "Zs" | Zl => "Zl" | Zp => "Zp"
    | Cc => "Cc" | Cf => "Cf" | Cs => "Cs" | Co => "Co" | Cn => "Cn"
    end
