// Composition tables for NFC.
//
// Two outputs, both ASCII-hex-pair encoded (see category_table.pony for the
// encoding rationale):
//
//   _UcdCompositionExclusion : cp → Bool
//     The set of codepoints that, even though they have a canonical
//     decomposition of length 2, must NOT be re-composed during NFC.
//     Derived from DerivedNormalizationProps.txt's
//     Full_Composition_Exclusion property (per UAX #15) — this is the
//     complete set that NFC implementations must honor, not just the
//     "primary" exclusions in CompositionExclusions.txt.
//     Record layout (per entry): 4 bytes raw / 8 hex chars
//       chars 0..7 : cp (LE U32)
//
//   _UcdCanonicalCompose : (lhs: U32, rhs: U32) → (U32 | None)
//     For every codepoint X with canonical decomposition `[L, R]` that
//     is NOT excluded, emit `(L, R) → X`. The composition algorithm in
//     NFC uses this for primary-composite recombination.
//     Record layout (per entry): 12 bytes raw / 24 hex chars
//       chars 0..7   : lhs (LE U32)
//       chars 8..15  : rhs (LE U32)
//       chars 16..23 : result (LE U32)
//     Sorted by (lhs, rhs) for binary search.

primitive CompositionTableEmitter
  fun emit_exclusion(
    derived_norm_props_lines: ReadSeq[String val] box)
    : String iso^ ?
  =>
    """
    Generate `unicode/_ucd_composition_exclusion.pony` from
    DerivedNormalizationProps.txt's Full_Composition_Exclusion entries.
    """
    let entries = _collect_exclusions(derived_norm_props_lines)?
    recover iso
      let out = String(16 * 1024)
      out.append("// Auto-generated by unicode-build. Do not edit by hand.\n")
      out.append("// Regenerate via:\n")
      out.append("//   make ucd-generate\n")
      out.append("//\n")
      out.append("// Source: DerivedNormalizationProps.txt Full_Composition_Exclusion.\n\n")

      out.append("primitive _UcdCompositionExclusion\n")
      out.append("  fun of(cp: U32): Bool =>\n")
      out.append("    let t = _table()\n")
      out.append("    var lo: USize = 0\n")
      out.append("    var hi: USize = t.size() / 8\n")
      out.append("    while lo < hi do\n")
      out.append("      let mid = lo + ((hi - lo) / 2)\n")
      out.append("      let base = mid * 8\n")
      out.append("      try\n")
      out.append("        let key: U32 =\n")
      out.append("          _UcdHex.byte(t, base)?\n")
      out.append("            or (_UcdHex.byte(t, base + 2)? << 8)\n")
      out.append("            or (_UcdHex.byte(t, base + 4)? << 16)\n")
      out.append("            or (_UcdHex.byte(t, base + 6)? << 24)\n")
      out.append("        if cp < key then hi = mid\n")
      out.append("        elseif cp > key then lo = mid + 1\n")
      out.append("        else return true\n")
      out.append("        end\n")
      out.append("      else return false\n")
      out.append("      end\n")
      out.append("    end\n")
      out.append("    false\n\n")

      out.append("  fun _table(): String val =>\n")
      out.append("    \"")
      for cp in entries.values() do
        _emit_le_u32(out, cp)
      end
      out.append("\"\n")
      out
    end

  fun emit_canonical_compose(
    entries: ReadSeq[UnicodeDataEntry val] box,
    derived_norm_props_lines: ReadSeq[String val] box)
    : String iso^ ?
  =>
    """
    Generate `unicode/_ucd_canonical_compose.pony` by inverting canonical
    decomposition (entries with 2-cp decomp not in the exclusion set).
    """
    let exclusion_set = _collect_exclusions(derived_norm_props_lines)?
    let compose_entries = _collect_canonical_composes(entries, exclusion_set)
    recover iso
      let out = String(64 * 1024)
      out.append("// Auto-generated by unicode-build. Do not edit by hand.\n")
      out.append("// Regenerate via:\n")
      out.append("//   make ucd-generate\n")
      out.append("//\n")
      out.append("// Source: UnicodeData.txt canonical decompositions, inverted,\n")
      out.append("// with Full_Composition_Exclusion entries removed.\n\n")

      out.append("primitive _UcdCanonicalCompose\n")
      out.append("  fun of(lhs: U32, rhs: U32): (U32 | None) =>\n")
      out.append("    let t = _table()\n")
      out.append("    var lo: USize = 0\n")
      out.append("    var hi: USize = t.size() / 24\n")
      out.append("    while lo < hi do\n")
      out.append("      let mid = lo + ((hi - lo) / 2)\n")
      out.append("      let base = mid * 24\n")
      out.append("      try\n")
      out.append("        let l: U32 =\n")
      out.append("          _UcdHex.byte(t, base)?\n")
      out.append("            or (_UcdHex.byte(t, base + 2)? << 8)\n")
      out.append("            or (_UcdHex.byte(t, base + 4)? << 16)\n")
      out.append("            or (_UcdHex.byte(t, base + 6)? << 24)\n")
      out.append("        let r: U32 =\n")
      out.append("          _UcdHex.byte(t, base + 8)?\n")
      out.append("            or (_UcdHex.byte(t, base + 10)? << 8)\n")
      out.append("            or (_UcdHex.byte(t, base + 12)? << 16)\n")
      out.append("            or (_UcdHex.byte(t, base + 14)? << 24)\n")
      out.append("        if (lhs < l) or ((lhs == l) and (rhs < r)) then hi = mid\n")
      out.append("        elseif (lhs > l) or ((lhs == l) and (rhs > r)) then lo = mid + 1\n")
      out.append("        else\n")
      out.append("          let result: U32 =\n")
      out.append("            _UcdHex.byte(t, base + 16)?\n")
      out.append("              or (_UcdHex.byte(t, base + 18)? << 8)\n")
      out.append("              or (_UcdHex.byte(t, base + 20)? << 16)\n")
      out.append("              or (_UcdHex.byte(t, base + 22)? << 24)\n")
      out.append("          return result\n")
      out.append("        end\n")
      out.append("      else return None\n")
      out.append("      end\n")
      out.append("    end\n")
      out.append("    None\n\n")

      out.append("  fun _table(): String val =>\n")
      out.append("    \"")
      for e in compose_entries.values() do
        _emit_le_u32(out, e._1)
        _emit_le_u32(out, e._2)
        _emit_le_u32(out, e._3)
      end
      out.append("\"\n")
      out
    end

  fun _collect_exclusions(
    lines: ReadSeq[String val] box)
    : Array[U32] val ?
  =>
    """
    Parse DerivedNormalizationProps.txt; collect all codepoints whose
    property is `Full_Composition_Exclusion`. Result is sorted ascending.
    """
    let raw = recover trn Array[U32] end
    for line in lines.values() do
      match PropertyFileParser.parse_line(line)?
      | let e: PropertyEntry val if e.property == "Full_Composition_Exclusion" =>
        var cp = e.range_lo
        while cp <= e.range_hi do
          raw.push(cp)
          cp = cp + 1
        end
      | None => None
      | let _: PropertyEntry val => None
      end
    end
    _sort_unique_u32(consume raw)

  fun _collect_canonical_composes(
    entries: ReadSeq[UnicodeDataEntry val] box,
    exclusions: Array[U32] val)
    : Array[(U32, U32, U32)] val
  =>
    """
    Invert canonical 2-cp decomps; drop entries whose target is excluded.
    Returns triples (lhs, rhs, result) sorted by (lhs, rhs).
    """
    let raw = recover trn Array[(U32, U32, U32)] end
    for e in entries.values() do
      if (e.decomposition.size() == 2) and (not e.is_compat_decomp) then
        if not _contains_u32(exclusions, e.codepoint) then
          try
            let l = e.decomposition(0)?
            let r = e.decomposition(1)?
            raw.push((l, r, e.codepoint))
          end
        end
      end
    end
    _sort_compose_triples(consume raw)

  fun _contains_u32(sorted: Array[U32] val, cp: U32): Bool =>
    var lo: USize = 0
    var hi: USize = sorted.size()
    while lo < hi do
      let mid = lo + ((hi - lo) / 2)
      try
        let k = sorted(mid)?
        if cp < k then hi = mid
        elseif cp > k then lo = mid + 1
        else return true
        end
      else return false
      end
    end
    false

  fun _sort_unique_u32(raw: Array[U32] trn): Array[U32] val =>
    let n = raw.size()
    var i: USize = 1
    while i < n do
      try
        var j = i
        let cur = raw(j)?
        while (j > 0) and (raw(j - 1)? > cur) do
          raw(j)? = raw(j - 1)?
          j = j - 1
        end
        raw(j)? = cur
      end
      i = i + 1
    end
    // dedupe in place
    let out = recover trn Array[U32](n) end
    var prev: I64 = -1
    for v in raw.values() do
      if I64.from[U32](v) != prev then
        out.push(v)
        prev = I64.from[U32](v)
      end
    end
    consume out

  fun _sort_compose_triples(raw: Array[(U32, U32, U32)] trn)
    : Array[(U32, U32, U32)] val
  =>
    let n = raw.size()
    var i: USize = 1
    while i < n do
      try
        var j = i
        let cur = raw(j)?
        while (j > 0) and _triple_lt(cur, raw(j - 1)?) do
          raw(j)? = raw(j - 1)?
          j = j - 1
        end
        raw(j)? = cur
      end
      i = i + 1
    end
    let out = recover trn Array[(U32, U32, U32)](n) end
    for t in raw.values() do out.push(t) end
    consume out

  fun _triple_lt(a: (U32, U32, U32), b: (U32, U32, U32)): Bool =>
    if a._1 < b._1 then true
    elseif a._1 > b._1 then false
    else a._2 < b._2
    end

  fun _emit_le_u32(out: String ref, value: U32) =>
    _emit_byte(out, U8.from[U32](value and 0xFF))
    _emit_byte(out, U8.from[U32]((value >> 8) and 0xFF))
    _emit_byte(out, U8.from[U32]((value >> 16) and 0xFF))
    _emit_byte(out, U8.from[U32]((value >> 24) and 0xFF))

  fun _emit_byte(out: String ref, b: U8) =>
    let digits = "0123456789ABCDEF"
    try out.push(digits(USize.from[U8](b >> 4))?) end
    try out.push(digits(USize.from[U8](b and 0xF))?) end
