// Combining class + canonical decomposition table generator.
//
// Two output tables, both ASCII-hex-pair encoded (see category_table.pony
// for the encoding rationale):
//
//   _UcdCombiningClass : cp → U8
//     Only codepoints with non-zero Canonical_Combining_Class get an
//     entry; lookups default to 0.
//     Record layout (per entry): 5 bytes raw / 10 hex chars
//       chars 0..7  : cp (LE U32, 8 hex)
//       chars 8..9  : CCC (1 byte, 2 hex)
//
//   _UcdCanonicalDecomposition : cp → (Array[U32] val | None)
//     Only codepoints with a non-empty canonical decomposition (no
//     `<...>` compatibility tag) get an entry. The decomposition is at
//     most 2 codepoints (this is true throughout the UCD; Hangul
//     decomposition is algorithmic and computed at runtime).
//     Record layout (per entry): 12 bytes raw / 24 hex chars
//       chars 0..7   : cp (LE U32)
//       chars 8..15  : decomp[0] (LE U32)
//       chars 16..23 : decomp[1] (LE U32; 0 if single-codepoint decomp)

primitive DecompTableEmitter
  fun emit_combining_class(
    entries: ReadSeq[UnicodeDataEntry val] box)
    : (String iso^, String iso^)
  =>
    """
    Generate (pony_source, c_source) for
    `unicode/_ucd_combining_class.pony` and its co-located blob. The
    table value is the combining class byte itself, so `of` returns it
    directly with no variant mapping.
    """
    let ccc_entries = _collect_ccc(entries)
    let coalesced = _coalesce_ccc(ccc_entries)
    let header =
      "// Auto-generated by unicode-build. Do not edit by hand.\n"
      + "// Regenerate via:\n"
      + "//   make ucd-generate\n"
      + "//\n"
      + "// Source: UnicodeData.txt Canonical_Combining_Class field.\n"
      + "// Only non-zero entries are stored; lookups default to 0."
    _TrieEmitter.emit(header, "_UcdCombiningClass", "U8", "", "",
      "ucd_ccc", coalesced, U8(0))

  fun _coalesce_ccc(
    entries: Array[(U32, U8)] val): Array[(U32, U32, U8)] val
  =>
    """
    Coalesce adjacent same-class entries into ranges. The source data
    is already sorted by codepoint; many neighbouring codepoints share
    a combining class (the U+0300..U+0314 above-marks all have class
    230), so coalescing cuts the emitted arm count substantially.
    """
    recover val
      let out = Array[(U32, U32, U8)]
      var have: Bool = false
      var cur_lo: U32 = 0
      var cur_hi: U32 = 0
      var cur_v:  U8 = 0
      for e in entries.values() do
        if have and (e._1 == (cur_hi + 1)) and (e._2 == cur_v) then
          cur_hi = e._1
        else
          if have then out.push((cur_lo, cur_hi, cur_v)) end
          cur_lo = e._1
          cur_hi = e._1
          cur_v = e._2
          have = true
        end
      end
      if have then out.push((cur_lo, cur_hi, cur_v)) end
      out
    end

  fun emit_canonical_decomposition(
    entries: ReadSeq[UnicodeDataEntry val] box)
    : (String iso^, String iso^)
  =>
    """
    Generate `unicode/_ucd_canonical_decomp.{pony,c}` as an offset trie.
    """
    let triples = _collect_canonical_decomp(entries)
    let pairs = recover val
      let a = Array[(U32, Array[U32] val)](triples.size())
      for t in triples.values() do
        let seq: Array[U32] val =
          if t._3 != 0 then [as U32: t._2; t._3] else [as U32: t._2] end
        a.push((t._1, seq))
      end
      a
    end
    let header =
      "// Auto-generated by unicode-build. Do not edit by hand.\n"
      + "// Regenerate via:\n"
      + "//   make ucd-generate\n"
      + "//\n"
      + "// Source: UnicodeData.txt Decomposition_Mapping field, canonical\n"
      + "// only (compat decomps go to _ucd_compat_decomp). All canonical\n"
      + "// decompositions are 1 or 2 codepoints. Hangul is algorithmic."
    _TrieEmitter.emit_varlen(header, "_UcdCanonicalDecomp", "ucd_cd", pairs)

  fun _collect_ccc(
    entries: ReadSeq[UnicodeDataEntry val] box)
    : Array[(U32, U8)] val
  =>
    """
    Pull out (codepoint, combining_class) pairs for codepoints with
    non-zero CCC.
    """
    let out = recover trn Array[(U32, U8)] end
    for e in entries.values() do
      if e.combining_class != 0 then
        out.push((e.codepoint, e.combining_class))
      end
    end
    consume out

  fun _collect_canonical_decomp(
    entries: ReadSeq[UnicodeDataEntry val] box)
    : Array[(U32, U32, U32)] val
  =>
    """
    Pull out (codepoint, decomp[0], decomp[1]) triples for codepoints
    with a canonical (non-compatibility) decomposition. `decomp[1]` is
    0 if the decomposition is a single codepoint.
    """
    let out = recover trn Array[(U32, U32, U32)] end
    for e in entries.values() do
      if (e.decomposition.size() > 0) and (not e.is_compat_decomp) then
        let d0 = try e.decomposition(0)? else U32(0) end
        let d1 = try e.decomposition(1)? else U32(0) end
        out.push((e.codepoint, d0, d1))
      end
    end
    consume out

  fun emit_compat_decomposition(
    entries: ReadSeq[UnicodeDataEntry val] box)
    : (String iso^, String iso^)
  =>
    """
    Generate `unicode/_ucd_compat_decomp.{pony,c}` as an offset trie over
    a payload blob. Compatibility decompositions run 1..18 codepoints.
    """
    let compat_entries = _collect_compat_decomp(entries)
    let header =
      "// Auto-generated by unicode-build. Do not edit by hand.\n"
      + "// Regenerate via:\n"
      + "//   make ucd-generate\n"
      + "//\n"
      + "// Source: UnicodeData.txt Decomposition_Mapping field,\n"
      + "// compatibility entries only (those with a `<...>` tag)."
    _TrieEmitter.emit_varlen(header, "_UcdCompatDecomp", "ucd_xd",
      compat_entries)

  fun _collect_compat_decomp(
    entries: ReadSeq[UnicodeDataEntry val] box)
    : Array[(U32, Array[U32] val)] val
  =>
    """
    Pull out (codepoint, decomposition) pairs for entries with a
    compatibility decomposition (tag-prefixed in UnicodeData.txt
    field 5). Sorted by codepoint for binary search at runtime.
    """
    let raw = recover trn Array[(U32, Array[U32] val)] end
    for e in entries.values() do
      if (e.decomposition.size() > 0) and e.is_compat_decomp then
        raw.push((e.codepoint, e.decomposition))
      end
    end
    // UnicodeData.txt is already sorted by codepoint, but assert by
    // building a fresh sorted out-array.
    let out = recover trn Array[(U32, Array[U32] val)](raw.size()) end
    for r in raw.values() do out.push(r) end
    consume out
