// Combining class + canonical decomposition table generator.
//
// Two output tables, both ASCII-hex-pair encoded (see category_table.pony
// for the encoding rationale):
//
//   _UcdCombiningClass : cp → U8
//     Only codepoints with non-zero Canonical_Combining_Class get an
//     entry; lookups default to 0.
//     Record layout (per entry): 5 bytes raw / 10 hex chars
//       chars 0..7  : cp (LE U32, 8 hex)
//       chars 8..9  : CCC (1 byte, 2 hex)
//
//   _UcdCanonicalDecomposition : cp → (Array[U32] val | None)
//     Only codepoints with a non-empty canonical decomposition (no
//     `<...>` compatibility tag) get an entry. The decomposition is at
//     most 2 codepoints (this is true throughout the UCD; Hangul
//     decomposition is algorithmic and computed at runtime).
//     Record layout (per entry): 12 bytes raw / 24 hex chars
//       chars 0..7   : cp (LE U32)
//       chars 8..15  : decomp[0] (LE U32)
//       chars 16..23 : decomp[1] (LE U32; 0 if single-codepoint decomp)

primitive DecompTableEmitter
  fun emit_combining_class(
    entries: ReadSeq[UnicodeDataEntry val] box)
    : String iso^
  =>
    """
    Generate the contents of `unicode/_ucd_combining_class.pony`.
    """
    // Materialize the non-zero-CCC entries as sendable val data so the
    // `recover iso` block can iterate them.
    let ccc_entries = _collect_ccc(entries)
    recover iso
      let out = String(32 * 1024)
      out.append("// Auto-generated by unicode-build. Do not edit by hand.\n")
      out.append("// Regenerate via:\n")
      out.append("//   make ucd-generate\n")
      out.append("//\n")
      out.append("// Source: UnicodeData.txt Canonical_Combining_Class field.\n")
      out.append("// Only non-zero entries are stored; lookups default to 0.\n\n")

      out.append("primitive _UcdCombiningClass\n")
      out.append("  fun of(cp: U32): U8 =>\n")
      out.append("    let t = _table()\n")
      out.append("    var lo: USize = 0\n")
      out.append("    var hi: USize = t.size() / 10\n")
      out.append("    while lo < hi do\n")
      out.append("      let mid = lo + ((hi - lo) / 2)\n")
      out.append("      let base = mid * 10\n")
      out.append("      try\n")
      out.append("        let key: U32 =\n")
      out.append("          _UcdHex.byte(t, base)?\n")
      out.append("            or (_UcdHex.byte(t, base + 2)? << 8)\n")
      out.append("            or (_UcdHex.byte(t, base + 4)? << 16)\n")
      out.append("            or (_UcdHex.byte(t, base + 6)? << 24)\n")
      out.append("        if cp < key then\n")
      out.append("          hi = mid\n")
      out.append("        elseif cp > key then\n")
      out.append("          lo = mid + 1\n")
      out.append("        else\n")
      out.append("          return U8.from[U32](_UcdHex.byte(t, base + 8)?)\n")
      out.append("        end\n")
      out.append("      else\n")
      out.append("        return 0\n")
      out.append("      end\n")
      out.append("    end\n")
      out.append("    0\n\n")


      out.append("  fun _table(): String val =>\n")
      out.append("    \"")
      for e in ccc_entries.values() do
        _emit_le_u32(out, e._1)
        _emit_byte(out, e._2)
      end
      out.append("\"\n")

      out
    end

  fun emit_canonical_decomposition(
    entries: ReadSeq[UnicodeDataEntry val] box)
    : String iso^
  =>
    """
    Generate the contents of `unicode/_ucd_canonical_decomp.pony`.
    """
    // Materialize canonical decomps as sendable val data.
    let decomp_entries = _collect_canonical_decomp(entries)
    recover iso
      let out = String(64 * 1024)
      out.append("// Auto-generated by unicode-build. Do not edit by hand.\n")
      out.append("// Regenerate via:\n")
      out.append("//   make ucd-generate\n")
      out.append("//\n")
      out.append("// Source: UnicodeData.txt Decomposition_Mapping field, canonical only.\n")
      out.append("// Compatibility decompositions (with `<tag>` prefix) are emitted to\n")
      out.append("// _ucd_compat_decomp.pony (used by NFKC/NFKD).\n")
      out.append("// All canonical decompositions are 1 or 2 codepoints. Hangul syllables\n")
      out.append("// are not in this table — their decomposition is algorithmic.\n\n")

      out.append("primitive _UcdCanonicalDecomp\n")
      out.append("  fun of(cp: U32): (Array[U32] val | None) =>\n")
      out.append("    let t = _table()\n")
      out.append("    var lo: USize = 0\n")
      out.append("    var hi: USize = t.size() / 24\n")
      out.append("    while lo < hi do\n")
      out.append("      let mid = lo + ((hi - lo) / 2)\n")
      out.append("      let base = mid * 24\n")
      out.append("      try\n")
      out.append("        let key: U32 =\n")
      out.append("          _UcdHex.byte(t, base)?\n")
      out.append("            or (_UcdHex.byte(t, base + 2)? << 8)\n")
      out.append("            or (_UcdHex.byte(t, base + 4)? << 16)\n")
      out.append("            or (_UcdHex.byte(t, base + 6)? << 24)\n")
      out.append("        if cp < key then\n")
      out.append("          hi = mid\n")
      out.append("        elseif cp > key then\n")
      out.append("          lo = mid + 1\n")
      out.append("        else\n")
      out.append("          let d0: U32 =\n")
      out.append("            _UcdHex.byte(t, base + 8)?\n")
      out.append("              or (_UcdHex.byte(t, base + 10)? << 8)\n")
      out.append("              or (_UcdHex.byte(t, base + 12)? << 16)\n")
      out.append("              or (_UcdHex.byte(t, base + 14)? << 24)\n")
      out.append("          let d1: U32 =\n")
      out.append("            _UcdHex.byte(t, base + 16)?\n")
      out.append("              or (_UcdHex.byte(t, base + 18)? << 8)\n")
      out.append("              or (_UcdHex.byte(t, base + 20)? << 16)\n")
      out.append("              or (_UcdHex.byte(t, base + 22)? << 24)\n")
      out.append("          let out_arr = recover trn Array[U32](2) end\n")
      out.append("          out_arr.push(d0)\n")
      out.append("          if d1 != 0 then out_arr.push(d1) end\n")
      out.append("          return consume out_arr\n")
      out.append("        end\n")
      out.append("      else\n")
      out.append("        return None\n")
      out.append("      end\n")
      out.append("    end\n")
      out.append("    None\n\n")


      out.append("  fun _table(): String val =>\n")
      out.append("    \"")
      for e in decomp_entries.values() do
        _emit_le_u32(out, e._1)
        _emit_le_u32(out, e._2)
        _emit_le_u32(out, e._3)
      end
      out.append("\"\n")

      out
    end

  fun _collect_ccc(
    entries: ReadSeq[UnicodeDataEntry val] box)
    : Array[(U32, U8)] val
  =>
    """
    Pull out (codepoint, combining_class) pairs for codepoints with
    non-zero CCC.
    """
    let out = recover trn Array[(U32, U8)] end
    for e in entries.values() do
      if e.combining_class != 0 then
        out.push((e.codepoint, e.combining_class))
      end
    end
    consume out

  fun _collect_canonical_decomp(
    entries: ReadSeq[UnicodeDataEntry val] box)
    : Array[(U32, U32, U32)] val
  =>
    """
    Pull out (codepoint, decomp[0], decomp[1]) triples for codepoints
    with a canonical (non-compatibility) decomposition. `decomp[1]` is
    0 if the decomposition is a single codepoint.
    """
    let out = recover trn Array[(U32, U32, U32)] end
    for e in entries.values() do
      if (e.decomposition.size() > 0) and (not e.is_compat_decomp) then
        let d0 = try e.decomposition(0)? else U32(0) end
        let d1 = try e.decomposition(1)? else U32(0) end
        out.push((e.codepoint, d0, d1))
      end
    end
    consume out

  fun emit_compat_decomposition(
    entries: ReadSeq[UnicodeDataEntry val] box)
    : String iso^
  =>
    """
    Generate `unicode/_ucd_compat_decomp.pony`. Compatibility
    decompositions have variable length (1..18 codepoints in the UCD),
    so a fixed-record format would waste space. Layout:

      _index : sorted records of (cp:U32, data_offset:U32, length:U8)
               9 bytes raw / 18 hex chars per entry.
      _data  : concatenated decomposition codepoints (4 bytes each).
               Binary-searched _index gives `(offset, length)`; data is
               read from `_data` starting at `offset * 4` bytes.
    """
    let compat_entries = _collect_compat_decomp(entries)
    recover iso
      let out = String(128 * 1024)
      out.append("// Auto-generated by unicode-build. Do not edit by hand.\n")
      out.append("// Regenerate via:\n")
      out.append("//   make ucd-generate\n")
      out.append("//\n")
      out.append("// Source: UnicodeData.txt Decomposition_Mapping field,\n")
      out.append("// compatibility entries only (those with a `<...>` tag).\n")
      out.append("// Two-table layout: index (cp, offset, length) + data (cps).\n\n")

      out.append("primitive _UcdCompatDecomp\n")
      out.append("  fun of(cp: U32): (Array[U32] val | None) =>\n")
      out.append("    let idx = _index()\n")
      out.append("    var lo: USize = 0\n")
      out.append("    var hi: USize = idx.size() / 18\n")
      out.append("    while lo < hi do\n")
      out.append("      let mid = lo + ((hi - lo) / 2)\n")
      out.append("      let base = mid * 18\n")
      out.append("      try\n")
      out.append("        let key: U32 =\n")
      out.append("          _UcdHex.byte(idx, base)?\n")
      out.append("            or (_UcdHex.byte(idx, base + 2)? << 8)\n")
      out.append("            or (_UcdHex.byte(idx, base + 4)? << 16)\n")
      out.append("            or (_UcdHex.byte(idx, base + 6)? << 24)\n")
      out.append("        if cp < key then hi = mid\n")
      out.append("        elseif cp > key then lo = mid + 1\n")
      out.append("        else\n")
      out.append("          let offset: U32 =\n")
      out.append("            _UcdHex.byte(idx, base + 8)?\n")
      out.append("              or (_UcdHex.byte(idx, base + 10)? << 8)\n")
      out.append("              or (_UcdHex.byte(idx, base + 12)? << 16)\n")
      out.append("              or (_UcdHex.byte(idx, base + 14)? << 24)\n")
      out.append("          let length = _UcdHex.byte(idx, base + 16)?\n")
      out.append("          return _read(\n")
      out.append("            USize.from[U32](offset),\n")
      out.append("            USize.from[U32](length))\n")
      out.append("        end\n")
      out.append("      else return None\n")
      out.append("      end\n")
      out.append("    end\n")
      out.append("    None\n\n")

      out.append("  fun _read(offset_cps: USize, length: USize)\n")
      out.append("    : (Array[U32] val | None)\n")
      out.append("  =>\n")
      out.append("    let data = _data()\n")
      out.append("    let buf = recover trn Array[U32](length) end\n")
      out.append("    var i: USize = 0\n")
      out.append("    while i < length do\n")
      out.append("      let base = (offset_cps + i) * 8\n")
      out.append("      try\n")
      out.append("        let cp: U32 =\n")
      out.append("          _UcdHex.byte(data, base)?\n")
      out.append("            or (_UcdHex.byte(data, base + 2)? << 8)\n")
      out.append("            or (_UcdHex.byte(data, base + 4)? << 16)\n")
      out.append("            or (_UcdHex.byte(data, base + 6)? << 24)\n")
      out.append("        buf.push(cp)\n")
      out.append("      else return None\n")
      out.append("      end\n")
      out.append("      i = i + 1\n")
      out.append("    end\n")
      out.append("    consume buf\n\n")

      out.append("  fun _index(): String val =>\n")
      out.append("    \"")
      var offset: U32 = 0
      for e in compat_entries.values() do
        _emit_le_u32(out, e._1)
        _emit_le_u32(out, offset)
        _emit_byte(out, U8.from[USize](e._2.size()))
        offset = offset + U32.from[USize](e._2.size())
      end
      out.append("\"\n\n")

      out.append("  fun _data(): String val =>\n")
      out.append("    \"")
      for e in compat_entries.values() do
        for cp in e._2.values() do
          _emit_le_u32(out, cp)
        end
      end
      out.append("\"\n")
      out
    end

  fun _collect_compat_decomp(
    entries: ReadSeq[UnicodeDataEntry val] box)
    : Array[(U32, Array[U32] val)] val
  =>
    """
    Pull out (codepoint, decomposition) pairs for entries with a
    compatibility decomposition (tag-prefixed in UnicodeData.txt
    field 5). Sorted by codepoint for binary search at runtime.
    """
    let raw = recover trn Array[(U32, Array[U32] val)] end
    for e in entries.values() do
      if (e.decomposition.size() > 0) and e.is_compat_decomp then
        raw.push((e.codepoint, e.decomposition))
      end
    end
    // UnicodeData.txt is already sorted by codepoint, but assert by
    // building a fresh sorted out-array.
    let out = recover trn Array[(U32, Array[U32] val)](raw.size()) end
    for r in raw.values() do out.push(r) end
    consume out

  fun _emit_le_u32(out: String ref, value: U32) =>
    _emit_byte(out, U8.from[U32](value and 0xFF))
    _emit_byte(out, U8.from[U32]((value >> 8) and 0xFF))
    _emit_byte(out, U8.from[U32]((value >> 16) and 0xFF))
    _emit_byte(out, U8.from[U32]((value >> 24) and 0xFF))

  fun _emit_byte(out: String ref, b: U8) =>
    let digits = "0123456789ABCDEF"
    try out.push(digits(USize.from[U8](b >> 4))?) end
    try out.push(digits(USize.from[U8](b and 0xF))?) end
