// East_Asian_Width property generator (UAX #11).
//
// Generates two files in lockstep from EastAsianWidth.txt:
//
//   unicode/east_asian_width.pony       — closed-union `EastAsianWidth`
//                                         type with one primitive per
//                                         property value (EAWA, EAWF,
//                                         EAWH, EAWN, EAWNa, EAWW),
//                                         plus the `EastAsianWidths`
//                                         helper.
//   unicode/_ucd_east_asian_width.pony  — cp-range → byte lookup table,
//                                         range-coalesced and binary-
//                                         searched.
//
// Byte 0 is the "N" (Neutral) default for codepoints not covered.
// UAX #11 also specifies that certain unassigned blocks default to "W"
// (CJK Extension A/B and Planes 2 & 3); EastAsianWidth.txt encodes
// those ranges explicitly so the lookup table is authoritative.

primitive EastAsianWidthTableEmitter
  fun emit_both(lines: ReadSeq[String val] box)
    : (String iso^, String iso^, String iso^) ?
  =>
    let entries = PropertyFileParser.parse_all(lines)?
    let names = _collect_names(entries)
    let ranges = _coalesce_ranges(entries, names)
    let runtime = _emit_runtime(names)
    (let table_pony, let table_c) = _emit_table(ranges)
    (consume runtime, consume table_pony, consume table_c)

  fun _collect_names(
    entries: ReadSeq[PropertyEntry val] box)
    : Array[String val] val
  =>
    """
    Distinct EAW names from the parsed entries, sorted alphabetically.
    `N` (Neutral) is forced to byte 0 so codepoints outside any range
    default to it via the binary-search miss path.
    """
    let seen = recover trn Array[String val] end
    seen.push("N")
    for e in entries.values() do
      var found: Bool = false
      for n in seen.values() do
        if n == e.property then found = true; break end
      end
      if not found then seen.push(e.property) end
    end
    let n = seen.size()
    var i: USize = 2
    while i < n do
      try
        var j = i
        let cur = seen(j)?
        while (j > 1) and (seen(j - 1)? > cur) do
          seen(j)? = seen(j - 1)?
          j = j - 1
        end
        seen(j)? = cur
      end
      i = i + 1
    end
    let out = recover trn Array[String val](seen.size()) end
    for v in seen.values() do out.push(v) end
    consume out

  fun _coalesce_ranges(
    entries: ReadSeq[PropertyEntry val] box,
    names: Array[String val] val)
    : Array[(U32, U32, U8)] val
  =>
    let raw = recover trn Array[(U32, U32, U8)] end
    for e in entries.values() do
      let b = _name_to_byte(names, e.property)
      raw.push((e.range_lo, e.range_hi, b))
    end
    let n = raw.size()
    var i: USize = 1
    while i < n do
      try
        var j = i
        let cur = raw(j)?
        while (j > 0) and (raw(j - 1)?._1 > cur._1) do
          raw(j)? = raw(j - 1)?
          j = j - 1
        end
        raw(j)? = cur
      end
      i = i + 1
    end
    let out = recover trn Array[(U32, U32, U8)] end
    var cur_lo: U32 = 0
    var cur_hi: U32 = 0
    var cur_b:  U8 = 0
    var have: Bool = false
    for r in raw.values() do
      if have and (r._3 == cur_b) and (r._1 == (cur_hi + 1)) then
        cur_hi = r._2
      else
        if have then out.push((cur_lo, cur_hi, cur_b)) end
        cur_lo = r._1; cur_hi = r._2; cur_b = r._3
        have = true
      end
    end
    if have then out.push((cur_lo, cur_hi, cur_b)) end
    consume out

  fun _name_to_byte(names: Array[String val] val, name: String val): U8 =>
    var i: USize = 0
    let n = names.size()
    while i < n do
      try
        if names(i)? == name then return U8.from[USize](i) end
      end
      i = i + 1
    end
    0  // N

  fun _type_name(name: String val): String val =>
    """
    Convert `N` → `EAWN`, `Na` → `EAWNa`, etc. EAW values have no
    underscores; we just prepend the `EAW` tag.
    """
    "EAW" + name

  fun _emit_runtime(names: Array[String val] val): String iso^ =>
    recover iso
      let out = String(8 * 1024)
      out.append("// Auto-generated by unicode-build. Do not edit by hand.\n")
      out.append("// Regenerate via:\n")
      out.append("//   make ucd-generate\n")
      out.append("//\n")
      out.append("// Source: EastAsianWidth.txt. `EastAsianWidth` is a\n")
      out.append("// closed union — exhaustive `match` is compile-checked.\n")
      out.append("// N (Neutral) is the default for unassigned codepoints.\n\n")

      for n in names.values() do
        let tn = _type_name(n)
        out.append("primitive " + tn + "\n")
        out.append("  fun code(): String val => \"" + n + "\"\n")
        out.append("  fun string(): String val => \"" + n + "\"\n\n")
      end

      out.append("type EastAsianWidth is\n  ( ")
      var first: Bool = true
      for n in names.values() do
        if first then first = false
        else out.append("\n  | ")
        end
        out.append(_type_name(n))
      end
      out.append("\n  )\n\n")

      out.append("primitive EastAsianWidths\n")
      out.append("  fun from_iso(s: String box): (EastAsianWidth | None) =>\n")
      out.append("    match s\n")
      for n in names.values() do
        out.append("    | \"" + n + "\" => " + _type_name(n) + "\n")
      end
      out.append("    else None\n")
      out.append("    end\n\n")

      out.append("  fun _to_byte(ea: EastAsianWidth): U8 =>\n")
      out.append("    match ea\n")
      var idx: USize = 0
      for n in names.values() do
        out.append("    | " + _type_name(n) + " => " + idx.string() + "\n")
        idx = idx + 1
      end
      out.append("    end\n\n")

      out.append("  fun _from_byte(b: U8): EastAsianWidth =>\n")
      out.append("    match b\n")
      idx = 0
      for n in names.values() do
        out.append("    | " + idx.string() + " => " + _type_name(n) + "\n")
        idx = idx + 1
      end
      out.append("    else EAWN\n")
      out.append("    end\n")
      out
    end

  fun _emit_table(
    ranges: Array[(U32, U32, U8)] val): (String iso^, String iso^)
  =>
    let header =
      "// Auto-generated by unicode-build. Do not edit by hand.\n"
      + "// Regenerate via:\n"
      + "//   make ucd-generate\n"
      + "//\n"
      + "// Source: EastAsianWidth.txt. Codepoints outside any\n"
      + "// range default to EAWN (byte 0)."
    _TrieEmitter.emit(header, "_UcdEastAsianWidth", "EastAsianWidth",
      "EastAsianWidths._from_byte(", ")", "ucd_eaw", ranges, U8(0))

  fun _emit_le_u32(out: String ref, value: U32) =>
    _emit_byte(out, U8.from[U32](value and 0xFF))
    _emit_byte(out, U8.from[U32]((value >> 8) and 0xFF))
    _emit_byte(out, U8.from[U32]((value >> 16) and 0xFF))
    _emit_byte(out, U8.from[U32]((value >> 24) and 0xFF))

  fun _emit_byte(out: String ref, b: U8) =>
    let digits = "0123456789ABCDEF"
    try out.push(digits(USize.from[U8](b >> 4))?) end
    try out.push(digits(USize.from[U8](b and 0xF))?) end
