// Grapheme_Cluster_Break property table generator.
//
// Source files:
//   - ucd/auxiliary/GraphemeBreakProperty.txt (13 of 14 values)
//   - ucd/emoji/emoji-data.txt → Extended_Pictographic
//
// Combined into a single sorted, coalesced array of (range_lo, range_hi,
// break_byte) records and emitted as a single `match` statement on `cp`.
// Each coalesced range becomes one match arm:
//
//     | let c: U32 if (c >= 0xLO) and (c <= 0xHI) => GBVariant
//
// Codepoints not covered by any arm fall through to the `else GBOther`
// branch. The match form replaces the previous hex-blob-plus-binary-
// search lookup; with sorted arms the early arms cover the ASCII range,
// so common Latin-script text resolves in a few comparisons.

primitive GraphemeBreakTableEmitter
  fun emit(
    gbp_lines: ReadSeq[String val] box,
    emoji_lines: ReadSeq[String val] box)
    : (String iso^, String iso^) ?
  =>
    """
    Generate (pony_source, c_source) for `unicode/_ucd_grapheme_break.pony`
    and its co-located `_ucd_grapheme_break.c` blob. Combines entries from
    both source files; raises on malformed input.
    """
    let merged = _collect(gbp_lines, emoji_lines)?
    let header =
      "// Auto-generated by unicode-build. Do not edit by hand.\n"
      + "// Regenerate via:\n"
      + "//   make ucd-generate\n"
      + "//\n"
      + "// Sources: auxiliary/GraphemeBreakProperty.txt +\n"
      + "// emoji/emoji-data.txt (Extended_Pictographic only).\n"
      + "// Codepoints outside any range default to GBOther."
    let default_byte = GraphemeBreakCodes.to_byte("Other") as U8
    _TrieEmitter.emit(header, "_UcdGraphemeBreak", "GraphemeBreak",
      "GraphemeBreaks._from_byte(", ")", "ucd_gb", merged, default_byte)

  fun _collect(
    gbp_lines: ReadSeq[String val] box,
    emoji_lines: ReadSeq[String val] box)
    : Array[(U32, U32, U8)] val ?
  =>
    """
    Parse both source files; keep only entries whose property maps to a
    known byte (everything from GraphemeBreakProperty.txt, plus
    Extended_Pictographic from emoji-data.txt). Sort by range_lo and
    coalesce adjacent equal-byte ranges to keep the table compact.
    """
    let raw = recover trn Array[(U32, U32, U8)] end
    for e in PropertyFileParser.parse_all(gbp_lines)?.values() do
      match GraphemeBreakCodes.to_byte(e.property)
      | let b: U8 => raw.push((e.range_lo, e.range_hi, b))
      | None => None
      end
    end
    for e in PropertyFileParser.parse_all(emoji_lines)?.values() do
      if e.property == "Extended_Pictographic" then
        match GraphemeBreakCodes.to_byte(e.property)
        | let b: U8 => raw.push((e.range_lo, e.range_hi, b))
        | None => None
        end
      end
    end

    // Sort by range_lo then coalesce adjacent equal-byte ranges. This
    // is a small enough N (~1000) that an insertion-sort-by-bubbling
    // pass is fine; production codegen runs in milliseconds.
    let sorted = recover trn Array[(U32, U32, U8)] end
    for entry in (consume raw).values() do
      var i: USize = 0
      var inserted: Bool = false
      while i < sorted.size() do
        try
          let s = sorted(i)?
          if entry._1 < s._1 then
            try sorted.insert(i, entry)? end
            inserted = true
            break
          end
        end
        i = i + 1
      end
      if not inserted then sorted.push(entry) end
    end

    let coalesced = recover trn Array[(U32, U32, U8)] end
    var cur_lo: U32 = 0
    var cur_hi: U32 = 0
    var cur_b: U8 = 0
    var have_cur: Bool = false
    for entry in sorted.values() do
      if have_cur and (entry._1 == (cur_hi + 1)) and (entry._3 == cur_b) then
        cur_hi = entry._2
      else
        if have_cur then coalesced.push((cur_lo, cur_hi, cur_b)) end
        cur_lo = entry._1
        cur_hi = entry._2
        cur_b = entry._3
        have_cur = true
      end
    end
    if have_cur then coalesced.push((cur_lo, cur_hi, cur_b)) end
    consume coalesced
