// Grapheme_Cluster_Break property table generator.
//
// Source files:
//   - ucd/auxiliary/GraphemeBreakProperty.txt (13 of 14 values)
//   - ucd/emoji/emoji-data.txt → Extended_Pictographic
//
// Combined into a single sorted, coalesced array of (range_lo, range_hi,
// break_byte) records. Same ASCII-hex-pair encoding as the category
// table (see category_table.pony) — codepoints not covered by any range
// default to `GBOther`.
//
// Record layout: 9 bytes raw / 18 ASCII hex chars per entry.
//   chars 0..7  : range_lo (LE U32)
//   chars 8..15 : range_hi (LE U32)
//   chars 16..17: grapheme-break byte (per GraphemeBreakCodes.to_byte)

primitive GraphemeBreakTableEmitter
  fun emit(
    gbp_lines: ReadSeq[String val] box,
    emoji_lines: ReadSeq[String val] box)
    : String iso^ ?
  =>
    """
    Generate the contents of `unicode/_ucd_grapheme_break.pony`.
    Combines entries from both source files; raises on malformed input.
    """
    let merged = _collect(gbp_lines, emoji_lines)?
    recover iso
      let out = String(64 * 1024)
      out.append("// Auto-generated by unicode-build. Do not edit by hand.\n")
      out.append("// Regenerate via:\n")
      out.append("//   make ucd-generate\n")
      out.append("//\n")
      out.append("// Sources: auxiliary/GraphemeBreakProperty.txt +\n")
      out.append("// emoji/emoji-data.txt (Extended_Pictographic only).\n")
      out.append("// Codepoints outside any range default to GBOther.\n\n")

      out.append("primitive _UcdGraphemeBreak\n")
      out.append("  fun of(cp: U32): GraphemeBreak =>\n")
      out.append("    let t = _table()\n")
      out.append("    var lo: USize = 0\n")
      out.append("    var hi: USize = t.size() / 18\n")
      out.append("    while lo < hi do\n")
      out.append("      let mid = lo + ((hi - lo) / 2)\n")
      out.append("      let base = mid * 18\n")
      out.append("      try\n")
      out.append("        let range_lo: U32 =\n")
      out.append("          _UcdHex.byte(t, base)?\n")
      out.append("            or (_UcdHex.byte(t, base + 2)? << 8)\n")
      out.append("            or (_UcdHex.byte(t, base + 4)? << 16)\n")
      out.append("            or (_UcdHex.byte(t, base + 6)? << 24)\n")
      out.append("        let range_hi: U32 =\n")
      out.append("          _UcdHex.byte(t, base + 8)?\n")
      out.append("            or (_UcdHex.byte(t, base + 10)? << 8)\n")
      out.append("            or (_UcdHex.byte(t, base + 12)? << 16)\n")
      out.append("            or (_UcdHex.byte(t, base + 14)? << 24)\n")
      out.append("        if cp < range_lo then\n")
      out.append("          hi = mid\n")
      out.append("        elseif cp > range_hi then\n")
      out.append("          lo = mid + 1\n")
      out.append("        else\n")
      out.append("          return GraphemeBreaks._from_byte(U8.from[U32](_UcdHex.byte(t, base + 16)?))\n")
      out.append("        end\n")
      out.append("      else\n")
      out.append("        return GBOther\n")
      out.append("      end\n")
      out.append("    end\n")
      out.append("    GBOther\n\n")

      out.append("  fun _table(): String val =>\n")
      out.append("    \"")
      for r in merged.values() do
        _emit_le_u32(out, r._1)
        _emit_le_u32(out, r._2)
        _emit_byte(out, r._3)
      end
      out.append("\"\n")

      out
    end

  fun _collect(
    gbp_lines: ReadSeq[String val] box,
    emoji_lines: ReadSeq[String val] box)
    : Array[(U32, U32, U8)] val ?
  =>
    """
    Parse both source files; keep only entries whose property maps to a
    known byte (everything from GraphemeBreakProperty.txt, plus
    Extended_Pictographic from emoji-data.txt). Sort by range_lo and
    coalesce adjacent equal-byte ranges to keep the table compact.
    """
    let raw = recover trn Array[(U32, U32, U8)] end
    for e in PropertyFileParser.parse_all(gbp_lines)?.values() do
      match GraphemeBreakCodes.to_byte(e.property)
      | let b: U8 => raw.push((e.range_lo, e.range_hi, b))
      | None => None
      end
    end
    for e in PropertyFileParser.parse_all(emoji_lines)?.values() do
      if e.property == "Extended_Pictographic" then
        match GraphemeBreakCodes.to_byte(e.property)
        | let b: U8 => raw.push((e.range_lo, e.range_hi, b))
        | None => None
        end
      end
    end

    // Sort by range_lo then coalesce adjacent equal-byte ranges. This
    // is a small enough N (~1000) that an insertion-sort-by-bubbling
    // pass is fine; production codegen runs in milliseconds.
    let sorted = recover trn Array[(U32, U32, U8)] end
    for entry in (consume raw).values() do
      var i: USize = 0
      var inserted: Bool = false
      while i < sorted.size() do
        try
          let s = sorted(i)?
          if entry._1 < s._1 then
            try sorted.insert(i, entry)? end
            inserted = true
            break
          end
        end
        i = i + 1
      end
      if not inserted then sorted.push(entry) end
    end

    let coalesced = recover trn Array[(U32, U32, U8)] end
    var cur_lo: U32 = 0
    var cur_hi: U32 = 0
    var cur_b: U8 = 0
    var have_cur: Bool = false
    for entry in sorted.values() do
      if have_cur and (entry._1 == (cur_hi + 1)) and (entry._3 == cur_b) then
        cur_hi = entry._2
      else
        if have_cur then coalesced.push((cur_lo, cur_hi, cur_b)) end
        cur_lo = entry._1
        cur_hi = entry._2
        cur_b = entry._3
        have_cur = true
      end
    end
    if have_cur then coalesced.push((cur_lo, cur_hi, cur_b)) end
    consume coalesced

  fun _emit_le_u32(out: String ref, value: U32) =>
    _emit_byte(out, U8.from[U32](value and 0xFF))
    _emit_byte(out, U8.from[U32]((value >> 8) and 0xFF))
    _emit_byte(out, U8.from[U32]((value >> 16) and 0xFF))
    _emit_byte(out, U8.from[U32]((value >> 24) and 0xFF))

  fun _emit_byte(out: String ref, b: U8) =>
    let digits = "0123456789ABCDEF"
    try out.push(digits(USize.from[U8](b >> 4))?) end
    try out.push(digits(USize.from[U8](b and 0xF))?) end
