// Indic_Conjunct_Break property table generator (UAX #44, Unicode 15.1+).
//
// Parses DerivedCoreProperties.txt looking for `InCB; <value>` entries
// and emits a cp-range table mapping cp → InCB byte code. Layout
// mirrors `_UcdGraphemeBreak`: 9 bytes raw / 18 hex chars per entry
// (range_lo: 4 bytes LE, range_hi: 4 bytes LE, value: 1 byte).
//
// The byte encoding MUST agree with
// `unicode/indic_conjunct_break.pony` `IndicConjunctBreaks._to_byte`:
//
//   None=0  Consonant=1  Linker=2  Extend=3

primitive IncbTableEmitter
  fun emit(dcp_lines: ReadSeq[String val] box): (String iso^, String iso^) =>
    let entries = _collect(dcp_lines)
    let ranges = _sort_and_coalesce(entries)
    let header =
      "// Auto-generated by unicode-build. Do not edit by hand.\n"
      + "// Regenerate via:\n"
      + "//   make ucd-generate\n"
      + "//\n"
      + "// Source: DerivedCoreProperties.txt InCB entries.\n"
      + "// Codepoints outside any range default to InCBNone."
    _TrieEmitter.emit(header, "_UcdIndicConjunctBreak", "IndicConjunctBreak",
      "IndicConjunctBreaks._from_byte(", ")", "ucd_incb", ranges, U8(0))

  fun _collect(dcp_lines: ReadSeq[String val] box)
    : Array[(U32, U32, U8)] val
  =>
    """
    Walk DerivedCoreProperties.txt lines, picking only those whose
    property field is exactly "InCB" — these are key-value lines with
    the value in the third semicolon field.
    """
    let out = recover trn Array[(U32, U32, U8)] end
    for line in dcp_lines.values() do
      if UcdLine.is_skippable(line) then continue end
      let f =
        try UcdLine.fields(line, 2)?
        else continue
        end
      if f.size() < 3 then continue end
      try
        let prop = f(1)?
        if prop != "InCB" then continue end
        (let lo, let hi) = UcdLine.parse_codepoint_range(f(0)?)?
        let value: U8 =
          match f(2)?
          | "Consonant" => 1
          | "Linker"    => 2
          | "Extend"    => 3
          else continue
          end
        out.push((lo, hi, value))
      end
    end
    consume out

  fun _sort_and_coalesce(raw: Array[(U32, U32, U8)] val)
    : Array[(U32, U32, U8)] val
  =>
    // copy into a ref buffer for sorting
    let buf = Array[(U32, U32, U8)](raw.size())
    for r in raw.values() do buf.push(r) end
    // insertion-sort by range_lo
    let n = buf.size()
    var i: USize = 1
    while i < n do
      try
        var j = i
        let cur = buf(j)?
        while (j > 0) and (buf(j - 1)?._1 > cur._1) do
          buf(j)? = buf(j - 1)?
          j = j - 1
        end
        buf(j)? = cur
      end
      i = i + 1
    end
    // coalesce adjacent same-value ranges
    let out = recover trn Array[(U32, U32, U8)] end
    var have: Bool = false
    var cur_lo: U32 = 0
    var cur_hi: U32 = 0
    var cur_v:  U8 = 0
    for r in buf.values() do
      if have and (r._3 == cur_v) and (r._1 == (cur_hi + 1)) then
        cur_hi = r._2
      else
        if have then out.push((cur_lo, cur_hi, cur_v)) end
        cur_lo = r._1
        cur_hi = r._2
        cur_v  = r._3
        have = true
      end
    end
    if have then out.push((cur_lo, cur_hi, cur_v)) end
    consume out
