// Codepoint name table generator.
//
// Generates `unicode/_ucd_name.pony` mapping cp → name (forward) and
// providing a linear-scan reverse lookup. Sources: UnicodeData.txt
// column 1.
//
// Skipped entries:
//   - Range-marker entries (`<...First>`/`<...Last>`) — the name is
//     synthetic and computed at runtime
//   - Entries with `<...>` placeholder names (controls, private use)
//
// Forward lookup `of(cp)` uses the standard two-level
// `match cp >> 12` dispatch — each arm returns the name as a
// `String val` literal, so there's no per-call allocation.
//
// Reverse lookup `from_name(name)` walks a slim cp-only hex blob
// (`_cps()`) and dispatches each through `of(cp)`. The reverse path
// is O(n) over ~30k entries by design — it's interactive-only and not
// on any hot path. Keeping the cp list as a compact hex blob avoids
// emitting a 30k-element array literal.

primitive NameTableEmitter
  fun emit(entries: ReadSeq[UnicodeDataEntry val] box): String iso^ =>
    let names = _collect_names(entries)
    recover iso
      let out = String(4 * 1024 * 1024)
      out.append("// Auto-generated by unicode-build. Do not edit by hand.\n")
      out.append("// Regenerate via:\n")
      out.append("//   make ucd-generate\n")
      out.append("//\n")
      out.append("// Source: UnicodeData.txt column 1 (Name).\n")
      out.append("// Range markers and `<...>` placeholder names are\n")
      out.append("// excluded — runtime callers handle those algorithmically.\n\n")

      out.append("primitive _UcdName\n")
      out.append("  fun of(cp: U32): (String val | None) =>\n")
      _emit_name_match(out, names)
      out.append("\n")
      out.append("  fun from_name(name: String box): (U32 | None) =>\n")
      out.append("    \"\"\"\n")
      out.append("    Linear-scan reverse lookup. O(n) over ~30k entries.\n")
      out.append("    For interactive use only; not on hot paths.\n")
      out.append("    \"\"\"\n")
      out.append("    let cps = _cps()\n")
      out.append("    let count = cps.size() / 8\n")
      out.append("    var i: USize = 0\n")
      out.append("    while i < count do\n")
      out.append("      let base = i * 8\n")
      out.append("      try\n")
      out.append("        let cp: U32 =\n")
      out.append("          _UcdHex.byte(cps, base)?\n")
      out.append("            or (_UcdHex.byte(cps, base + 2)? << 8)\n")
      out.append("            or (_UcdHex.byte(cps, base + 4)? << 16)\n")
      out.append("            or (_UcdHex.byte(cps, base + 6)? << 24)\n")
      out.append("        match of(cp)\n")
      out.append("        | let n: String val if n == name => return cp\n")
      out.append("        end\n")
      out.append("      end\n")
      out.append("      i = i + 1\n")
      out.append("    end\n")
      out.append("    None\n\n")

      out.append("  fun _cps(): String val =>\n")
      out.append("    \"")
      for p in names.values() do
        _emit_le_u32(out, p._1)
      end
      out.append("\"\n")
      out
    end

  fun _emit_name_match(
    out: String ref,
    entries: Array[(U32, String val)] val)
  =>
    """
    Two-level dispatch for cp → name. Top-level `match cp >> 12`
    picks a 4096-cp bucket; inner `match cp` selects the exact
    codepoint and returns the name as a `String val` literal. The
    default arm at every level returns `None`.

    Unicode names use only `A-Z`, `0-9`, `-`, and space (UAX #44), so
    no escaping is needed in the emitted string literals.
    """
    out.append("    match cp >> 12\n")
    var prev_bucket: U32 = 0xFFFFFFFF
    var bucket_open: Bool = false
    for e in entries.values() do
      let bucket = e._1 >> 12
      if bucket != prev_bucket then
        if bucket_open then
          out.append("      else None\n")
          out.append("      end\n")
        end
        out.append("    | 0x")
        _RangeMatchEmitter.emit_hex_u32(out, bucket)
        out.append(" =>\n")
        out.append("      match cp\n")
        bucket_open = true
        prev_bucket = bucket
      end
      out.append("      | 0x")
      _RangeMatchEmitter.emit_hex_u32(out, e._1)
      out.append(" => \"")
      out.append(e._2)
      out.append("\"\n")
    end
    if bucket_open then
      out.append("      else None\n")
      out.append("      end\n")
    end
    out.append("    else\n")
    out.append("      None\n")
    out.append("    end\n")

  fun _collect_names(entries: ReadSeq[UnicodeDataEntry val] box)
    : Array[(U32, String val)] val
  =>
    let out = recover trn Array[(U32, String val)] end
    for e in entries.values() do
      // Skip range markers and `<...>` placeholder names.
      if e.range_end != e.codepoint then continue end
      if e.name.size() == 0 then continue end
      let placeholder: Bool =
        try e.name(0)? == '<' else true end
      if placeholder then continue end
      out.push((e.codepoint, e.name))
    end
    consume out

  fun _emit_le_u32(out: String ref, value: U32) =>
    _emit_byte(out, U8.from[U32](value and 0xFF))
    _emit_byte(out, U8.from[U32]((value >> 8) and 0xFF))
    _emit_byte(out, U8.from[U32]((value >> 16) and 0xFF))
    _emit_byte(out, U8.from[U32]((value >> 24) and 0xFF))

  fun _emit_byte(out: String ref, b: U8) =>
    let digits = "0123456789ABCDEF"
    try out.push(digits(USize.from[U8](b >> 4))?) end
    try out.push(digits(USize.from[U8](b and 0xF))?) end
