// Codepoint name table generator.
//
// Generates `unicode/_ucd_name.pony` mapping cp → name (forward) and
// providing a linear-scan reverse lookup. Sources: UnicodeData.txt
// column 1.
//
// Skipped entries:
//   - Range-marker entries (`<...First>`/`<...Last>`) — the name is
//     synthetic and computed at runtime
//   - Entries with `<...>` placeholder names (controls, private use)
//
// Layout:
//   _index : sorted records of (cp:U32, name_offset:U32, length:U8)
//            9 bytes raw / 18 hex chars per entry.
//   _data  : concatenated name bytes (ASCII; emitted via hex pair).

primitive NameTableEmitter
  fun emit(entries: ReadSeq[UnicodeDataEntry val] box): String iso^ =>
    let names = _collect_names(entries)
    recover iso
      let out = String(2 * 1024 * 1024)
      out.append("// Auto-generated by unicode-build. Do not edit by hand.\n")
      out.append("// Regenerate via:\n")
      out.append("//   make ucd-generate\n")
      out.append("//\n")
      out.append("// Source: UnicodeData.txt column 1 (Name).\n")
      out.append("// Range markers and `<...>` placeholder names are\n")
      out.append("// excluded — runtime callers handle those algorithmically.\n\n")

      out.append("primitive _UcdName\n")
      out.append("  fun of(cp: U32): (String val | None) =>\n")
      out.append("    let idx = _index()\n")
      out.append("    var lo: USize = 0\n")
      out.append("    var hi: USize = idx.size() / 18\n")
      out.append("    while lo < hi do\n")
      out.append("      let mid = lo + ((hi - lo) / 2)\n")
      out.append("      let base = mid * 18\n")
      out.append("      try\n")
      out.append("        let key: U32 =\n")
      out.append("          _UcdHex.byte(idx, base)?\n")
      out.append("            or (_UcdHex.byte(idx, base + 2)? << 8)\n")
      out.append("            or (_UcdHex.byte(idx, base + 4)? << 16)\n")
      out.append("            or (_UcdHex.byte(idx, base + 6)? << 24)\n")
      out.append("        if cp < key then hi = mid\n")
      out.append("        elseif cp > key then lo = mid + 1\n")
      out.append("        else\n")
      out.append("          let offset: U32 =\n")
      out.append("            _UcdHex.byte(idx, base + 8)?\n")
      out.append("              or (_UcdHex.byte(idx, base + 10)? << 8)\n")
      out.append("              or (_UcdHex.byte(idx, base + 12)? << 16)\n")
      out.append("              or (_UcdHex.byte(idx, base + 14)? << 24)\n")
      out.append("          let length = _UcdHex.byte(idx, base + 16)?\n")
      out.append("          return _read(\n")
      out.append("            USize.from[U32](offset),\n")
      out.append("            USize.from[U32](length))\n")
      out.append("        end\n")
      out.append("      else return None\n")
      out.append("      end\n")
      out.append("    end\n")
      out.append("    None\n\n")

      out.append("  fun _read(offset_bytes: USize, length: USize): String val =>\n")
      out.append("    let data = _data()\n")
      out.append("    let buf = recover trn String(length) end\n")
      out.append("    var i: USize = 0\n")
      out.append("    while i < length do\n")
      out.append("      try buf.push(U8.from[U32](_UcdHex.byte(data, (offset_bytes + i) * 2)?)) end\n")
      out.append("      i = i + 1\n")
      out.append("    end\n")
      out.append("    consume buf\n\n")

      out.append("  fun from_name(name: String box): (U32 | None) =>\n")
      out.append("    \"\"\"\n")
      out.append("    Linear-scan reverse lookup. O(n) over ~30k entries.\n")
      out.append("    For interactive use only; not on hot paths.\n")
      out.append("    \"\"\"\n")
      out.append("    let idx = _index()\n")
      out.append("    let count = idx.size() / 18\n")
      out.append("    var i: USize = 0\n")
      out.append("    while i < count do\n")
      out.append("      let base = i * 18\n")
      out.append("      try\n")
      out.append("        let cp: U32 =\n")
      out.append("          _UcdHex.byte(idx, base)?\n")
      out.append("            or (_UcdHex.byte(idx, base + 2)? << 8)\n")
      out.append("            or (_UcdHex.byte(idx, base + 4)? << 16)\n")
      out.append("            or (_UcdHex.byte(idx, base + 6)? << 24)\n")
      out.append("        let candidate = of(cp)\n")
      out.append("        match candidate\n")
      out.append("        | let n: String val if n == name => return cp\n")
      out.append("        end\n")
      out.append("      end\n")
      out.append("      i = i + 1\n")
      out.append("    end\n")
      out.append("    None\n\n")

      out.append("  fun _index(): String val =>\n")
      out.append("    \"")
      var offset: U32 = 0
      for p in names.values() do
        _emit_le_u32(out, p._1)
        _emit_le_u32(out, offset)
        _emit_byte(out, U8.from[USize](p._2.size()))
        offset = offset + U32.from[USize](p._2.size())
      end
      out.append("\"\n\n")

      out.append("  fun _data(): String val =>\n")
      out.append("    \"")
      for p in names.values() do
        for c in p._2.values() do
          _emit_byte(out, c)
        end
      end
      out.append("\"\n")
      out
    end

  fun _collect_names(entries: ReadSeq[UnicodeDataEntry val] box)
    : Array[(U32, String val)] val
  =>
    let out = recover trn Array[(U32, String val)] end
    for e in entries.values() do
      // Skip range markers and `<...>` placeholder names.
      if e.range_end != e.codepoint then continue end
      if e.name.size() == 0 then continue end
      let placeholder: Bool =
        try e.name(0)? == '<' else true end
      if placeholder then continue end
      out.push((e.codepoint, e.name))
    end
    consume out

  fun _emit_le_u32(out: String ref, value: U32) =>
    _emit_byte(out, U8.from[U32](value and 0xFF))
    _emit_byte(out, U8.from[U32]((value >> 8) and 0xFF))
    _emit_byte(out, U8.from[U32]((value >> 16) and 0xFF))
    _emit_byte(out, U8.from[U32]((value >> 24) and 0xFF))

  fun _emit_byte(out: String ref, b: U8) =>
    let digits = "0123456789ABCDEF"
    try out.push(digits(USize.from[U8](b >> 4))?) end
    try out.push(digits(USize.from[U8](b and 0xF))?) end
