// Codepoint name table generator.
//
// Generates `unicode/_ucd_name.pony` mapping cp → name (forward) and
// providing a linear-scan reverse lookup. Sources: UnicodeData.txt
// column 1.
//
// Skipped entries:
//   - Range-marker entries (`<...First>`/`<...Last>`) — the name is
//     synthetic and computed at runtime
//   - Entries with `<...>` placeholder names (controls, private use)
//
// Forward lookup `of(cp)` uses the standard two-level
// `match cp >> 12` dispatch — each arm returns the name as a
// `String val` literal, so there's no per-call allocation.
//
// Reverse lookup `from_name(name)` walks a slim cp-only hex blob
// (`_cps()`) and dispatches each through `of(cp)`. The reverse path
// is O(n) over ~30k entries by design — it's interactive-only and not
// on any hot path. Keeping the cp list as a compact hex blob avoids
// emitting a 30k-element array literal.

primitive NameTableEmitter
  fun emit(entries: ReadSeq[UnicodeDataEntry val] box)
    : (String iso^, String iso^)
  =>
    let names = _collect_names(entries)
    let header =
      "// Auto-generated by unicode-build. Do not edit by hand.\n"
      + "// Regenerate via:\n"
      + "//   make ucd-generate\n"
      + "//\n"
      + "// Source: UnicodeData.txt column 1 (Name). Range markers and\n"
      + "// `<...>` placeholder names are excluded — runtime callers handle\n"
      + "// those algorithmically. Offset trie over a byte payload; reverse\n"
      + "// `from_name` walks the named-codepoint list (slow path)."
    _TrieEmitter.emit_name(header, "ucd_name", names)


  fun _collect_names(entries: ReadSeq[UnicodeDataEntry val] box)
    : Array[(U32, String val)] val
  =>
    let out = recover trn Array[(U32, String val)] end
    for e in entries.values() do
      // Skip range markers and `<...>` placeholder names.
      if e.range_end != e.codepoint then continue end
      if e.name.size() == 0 then continue end
      let placeholder: Bool =
        try e.name(0)? == '<' else true end
      if placeholder then continue end
      out.push((e.codepoint, e.name))
    end
    consume out
