// Script_Extensions property generator (UAX #24).
//
// Generates `unicode/_ucd_script_extensions.pony` — a cp-range → list
// of Script bytes lookup table, binary-searched at runtime.
//
// The Script_Extensions table only stores cps whose Script_Extensions
// value differs from the Script value (i.e., cps used in more than one
// script). For everything else, `script_extensions(cp)` falls back to
// `[script(cp)]` at the API layer.
//
// Storage layout:
//   _index : sorted (range_lo:U32, range_hi:U32, data_offset:U16,
//                    length:U8) records, 11 bytes raw / 22 hex chars
//            per entry.
//   _data  : concatenated Script bytes (1 byte each / 2 hex chars).
// Binary-search _index for `cp ∈ [range_lo, range_hi]`; on hit, read
// `length` Script bytes from _data starting at `data_offset`.

primitive ScriptExtensionsTableEmitter
  fun emit(
    scx_lines: ReadSeq[String val] box,
    pva_lines: ReadSeq[String val] box,
    script_names: Array[String val] val)
    : String iso^ ?
  =>
    """
    `script_names` must come from `ScriptTableEmitter.collect_names`
    on the same Scripts.txt — its index encoding (byte 0 = Unknown,
    then alphabetical) is the encoding we share with the runtime
    `Scripts._to_byte` / `Scripts._from_byte`.
    """
    let short_to_long = _parse_script_aliases(pva_lines)
    let entries = _parse_entries(scx_lines, short_to_long, script_names)?
    _emit(entries, script_names)

  fun _parse_script_aliases(
    pva_lines: ReadSeq[String val] box)
    : Array[(String val, String val)] val
  =>
    """
    Build a (short_code, long_name) list from PropertyValueAliases.txt
    `sc` rows. The long_name matches what Scripts.txt uses (and what
    `Scripts._to_byte` keys on).
    """
    let out = recover trn Array[(String val, String val)] end
    for line in pva_lines.values() do
      if UcdLine.is_skippable(line) then continue end
      let stripped: String val = UcdLine.strip_comment(line)
      let parts: Array[String val] val = _split_semi(stripped)
      if parts.size() < 3 then continue end
      try
        let kind: String val = _trim(parts(0)?)
        if kind != "sc" then continue end
        let short: String val = _trim(parts(1)?)
        let long: String val = _trim(parts(2)?)
        out.push((short, long))
      end
    end
    consume out

  fun _parse_entries(
    scx_lines: ReadSeq[String val] box,
    short_to_long: Array[(String val, String val)] val,
    script_names: Array[String val] val)
    : Array[(U32, U32, Array[U8] val)] val ?
  =>
    """
    Each entry maps a cp-range to a list of Script bytes (sorted by
    byte for stable presentation, mirroring file order).
    """
    let raw = PropertyFileParser.parse_all(scx_lines)?
    let out = recover trn Array[(U32, U32, Array[U8] val)] end
    for e in raw.values() do
      let bytes = _resolve_script_list(
        e.property, short_to_long, script_names)?
      out.push((e.range_lo, e.range_hi, bytes))
    end
    let n = out.size()
    var i: USize = 1
    while i < n do
      try
        var j = i
        let cur = out(j)?
        while (j > 0) and (out(j - 1)?._1 > cur._1) do
          out(j)? = out(j - 1)?
          j = j - 1
        end
        out(j)? = cur
      end
      i = i + 1
    end
    consume out

  fun _resolve_script_list(
    raw_list: String val,
    short_to_long: Array[(String val, String val)] val,
    script_names: Array[String val] val)
    : Array[U8] val ?
  =>
    let codes = _split_ws(raw_list)
    let bytes = recover trn Array[U8] end
    for code in codes.values() do
      let long = _lookup_long(code, short_to_long)?
      bytes.push(_name_to_byte(script_names, long)?)
    end
    consume bytes

  fun _lookup_long(
    short: String val,
    short_to_long: Array[(String val, String val)] val)
    : String val ?
  =>
    for pair in short_to_long.values() do
      if pair._1 == short then return pair._2 end
    end
    error

  fun _name_to_byte(
    script_names: Array[String val] val,
    name: String val): U8 ?
  =>
    var i: USize = 0
    let n = script_names.size()
    while i < n do
      if script_names(i)? == name then return U8.from[USize](i) end
      i = i + 1
    end
    error

  fun _emit(
    entries: Array[(U32, U32, Array[U8] val)] val,
    script_names: Array[String val] val)
    : String iso^
  =>
    let split = _split_at_buckets(entries)
    recover iso
      let out = String(256 * 1024)
      out.append("// Auto-generated by unicode-build. Do not edit by hand.\n")
      out.append("// Regenerate via:\n")
      out.append("//   make ucd-generate\n")
      out.append("//\n")
      out.append("// Source: ScriptExtensions.txt + PropertyValueAliases.txt.\n")
      out.append("// Two-level `match cp >> 12` / `match cp` dispatch (see\n")
      out.append("// `_RangeMatchEmitter` in unicode_build/ for the broader\n")
      out.append("// pattern). Each non-empty range arm returns a fresh\n")
      out.append("// `Array[Script] val` literal; codepoints not listed here\n")
      out.append("// return `None` and the API layer falls back to\n")
      out.append("// `[script(cp)]`.\n\n")

      out.append("primitive _UcdScriptExtensions\n")
      out.append("  fun of(cp: U32): (Array[Script] val | None) =>\n")
      out.append("    match cp >> 12\n")
      var prev_bucket: U32 = 0xFFFFFFFF
      var bucket_open: Bool = false
      var prev_hi_plus_1: U32 = 0
      for e in split.values() do
        let bucket = e._1 >> 12
        if bucket != prev_bucket then
          if bucket_open then
            out.append("      else None\n")
            out.append("      end\n")
          end
          out.append("    | 0x")
          _RangeMatchEmitter.emit_hex_u32(out, bucket)
          out.append(" =>\n")
          out.append("      match cp\n")
          prev_hi_plus_1 = bucket << 12
          bucket_open = true
          prev_bucket = bucket
        end
        if e._1 > prev_hi_plus_1 then
          out.append("      | let c: U32 if c <= 0x")
          _RangeMatchEmitter.emit_hex_u32(out, e._1 - 1)
          out.append(" => None\n")
        end
        out.append("      | let c: U32 if c <= 0x")
        _RangeMatchEmitter.emit_hex_u32(out, e._2)
        out.append(" => recover val [as Script: ")
        var first: Bool = true
        for byte in e._3.values() do
          if not first then out.append("; ") end
          first = false
          let idx = USize.from[U8](byte)
          try out.append(ScriptTableEmitter._type_name(script_names(idx)?)) end
        end
        out.append("] end\n")
        prev_hi_plus_1 = e._2 + 1
      end
      if bucket_open then
        out.append("      else None\n")
        out.append("      end\n")
      end
      out.append("    else\n")
      out.append("      None\n")
      out.append("    end\n")
      out
    end

  fun _split_at_buckets(
    entries: Array[(U32, U32, Array[U8] val)] val)
    : Array[(U32, U32, Array[U8] val)] val
  =>
    """
    Split every input range so each output sub-range stays inside one
    4096-cp bucket. Mirrors `_RangeMatchEmitter._split_at_buckets`
    but for the `Array[U8] val`-payloaded entries used here.
    """
    recover val
      let out = Array[(U32, U32, Array[U8] val)]
      for e in entries.values() do
        var lo = e._1
        while lo <= e._2 do
          let bucket = lo >> 12
          let bucket_end = ((bucket + 1) << 12) - 1
          let hi = if e._2 < bucket_end then e._2 else bucket_end end
          out.push((lo, hi, e._3))
          lo = hi + 1
        end
      end
      out
    end

  fun _split_semi(s: String box): Array[String val] val =>
    let out = recover trn Array[String val] end
    var start: USize = 0
    var i: USize = 0
    let n = s.size()
    while i < n do
      try
        if s(i)? == ';' then
          out.push(s.substring(
            ISize.from[USize](start), ISize.from[USize](i)))
          start = i + 1
        end
      end
      i = i + 1
    end
    out.push(s.substring(ISize.from[USize](start), ISize.from[USize](n)))
    consume out

  fun _split_ws(s: String box): Array[String val] val =>
    let out = recover trn Array[String val] end
    var i: USize = 0
    let n = s.size()
    while i < n do
      try while (i < n) and _is_ws(s(i)?) do i = i + 1 end end
      if i >= n then break end
      var j = i
      try while (j < n) and not _is_ws(s(j)?) do j = j + 1 end end
      out.push(s.substring(
        ISize.from[USize](i), ISize.from[USize](j)))
      i = j
    end
    consume out

  fun _trim(s: String box): String val =>
    var lo: USize = 0
    var hi: USize = s.size()
    try while (lo < hi) and _is_ws(s(lo)?) do lo = lo + 1 end end
    try while (hi > lo) and _is_ws(s(hi - 1)?) do hi = hi - 1 end end
    s.substring(ISize.from[USize](lo), ISize.from[USize](hi))

  fun _is_ws(b: U8): Bool =>
    (b == ' ') or (b == '\t')
