// Script_Extensions property generator (UAX #24).
//
// Generates `unicode/_ucd_script_extensions.pony` — a cp-range → list
// of Script bytes lookup table, binary-searched at runtime.
//
// The Script_Extensions table only stores cps whose Script_Extensions
// value differs from the Script value (i.e., cps used in more than one
// script). For everything else, `script_extensions(cp)` falls back to
// `[script(cp)]` at the API layer.
//
// Storage layout:
//   _index : sorted (range_lo:U32, range_hi:U32, data_offset:U16,
//                    length:U8) records, 11 bytes raw / 22 hex chars
//            per entry.
//   _data  : concatenated Script bytes (1 byte each / 2 hex chars).
// Binary-search _index for `cp ∈ [range_lo, range_hi]`; on hit, read
// `length` Script bytes from _data starting at `data_offset`.

primitive ScriptExtensionsTableEmitter
  fun emit(
    scx_lines: ReadSeq[String val] box,
    pva_lines: ReadSeq[String val] box,
    script_names: Array[String val] val)
    : String iso^ ?
  =>
    """
    `script_names` must come from `ScriptTableEmitter.collect_names`
    on the same Scripts.txt — its index encoding (byte 0 = Unknown,
    then alphabetical) is the encoding we share with the runtime
    `Scripts._to_byte` / `Scripts._from_byte`.
    """
    let short_to_long = _parse_script_aliases(pva_lines)
    let entries = _parse_entries(scx_lines, short_to_long, script_names)?
    _emit(entries)

  fun _parse_script_aliases(
    pva_lines: ReadSeq[String val] box)
    : Array[(String val, String val)] val
  =>
    """
    Build a (short_code, long_name) list from PropertyValueAliases.txt
    `sc` rows. The long_name matches what Scripts.txt uses (and what
    `Scripts._to_byte` keys on).
    """
    let out = recover trn Array[(String val, String val)] end
    for line in pva_lines.values() do
      if UcdLine.is_skippable(line) then continue end
      let stripped: String val = UcdLine.strip_comment(line)
      let parts: Array[String val] val = _split_semi(stripped)
      if parts.size() < 3 then continue end
      try
        let kind: String val = _trim(parts(0)?)
        if kind != "sc" then continue end
        let short: String val = _trim(parts(1)?)
        let long: String val = _trim(parts(2)?)
        out.push((short, long))
      end
    end
    consume out

  fun _parse_entries(
    scx_lines: ReadSeq[String val] box,
    short_to_long: Array[(String val, String val)] val,
    script_names: Array[String val] val)
    : Array[(U32, U32, Array[U8] val)] val ?
  =>
    """
    Each entry maps a cp-range to a list of Script bytes (sorted by
    byte for stable presentation, mirroring file order).
    """
    let raw = PropertyFileParser.parse_all(scx_lines)?
    let out = recover trn Array[(U32, U32, Array[U8] val)] end
    for e in raw.values() do
      let bytes = _resolve_script_list(
        e.property, short_to_long, script_names)?
      out.push((e.range_lo, e.range_hi, bytes))
    end
    let n = out.size()
    var i: USize = 1
    while i < n do
      try
        var j = i
        let cur = out(j)?
        while (j > 0) and (out(j - 1)?._1 > cur._1) do
          out(j)? = out(j - 1)?
          j = j - 1
        end
        out(j)? = cur
      end
      i = i + 1
    end
    consume out

  fun _resolve_script_list(
    raw_list: String val,
    short_to_long: Array[(String val, String val)] val,
    script_names: Array[String val] val)
    : Array[U8] val ?
  =>
    let codes = _split_ws(raw_list)
    let bytes = recover trn Array[U8] end
    for code in codes.values() do
      let long = _lookup_long(code, short_to_long)?
      bytes.push(_name_to_byte(script_names, long)?)
    end
    consume bytes

  fun _lookup_long(
    short: String val,
    short_to_long: Array[(String val, String val)] val)
    : String val ?
  =>
    for pair in short_to_long.values() do
      if pair._1 == short then return pair._2 end
    end
    error

  fun _name_to_byte(
    script_names: Array[String val] val,
    name: String val): U8 ?
  =>
    var i: USize = 0
    let n = script_names.size()
    while i < n do
      if script_names(i)? == name then return U8.from[USize](i) end
      i = i + 1
    end
    error

  fun _emit(
    entries: Array[(U32, U32, Array[U8] val)] val)
    : String iso^
  =>
    recover iso
      let out = String(64 * 1024)
      out.append("// Auto-generated by unicode-build. Do not edit by hand.\n")
      out.append("// Regenerate via:\n")
      out.append("//   make ucd-generate\n")
      out.append("//\n")
      out.append("// Source: ScriptExtensions.txt + PropertyValueAliases.txt.\n")
      out.append("// Codepoints not listed here have Script_Extensions =\n")
      out.append("// [script(cp)] — the API layer falls back to that.\n\n")

      out.append("primitive _UcdScriptExtensions\n")
      out.append("  fun of(cp: U32): (Array[Script] val | None) =>\n")
      out.append("    let t = _index()\n")
      out.append("    var lo: USize = 0\n")
      out.append("    var hi: USize = t.size() / 22\n")
      out.append("    while lo < hi do\n")
      out.append("      let mid = lo + ((hi - lo) / 2)\n")
      out.append("      let base = mid * 22\n")
      out.append("      try\n")
      out.append("        let range_lo: U32 =\n")
      out.append("          _UcdHex.byte(t, base)?\n")
      out.append("            or (_UcdHex.byte(t, base + 2)? << 8)\n")
      out.append("            or (_UcdHex.byte(t, base + 4)? << 16)\n")
      out.append("            or (_UcdHex.byte(t, base + 6)? << 24)\n")
      out.append("        let range_hi: U32 =\n")
      out.append("          _UcdHex.byte(t, base + 8)?\n")
      out.append("            or (_UcdHex.byte(t, base + 10)? << 8)\n")
      out.append("            or (_UcdHex.byte(t, base + 12)? << 16)\n")
      out.append("            or (_UcdHex.byte(t, base + 14)? << 24)\n")
      out.append("        if cp < range_lo then hi = mid\n")
      out.append("        elseif cp > range_hi then lo = mid + 1\n")
      out.append("        else\n")
      out.append("          let offset: U32 =\n")
      out.append("            _UcdHex.byte(t, base + 16)?\n")
      out.append("              or (_UcdHex.byte(t, base + 18)? << 8)\n")
      out.append("          let length = _UcdHex.byte(t, base + 20)?\n")
      out.append("          return _read(\n")
      out.append("            USize.from[U32](offset),\n")
      out.append("            USize.from[U32](length))\n")
      out.append("        end\n")
      out.append("      else return None\n")
      out.append("      end\n")
      out.append("    end\n")
      out.append("    None\n\n")

      out.append("  fun _read(off: USize, length: USize)\n")
      out.append("    : (Array[Script] val | None)\n")
      out.append("  =>\n")
      out.append("    let data = _data()\n")
      out.append("    let buf = recover trn Array[Script](length) end\n")
      out.append("    var i: USize = 0\n")
      out.append("    while i < length do\n")
      out.append("      try\n")
      out.append("        let b = _UcdHex.byte(data, (off + i) * 2)?\n")
      out.append("        buf.push(_ScriptCodec.from_byte(U8.from[U32](b)))\n")
      out.append("      else return None\n")
      out.append("      end\n")
      out.append("      i = i + 1\n")
      out.append("    end\n")
      out.append("    consume buf\n\n")

      out.append("  fun _index(): String val =>\n")
      out.append("    \"")
      var off: U32 = 0
      for e in entries.values() do
        _emit_le_u32(out, e._1)
        _emit_le_u32(out, e._2)
        _emit_le_u16(out, U16.from[U32](off))
        _emit_byte(out, U8.from[USize](e._3.size()))
        off = off + U32.from[USize](e._3.size())
      end
      out.append("\"\n\n")

      out.append("  fun _data(): String val =>\n")
      out.append("    \"")
      for e in entries.values() do
        for b in e._3.values() do
          _emit_byte(out, b)
        end
      end
      out.append("\"\n")
      out
    end

  fun _emit_le_u32(out: String ref, value: U32) =>
    _emit_byte(out, U8.from[U32](value and 0xFF))
    _emit_byte(out, U8.from[U32]((value >> 8) and 0xFF))
    _emit_byte(out, U8.from[U32]((value >> 16) and 0xFF))
    _emit_byte(out, U8.from[U32]((value >> 24) and 0xFF))

  fun _emit_le_u16(out: String ref, value: U16) =>
    _emit_byte(out, U8.from[U16](value and 0xFF))
    _emit_byte(out, U8.from[U16]((value >> 8) and 0xFF))

  fun _emit_byte(out: String ref, b: U8) =>
    let digits = "0123456789ABCDEF"
    try out.push(digits(USize.from[U8](b >> 4))?) end
    try out.push(digits(USize.from[U8](b and 0xF))?) end

  fun _split_semi(s: String box): Array[String val] val =>
    let out = recover trn Array[String val] end
    var start: USize = 0
    var i: USize = 0
    let n = s.size()
    while i < n do
      try
        if s(i)? == ';' then
          out.push(s.substring(
            ISize.from[USize](start), ISize.from[USize](i)))
          start = i + 1
        end
      end
      i = i + 1
    end
    out.push(s.substring(ISize.from[USize](start), ISize.from[USize](n)))
    consume out

  fun _split_ws(s: String box): Array[String val] val =>
    let out = recover trn Array[String val] end
    var i: USize = 0
    let n = s.size()
    while i < n do
      try while (i < n) and _is_ws(s(i)?) do i = i + 1 end end
      if i >= n then break end
      var j = i
      try while (j < n) and not _is_ws(s(j)?) do j = j + 1 end end
      out.push(s.substring(
        ISize.from[USize](i), ISize.from[USize](j)))
      i = j
    end
    consume out

  fun _trim(s: String box): String val =>
    var lo: USize = 0
    var hi: USize = s.size()
    try while (lo < hi) and _is_ws(s(lo)?) do lo = lo + 1 end end
    try while (hi > lo) and _is_ws(s(hi - 1)?) do hi = hi - 1 end end
    s.substring(ISize.from[USize](lo), ISize.from[USize](hi))

  fun _is_ws(b: U8): Bool =>
    (b == ' ') or (b == '\t')
