// Sentence_Break property table generator.
//
// Source: ucd/auxiliary/SentenceBreakProperty.txt only — no emoji-data
// contribution (SB rules don't reference Extended_Pictographic).
//
// Record layout: 9 bytes raw / 18 ASCII hex chars per entry.
//   chars 0..7  : range_lo (LE U32)
//   chars 8..15 : range_hi (LE U32)
//   chars 16..17: sentence-break byte

primitive SentenceBreakTableEmitter
  fun emit(sbp_lines: ReadSeq[String val] box): String iso^ ? =>
    let merged = _collect(sbp_lines)?
    recover iso
      let out = String(64 * 1024)
      out.append("// Auto-generated by unicode-build. Do not edit by hand.\n")
      out.append("// Regenerate via:\n")
      out.append("//   make ucd-generate\n")
      out.append("//\n")
      out.append("// Source: auxiliary/SentenceBreakProperty.txt.\n")
      out.append("// Codepoints outside any range default to SBOther.\n\n")

      out.append("primitive _UcdSentenceBreak\n")
      out.append("  fun of(cp: U32): SentenceBreak =>\n")
      out.append("    let t = _table()\n")
      out.append("    var lo: USize = 0\n")
      out.append("    var hi: USize = t.size() / 18\n")
      out.append("    while lo < hi do\n")
      out.append("      let mid = lo + ((hi - lo) / 2)\n")
      out.append("      let base = mid * 18\n")
      out.append("      try\n")
      out.append("        let range_lo: U32 =\n")
      out.append("          _UcdHex.byte(t, base)?\n")
      out.append("            or (_UcdHex.byte(t, base + 2)? << 8)\n")
      out.append("            or (_UcdHex.byte(t, base + 4)? << 16)\n")
      out.append("            or (_UcdHex.byte(t, base + 6)? << 24)\n")
      out.append("        let range_hi: U32 =\n")
      out.append("          _UcdHex.byte(t, base + 8)?\n")
      out.append("            or (_UcdHex.byte(t, base + 10)? << 8)\n")
      out.append("            or (_UcdHex.byte(t, base + 12)? << 16)\n")
      out.append("            or (_UcdHex.byte(t, base + 14)? << 24)\n")
      out.append("        if cp < range_lo then hi = mid\n")
      out.append("        elseif cp > range_hi then lo = mid + 1\n")
      out.append("        else\n")
      out.append("          return SentenceBreaks._from_byte(\n")
      out.append("            U8.from[U32](_UcdHex.byte(t, base + 16)?))\n")
      out.append("        end\n")
      out.append("      else return SBOther\n")
      out.append("      end\n")
      out.append("    end\n")
      out.append("    SBOther\n\n")

      out.append("  fun _table(): String val =>\n")
      out.append("    \"")
      for r in merged.values() do
        _emit_le_u32(out, r._1)
        _emit_le_u32(out, r._2)
        _emit_byte(out, r._3)
      end
      out.append("\"\n")
      out
    end

  fun _collect(sbp_lines: ReadSeq[String val] box)
    : Array[(U32, U32, U8)] val ?
  =>
    let raw = recover trn Array[(U32, U32, U8)] end
    for e in PropertyFileParser.parse_all(sbp_lines)?.values() do
      match SentenceBreakCodes.to_byte(e.property)
      | let b: U8 => raw.push((e.range_lo, e.range_hi, b))
      | None => None
      end
    end
    let sorted = recover trn Array[(U32, U32, U8)] end
    for entry in (consume raw).values() do
      var i: USize = 0
      var inserted: Bool = false
      while i < sorted.size() do
        try
          let s = sorted(i)?
          if entry._1 < s._1 then
            try sorted.insert(i, entry)? end
            inserted = true
            break
          end
        end
        i = i + 1
      end
      if not inserted then sorted.push(entry) end
    end
    let coalesced = recover trn Array[(U32, U32, U8)] end
    var have: Bool = false
    var cur_lo: U32 = 0
    var cur_hi: U32 = 0
    var cur_v:  U8 = 0
    for entry in sorted.values() do
      if have and (entry._1 == (cur_hi + 1)) and (entry._3 == cur_v) then
        cur_hi = entry._2
      else
        if have then coalesced.push((cur_lo, cur_hi, cur_v)) end
        cur_lo = entry._1
        cur_hi = entry._2
        cur_v = entry._3
        have = true
      end
    end
    if have then coalesced.push((cur_lo, cur_hi, cur_v)) end
    consume coalesced

  fun _emit_le_u32(out: String ref, value: U32) =>
    _emit_byte(out, U8.from[U32](value and 0xFF))
    _emit_byte(out, U8.from[U32]((value >> 8) and 0xFF))
    _emit_byte(out, U8.from[U32]((value >> 16) and 0xFF))
    _emit_byte(out, U8.from[U32]((value >> 24) and 0xFF))

  fun _emit_byte(out: String ref, b: U8) =>
    let digits = "0123456789ABCDEF"
    try out.push(digits(USize.from[U8](b >> 4))?) end
    try out.push(digits(USize.from[U8](b and 0xF))?) end
