// Sentence_Break property table generator.
//
// Source: ucd/auxiliary/SentenceBreakProperty.txt only — no emoji-data
// contribution (SB rules don't reference Extended_Pictographic).
//
// Record layout: 9 bytes raw / 18 ASCII hex chars per entry.
//   chars 0..7  : range_lo (LE U32)
//   chars 8..15 : range_hi (LE U32)
//   chars 16..17: sentence-break byte

primitive SentenceBreakTableEmitter
  fun emit(sbp_lines: ReadSeq[String val] box)
    : (String iso^, String iso^) ?
  =>
    let merged = _collect(sbp_lines)?
    let header =
      "// Auto-generated by unicode-build. Do not edit by hand.\n"
      + "// Regenerate via:\n"
      + "//   make ucd-generate\n"
      + "//\n"
      + "// Source: auxiliary/SentenceBreakProperty.txt.\n"
      + "// Codepoints outside any range default to SBOther."
    let default_byte = SentenceBreakCodes.to_byte("Other") as U8
    _TrieEmitter.emit(header, "_UcdSentenceBreak", "SentenceBreak",
      "SentenceBreaks._from_byte(", ")", "ucd_sb", merged, default_byte)

  fun _collect(sbp_lines: ReadSeq[String val] box)
    : Array[(U32, U32, U8)] val ?
  =>
    let raw = recover trn Array[(U32, U32, U8)] end
    for e in PropertyFileParser.parse_all(sbp_lines)?.values() do
      match SentenceBreakCodes.to_byte(e.property)
      | let b: U8 => raw.push((e.range_lo, e.range_hi, b))
      | None => None
      end
    end
    let sorted = recover trn Array[(U32, U32, U8)] end
    for entry in (consume raw).values() do
      var i: USize = 0
      var inserted: Bool = false
      while i < sorted.size() do
        try
          let s = sorted(i)?
          if entry._1 < s._1 then
            try sorted.insert(i, entry)? end
            inserted = true
            break
          end
        end
        i = i + 1
      end
      if not inserted then sorted.push(entry) end
    end
    let coalesced = recover trn Array[(U32, U32, U8)] end
    var have: Bool = false
    var cur_lo: U32 = 0
    var cur_hi: U32 = 0
    var cur_v:  U8 = 0
    for entry in sorted.values() do
      if have and (entry._1 == (cur_hi + 1)) and (entry._3 == cur_v) then
        cur_hi = entry._2
      else
        if have then coalesced.push((cur_lo, cur_hi, cur_v)) end
        cur_lo = entry._1
        cur_hi = entry._2
        cur_v = entry._3
        have = true
      end
    end
    if have then coalesced.push((cur_lo, cur_hi, cur_v)) end
    consume coalesced

  fun _emit_le_u32(out: String ref, value: U32) =>
    _emit_byte(out, U8.from[U32](value and 0xFF))
    _emit_byte(out, U8.from[U32]((value >> 8) and 0xFF))
    _emit_byte(out, U8.from[U32]((value >> 16) and 0xFF))
    _emit_byte(out, U8.from[U32]((value >> 24) and 0xFF))

  fun _emit_byte(out: String ref, b: U8) =>
    let digits = "0123456789ABCDEF"
    try out.push(digits(USize.from[U8](b >> 4))?) end
    try out.push(digits(USize.from[U8](b and 0xF))?) end
