// Shared emitter for variable-length cp → `Array[U32]` lookup tables.
//
// Used for:
//   - _UcdFullUpper / _UcdFullLower / _UcdFullTitle (SpecialCasing.txt)
//   - _UcdFullCaseFold (CaseFolding.txt status C+F)
//
// Same two-level `match cp >> 12` pattern as `_emit_varlen_decomp_match`
// in decomp_table.pony — outer match picks a 4096-cp bucket, inner
// match selects the exact codepoint and emits its mapping as a
// `recover val [as U32: 0xX; 0xY; ...] end` literal. The default arm
// at every level returns `None`.

primitive VarLenTableEmitter
  fun emit(
    primitive_name: String val,
    source_note: String val,
    pairs: Array[(U32, Array[U32] val)] val)
    : String iso^
  =>
    """
    Emit a complete `.pony` file body for one cp → Array[U32] table.
    `pairs` must be sorted by cp ascending and contain no duplicates.
    """
    recover iso
      let out = String(128 * 1024)
      out.append("// Auto-generated by unicode-build. Do not edit by hand.\n")
      out.append("// Regenerate via:\n")
      out.append("//   make ucd-generate\n")
      out.append("//\n")
      out.append("// Source: " + source_note + ".\n\n")

      out.append("primitive " + primitive_name + "\n")
      out.append("  fun of(cp: U32): (Array[U32] val | None) =>\n")
      _emit_varlen_match(out, pairs)
      out
    end

  fun _emit_varlen_match(
    out: String ref,
    entries: Array[(U32, Array[U32] val)] val)
  =>
    """
    Two-level dispatch for variable-length cp → Array[U32] tables.
    Each arm emits a `recover val [as U32: …] end` literal containing
    the full mapping (case mappings run up to 3 codepoints; this
    pattern is identical to the one used for compat decomp, which
    runs up to ~18 codepoints).
    """
    out.append("    match cp >> 12\n")
    var prev_bucket: U32 = 0xFFFFFFFF
    var bucket_open: Bool = false
    for e in entries.values() do
      let bucket = e._1 >> 12
      if bucket != prev_bucket then
        if bucket_open then
          out.append("      else None\n")
          out.append("      end\n")
        end
        out.append("    | 0x")
        _RangeMatchEmitter.emit_hex_u32(out, bucket)
        out.append(" =>\n")
        out.append("      match cp\n")
        bucket_open = true
        prev_bucket = bucket
      end
      out.append("      | 0x")
      _RangeMatchEmitter.emit_hex_u32(out, e._1)
      out.append(" => recover val [as U32: ")
      var first: Bool = true
      for cp in e._2.values() do
        if not first then out.append("; ") end
        first = false
        out.append("0x")
        _RangeMatchEmitter.emit_hex_u32(out, cp)
      end
      out.append("] end\n")
    end
    if bucket_open then
      out.append("      else None\n")
      out.append("      end\n")
    end
    out.append("    else\n")
    out.append("      None\n")
    out.append("    end\n")
