// Shared emitter for variable-length cp → `Array[U32]` lookup tables.
//
// Used for:
//   - _UcdFullUpper / _UcdFullLower / _UcdFullTitle (SpecialCasing.txt)
//   - _UcdFullCaseFold (CaseFolding.txt status C+F)
//
// Same two-level `match cp >> 12` pattern as `_emit_varlen_decomp_match`
// in decomp_table.pony — outer match picks a 4096-cp bucket, inner
// match selects the exact codepoint and emits its mapping as a
// `recover val [as U32: 0xX; 0xY; ...] end` literal. The default arm
// at every level returns `None`.

primitive VarLenTableEmitter
  fun emit(
    primitive_name: String val,
    source_note: String val,
    c_prefix: String val,
    pairs: Array[(U32, Array[U32] val)] val)
    : (String iso^, String iso^)
  =>
    """
    Emit (pony, c) for one cp → (Array[U32] val | None) table as an
    offset trie over a payload blob. `pairs` must be sorted by cp
    ascending with no duplicates.
    """
    let header: String val =
      "// Auto-generated by unicode-build. Do not edit by hand.\n"
      + "// Regenerate via:\n"
      + "//   make ucd-generate\n"
      + "//\n"
      + "// Source: " + source_note + "."
    _TrieEmitter.emit_varlen(header, primitive_name, c_prefix, pairs)
