// Word_Break property table generator.
//
// Source files:
//   - ucd/auxiliary/WordBreakProperty.txt (18 of 20 values)
//   - ucd/emoji/emoji-data.txt → Extended_Pictographic (for WB3c)
//
// Combined into a single sorted, coalesced array of
// (range_lo, range_hi, break_byte) records. ASCII-hex-pair encoding;
// codepoints not covered default to `WBOther`.
//
// Record layout: 9 bytes raw / 18 ASCII hex chars per entry.
//   chars 0..7  : range_lo (LE U32)
//   chars 8..15 : range_hi (LE U32)
//   chars 16..17: word-break byte (per WordBreakCodes.to_byte)

primitive WordBreakTableEmitter
  fun emit(
    wbp_lines: ReadSeq[String val] box,
    emoji_lines: ReadSeq[String val] box)
    : (String iso^, String iso^) ?
  =>
    """
    Generate (pony_source, c_source) for `unicode/_ucd_word_break.pony`
    and its co-located `_ucd_word_break.c` blob.
    """
    let merged = _collect(wbp_lines, emoji_lines)?
    let header =
      "// Auto-generated by unicode-build. Do not edit by hand.\n"
      + "// Regenerate via:\n"
      + "//   make ucd-generate\n"
      + "//\n"
      + "// Sources: auxiliary/WordBreakProperty.txt +\n"
      + "// emoji/emoji-data.txt (Extended_Pictographic only).\n"
      + "// Codepoints outside any range default to WBOther."
    let default_byte = WordBreakCodes.to_byte("Other") as U8
    _TrieEmitter.emit(header, "_UcdWordBreak", "WordBreak",
      "WordBreaks._from_byte(", ")", "ucd_wb", merged, default_byte)

  fun _collect(
    wbp_lines: ReadSeq[String val] box,
    emoji_lines: ReadSeq[String val] box)
    : Array[(U32, U32, U8)] val ?
  =>
    """
    Parse both files; combine; sort by range_lo; coalesce adjacent
    ranges with the same byte. Extended_Pictographic entries from
    emoji-data.txt override any conflicting WBP entries on the same
    codepoint — but they're disjoint in practice, so coalescing
    handles the normal case cleanly.
    """
    let raw = recover trn Array[(U32, U32, U8)] end
    for e in PropertyFileParser.parse_all(wbp_lines)?.values() do
      match WordBreakCodes.to_byte(e.property)
      | let b: U8 => raw.push((e.range_lo, e.range_hi, b))
      | None => None
      end
    end
    for e in PropertyFileParser.parse_all(emoji_lines)?.values() do
      if e.property == "Extended_Pictographic" then
        raw.push((e.range_lo, e.range_hi, U8(19)))
      end
    end

    // Sort by range_lo via insertion (small N — milliseconds).
    let sorted = recover trn Array[(U32, U32, U8)] end
    for entry in (consume raw).values() do
      var i: USize = 0
      var inserted: Bool = false
      while i < sorted.size() do
        try
          let s = sorted(i)?
          if entry._1 < s._1 then
            try sorted.insert(i, entry)? end
            inserted = true
            break
          end
        end
        i = i + 1
      end
      if not inserted then sorted.push(entry) end
    end

    // Coalesce adjacent same-value ranges.
    let coalesced = recover trn Array[(U32, U32, U8)] end
    var have: Bool = false
    var cur_lo: U32 = 0
    var cur_hi: U32 = 0
    var cur_v:  U8 = 0
    for entry in sorted.values() do
      if have and (entry._1 == (cur_hi + 1)) and (entry._3 == cur_v) then
        cur_hi = entry._2
      else
        if have then coalesced.push((cur_lo, cur_hi, cur_v)) end
        cur_lo = entry._1
        cur_hi = entry._2
        cur_v = entry._3
        have = true
      end
    end
    if have then coalesced.push((cur_lo, cur_hi, cur_v)) end
    consume coalesced

  fun _emit_le_u32(out: String ref, value: U32) =>
    _emit_byte(out, U8.from[U32](value and 0xFF))
    _emit_byte(out, U8.from[U32]((value >> 8) and 0xFF))
    _emit_byte(out, U8.from[U32]((value >> 16) and 0xFF))
    _emit_byte(out, U8.from[U32]((value >> 24) and 0xFF))

  fun _emit_byte(out: String ref, b: U8) =>
    let digits = "0123456789ABCDEF"
    try out.push(digits(USize.from[U8](b >> 4))?) end
    try out.push(digits(USize.from[U8](b and 0xF))?) end
