// Auto-generated by unicode-build. Do not edit by hand.
// Regenerate via:
//   make ucd-generate
//
// Source: EastAsianWidth.txt. Codepoints outside any
// range default to EAWN (byte 0).
use @ucd_eaw_lookup[U8](cp: U32)

primitive _UcdEastAsianWidth
  fun of(cp: U32): EastAsianWidth =>
    EastAsianWidths._from_byte(@ucd_eaw_lookup(cp))
