// Auto-generated by unicode-build. Do not edit by hand.
// Regenerate via:
//   make ucd-generate
//
// Source: DerivedNormalizationProps.txt Full_Composition_Exclusion.
// True for Full_Composition_Exclusion codepoints.
use @ucd_compex_lookup[U8](cp: U32)

primitive _UcdCompositionExclusion
  fun of(cp: U32): Bool =>
    @ucd_compex_lookup(cp) != 0
