// Auto-generated by unicode-build. Do not edit by hand.
// Regenerate via:
//   make ucd-generate
//
// Source: UnicodeData.txt canonical decompositions, inverted,
// with Full_Composition_Exclusion entries removed.
use @ucd_cc_compose[U32](lhs: U32, rhs: U32)

primitive _UcdCanonicalCompose
  fun of(lhs: U32, rhs: U32): (U32 | None) =>
    let r = @ucd_cc_compose(lhs, rhs)
    if r == 0 then None else r end
