// Auto-generated by unicode-build. Do not edit by hand.
// Regenerate via:
//   make ucd-generate
//
// Source: ScriptExtensions.txt + PropertyValueAliases.txt.
// cp -> list of Script bytes (decoded via _ScriptCodec.from_byte);
// codepoints not listed return None and the API falls back to
// [script(cp)].
use @ucd_scx_lookup[U32](cp: U32)
use @ucd_scx_at[U32](i: U32)

primitive _UcdScriptExtensions
  fun of(cp: U32): (Array[Script] val | None) =>
    let off = @ucd_scx_lookup(cp)
    if off == 0 then return None end
    let n = @ucd_scx_at(off)
    recover val
      let a = Array[Script](n.usize())
      var i: U32 = 1
      while i <= n do a.push(_ScriptCodec.from_byte(@ucd_scx_at(off + i).u8())); i = i + 1 end
      a
    end
