// Auto-generated by unicode-build. Do not edit by hand.
// Regenerate via:
//   make ucd-generate
//
// Source: UnicodeData.txt Simple_Lowercase_Mapping.
// Only non-identity mappings are stored (value 0 = identity);
// `of` returns `cp` for those so the API is identity-preserving.
use @ucd_sl_lookup[U32](cp: U32)

primitive _UcdSimpleLower
  fun of(cp: U32): U32 =>
    let m = @ucd_sl_lookup(cp)
    if m == 0 then cp else m end
