// Auto-generated by unicode-build. Do not edit by hand.
// Regenerate via:
//   make ucd-generate
//
// Source: UnicodeData.txt Decomposition_Mapping field,
// compatibility entries only (those with a `<...>` tag).
use @ucd_xd_lookup[U32](cp: U32)
use @ucd_xd_at[U32](i: U32)

primitive _UcdCompatDecomp
  fun of(cp: U32): (Array[U32] val | None) =>
    let off = @ucd_xd_lookup(cp)
    if off == 0 then return None end
    let n = @ucd_xd_at(off)
    recover val
      let a = Array[U32](n.usize())
      var i: U32 = 1
      while i <= n do a.push(@ucd_xd_at(off + i)); i = i + 1 end
      a
    end
