// Auto-generated by unicode-build. Do not edit by hand.
// Regenerate via:
//   make ucd-generate
//
// Source: UnicodeData.txt column 1 (Name). Range markers and
// `<...>` placeholder names are excluded — runtime callers handle
// those algorithmically. Offset trie over a byte payload; reverse
// `from_name` walks the named-codepoint list (slow path).
use @ucd_name_lookup[U32](cp: U32)
use @ucd_name_at[U8](i: U32)
use @ucd_name_count[U32]()
use @ucd_name_cpat[U32](i: U32)

primitive _UcdName
  fun of(cp: U32): (String val | None) =>
    let off = @ucd_name_lookup(cp)
    if off == 0 then return None end
    let n = @ucd_name_at(off)
    recover val
      let s = String(n.usize())
      var i: U32 = 1
      while i <= n.u32() do s.push(@ucd_name_at(off + i)); i = i + 1 end
      s
    end

  fun from_name(name: String box): (U32 | None) =>
    // Linear-scan reverse lookup over named codepoints.
    var i: U32 = 0
    let count = @ucd_name_count()
    while i < count do
      let cp = @ucd_name_cpat(i)
      match of(cp) | let nm: String val if nm == name => return cp end
      i = i + 1
    end
    None
