// Auto-generated by unicode-build. Do not edit by hand.
// Regenerate via:
//   make ucd-generate
//
// Source: CaseFolding.txt status C + F entries (default full folding).
use @ucd_ff_lookup[U32](cp: U32)
use @ucd_ff_at[U32](i: U32)

primitive _UcdFullCaseFold
  fun of(cp: U32): (Array[U32] val | None) =>
    let off = @ucd_ff_lookup(cp)
    if off == 0 then return None end
    let n = @ucd_ff_at(off)
    recover val
      let a = Array[U32](n.usize())
      var i: U32 = 1
      while i <= n do a.push(@ucd_ff_at(off + i)); i = i + 1 end
      a
    end
