// Auto-generated by unicode-build. Do not edit by hand.
// Regenerate via:
//   make ucd-generate
//
// Sources: auxiliary/GraphemeBreakProperty.txt +
// emoji/emoji-data.txt (Extended_Pictographic only).
// Codepoints outside any range default to GBOther.
use @ucd_gb_lookup[U8](cp: U32)

primitive _UcdGraphemeBreak
  fun of(cp: U32): GraphemeBreak =>
    GraphemeBreaks._from_byte(@ucd_gb_lookup(cp))
