// Auto-generated by unicode-build. Do not edit by hand.
// Regenerate via:
//   make ucd-generate
//
// Source: UnicodeData.txt canonical decompositions, inverted,
// with Full_Composition_Exclusion entries removed.

primitive _UcdCanonicalCompose
  fun of(lhs: U32, rhs: U32): (U32 | None) =>
    match lhs >> 12
    | 0x0000 =>
      match lhs
      | 0x003C =>
        match rhs
        | 0x0338 => 0x226E
        else None
        end
      | 0x003D =>
        match rhs
        | 0x0338 => 0x2260
        else None
        end
      | 0x003E =>
        match rhs
        | 0x0338 => 0x226F
        else None
        end
      | 0x0041 =>
        match rhs
        | 0x0300 => 0x00C0
        | 0x0301 => 0x00C1
        | 0x0302 => 0x00C2
        | 0x0303 => 0x00C3
        | 0x0304 => 0x0100
        | 0x0306 => 0x0102
        | 0x0307 => 0x0226
        | 0x0308 => 0x00C4
        | 0x0309 => 0x1EA2
        | 0x030A => 0x00C5
        | 0x030C => 0x01CD
        | 0x030F => 0x0200
        | 0x0311 => 0x0202
        | 0x0323 => 0x1EA0
        | 0x0325 => 0x1E00
        | 0x0328 => 0x0104
        else None
        end
      | 0x0042 =>
        match rhs
        | 0x0307 => 0x1E02
        | 0x0323 => 0x1E04
        | 0x0331 => 0x1E06
        else None
        end
      | 0x0043 =>
        match rhs
        | 0x0301 => 0x0106
        | 0x0302 => 0x0108
        | 0x0307 => 0x010A
        | 0x030C => 0x010C
        | 0x0327 => 0x00C7
        else None
        end
      | 0x0044 =>
        match rhs
        | 0x0307 => 0x1E0A
        | 0x030C => 0x010E
        | 0x0323 => 0x1E0C
        | 0x0327 => 0x1E10
        | 0x032D => 0x1E12
        | 0x0331 => 0x1E0E
        else None
        end
      | 0x0045 =>
        match rhs
        | 0x0300 => 0x00C8
        | 0x0301 => 0x00C9
        | 0x0302 => 0x00CA
        | 0x0303 => 0x1EBC
        | 0x0304 => 0x0112
        | 0x0306 => 0x0114
        | 0x0307 => 0x0116
        | 0x0308 => 0x00CB
        | 0x0309 => 0x1EBA
        | 0x030C => 0x011A
        | 0x030F => 0x0204
        | 0x0311 => 0x0206
        | 0x0323 => 0x1EB8
        | 0x0327 => 0x0228
        | 0x0328 => 0x0118
        | 0x032D => 0x1E18
        | 0x0330 => 0x1E1A
        else None
        end
      | 0x0046 =>
        match rhs
        | 0x0307 => 0x1E1E
        else None
        end
      | 0x0047 =>
        match rhs
        | 0x0301 => 0x01F4
        | 0x0302 => 0x011C
        | 0x0304 => 0x1E20
        | 0x0306 => 0x011E
        | 0x0307 => 0x0120
        | 0x030C => 0x01E6
        | 0x0327 => 0x0122
        else None
        end
      | 0x0048 =>
        match rhs
        | 0x0302 => 0x0124
        | 0x0307 => 0x1E22
        | 0x0308 => 0x1E26
        | 0x030C => 0x021E
        | 0x0323 => 0x1E24
        | 0x0327 => 0x1E28
        | 0x032E => 0x1E2A
        else None
        end
      | 0x0049 =>
        match rhs
        | 0x0300 => 0x00CC
        | 0x0301 => 0x00CD
        | 0x0302 => 0x00CE
        | 0x0303 => 0x0128
        | 0x0304 => 0x012A
        | 0x0306 => 0x012C
        | 0x0307 => 0x0130
        | 0x0308 => 0x00CF
        | 0x0309 => 0x1EC8
        | 0x030C => 0x01CF
        | 0x030F => 0x0208
        | 0x0311 => 0x020A
        | 0x0323 => 0x1ECA
        | 0x0328 => 0x012E
        | 0x0330 => 0x1E2C
        else None
        end
      | 0x004A =>
        match rhs
        | 0x0302 => 0x0134
        else None
        end
      | 0x004B =>
        match rhs
        | 0x0301 => 0x1E30
        | 0x030C => 0x01E8
        | 0x0323 => 0x1E32
        | 0x0327 => 0x0136
        | 0x0331 => 0x1E34
        else None
        end
      | 0x004C =>
        match rhs
        | 0x0301 => 0x0139
        | 0x030C => 0x013D
        | 0x0323 => 0x1E36
        | 0x0327 => 0x013B
        | 0x032D => 0x1E3C
        | 0x0331 => 0x1E3A
        else None
        end
      | 0x004D =>
        match rhs
        | 0x0301 => 0x1E3E
        | 0x0307 => 0x1E40
        | 0x0323 => 0x1E42
        else None
        end
      | 0x004E =>
        match rhs
        | 0x0300 => 0x01F8
        | 0x0301 => 0x0143
        | 0x0303 => 0x00D1
        | 0x0307 => 0x1E44
        | 0x030C => 0x0147
        | 0x0323 => 0x1E46
        | 0x0327 => 0x0145
        | 0x032D => 0x1E4A
        | 0x0331 => 0x1E48
        else None
        end
      | 0x004F =>
        match rhs
        | 0x0300 => 0x00D2
        | 0x0301 => 0x00D3
        | 0x0302 => 0x00D4
        | 0x0303 => 0x00D5
        | 0x0304 => 0x014C
        | 0x0306 => 0x014E
        | 0x0307 => 0x022E
        | 0x0308 => 0x00D6
        | 0x0309 => 0x1ECE
        | 0x030B => 0x0150
        | 0x030C => 0x01D1
        | 0x030F => 0x020C
        | 0x0311 => 0x020E
        | 0x031B => 0x01A0
        | 0x0323 => 0x1ECC
        | 0x0328 => 0x01EA
        else None
        end
      | 0x0050 =>
        match rhs
        | 0x0301 => 0x1E54
        | 0x0307 => 0x1E56
        else None
        end
      | 0x0052 =>
        match rhs
        | 0x0301 => 0x0154
        | 0x0307 => 0x1E58
        | 0x030C => 0x0158
        | 0x030F => 0x0210
        | 0x0311 => 0x0212
        | 0x0323 => 0x1E5A
        | 0x0327 => 0x0156
        | 0x0331 => 0x1E5E
        else None
        end
      | 0x0053 =>
        match rhs
        | 0x0301 => 0x015A
        | 0x0302 => 0x015C
        | 0x0307 => 0x1E60
        | 0x030C => 0x0160
        | 0x0323 => 0x1E62
        | 0x0326 => 0x0218
        | 0x0327 => 0x015E
        else None
        end
      | 0x0054 =>
        match rhs
        | 0x0307 => 0x1E6A
        | 0x030C => 0x0164
        | 0x0323 => 0x1E6C
        | 0x0326 => 0x021A
        | 0x0327 => 0x0162
        | 0x032D => 0x1E70
        | 0x0331 => 0x1E6E
        else None
        end
      | 0x0055 =>
        match rhs
        | 0x0300 => 0x00D9
        | 0x0301 => 0x00DA
        | 0x0302 => 0x00DB
        | 0x0303 => 0x0168
        | 0x0304 => 0x016A
        | 0x0306 => 0x016C
        | 0x0308 => 0x00DC
        | 0x0309 => 0x1EE6
        | 0x030A => 0x016E
        | 0x030B => 0x0170
        | 0x030C => 0x01D3
        | 0x030F => 0x0214
        | 0x0311 => 0x0216
        | 0x031B => 0x01AF
        | 0x0323 => 0x1EE4
        | 0x0324 => 0x1E72
        | 0x0328 => 0x0172
        | 0x032D => 0x1E76
        | 0x0330 => 0x1E74
        else None
        end
      | 0x0056 =>
        match rhs
        | 0x0303 => 0x1E7C
        | 0x0323 => 0x1E7E
        else None
        end
      | 0x0057 =>
        match rhs
        | 0x0300 => 0x1E80
        | 0x0301 => 0x1E82
        | 0x0302 => 0x0174
        | 0x0307 => 0x1E86
        | 0x0308 => 0x1E84
        | 0x0323 => 0x1E88
        else None
        end
      | 0x0058 =>
        match rhs
        | 0x0307 => 0x1E8A
        | 0x0308 => 0x1E8C
        else None
        end
      | 0x0059 =>
        match rhs
        | 0x0300 => 0x1EF2
        | 0x0301 => 0x00DD
        | 0x0302 => 0x0176
        | 0x0303 => 0x1EF8
        | 0x0304 => 0x0232
        | 0x0307 => 0x1E8E
        | 0x0308 => 0x0178
        | 0x0309 => 0x1EF6
        | 0x0323 => 0x1EF4
        else None
        end
      | 0x005A =>
        match rhs
        | 0x0301 => 0x0179
        | 0x0302 => 0x1E90
        | 0x0307 => 0x017B
        | 0x030C => 0x017D
        | 0x0323 => 0x1E92
        | 0x0331 => 0x1E94
        else None
        end
      | 0x0061 =>
        match rhs
        | 0x0300 => 0x00E0
        | 0x0301 => 0x00E1
        | 0x0302 => 0x00E2
        | 0x0303 => 0x00E3
        | 0x0304 => 0x0101
        | 0x0306 => 0x0103
        | 0x0307 => 0x0227
        | 0x0308 => 0x00E4
        | 0x0309 => 0x1EA3
        | 0x030A => 0x00E5
        | 0x030C => 0x01CE
        | 0x030F => 0x0201
        | 0x0311 => 0x0203
        | 0x0323 => 0x1EA1
        | 0x0325 => 0x1E01
        | 0x0328 => 0x0105
        else None
        end
      | 0x0062 =>
        match rhs
        | 0x0307 => 0x1E03
        | 0x0323 => 0x1E05
        | 0x0331 => 0x1E07
        else None
        end
      | 0x0063 =>
        match rhs
        | 0x0301 => 0x0107
        | 0x0302 => 0x0109
        | 0x0307 => 0x010B
        | 0x030C => 0x010D
        | 0x0327 => 0x00E7
        else None
        end
      | 0x0064 =>
        match rhs
        | 0x0307 => 0x1E0B
        | 0x030C => 0x010F
        | 0x0323 => 0x1E0D
        | 0x0327 => 0x1E11
        | 0x032D => 0x1E13
        | 0x0331 => 0x1E0F
        else None
        end
      | 0x0065 =>
        match rhs
        | 0x0300 => 0x00E8
        | 0x0301 => 0x00E9
        | 0x0302 => 0x00EA
        | 0x0303 => 0x1EBD
        | 0x0304 => 0x0113
        | 0x0306 => 0x0115
        | 0x0307 => 0x0117
        | 0x0308 => 0x00EB
        | 0x0309 => 0x1EBB
        | 0x030C => 0x011B
        | 0x030F => 0x0205
        | 0x0311 => 0x0207
        | 0x0323 => 0x1EB9
        | 0x0327 => 0x0229
        | 0x0328 => 0x0119
        | 0x032D => 0x1E19
        | 0x0330 => 0x1E1B
        else None
        end
      | 0x0066 =>
        match rhs
        | 0x0307 => 0x1E1F
        else None
        end
      | 0x0067 =>
        match rhs
        | 0x0301 => 0x01F5
        | 0x0302 => 0x011D
        | 0x0304 => 0x1E21
        | 0x0306 => 0x011F
        | 0x0307 => 0x0121
        | 0x030C => 0x01E7
        | 0x0327 => 0x0123
        else None
        end
      | 0x0068 =>
        match rhs
        | 0x0302 => 0x0125
        | 0x0307 => 0x1E23
        | 0x0308 => 0x1E27
        | 0x030C => 0x021F
        | 0x0323 => 0x1E25
        | 0x0327 => 0x1E29
        | 0x032E => 0x1E2B
        | 0x0331 => 0x1E96
        else None
        end
      | 0x0069 =>
        match rhs
        | 0x0300 => 0x00EC
        | 0x0301 => 0x00ED
        | 0x0302 => 0x00EE
        | 0x0303 => 0x0129
        | 0x0304 => 0x012B
        | 0x0306 => 0x012D
        | 0x0308 => 0x00EF
        | 0x0309 => 0x1EC9
        | 0x030C => 0x01D0
        | 0x030F => 0x0209
        | 0x0311 => 0x020B
        | 0x0323 => 0x1ECB
        | 0x0328 => 0x012F
        | 0x0330 => 0x1E2D
        else None
        end
      | 0x006A =>
        match rhs
        | 0x0302 => 0x0135
        | 0x030C => 0x01F0
        else None
        end
      | 0x006B =>
        match rhs
        | 0x0301 => 0x1E31
        | 0x030C => 0x01E9
        | 0x0323 => 0x1E33
        | 0x0327 => 0x0137
        | 0x0331 => 0x1E35
        else None
        end
      | 0x006C =>
        match rhs
        | 0x0301 => 0x013A
        | 0x030C => 0x013E
        | 0x0323 => 0x1E37
        | 0x0327 => 0x013C
        | 0x032D => 0x1E3D
        | 0x0331 => 0x1E3B
        else None
        end
      | 0x006D =>
        match rhs
        | 0x0301 => 0x1E3F
        | 0x0307 => 0x1E41
        | 0x0323 => 0x1E43
        else None
        end
      | 0x006E =>
        match rhs
        | 0x0300 => 0x01F9
        | 0x0301 => 0x0144
        | 0x0303 => 0x00F1
        | 0x0307 => 0x1E45
        | 0x030C => 0x0148
        | 0x0323 => 0x1E47
        | 0x0327 => 0x0146
        | 0x032D => 0x1E4B
        | 0x0331 => 0x1E49
        else None
        end
      | 0x006F =>
        match rhs
        | 0x0300 => 0x00F2
        | 0x0301 => 0x00F3
        | 0x0302 => 0x00F4
        | 0x0303 => 0x00F5
        | 0x0304 => 0x014D
        | 0x0306 => 0x014F
        | 0x0307 => 0x022F
        | 0x0308 => 0x00F6
        | 0x0309 => 0x1ECF
        | 0x030B => 0x0151
        | 0x030C => 0x01D2
        | 0x030F => 0x020D
        | 0x0311 => 0x020F
        | 0x031B => 0x01A1
        | 0x0323 => 0x1ECD
        | 0x0328 => 0x01EB
        else None
        end
      | 0x0070 =>
        match rhs
        | 0x0301 => 0x1E55
        | 0x0307 => 0x1E57
        else None
        end
      | 0x0072 =>
        match rhs
        | 0x0301 => 0x0155
        | 0x0307 => 0x1E59
        | 0x030C => 0x0159
        | 0x030F => 0x0211
        | 0x0311 => 0x0213
        | 0x0323 => 0x1E5B
        | 0x0327 => 0x0157
        | 0x0331 => 0x1E5F
        else None
        end
      | 0x0073 =>
        match rhs
        | 0x0301 => 0x015B
        | 0x0302 => 0x015D
        | 0x0307 => 0x1E61
        | 0x030C => 0x0161
        | 0x0323 => 0x1E63
        | 0x0326 => 0x0219
        | 0x0327 => 0x015F
        else None
        end
      | 0x0074 =>
        match rhs
        | 0x0307 => 0x1E6B
        | 0x0308 => 0x1E97
        | 0x030C => 0x0165
        | 0x0323 => 0x1E6D
        | 0x0326 => 0x021B
        | 0x0327 => 0x0163
        | 0x032D => 0x1E71
        | 0x0331 => 0x1E6F
        else None
        end
      | 0x0075 =>
        match rhs
        | 0x0300 => 0x00F9
        | 0x0301 => 0x00FA
        | 0x0302 => 0x00FB
        | 0x0303 => 0x0169
        | 0x0304 => 0x016B
        | 0x0306 => 0x016D
        | 0x0308 => 0x00FC
        | 0x0309 => 0x1EE7
        | 0x030A => 0x016F
        | 0x030B => 0x0171
        | 0x030C => 0x01D4
        | 0x030F => 0x0215
        | 0x0311 => 0x0217
        | 0x031B => 0x01B0
        | 0x0323 => 0x1EE5
        | 0x0324 => 0x1E73
        | 0x0328 => 0x0173
        | 0x032D => 0x1E77
        | 0x0330 => 0x1E75
        else None
        end
      | 0x0076 =>
        match rhs
        | 0x0303 => 0x1E7D
        | 0x0323 => 0x1E7F
        else None
        end
      | 0x0077 =>
        match rhs
        | 0x0300 => 0x1E81
        | 0x0301 => 0x1E83
        | 0x0302 => 0x0175
        | 0x0307 => 0x1E87
        | 0x0308 => 0x1E85
        | 0x030A => 0x1E98
        | 0x0323 => 0x1E89
        else None
        end
      | 0x0078 =>
        match rhs
        | 0x0307 => 0x1E8B
        | 0x0308 => 0x1E8D
        else None
        end
      | 0x0079 =>
        match rhs
        | 0x0300 => 0x1EF3
        | 0x0301 => 0x00FD
        | 0x0302 => 0x0177
        | 0x0303 => 0x1EF9
        | 0x0304 => 0x0233
        | 0x0307 => 0x1E8F
        | 0x0308 => 0x00FF
        | 0x0309 => 0x1EF7
        | 0x030A => 0x1E99
        | 0x0323 => 0x1EF5
        else None
        end
      | 0x007A =>
        match rhs
        | 0x0301 => 0x017A
        | 0x0302 => 0x1E91
        | 0x0307 => 0x017C
        | 0x030C => 0x017E
        | 0x0323 => 0x1E93
        | 0x0331 => 0x1E95
        else None
        end
      | 0x00A8 =>
        match rhs
        | 0x0300 => 0x1FED
        | 0x0301 => 0x0385
        | 0x0342 => 0x1FC1
        else None
        end
      | 0x00C2 =>
        match rhs
        | 0x0300 => 0x1EA6
        | 0x0301 => 0x1EA4
        | 0x0303 => 0x1EAA
        | 0x0309 => 0x1EA8
        else None
        end
      | 0x00C4 =>
        match rhs
        | 0x0304 => 0x01DE
        else None
        end
      | 0x00C5 =>
        match rhs
        | 0x0301 => 0x01FA
        else None
        end
      | 0x00C6 =>
        match rhs
        | 0x0301 => 0x01FC
        | 0x0304 => 0x01E2
        else None
        end
      | 0x00C7 =>
        match rhs
        | 0x0301 => 0x1E08
        else None
        end
      | 0x00CA =>
        match rhs
        | 0x0300 => 0x1EC0
        | 0x0301 => 0x1EBE
        | 0x0303 => 0x1EC4
        | 0x0309 => 0x1EC2
        else None
        end
      | 0x00CF =>
        match rhs
        | 0x0301 => 0x1E2E
        else None
        end
      | 0x00D4 =>
        match rhs
        | 0x0300 => 0x1ED2
        | 0x0301 => 0x1ED0
        | 0x0303 => 0x1ED6
        | 0x0309 => 0x1ED4
        else None
        end
      | 0x00D5 =>
        match rhs
        | 0x0301 => 0x1E4C
        | 0x0304 => 0x022C
        | 0x0308 => 0x1E4E
        else None
        end
      | 0x00D6 =>
        match rhs
        | 0x0304 => 0x022A
        else None
        end
      | 0x00D8 =>
        match rhs
        | 0x0301 => 0x01FE
        else None
        end
      | 0x00DC =>
        match rhs
        | 0x0300 => 0x01DB
        | 0x0301 => 0x01D7
        | 0x0304 => 0x01D5
        | 0x030C => 0x01D9
        else None
        end
      | 0x00E2 =>
        match rhs
        | 0x0300 => 0x1EA7
        | 0x0301 => 0x1EA5
        | 0x0303 => 0x1EAB
        | 0x0309 => 0x1EA9
        else None
        end
      | 0x00E4 =>
        match rhs
        | 0x0304 => 0x01DF
        else None
        end
      | 0x00E5 =>
        match rhs
        | 0x0301 => 0x01FB
        else None
        end
      | 0x00E6 =>
        match rhs
        | 0x0301 => 0x01FD
        | 0x0304 => 0x01E3
        else None
        end
      | 0x00E7 =>
        match rhs
        | 0x0301 => 0x1E09
        else None
        end
      | 0x00EA =>
        match rhs
        | 0x0300 => 0x1EC1
        | 0x0301 => 0x1EBF
        | 0x0303 => 0x1EC5
        | 0x0309 => 0x1EC3
        else None
        end
      | 0x00EF =>
        match rhs
        | 0x0301 => 0x1E2F
        else None
        end
      | 0x00F4 =>
        match rhs
        | 0x0300 => 0x1ED3
        | 0x0301 => 0x1ED1
        | 0x0303 => 0x1ED7
        | 0x0309 => 0x1ED5
        else None
        end
      | 0x00F5 =>
        match rhs
        | 0x0301 => 0x1E4D
        | 0x0304 => 0x022D
        | 0x0308 => 0x1E4F
        else None
        end
      | 0x00F6 =>
        match rhs
        | 0x0304 => 0x022B
        else None
        end
      | 0x00F8 =>
        match rhs
        | 0x0301 => 0x01FF
        else None
        end
      | 0x00FC =>
        match rhs
        | 0x0300 => 0x01DC
        | 0x0301 => 0x01D8
        | 0x0304 => 0x01D6
        | 0x030C => 0x01DA
        else None
        end
      | 0x0102 =>
        match rhs
        | 0x0300 => 0x1EB0
        | 0x0301 => 0x1EAE
        | 0x0303 => 0x1EB4
        | 0x0309 => 0x1EB2
        else None
        end
      | 0x0103 =>
        match rhs
        | 0x0300 => 0x1EB1
        | 0x0301 => 0x1EAF
        | 0x0303 => 0x1EB5
        | 0x0309 => 0x1EB3
        else None
        end
      | 0x0112 =>
        match rhs
        | 0x0300 => 0x1E14
        | 0x0301 => 0x1E16
        else None
        end
      | 0x0113 =>
        match rhs
        | 0x0300 => 0x1E15
        | 0x0301 => 0x1E17
        else None
        end
      | 0x014C =>
        match rhs
        | 0x0300 => 0x1E50
        | 0x0301 => 0x1E52
        else None
        end
      | 0x014D =>
        match rhs
        | 0x0300 => 0x1E51
        | 0x0301 => 0x1E53
        else None
        end
      | 0x015A =>
        match rhs
        | 0x0307 => 0x1E64
        else None
        end
      | 0x015B =>
        match rhs
        | 0x0307 => 0x1E65
        else None
        end
      | 0x0160 =>
        match rhs
        | 0x0307 => 0x1E66
        else None
        end
      | 0x0161 =>
        match rhs
        | 0x0307 => 0x1E67
        else None
        end
      | 0x0168 =>
        match rhs
        | 0x0301 => 0x1E78
        else None
        end
      | 0x0169 =>
        match rhs
        | 0x0301 => 0x1E79
        else None
        end
      | 0x016A =>
        match rhs
        | 0x0308 => 0x1E7A
        else None
        end
      | 0x016B =>
        match rhs
        | 0x0308 => 0x1E7B
        else None
        end
      | 0x017F =>
        match rhs
        | 0x0307 => 0x1E9B
        else None
        end
      | 0x01A0 =>
        match rhs
        | 0x0300 => 0x1EDC
        | 0x0301 => 0x1EDA
        | 0x0303 => 0x1EE0
        | 0x0309 => 0x1EDE
        | 0x0323 => 0x1EE2
        else None
        end
      | 0x01A1 =>
        match rhs
        | 0x0300 => 0x1EDD
        | 0x0301 => 0x1EDB
        | 0x0303 => 0x1EE1
        | 0x0309 => 0x1EDF
        | 0x0323 => 0x1EE3
        else None
        end
      | 0x01AF =>
        match rhs
        | 0x0300 => 0x1EEA
        | 0x0301 => 0x1EE8
        | 0x0303 => 0x1EEE
        | 0x0309 => 0x1EEC
        | 0x0323 => 0x1EF0
        else None
        end
      | 0x01B0 =>
        match rhs
        | 0x0300 => 0x1EEB
        | 0x0301 => 0x1EE9
        | 0x0303 => 0x1EEF
        | 0x0309 => 0x1EED
        | 0x0323 => 0x1EF1
        else None
        end
      | 0x01B7 =>
        match rhs
        | 0x030C => 0x01EE
        else None
        end
      | 0x01EA =>
        match rhs
        | 0x0304 => 0x01EC
        else None
        end
      | 0x01EB =>
        match rhs
        | 0x0304 => 0x01ED
        else None
        end
      | 0x0226 =>
        match rhs
        | 0x0304 => 0x01E0
        else None
        end
      | 0x0227 =>
        match rhs
        | 0x0304 => 0x01E1
        else None
        end
      | 0x0228 =>
        match rhs
        | 0x0306 => 0x1E1C
        else None
        end
      | 0x0229 =>
        match rhs
        | 0x0306 => 0x1E1D
        else None
        end
      | 0x022E =>
        match rhs
        | 0x0304 => 0x0230
        else None
        end
      | 0x022F =>
        match rhs
        | 0x0304 => 0x0231
        else None
        end
      | 0x0292 =>
        match rhs
        | 0x030C => 0x01EF
        else None
        end
      | 0x0391 =>
        match rhs
        | 0x0300 => 0x1FBA
        | 0x0301 => 0x0386
        | 0x0304 => 0x1FB9
        | 0x0306 => 0x1FB8
        | 0x0313 => 0x1F08
        | 0x0314 => 0x1F09
        | 0x0345 => 0x1FBC
        else None
        end
      | 0x0395 =>
        match rhs
        | 0x0300 => 0x1FC8
        | 0x0301 => 0x0388
        | 0x0313 => 0x1F18
        | 0x0314 => 0x1F19
        else None
        end
      | 0x0397 =>
        match rhs
        | 0x0300 => 0x1FCA
        | 0x0301 => 0x0389
        | 0x0313 => 0x1F28
        | 0x0314 => 0x1F29
        | 0x0345 => 0x1FCC
        else None
        end
      | 0x0399 =>
        match rhs
        | 0x0300 => 0x1FDA
        | 0x0301 => 0x038A
        | 0x0304 => 0x1FD9
        | 0x0306 => 0x1FD8
        | 0x0308 => 0x03AA
        | 0x0313 => 0x1F38
        | 0x0314 => 0x1F39
        else None
        end
      | 0x039F =>
        match rhs
        | 0x0300 => 0x1FF8
        | 0x0301 => 0x038C
        | 0x0313 => 0x1F48
        | 0x0314 => 0x1F49
        else None
        end
      | 0x03A1 =>
        match rhs
        | 0x0314 => 0x1FEC
        else None
        end
      | 0x03A5 =>
        match rhs
        | 0x0300 => 0x1FEA
        | 0x0301 => 0x038E
        | 0x0304 => 0x1FE9
        | 0x0306 => 0x1FE8
        | 0x0308 => 0x03AB
        | 0x0314 => 0x1F59
        else None
        end
      | 0x03A9 =>
        match rhs
        | 0x0300 => 0x1FFA
        | 0x0301 => 0x038F
        | 0x0313 => 0x1F68
        | 0x0314 => 0x1F69
        | 0x0345 => 0x1FFC
        else None
        end
      | 0x03AC =>
        match rhs
        | 0x0345 => 0x1FB4
        else None
        end
      | 0x03AE =>
        match rhs
        | 0x0345 => 0x1FC4
        else None
        end
      | 0x03B1 =>
        match rhs
        | 0x0300 => 0x1F70
        | 0x0301 => 0x03AC
        | 0x0304 => 0x1FB1
        | 0x0306 => 0x1FB0
        | 0x0313 => 0x1F00
        | 0x0314 => 0x1F01
        | 0x0342 => 0x1FB6
        | 0x0345 => 0x1FB3
        else None
        end
      | 0x03B5 =>
        match rhs
        | 0x0300 => 0x1F72
        | 0x0301 => 0x03AD
        | 0x0313 => 0x1F10
        | 0x0314 => 0x1F11
        else None
        end
      | 0x03B7 =>
        match rhs
        | 0x0300 => 0x1F74
        | 0x0301 => 0x03AE
        | 0x0313 => 0x1F20
        | 0x0314 => 0x1F21
        | 0x0342 => 0x1FC6
        | 0x0345 => 0x1FC3
        else None
        end
      | 0x03B9 =>
        match rhs
        | 0x0300 => 0x1F76
        | 0x0301 => 0x03AF
        | 0x0304 => 0x1FD1
        | 0x0306 => 0x1FD0
        | 0x0308 => 0x03CA
        | 0x0313 => 0x1F30
        | 0x0314 => 0x1F31
        | 0x0342 => 0x1FD6
        else None
        end
      | 0x03BF =>
        match rhs
        | 0x0300 => 0x1F78
        | 0x0301 => 0x03CC
        | 0x0313 => 0x1F40
        | 0x0314 => 0x1F41
        else None
        end
      | 0x03C1 =>
        match rhs
        | 0x0313 => 0x1FE4
        | 0x0314 => 0x1FE5
        else None
        end
      | 0x03C5 =>
        match rhs
        | 0x0300 => 0x1F7A
        | 0x0301 => 0x03CD
        | 0x0304 => 0x1FE1
        | 0x0306 => 0x1FE0
        | 0x0308 => 0x03CB
        | 0x0313 => 0x1F50
        | 0x0314 => 0x1F51
        | 0x0342 => 0x1FE6
        else None
        end
      | 0x03C9 =>
        match rhs
        | 0x0300 => 0x1F7C
        | 0x0301 => 0x03CE
        | 0x0313 => 0x1F60
        | 0x0314 => 0x1F61
        | 0x0342 => 0x1FF6
        | 0x0345 => 0x1FF3
        else None
        end
      | 0x03CA =>
        match rhs
        | 0x0300 => 0x1FD2
        | 0x0301 => 0x0390
        | 0x0342 => 0x1FD7
        else None
        end
      | 0x03CB =>
        match rhs
        | 0x0300 => 0x1FE2
        | 0x0301 => 0x03B0
        | 0x0342 => 0x1FE7
        else None
        end
      | 0x03CE =>
        match rhs
        | 0x0345 => 0x1FF4
        else None
        end
      | 0x03D2 =>
        match rhs
        | 0x0301 => 0x03D3
        | 0x0308 => 0x03D4
        else None
        end
      | 0x0406 =>
        match rhs
        | 0x0308 => 0x0407
        else None
        end
      | 0x0410 =>
        match rhs
        | 0x0306 => 0x04D0
        | 0x0308 => 0x04D2
        else None
        end
      | 0x0413 =>
        match rhs
        | 0x0301 => 0x0403
        else None
        end
      | 0x0415 =>
        match rhs
        | 0x0300 => 0x0400
        | 0x0306 => 0x04D6
        | 0x0308 => 0x0401
        else None
        end
      | 0x0416 =>
        match rhs
        | 0x0306 => 0x04C1
        | 0x0308 => 0x04DC
        else None
        end
      | 0x0417 =>
        match rhs
        | 0x0308 => 0x04DE
        else None
        end
      | 0x0418 =>
        match rhs
        | 0x0300 => 0x040D
        | 0x0304 => 0x04E2
        | 0x0306 => 0x0419
        | 0x0308 => 0x04E4
        else None
        end
      | 0x041A =>
        match rhs
        | 0x0301 => 0x040C
        else None
        end
      | 0x041E =>
        match rhs
        | 0x0308 => 0x04E6
        else None
        end
      | 0x0423 =>
        match rhs
        | 0x0304 => 0x04EE
        | 0x0306 => 0x040E
        | 0x0308 => 0x04F0
        | 0x030B => 0x04F2
        else None
        end
      | 0x0427 =>
        match rhs
        | 0x0308 => 0x04F4
        else None
        end
      | 0x042B =>
        match rhs
        | 0x0308 => 0x04F8
        else None
        end
      | 0x042D =>
        match rhs
        | 0x0308 => 0x04EC
        else None
        end
      | 0x0430 =>
        match rhs
        | 0x0306 => 0x04D1
        | 0x0308 => 0x04D3
        else None
        end
      | 0x0433 =>
        match rhs
        | 0x0301 => 0x0453
        else None
        end
      | 0x0435 =>
        match rhs
        | 0x0300 => 0x0450
        | 0x0306 => 0x04D7
        | 0x0308 => 0x0451
        else None
        end
      | 0x0436 =>
        match rhs
        | 0x0306 => 0x04C2
        | 0x0308 => 0x04DD
        else None
        end
      | 0x0437 =>
        match rhs
        | 0x0308 => 0x04DF
        else None
        end
      | 0x0438 =>
        match rhs
        | 0x0300 => 0x045D
        | 0x0304 => 0x04E3
        | 0x0306 => 0x0439
        | 0x0308 => 0x04E5
        else None
        end
      | 0x043A =>
        match rhs
        | 0x0301 => 0x045C
        else None
        end
      | 0x043E =>
        match rhs
        | 0x0308 => 0x04E7
        else None
        end
      | 0x0443 =>
        match rhs
        | 0x0304 => 0x04EF
        | 0x0306 => 0x045E
        | 0x0308 => 0x04F1
        | 0x030B => 0x04F3
        else None
        end
      | 0x0447 =>
        match rhs
        | 0x0308 => 0x04F5
        else None
        end
      | 0x044B =>
        match rhs
        | 0x0308 => 0x04F9
        else None
        end
      | 0x044D =>
        match rhs
        | 0x0308 => 0x04ED
        else None
        end
      | 0x0456 =>
        match rhs
        | 0x0308 => 0x0457
        else None
        end
      | 0x0474 =>
        match rhs
        | 0x030F => 0x0476
        else None
        end
      | 0x0475 =>
        match rhs
        | 0x030F => 0x0477
        else None
        end
      | 0x04D8 =>
        match rhs
        | 0x0308 => 0x04DA
        else None
        end
      | 0x04D9 =>
        match rhs
        | 0x0308 => 0x04DB
        else None
        end
      | 0x04E8 =>
        match rhs
        | 0x0308 => 0x04EA
        else None
        end
      | 0x04E9 =>
        match rhs
        | 0x0308 => 0x04EB
        else None
        end
      | 0x0627 =>
        match rhs
        | 0x0653 => 0x0622
        | 0x0654 => 0x0623
        | 0x0655 => 0x0625
        else None
        end
      | 0x0648 =>
        match rhs
        | 0x0654 => 0x0624
        else None
        end
      | 0x064A =>
        match rhs
        | 0x0654 => 0x0626
        else None
        end
      | 0x06C1 =>
        match rhs
        | 0x0654 => 0x06C2
        else None
        end
      | 0x06D2 =>
        match rhs
        | 0x0654 => 0x06D3
        else None
        end
      | 0x06D5 =>
        match rhs
        | 0x0654 => 0x06C0
        else None
        end
      | 0x0928 =>
        match rhs
        | 0x093C => 0x0929
        else None
        end
      | 0x0930 =>
        match rhs
        | 0x093C => 0x0931
        else None
        end
      | 0x0933 =>
        match rhs
        | 0x093C => 0x0934
        else None
        end
      | 0x09C7 =>
        match rhs
        | 0x09BE => 0x09CB
        | 0x09D7 => 0x09CC
        else None
        end
      | 0x0B47 =>
        match rhs
        | 0x0B3E => 0x0B4B
        | 0x0B56 => 0x0B48
        | 0x0B57 => 0x0B4C
        else None
        end
      | 0x0B92 =>
        match rhs
        | 0x0BD7 => 0x0B94
        else None
        end
      | 0x0BC6 =>
        match rhs
        | 0x0BBE => 0x0BCA
        | 0x0BD7 => 0x0BCC
        else None
        end
      | 0x0BC7 =>
        match rhs
        | 0x0BBE => 0x0BCB
        else None
        end
      | 0x0C46 =>
        match rhs
        | 0x0C56 => 0x0C48
        else None
        end
      | 0x0CBF =>
        match rhs
        | 0x0CD5 => 0x0CC0
        else None
        end
      | 0x0CC6 =>
        match rhs
        | 0x0CC2 => 0x0CCA
        | 0x0CD5 => 0x0CC7
        | 0x0CD6 => 0x0CC8
        else None
        end
      | 0x0CCA =>
        match rhs
        | 0x0CD5 => 0x0CCB
        else None
        end
      | 0x0D46 =>
        match rhs
        | 0x0D3E => 0x0D4A
        | 0x0D57 => 0x0D4C
        else None
        end
      | 0x0D47 =>
        match rhs
        | 0x0D3E => 0x0D4B
        else None
        end
      | 0x0DD9 =>
        match rhs
        | 0x0DCA => 0x0DDA
        | 0x0DCF => 0x0DDC
        | 0x0DDF => 0x0DDE
        else None
        end
      | 0x0DDC =>
        match rhs
        | 0x0DCA => 0x0DDD
        else None
        end
      else None
      end
    | 0x0001 =>
      match lhs
      | 0x1025 =>
        match rhs
        | 0x102E => 0x1026
        else None
        end
      | 0x1B05 =>
        match rhs
        | 0x1B35 => 0x1B06
        else None
        end
      | 0x1B07 =>
        match rhs
        | 0x1B35 => 0x1B08
        else None
        end
      | 0x1B09 =>
        match rhs
        | 0x1B35 => 0x1B0A
        else None
        end
      | 0x1B0B =>
        match rhs
        | 0x1B35 => 0x1B0C
        else None
        end
      | 0x1B0D =>
        match rhs
        | 0x1B35 => 0x1B0E
        else None
        end
      | 0x1B11 =>
        match rhs
        | 0x1B35 => 0x1B12
        else None
        end
      | 0x1B3A =>
        match rhs
        | 0x1B35 => 0x1B3B
        else None
        end
      | 0x1B3C =>
        match rhs
        | 0x1B35 => 0x1B3D
        else None
        end
      | 0x1B3E =>
        match rhs
        | 0x1B35 => 0x1B40
        else None
        end
      | 0x1B3F =>
        match rhs
        | 0x1B35 => 0x1B41
        else None
        end
      | 0x1B42 =>
        match rhs
        | 0x1B35 => 0x1B43
        else None
        end
      | 0x1E36 =>
        match rhs
        | 0x0304 => 0x1E38
        else None
        end
      | 0x1E37 =>
        match rhs
        | 0x0304 => 0x1E39
        else None
        end
      | 0x1E5A =>
        match rhs
        | 0x0304 => 0x1E5C
        else None
        end
      | 0x1E5B =>
        match rhs
        | 0x0304 => 0x1E5D
        else None
        end
      | 0x1E62 =>
        match rhs
        | 0x0307 => 0x1E68
        else None
        end
      | 0x1E63 =>
        match rhs
        | 0x0307 => 0x1E69
        else None
        end
      | 0x1EA0 =>
        match rhs
        | 0x0302 => 0x1EAC
        | 0x0306 => 0x1EB6
        else None
        end
      | 0x1EA1 =>
        match rhs
        | 0x0302 => 0x1EAD
        | 0x0306 => 0x1EB7
        else None
        end
      | 0x1EB8 =>
        match rhs
        | 0x0302 => 0x1EC6
        else None
        end
      | 0x1EB9 =>
        match rhs
        | 0x0302 => 0x1EC7
        else None
        end
      | 0x1ECC =>
        match rhs
        | 0x0302 => 0x1ED8
        else None
        end
      | 0x1ECD =>
        match rhs
        | 0x0302 => 0x1ED9
        else None
        end
      | 0x1F00 =>
        match rhs
        | 0x0300 => 0x1F02
        | 0x0301 => 0x1F04
        | 0x0342 => 0x1F06
        | 0x0345 => 0x1F80
        else None
        end
      | 0x1F01 =>
        match rhs
        | 0x0300 => 0x1F03
        | 0x0301 => 0x1F05
        | 0x0342 => 0x1F07
        | 0x0345 => 0x1F81
        else None
        end
      | 0x1F02 =>
        match rhs
        | 0x0345 => 0x1F82
        else None
        end
      | 0x1F03 =>
        match rhs
        | 0x0345 => 0x1F83
        else None
        end
      | 0x1F04 =>
        match rhs
        | 0x0345 => 0x1F84
        else None
        end
      | 0x1F05 =>
        match rhs
        | 0x0345 => 0x1F85
        else None
        end
      | 0x1F06 =>
        match rhs
        | 0x0345 => 0x1F86
        else None
        end
      | 0x1F07 =>
        match rhs
        | 0x0345 => 0x1F87
        else None
        end
      | 0x1F08 =>
        match rhs
        | 0x0300 => 0x1F0A
        | 0x0301 => 0x1F0C
        | 0x0342 => 0x1F0E
        | 0x0345 => 0x1F88
        else None
        end
      | 0x1F09 =>
        match rhs
        | 0x0300 => 0x1F0B
        | 0x0301 => 0x1F0D
        | 0x0342 => 0x1F0F
        | 0x0345 => 0x1F89
        else None
        end
      | 0x1F0A =>
        match rhs
        | 0x0345 => 0x1F8A
        else None
        end
      | 0x1F0B =>
        match rhs
        | 0x0345 => 0x1F8B
        else None
        end
      | 0x1F0C =>
        match rhs
        | 0x0345 => 0x1F8C
        else None
        end
      | 0x1F0D =>
        match rhs
        | 0x0345 => 0x1F8D
        else None
        end
      | 0x1F0E =>
        match rhs
        | 0x0345 => 0x1F8E
        else None
        end
      | 0x1F0F =>
        match rhs
        | 0x0345 => 0x1F8F
        else None
        end
      | 0x1F10 =>
        match rhs
        | 0x0300 => 0x1F12
        | 0x0301 => 0x1F14
        else None
        end
      | 0x1F11 =>
        match rhs
        | 0x0300 => 0x1F13
        | 0x0301 => 0x1F15
        else None
        end
      | 0x1F18 =>
        match rhs
        | 0x0300 => 0x1F1A
        | 0x0301 => 0x1F1C
        else None
        end
      | 0x1F19 =>
        match rhs
        | 0x0300 => 0x1F1B
        | 0x0301 => 0x1F1D
        else None
        end
      | 0x1F20 =>
        match rhs
        | 0x0300 => 0x1F22
        | 0x0301 => 0x1F24
        | 0x0342 => 0x1F26
        | 0x0345 => 0x1F90
        else None
        end
      | 0x1F21 =>
        match rhs
        | 0x0300 => 0x1F23
        | 0x0301 => 0x1F25
        | 0x0342 => 0x1F27
        | 0x0345 => 0x1F91
        else None
        end
      | 0x1F22 =>
        match rhs
        | 0x0345 => 0x1F92
        else None
        end
      | 0x1F23 =>
        match rhs
        | 0x0345 => 0x1F93
        else None
        end
      | 0x1F24 =>
        match rhs
        | 0x0345 => 0x1F94
        else None
        end
      | 0x1F25 =>
        match rhs
        | 0x0345 => 0x1F95
        else None
        end
      | 0x1F26 =>
        match rhs
        | 0x0345 => 0x1F96
        else None
        end
      | 0x1F27 =>
        match rhs
        | 0x0345 => 0x1F97
        else None
        end
      | 0x1F28 =>
        match rhs
        | 0x0300 => 0x1F2A
        | 0x0301 => 0x1F2C
        | 0x0342 => 0x1F2E
        | 0x0345 => 0x1F98
        else None
        end
      | 0x1F29 =>
        match rhs
        | 0x0300 => 0x1F2B
        | 0x0301 => 0x1F2D
        | 0x0342 => 0x1F2F
        | 0x0345 => 0x1F99
        else None
        end
      | 0x1F2A =>
        match rhs
        | 0x0345 => 0x1F9A
        else None
        end
      | 0x1F2B =>
        match rhs
        | 0x0345 => 0x1F9B
        else None
        end
      | 0x1F2C =>
        match rhs
        | 0x0345 => 0x1F9C
        else None
        end
      | 0x1F2D =>
        match rhs
        | 0x0345 => 0x1F9D
        else None
        end
      | 0x1F2E =>
        match rhs
        | 0x0345 => 0x1F9E
        else None
        end
      | 0x1F2F =>
        match rhs
        | 0x0345 => 0x1F9F
        else None
        end
      | 0x1F30 =>
        match rhs
        | 0x0300 => 0x1F32
        | 0x0301 => 0x1F34
        | 0x0342 => 0x1F36
        else None
        end
      | 0x1F31 =>
        match rhs
        | 0x0300 => 0x1F33
        | 0x0301 => 0x1F35
        | 0x0342 => 0x1F37
        else None
        end
      | 0x1F38 =>
        match rhs
        | 0x0300 => 0x1F3A
        | 0x0301 => 0x1F3C
        | 0x0342 => 0x1F3E
        else None
        end
      | 0x1F39 =>
        match rhs
        | 0x0300 => 0x1F3B
        | 0x0301 => 0x1F3D
        | 0x0342 => 0x1F3F
        else None
        end
      | 0x1F40 =>
        match rhs
        | 0x0300 => 0x1F42
        | 0x0301 => 0x1F44
        else None
        end
      | 0x1F41 =>
        match rhs
        | 0x0300 => 0x1F43
        | 0x0301 => 0x1F45
        else None
        end
      | 0x1F48 =>
        match rhs
        | 0x0300 => 0x1F4A
        | 0x0301 => 0x1F4C
        else None
        end
      | 0x1F49 =>
        match rhs
        | 0x0300 => 0x1F4B
        | 0x0301 => 0x1F4D
        else None
        end
      | 0x1F50 =>
        match rhs
        | 0x0300 => 0x1F52
        | 0x0301 => 0x1F54
        | 0x0342 => 0x1F56
        else None
        end
      | 0x1F51 =>
        match rhs
        | 0x0300 => 0x1F53
        | 0x0301 => 0x1F55
        | 0x0342 => 0x1F57
        else None
        end
      | 0x1F59 =>
        match rhs
        | 0x0300 => 0x1F5B
        | 0x0301 => 0x1F5D
        | 0x0342 => 0x1F5F
        else None
        end
      | 0x1F60 =>
        match rhs
        | 0x0300 => 0x1F62
        | 0x0301 => 0x1F64
        | 0x0342 => 0x1F66
        | 0x0345 => 0x1FA0
        else None
        end
      | 0x1F61 =>
        match rhs
        | 0x0300 => 0x1F63
        | 0x0301 => 0x1F65
        | 0x0342 => 0x1F67
        | 0x0345 => 0x1FA1
        else None
        end
      | 0x1F62 =>
        match rhs
        | 0x0345 => 0x1FA2
        else None
        end
      | 0x1F63 =>
        match rhs
        | 0x0345 => 0x1FA3
        else None
        end
      | 0x1F64 =>
        match rhs
        | 0x0345 => 0x1FA4
        else None
        end
      | 0x1F65 =>
        match rhs
        | 0x0345 => 0x1FA5
        else None
        end
      | 0x1F66 =>
        match rhs
        | 0x0345 => 0x1FA6
        else None
        end
      | 0x1F67 =>
        match rhs
        | 0x0345 => 0x1FA7
        else None
        end
      | 0x1F68 =>
        match rhs
        | 0x0300 => 0x1F6A
        | 0x0301 => 0x1F6C
        | 0x0342 => 0x1F6E
        | 0x0345 => 0x1FA8
        else None
        end
      | 0x1F69 =>
        match rhs
        | 0x0300 => 0x1F6B
        | 0x0301 => 0x1F6D
        | 0x0342 => 0x1F6F
        | 0x0345 => 0x1FA9
        else None
        end
      | 0x1F6A =>
        match rhs
        | 0x0345 => 0x1FAA
        else None
        end
      | 0x1F6B =>
        match rhs
        | 0x0345 => 0x1FAB
        else None
        end
      | 0x1F6C =>
        match rhs
        | 0x0345 => 0x1FAC
        else None
        end
      | 0x1F6D =>
        match rhs
        | 0x0345 => 0x1FAD
        else None
        end
      | 0x1F6E =>
        match rhs
        | 0x0345 => 0x1FAE
        else None
        end
      | 0x1F6F =>
        match rhs
        | 0x0345 => 0x1FAF
        else None
        end
      | 0x1F70 =>
        match rhs
        | 0x0345 => 0x1FB2
        else None
        end
      | 0x1F74 =>
        match rhs
        | 0x0345 => 0x1FC2
        else None
        end
      | 0x1F7C =>
        match rhs
        | 0x0345 => 0x1FF2
        else None
        end
      | 0x1FB6 =>
        match rhs
        | 0x0345 => 0x1FB7
        else None
        end
      | 0x1FBF =>
        match rhs
        | 0x0300 => 0x1FCD
        | 0x0301 => 0x1FCE
        | 0x0342 => 0x1FCF
        else None
        end
      | 0x1FC6 =>
        match rhs
        | 0x0345 => 0x1FC7
        else None
        end
      | 0x1FF6 =>
        match rhs
        | 0x0345 => 0x1FF7
        else None
        end
      | 0x1FFE =>
        match rhs
        | 0x0300 => 0x1FDD
        | 0x0301 => 0x1FDE
        | 0x0342 => 0x1FDF
        else None
        end
      else None
      end
    | 0x0002 =>
      match lhs
      | 0x2190 =>
        match rhs
        | 0x0338 => 0x219A
        else None
        end
      | 0x2192 =>
        match rhs
        | 0x0338 => 0x219B
        else None
        end
      | 0x2194 =>
        match rhs
        | 0x0338 => 0x21AE
        else None
        end
      | 0x21D0 =>
        match rhs
        | 0x0338 => 0x21CD
        else None
        end
      | 0x21D2 =>
        match rhs
        | 0x0338 => 0x21CF
        else None
        end
      | 0x21D4 =>
        match rhs
        | 0x0338 => 0x21CE
        else None
        end
      | 0x2203 =>
        match rhs
        | 0x0338 => 0x2204
        else None
        end
      | 0x2208 =>
        match rhs
        | 0x0338 => 0x2209
        else None
        end
      | 0x220B =>
        match rhs
        | 0x0338 => 0x220C
        else None
        end
      | 0x2223 =>
        match rhs
        | 0x0338 => 0x2224
        else None
        end
      | 0x2225 =>
        match rhs
        | 0x0338 => 0x2226
        else None
        end
      | 0x223C =>
        match rhs
        | 0x0338 => 0x2241
        else None
        end
      | 0x2243 =>
        match rhs
        | 0x0338 => 0x2244
        else None
        end
      | 0x2245 =>
        match rhs
        | 0x0338 => 0x2247
        else None
        end
      | 0x2248 =>
        match rhs
        | 0x0338 => 0x2249
        else None
        end
      | 0x224D =>
        match rhs
        | 0x0338 => 0x226D
        else None
        end
      | 0x2261 =>
        match rhs
        | 0x0338 => 0x2262
        else None
        end
      | 0x2264 =>
        match rhs
        | 0x0338 => 0x2270
        else None
        end
      | 0x2265 =>
        match rhs
        | 0x0338 => 0x2271
        else None
        end
      | 0x2272 =>
        match rhs
        | 0x0338 => 0x2274
        else None
        end
      | 0x2273 =>
        match rhs
        | 0x0338 => 0x2275
        else None
        end
      | 0x2276 =>
        match rhs
        | 0x0338 => 0x2278
        else None
        end
      | 0x2277 =>
        match rhs
        | 0x0338 => 0x2279
        else None
        end
      | 0x227A =>
        match rhs
        | 0x0338 => 0x2280
        else None
        end
      | 0x227B =>
        match rhs
        | 0x0338 => 0x2281
        else None
        end
      | 0x227C =>
        match rhs
        | 0x0338 => 0x22E0
        else None
        end
      | 0x227D =>
        match rhs
        | 0x0338 => 0x22E1
        else None
        end
      | 0x2282 =>
        match rhs
        | 0x0338 => 0x2284
        else None
        end
      | 0x2283 =>
        match rhs
        | 0x0338 => 0x2285
        else None
        end
      | 0x2286 =>
        match rhs
        | 0x0338 => 0x2288
        else None
        end
      | 0x2287 =>
        match rhs
        | 0x0338 => 0x2289
        else None
        end
      | 0x2291 =>
        match rhs
        | 0x0338 => 0x22E2
        else None
        end
      | 0x2292 =>
        match rhs
        | 0x0338 => 0x22E3
        else None
        end
      | 0x22A2 =>
        match rhs
        | 0x0338 => 0x22AC
        else None
        end
      | 0x22A8 =>
        match rhs
        | 0x0338 => 0x22AD
        else None
        end
      | 0x22A9 =>
        match rhs
        | 0x0338 => 0x22AE
        else None
        end
      | 0x22AB =>
        match rhs
        | 0x0338 => 0x22AF
        else None
        end
      | 0x22B2 =>
        match rhs
        | 0x0338 => 0x22EA
        else None
        end
      | 0x22B3 =>
        match rhs
        | 0x0338 => 0x22EB
        else None
        end
      | 0x22B4 =>
        match rhs
        | 0x0338 => 0x22EC
        else None
        end
      | 0x22B5 =>
        match rhs
        | 0x0338 => 0x22ED
        else None
        end
      else None
      end
    | 0x0003 =>
      match lhs
      | 0x3046 =>
        match rhs
        | 0x3099 => 0x3094
        else None
        end
      | 0x304B =>
        match rhs
        | 0x3099 => 0x304C
        else None
        end
      | 0x304D =>
        match rhs
        | 0x3099 => 0x304E
        else None
        end
      | 0x304F =>
        match rhs
        | 0x3099 => 0x3050
        else None
        end
      | 0x3051 =>
        match rhs
        | 0x3099 => 0x3052
        else None
        end
      | 0x3053 =>
        match rhs
        | 0x3099 => 0x3054
        else None
        end
      | 0x3055 =>
        match rhs
        | 0x3099 => 0x3056
        else None
        end
      | 0x3057 =>
        match rhs
        | 0x3099 => 0x3058
        else None
        end
      | 0x3059 =>
        match rhs
        | 0x3099 => 0x305A
        else None
        end
      | 0x305B =>
        match rhs
        | 0x3099 => 0x305C
        else None
        end
      | 0x305D =>
        match rhs
        | 0x3099 => 0x305E
        else None
        end
      | 0x305F =>
        match rhs
        | 0x3099 => 0x3060
        else None
        end
      | 0x3061 =>
        match rhs
        | 0x3099 => 0x3062
        else None
        end
      | 0x3064 =>
        match rhs
        | 0x3099 => 0x3065
        else None
        end
      | 0x3066 =>
        match rhs
        | 0x3099 => 0x3067
        else None
        end
      | 0x3068 =>
        match rhs
        | 0x3099 => 0x3069
        else None
        end
      | 0x306F =>
        match rhs
        | 0x3099 => 0x3070
        | 0x309A => 0x3071
        else None
        end
      | 0x3072 =>
        match rhs
        | 0x3099 => 0x3073
        | 0x309A => 0x3074
        else None
        end
      | 0x3075 =>
        match rhs
        | 0x3099 => 0x3076
        | 0x309A => 0x3077
        else None
        end
      | 0x3078 =>
        match rhs
        | 0x3099 => 0x3079
        | 0x309A => 0x307A
        else None
        end
      | 0x307B =>
        match rhs
        | 0x3099 => 0x307C
        | 0x309A => 0x307D
        else None
        end
      | 0x309D =>
        match rhs
        | 0x3099 => 0x309E
        else None
        end
      | 0x30A6 =>
        match rhs
        | 0x3099 => 0x30F4
        else None
        end
      | 0x30AB =>
        match rhs
        | 0x3099 => 0x30AC
        else None
        end
      | 0x30AD =>
        match rhs
        | 0x3099 => 0x30AE
        else None
        end
      | 0x30AF =>
        match rhs
        | 0x3099 => 0x30B0
        else None
        end
      | 0x30B1 =>
        match rhs
        | 0x3099 => 0x30B2
        else None
        end
      | 0x30B3 =>
        match rhs
        | 0x3099 => 0x30B4
        else None
        end
      | 0x30B5 =>
        match rhs
        | 0x3099 => 0x30B6
        else None
        end
      | 0x30B7 =>
        match rhs
        | 0x3099 => 0x30B8
        else None
        end
      | 0x30B9 =>
        match rhs
        | 0x3099 => 0x30BA
        else None
        end
      | 0x30BB =>
        match rhs
        | 0x3099 => 0x30BC
        else None
        end
      | 0x30BD =>
        match rhs
        | 0x3099 => 0x30BE
        else None
        end
      | 0x30BF =>
        match rhs
        | 0x3099 => 0x30C0
        else None
        end
      | 0x30C1 =>
        match rhs
        | 0x3099 => 0x30C2
        else None
        end
      | 0x30C4 =>
        match rhs
        | 0x3099 => 0x30C5
        else None
        end
      | 0x30C6 =>
        match rhs
        | 0x3099 => 0x30C7
        else None
        end
      | 0x30C8 =>
        match rhs
        | 0x3099 => 0x30C9
        else None
        end
      | 0x30CF =>
        match rhs
        | 0x3099 => 0x30D0
        | 0x309A => 0x30D1
        else None
        end
      | 0x30D2 =>
        match rhs
        | 0x3099 => 0x30D3
        | 0x309A => 0x30D4
        else None
        end
      | 0x30D5 =>
        match rhs
        | 0x3099 => 0x30D6
        | 0x309A => 0x30D7
        else None
        end
      | 0x30D8 =>
        match rhs
        | 0x3099 => 0x30D9
        | 0x309A => 0x30DA
        else None
        end
      | 0x30DB =>
        match rhs
        | 0x3099 => 0x30DC
        | 0x309A => 0x30DD
        else None
        end
      | 0x30EF =>
        match rhs
        | 0x3099 => 0x30F7
        else None
        end
      | 0x30F0 =>
        match rhs
        | 0x3099 => 0x30F8
        else None
        end
      | 0x30F1 =>
        match rhs
        | 0x3099 => 0x30F9
        else None
        end
      | 0x30F2 =>
        match rhs
        | 0x3099 => 0x30FA
        else None
        end
      | 0x30FD =>
        match rhs
        | 0x3099 => 0x30FE
        else None
        end
      else None
      end
    | 0x0010 =>
      match lhs
      | 0x105D2 =>
        match rhs
        | 0x0307 => 0x105C9
        else None
        end
      | 0x105DA =>
        match rhs
        | 0x0307 => 0x105E4
        else None
        end
      else None
      end
    | 0x0011 =>
      match lhs
      | 0x11099 =>
        match rhs
        | 0x110BA => 0x1109A
        else None
        end
      | 0x1109B =>
        match rhs
        | 0x110BA => 0x1109C
        else None
        end
      | 0x110A5 =>
        match rhs
        | 0x110BA => 0x110AB
        else None
        end
      | 0x11131 =>
        match rhs
        | 0x11127 => 0x1112E
        else None
        end
      | 0x11132 =>
        match rhs
        | 0x11127 => 0x1112F
        else None
        end
      | 0x11347 =>
        match rhs
        | 0x1133E => 0x1134B
        | 0x11357 => 0x1134C
        else None
        end
      | 0x11382 =>
        match rhs
        | 0x113C9 => 0x11383
        else None
        end
      | 0x11384 =>
        match rhs
        | 0x113BB => 0x11385
        else None
        end
      | 0x1138B =>
        match rhs
        | 0x113C2 => 0x1138E
        else None
        end
      | 0x11390 =>
        match rhs
        | 0x113C9 => 0x11391
        else None
        end
      | 0x113C2 =>
        match rhs
        | 0x113B8 => 0x113C7
        | 0x113C2 => 0x113C5
        | 0x113C9 => 0x113C8
        else None
        end
      | 0x114B9 =>
        match rhs
        | 0x114B0 => 0x114BC
        | 0x114BA => 0x114BB
        | 0x114BD => 0x114BE
        else None
        end
      | 0x115B8 =>
        match rhs
        | 0x115AF => 0x115BA
        else None
        end
      | 0x115B9 =>
        match rhs
        | 0x115AF => 0x115BB
        else None
        end
      | 0x11935 =>
        match rhs
        | 0x11930 => 0x11938
        else None
        end
      else None
      end
    | 0x0016 =>
      match lhs
      | 0x1611E =>
        match rhs
        | 0x1611E => 0x16121
        | 0x1611F => 0x16123
        | 0x16120 => 0x16125
        | 0x16129 => 0x16122
        else None
        end
      | 0x16121 =>
        match rhs
        | 0x1611F => 0x16126
        | 0x16120 => 0x16128
        else None
        end
      | 0x16122 =>
        match rhs
        | 0x1611F => 0x16127
        else None
        end
      | 0x16129 =>
        match rhs
        | 0x1611F => 0x16124
        else None
        end
      | 0x16D63 =>
        match rhs
        | 0x16D67 => 0x16D69
        else None
        end
      | 0x16D67 =>
        match rhs
        | 0x16D67 => 0x16D68
        else None
        end
      | 0x16D69 =>
        match rhs
        | 0x16D67 => 0x16D6A
        else None
        end
      else None
      end
    else
      None
    end
