// Auto-generated by unicode-build. Do not edit by hand.
// Regenerate via:
//   make ucd-generate
//
// Source: UnicodeData.txt Canonical_Combining_Class field.
// Only non-zero entries are stored; lookups default to 0.
use @ucd_ccc_lookup[U8](cp: U32)

primitive _UcdCombiningClass
  fun of(cp: U32): U8 =>
    @ucd_ccc_lookup(cp)
