// Auto-generated by unicode-build. Do not edit by hand.
// Regenerate via:
//   make ucd-generate
//
// Source: Scripts.txt. Codepoints outside any range
// default to ScriptUnknown.

primitive _UcdScript
  fun of(cp: U32): Script =>
    match cp >> 12
    | 0x0000 =>
      match cp
      | let c: U32 if c <= 0x0040 => ScriptCommon
      | let c: U32 if c <= 0x005A => ScriptLatin
      | let c: U32 if c <= 0x0060 => ScriptCommon
      | let c: U32 if c <= 0x007A => ScriptLatin
      | let c: U32 if c <= 0x00A9 => ScriptCommon
      | let c: U32 if c <= 0x00AA => ScriptLatin
      | let c: U32 if c <= 0x00B9 => ScriptCommon
      | let c: U32 if c <= 0x00BA => ScriptLatin
      | let c: U32 if c <= 0x00BF => ScriptCommon
      | let c: U32 if c <= 0x00D6 => ScriptLatin
      | let c: U32 if c <= 0x00D7 => ScriptCommon
      | let c: U32 if c <= 0x00F6 => ScriptLatin
      | let c: U32 if c <= 0x00F7 => ScriptCommon
      | let c: U32 if c <= 0x02B8 => ScriptLatin
      | let c: U32 if c <= 0x02DF => ScriptCommon
      | let c: U32 if c <= 0x02E4 => ScriptLatin
      | let c: U32 if c <= 0x02E9 => ScriptCommon
      | let c: U32 if c <= 0x02EB => ScriptBopomofo
      | let c: U32 if c <= 0x02FF => ScriptCommon
      | let c: U32 if c <= 0x036F => ScriptInherited
      | let c: U32 if c <= 0x0373 => ScriptGreek
      | let c: U32 if c <= 0x0374 => ScriptCommon
      | let c: U32 if c <= 0x0377 => ScriptGreek
      | let c: U32 if c <= 0x0379 => ScriptUnknown
      | let c: U32 if c <= 0x037D => ScriptGreek
      | let c: U32 if c <= 0x037E => ScriptCommon
      | let c: U32 if c <= 0x037F => ScriptGreek
      | let c: U32 if c <= 0x0383 => ScriptUnknown
      | let c: U32 if c <= 0x0384 => ScriptGreek
      | let c: U32 if c <= 0x0385 => ScriptCommon
      | let c: U32 if c <= 0x0386 => ScriptGreek
      | let c: U32 if c <= 0x0387 => ScriptCommon
      | let c: U32 if c <= 0x038A => ScriptGreek
      | let c: U32 if c <= 0x038B => ScriptUnknown
      | let c: U32 if c <= 0x038C => ScriptGreek
      | let c: U32 if c <= 0x038D => ScriptUnknown
      | let c: U32 if c <= 0x03A1 => ScriptGreek
      | let c: U32 if c <= 0x03A2 => ScriptUnknown
      | let c: U32 if c <= 0x03E1 => ScriptGreek
      | let c: U32 if c <= 0x03EF => ScriptCoptic
      | let c: U32 if c <= 0x03FF => ScriptGreek
      | let c: U32 if c <= 0x0484 => ScriptCyrillic
      | let c: U32 if c <= 0x0486 => ScriptInherited
      | let c: U32 if c <= 0x052F => ScriptCyrillic
      | let c: U32 if c <= 0x0530 => ScriptUnknown
      | let c: U32 if c <= 0x0556 => ScriptArmenian
      | let c: U32 if c <= 0x0558 => ScriptUnknown
      | let c: U32 if c <= 0x058A => ScriptArmenian
      | let c: U32 if c <= 0x058C => ScriptUnknown
      | let c: U32 if c <= 0x058F => ScriptArmenian
      | let c: U32 if c <= 0x0590 => ScriptUnknown
      | let c: U32 if c <= 0x05C7 => ScriptHebrew
      | let c: U32 if c <= 0x05CF => ScriptUnknown
      | let c: U32 if c <= 0x05EA => ScriptHebrew
      | let c: U32 if c <= 0x05EE => ScriptUnknown
      | let c: U32 if c <= 0x05F4 => ScriptHebrew
      | let c: U32 if c <= 0x05FF => ScriptUnknown
      | let c: U32 if c <= 0x0604 => ScriptArabic
      | let c: U32 if c <= 0x0605 => ScriptCommon
      | let c: U32 if c <= 0x060B => ScriptArabic
      | let c: U32 if c <= 0x060C => ScriptCommon
      | let c: U32 if c <= 0x061A => ScriptArabic
      | let c: U32 if c <= 0x061B => ScriptCommon
      | let c: U32 if c <= 0x061E => ScriptArabic
      | let c: U32 if c <= 0x061F => ScriptCommon
      | let c: U32 if c <= 0x063F => ScriptArabic
      | let c: U32 if c <= 0x0640 => ScriptCommon
      | let c: U32 if c <= 0x064A => ScriptArabic
      | let c: U32 if c <= 0x0655 => ScriptInherited
      | let c: U32 if c <= 0x066F => ScriptArabic
      | let c: U32 if c <= 0x0670 => ScriptInherited
      | let c: U32 if c <= 0x06DC => ScriptArabic
      | let c: U32 if c <= 0x06DD => ScriptCommon
      | let c: U32 if c <= 0x06FF => ScriptArabic
      | let c: U32 if c <= 0x070D => ScriptSyriac
      | let c: U32 if c <= 0x070E => ScriptUnknown
      | let c: U32 if c <= 0x074A => ScriptSyriac
      | let c: U32 if c <= 0x074C => ScriptUnknown
      | let c: U32 if c <= 0x074F => ScriptSyriac
      | let c: U32 if c <= 0x077F => ScriptArabic
      | let c: U32 if c <= 0x07B1 => ScriptThaana
      | let c: U32 if c <= 0x07BF => ScriptUnknown
      | let c: U32 if c <= 0x07FA => ScriptNko
      | let c: U32 if c <= 0x07FC => ScriptUnknown
      | let c: U32 if c <= 0x07FF => ScriptNko
      | let c: U32 if c <= 0x082D => ScriptSamaritan
      | let c: U32 if c <= 0x082F => ScriptUnknown
      | let c: U32 if c <= 0x083E => ScriptSamaritan
      | let c: U32 if c <= 0x083F => ScriptUnknown
      | let c: U32 if c <= 0x085B => ScriptMandaic
      | let c: U32 if c <= 0x085D => ScriptUnknown
      | let c: U32 if c <= 0x085E => ScriptMandaic
      | let c: U32 if c <= 0x085F => ScriptUnknown
      | let c: U32 if c <= 0x086A => ScriptSyriac
      | let c: U32 if c <= 0x086F => ScriptUnknown
      | let c: U32 if c <= 0x088E => ScriptArabic
      | let c: U32 if c <= 0x088F => ScriptUnknown
      | let c: U32 if c <= 0x0891 => ScriptArabic
      | let c: U32 if c <= 0x0896 => ScriptUnknown
      | let c: U32 if c <= 0x08E1 => ScriptArabic
      | let c: U32 if c <= 0x08E2 => ScriptCommon
      | let c: U32 if c <= 0x08FF => ScriptArabic
      | let c: U32 if c <= 0x0950 => ScriptDevanagari
      | let c: U32 if c <= 0x0954 => ScriptInherited
      | let c: U32 if c <= 0x0963 => ScriptDevanagari
      | let c: U32 if c <= 0x0965 => ScriptCommon
      | let c: U32 if c <= 0x097F => ScriptDevanagari
      | let c: U32 if c <= 0x0983 => ScriptBengali
      | let c: U32 if c <= 0x0984 => ScriptUnknown
      | let c: U32 if c <= 0x098C => ScriptBengali
      | let c: U32 if c <= 0x098E => ScriptUnknown
      | let c: U32 if c <= 0x0990 => ScriptBengali
      | let c: U32 if c <= 0x0992 => ScriptUnknown
      | let c: U32 if c <= 0x09A8 => ScriptBengali
      | let c: U32 if c <= 0x09A9 => ScriptUnknown
      | let c: U32 if c <= 0x09B0 => ScriptBengali
      | let c: U32 if c <= 0x09B1 => ScriptUnknown
      | let c: U32 if c <= 0x09B2 => ScriptBengali
      | let c: U32 if c <= 0x09B5 => ScriptUnknown
      | let c: U32 if c <= 0x09B9 => ScriptBengali
      | let c: U32 if c <= 0x09BB => ScriptUnknown
      | let c: U32 if c <= 0x09C4 => ScriptBengali
      | let c: U32 if c <= 0x09C6 => ScriptUnknown
      | let c: U32 if c <= 0x09C8 => ScriptBengali
      | let c: U32 if c <= 0x09CA => ScriptUnknown
      | let c: U32 if c <= 0x09CE => ScriptBengali
      | let c: U32 if c <= 0x09D6 => ScriptUnknown
      | let c: U32 if c <= 0x09D7 => ScriptBengali
      | let c: U32 if c <= 0x09DB => ScriptUnknown
      | let c: U32 if c <= 0x09DD => ScriptBengali
      | let c: U32 if c <= 0x09DE => ScriptUnknown
      | let c: U32 if c <= 0x09E3 => ScriptBengali
      | let c: U32 if c <= 0x09E5 => ScriptUnknown
      | let c: U32 if c <= 0x09FE => ScriptBengali
      | let c: U32 if c <= 0x0A00 => ScriptUnknown
      | let c: U32 if c <= 0x0A03 => ScriptGurmukhi
      | let c: U32 if c <= 0x0A04 => ScriptUnknown
      | let c: U32 if c <= 0x0A0A => ScriptGurmukhi
      | let c: U32 if c <= 0x0A0E => ScriptUnknown
      | let c: U32 if c <= 0x0A10 => ScriptGurmukhi
      | let c: U32 if c <= 0x0A12 => ScriptUnknown
      | let c: U32 if c <= 0x0A28 => ScriptGurmukhi
      | let c: U32 if c <= 0x0A29 => ScriptUnknown
      | let c: U32 if c <= 0x0A30 => ScriptGurmukhi
      | let c: U32 if c <= 0x0A31 => ScriptUnknown
      | let c: U32 if c <= 0x0A33 => ScriptGurmukhi
      | let c: U32 if c <= 0x0A34 => ScriptUnknown
      | let c: U32 if c <= 0x0A36 => ScriptGurmukhi
      | let c: U32 if c <= 0x0A37 => ScriptUnknown
      | let c: U32 if c <= 0x0A39 => ScriptGurmukhi
      | let c: U32 if c <= 0x0A3B => ScriptUnknown
      | let c: U32 if c <= 0x0A3C => ScriptGurmukhi
      | let c: U32 if c <= 0x0A3D => ScriptUnknown
      | let c: U32 if c <= 0x0A42 => ScriptGurmukhi
      | let c: U32 if c <= 0x0A46 => ScriptUnknown
      | let c: U32 if c <= 0x0A48 => ScriptGurmukhi
      | let c: U32 if c <= 0x0A4A => ScriptUnknown
      | let c: U32 if c <= 0x0A4D => ScriptGurmukhi
      | let c: U32 if c <= 0x0A50 => ScriptUnknown
      | let c: U32 if c <= 0x0A51 => ScriptGurmukhi
      | let c: U32 if c <= 0x0A58 => ScriptUnknown
      | let c: U32 if c <= 0x0A5C => ScriptGurmukhi
      | let c: U32 if c <= 0x0A5D => ScriptUnknown
      | let c: U32 if c <= 0x0A5E => ScriptGurmukhi
      | let c: U32 if c <= 0x0A65 => ScriptUnknown
      | let c: U32 if c <= 0x0A76 => ScriptGurmukhi
      | let c: U32 if c <= 0x0A80 => ScriptUnknown
      | let c: U32 if c <= 0x0A83 => ScriptGujarati
      | let c: U32 if c <= 0x0A84 => ScriptUnknown
      | let c: U32 if c <= 0x0A8D => ScriptGujarati
      | let c: U32 if c <= 0x0A8E => ScriptUnknown
      | let c: U32 if c <= 0x0A91 => ScriptGujarati
      | let c: U32 if c <= 0x0A92 => ScriptUnknown
      | let c: U32 if c <= 0x0AA8 => ScriptGujarati
      | let c: U32 if c <= 0x0AA9 => ScriptUnknown
      | let c: U32 if c <= 0x0AB0 => ScriptGujarati
      | let c: U32 if c <= 0x0AB1 => ScriptUnknown
      | let c: U32 if c <= 0x0AB3 => ScriptGujarati
      | let c: U32 if c <= 0x0AB4 => ScriptUnknown
      | let c: U32 if c <= 0x0AB9 => ScriptGujarati
      | let c: U32 if c <= 0x0ABB => ScriptUnknown
      | let c: U32 if c <= 0x0AC5 => ScriptGujarati
      | let c: U32 if c <= 0x0AC6 => ScriptUnknown
      | let c: U32 if c <= 0x0AC9 => ScriptGujarati
      | let c: U32 if c <= 0x0ACA => ScriptUnknown
      | let c: U32 if c <= 0x0ACD => ScriptGujarati
      | let c: U32 if c <= 0x0ACF => ScriptUnknown
      | let c: U32 if c <= 0x0AD0 => ScriptGujarati
      | let c: U32 if c <= 0x0ADF => ScriptUnknown
      | let c: U32 if c <= 0x0AE3 => ScriptGujarati
      | let c: U32 if c <= 0x0AE5 => ScriptUnknown
      | let c: U32 if c <= 0x0AF1 => ScriptGujarati
      | let c: U32 if c <= 0x0AF8 => ScriptUnknown
      | let c: U32 if c <= 0x0AFF => ScriptGujarati
      | let c: U32 if c <= 0x0B00 => ScriptUnknown
      | let c: U32 if c <= 0x0B03 => ScriptOriya
      | let c: U32 if c <= 0x0B04 => ScriptUnknown
      | let c: U32 if c <= 0x0B0C => ScriptOriya
      | let c: U32 if c <= 0x0B0E => ScriptUnknown
      | let c: U32 if c <= 0x0B10 => ScriptOriya
      | let c: U32 if c <= 0x0B12 => ScriptUnknown
      | let c: U32 if c <= 0x0B28 => ScriptOriya
      | let c: U32 if c <= 0x0B29 => ScriptUnknown
      | let c: U32 if c <= 0x0B30 => ScriptOriya
      | let c: U32 if c <= 0x0B31 => ScriptUnknown
      | let c: U32 if c <= 0x0B33 => ScriptOriya
      | let c: U32 if c <= 0x0B34 => ScriptUnknown
      | let c: U32 if c <= 0x0B39 => ScriptOriya
      | let c: U32 if c <= 0x0B3B => ScriptUnknown
      | let c: U32 if c <= 0x0B44 => ScriptOriya
      | let c: U32 if c <= 0x0B46 => ScriptUnknown
      | let c: U32 if c <= 0x0B48 => ScriptOriya
      | let c: U32 if c <= 0x0B4A => ScriptUnknown
      | let c: U32 if c <= 0x0B4D => ScriptOriya
      | let c: U32 if c <= 0x0B54 => ScriptUnknown
      | let c: U32 if c <= 0x0B57 => ScriptOriya
      | let c: U32 if c <= 0x0B5B => ScriptUnknown
      | let c: U32 if c <= 0x0B5D => ScriptOriya
      | let c: U32 if c <= 0x0B5E => ScriptUnknown
      | let c: U32 if c <= 0x0B63 => ScriptOriya
      | let c: U32 if c <= 0x0B65 => ScriptUnknown
      | let c: U32 if c <= 0x0B77 => ScriptOriya
      | let c: U32 if c <= 0x0B81 => ScriptUnknown
      | let c: U32 if c <= 0x0B83 => ScriptTamil
      | let c: U32 if c <= 0x0B84 => ScriptUnknown
      | let c: U32 if c <= 0x0B8A => ScriptTamil
      | let c: U32 if c <= 0x0B8D => ScriptUnknown
      | let c: U32 if c <= 0x0B90 => ScriptTamil
      | let c: U32 if c <= 0x0B91 => ScriptUnknown
      | let c: U32 if c <= 0x0B95 => ScriptTamil
      | let c: U32 if c <= 0x0B98 => ScriptUnknown
      | let c: U32 if c <= 0x0B9A => ScriptTamil
      | let c: U32 if c <= 0x0B9B => ScriptUnknown
      | let c: U32 if c <= 0x0B9C => ScriptTamil
      | let c: U32 if c <= 0x0B9D => ScriptUnknown
      | let c: U32 if c <= 0x0B9F => ScriptTamil
      | let c: U32 if c <= 0x0BA2 => ScriptUnknown
      | let c: U32 if c <= 0x0BA4 => ScriptTamil
      | let c: U32 if c <= 0x0BA7 => ScriptUnknown
      | let c: U32 if c <= 0x0BAA => ScriptTamil
      | let c: U32 if c <= 0x0BAD => ScriptUnknown
      | let c: U32 if c <= 0x0BB9 => ScriptTamil
      | let c: U32 if c <= 0x0BBD => ScriptUnknown
      | let c: U32 if c <= 0x0BC2 => ScriptTamil
      | let c: U32 if c <= 0x0BC5 => ScriptUnknown
      | let c: U32 if c <= 0x0BC8 => ScriptTamil
      | let c: U32 if c <= 0x0BC9 => ScriptUnknown
      | let c: U32 if c <= 0x0BCD => ScriptTamil
      | let c: U32 if c <= 0x0BCF => ScriptUnknown
      | let c: U32 if c <= 0x0BD0 => ScriptTamil
      | let c: U32 if c <= 0x0BD6 => ScriptUnknown
      | let c: U32 if c <= 0x0BD7 => ScriptTamil
      | let c: U32 if c <= 0x0BE5 => ScriptUnknown
      | let c: U32 if c <= 0x0BFA => ScriptTamil
      | let c: U32 if c <= 0x0BFF => ScriptUnknown
      | let c: U32 if c <= 0x0C0C => ScriptTelugu
      | let c: U32 if c <= 0x0C0D => ScriptUnknown
      | let c: U32 if c <= 0x0C10 => ScriptTelugu
      | let c: U32 if c <= 0x0C11 => ScriptUnknown
      | let c: U32 if c <= 0x0C28 => ScriptTelugu
      | let c: U32 if c <= 0x0C29 => ScriptUnknown
      | let c: U32 if c <= 0x0C39 => ScriptTelugu
      | let c: U32 if c <= 0x0C3B => ScriptUnknown
      | let c: U32 if c <= 0x0C44 => ScriptTelugu
      | let c: U32 if c <= 0x0C45 => ScriptUnknown
      | let c: U32 if c <= 0x0C48 => ScriptTelugu
      | let c: U32 if c <= 0x0C49 => ScriptUnknown
      | let c: U32 if c <= 0x0C4D => ScriptTelugu
      | let c: U32 if c <= 0x0C54 => ScriptUnknown
      | let c: U32 if c <= 0x0C56 => ScriptTelugu
      | let c: U32 if c <= 0x0C57 => ScriptUnknown
      | let c: U32 if c <= 0x0C5A => ScriptTelugu
      | let c: U32 if c <= 0x0C5C => ScriptUnknown
      | let c: U32 if c <= 0x0C5D => ScriptTelugu
      | let c: U32 if c <= 0x0C5F => ScriptUnknown
      | let c: U32 if c <= 0x0C63 => ScriptTelugu
      | let c: U32 if c <= 0x0C65 => ScriptUnknown
      | let c: U32 if c <= 0x0C6F => ScriptTelugu
      | let c: U32 if c <= 0x0C76 => ScriptUnknown
      | let c: U32 if c <= 0x0C7F => ScriptTelugu
      | let c: U32 if c <= 0x0C8C => ScriptKannada
      | let c: U32 if c <= 0x0C8D => ScriptUnknown
      | let c: U32 if c <= 0x0C90 => ScriptKannada
      | let c: U32 if c <= 0x0C91 => ScriptUnknown
      | let c: U32 if c <= 0x0CA8 => ScriptKannada
      | let c: U32 if c <= 0x0CA9 => ScriptUnknown
      | let c: U32 if c <= 0x0CB3 => ScriptKannada
      | let c: U32 if c <= 0x0CB4 => ScriptUnknown
      | let c: U32 if c <= 0x0CB9 => ScriptKannada
      | let c: U32 if c <= 0x0CBB => ScriptUnknown
      | let c: U32 if c <= 0x0CC4 => ScriptKannada
      | let c: U32 if c <= 0x0CC5 => ScriptUnknown
      | let c: U32 if c <= 0x0CC8 => ScriptKannada
      | let c: U32 if c <= 0x0CC9 => ScriptUnknown
      | let c: U32 if c <= 0x0CCD => ScriptKannada
      | let c: U32 if c <= 0x0CD4 => ScriptUnknown
      | let c: U32 if c <= 0x0CD6 => ScriptKannada
      | let c: U32 if c <= 0x0CDC => ScriptUnknown
      | let c: U32 if c <= 0x0CDE => ScriptKannada
      | let c: U32 if c <= 0x0CDF => ScriptUnknown
      | let c: U32 if c <= 0x0CE3 => ScriptKannada
      | let c: U32 if c <= 0x0CE5 => ScriptUnknown
      | let c: U32 if c <= 0x0CEF => ScriptKannada
      | let c: U32 if c <= 0x0CF0 => ScriptUnknown
      | let c: U32 if c <= 0x0CF3 => ScriptKannada
      | let c: U32 if c <= 0x0CFF => ScriptUnknown
      | let c: U32 if c <= 0x0D0C => ScriptMalayalam
      | let c: U32 if c <= 0x0D0D => ScriptUnknown
      | let c: U32 if c <= 0x0D10 => ScriptMalayalam
      | let c: U32 if c <= 0x0D11 => ScriptUnknown
      | let c: U32 if c <= 0x0D44 => ScriptMalayalam
      | let c: U32 if c <= 0x0D45 => ScriptUnknown
      | let c: U32 if c <= 0x0D48 => ScriptMalayalam
      | let c: U32 if c <= 0x0D49 => ScriptUnknown
      | let c: U32 if c <= 0x0D4F => ScriptMalayalam
      | let c: U32 if c <= 0x0D53 => ScriptUnknown
      | let c: U32 if c <= 0x0D63 => ScriptMalayalam
      | let c: U32 if c <= 0x0D65 => ScriptUnknown
      | let c: U32 if c <= 0x0D7F => ScriptMalayalam
      | let c: U32 if c <= 0x0D80 => ScriptUnknown
      | let c: U32 if c <= 0x0D83 => ScriptSinhala
      | let c: U32 if c <= 0x0D84 => ScriptUnknown
      | let c: U32 if c <= 0x0D96 => ScriptSinhala
      | let c: U32 if c <= 0x0D99 => ScriptUnknown
      | let c: U32 if c <= 0x0DB1 => ScriptSinhala
      | let c: U32 if c <= 0x0DB2 => ScriptUnknown
      | let c: U32 if c <= 0x0DBB => ScriptSinhala
      | let c: U32 if c <= 0x0DBC => ScriptUnknown
      | let c: U32 if c <= 0x0DBD => ScriptSinhala
      | let c: U32 if c <= 0x0DBF => ScriptUnknown
      | let c: U32 if c <= 0x0DC6 => ScriptSinhala
      | let c: U32 if c <= 0x0DC9 => ScriptUnknown
      | let c: U32 if c <= 0x0DCA => ScriptSinhala
      | let c: U32 if c <= 0x0DCE => ScriptUnknown
      | let c: U32 if c <= 0x0DD4 => ScriptSinhala
      | let c: U32 if c <= 0x0DD5 => ScriptUnknown
      | let c: U32 if c <= 0x0DD6 => ScriptSinhala
      | let c: U32 if c <= 0x0DD7 => ScriptUnknown
      | let c: U32 if c <= 0x0DDF => ScriptSinhala
      | let c: U32 if c <= 0x0DE5 => ScriptUnknown
      | let c: U32 if c <= 0x0DEF => ScriptSinhala
      | let c: U32 if c <= 0x0DF1 => ScriptUnknown
      | let c: U32 if c <= 0x0DF4 => ScriptSinhala
      | let c: U32 if c <= 0x0E00 => ScriptUnknown
      | let c: U32 if c <= 0x0E3A => ScriptThai
      | let c: U32 if c <= 0x0E3E => ScriptUnknown
      | let c: U32 if c <= 0x0E3F => ScriptCommon
      | let c: U32 if c <= 0x0E5B => ScriptThai
      | let c: U32 if c <= 0x0E80 => ScriptUnknown
      | let c: U32 if c <= 0x0E82 => ScriptLao
      | let c: U32 if c <= 0x0E83 => ScriptUnknown
      | let c: U32 if c <= 0x0E84 => ScriptLao
      | let c: U32 if c <= 0x0E85 => ScriptUnknown
      | let c: U32 if c <= 0x0E8A => ScriptLao
      | let c: U32 if c <= 0x0E8B => ScriptUnknown
      | let c: U32 if c <= 0x0EA3 => ScriptLao
      | let c: U32 if c <= 0x0EA4 => ScriptUnknown
      | let c: U32 if c <= 0x0EA5 => ScriptLao
      | let c: U32 if c <= 0x0EA6 => ScriptUnknown
      | let c: U32 if c <= 0x0EBD => ScriptLao
      | let c: U32 if c <= 0x0EBF => ScriptUnknown
      | let c: U32 if c <= 0x0EC4 => ScriptLao
      | let c: U32 if c <= 0x0EC5 => ScriptUnknown
      | let c: U32 if c <= 0x0EC6 => ScriptLao
      | let c: U32 if c <= 0x0EC7 => ScriptUnknown
      | let c: U32 if c <= 0x0ECE => ScriptLao
      | let c: U32 if c <= 0x0ECF => ScriptUnknown
      | let c: U32 if c <= 0x0ED9 => ScriptLao
      | let c: U32 if c <= 0x0EDB => ScriptUnknown
      | let c: U32 if c <= 0x0EDF => ScriptLao
      | let c: U32 if c <= 0x0EFF => ScriptUnknown
      | let c: U32 if c <= 0x0F47 => ScriptTibetan
      | let c: U32 if c <= 0x0F48 => ScriptUnknown
      | let c: U32 if c <= 0x0F6C => ScriptTibetan
      | let c: U32 if c <= 0x0F70 => ScriptUnknown
      | let c: U32 if c <= 0x0F97 => ScriptTibetan
      | let c: U32 if c <= 0x0F98 => ScriptUnknown
      | let c: U32 if c <= 0x0FBC => ScriptTibetan
      | let c: U32 if c <= 0x0FBD => ScriptUnknown
      | let c: U32 if c <= 0x0FCC => ScriptTibetan
      | let c: U32 if c <= 0x0FCD => ScriptUnknown
      | let c: U32 if c <= 0x0FD4 => ScriptTibetan
      | let c: U32 if c <= 0x0FD8 => ScriptCommon
      | let c: U32 if c <= 0x0FDA => ScriptTibetan
      else ScriptUnknown
      end
    | 0x0001 =>
      match cp
      | let c: U32 if c <= 0x109F => ScriptMyanmar
      | let c: U32 if c <= 0x10C5 => ScriptGeorgian
      | let c: U32 if c <= 0x10C6 => ScriptUnknown
      | let c: U32 if c <= 0x10C7 => ScriptGeorgian
      | let c: U32 if c <= 0x10CC => ScriptUnknown
      | let c: U32 if c <= 0x10CD => ScriptGeorgian
      | let c: U32 if c <= 0x10CF => ScriptUnknown
      | let c: U32 if c <= 0x10FA => ScriptGeorgian
      | let c: U32 if c <= 0x10FB => ScriptCommon
      | let c: U32 if c <= 0x10FF => ScriptGeorgian
      | let c: U32 if c <= 0x11FF => ScriptHangul
      | let c: U32 if c <= 0x1248 => ScriptEthiopic
      | let c: U32 if c <= 0x1249 => ScriptUnknown
      | let c: U32 if c <= 0x124D => ScriptEthiopic
      | let c: U32 if c <= 0x124F => ScriptUnknown
      | let c: U32 if c <= 0x1256 => ScriptEthiopic
      | let c: U32 if c <= 0x1257 => ScriptUnknown
      | let c: U32 if c <= 0x1258 => ScriptEthiopic
      | let c: U32 if c <= 0x1259 => ScriptUnknown
      | let c: U32 if c <= 0x125D => ScriptEthiopic
      | let c: U32 if c <= 0x125F => ScriptUnknown
      | let c: U32 if c <= 0x1288 => ScriptEthiopic
      | let c: U32 if c <= 0x1289 => ScriptUnknown
      | let c: U32 if c <= 0x128D => ScriptEthiopic
      | let c: U32 if c <= 0x128F => ScriptUnknown
      | let c: U32 if c <= 0x12B0 => ScriptEthiopic
      | let c: U32 if c <= 0x12B1 => ScriptUnknown
      | let c: U32 if c <= 0x12B5 => ScriptEthiopic
      | let c: U32 if c <= 0x12B7 => ScriptUnknown
      | let c: U32 if c <= 0x12BE => ScriptEthiopic
      | let c: U32 if c <= 0x12BF => ScriptUnknown
      | let c: U32 if c <= 0x12C0 => ScriptEthiopic
      | let c: U32 if c <= 0x12C1 => ScriptUnknown
      | let c: U32 if c <= 0x12C5 => ScriptEthiopic
      | let c: U32 if c <= 0x12C7 => ScriptUnknown
      | let c: U32 if c <= 0x12D6 => ScriptEthiopic
      | let c: U32 if c <= 0x12D7 => ScriptUnknown
      | let c: U32 if c <= 0x1310 => ScriptEthiopic
      | let c: U32 if c <= 0x1311 => ScriptUnknown
      | let c: U32 if c <= 0x1315 => ScriptEthiopic
      | let c: U32 if c <= 0x1317 => ScriptUnknown
      | let c: U32 if c <= 0x135A => ScriptEthiopic
      | let c: U32 if c <= 0x135C => ScriptUnknown
      | let c: U32 if c <= 0x137C => ScriptEthiopic
      | let c: U32 if c <= 0x137F => ScriptUnknown
      | let c: U32 if c <= 0x1399 => ScriptEthiopic
      | let c: U32 if c <= 0x139F => ScriptUnknown
      | let c: U32 if c <= 0x13F5 => ScriptCherokee
      | let c: U32 if c <= 0x13F7 => ScriptUnknown
      | let c: U32 if c <= 0x13FD => ScriptCherokee
      | let c: U32 if c <= 0x13FF => ScriptUnknown
      | let c: U32 if c <= 0x167F => ScriptCanadianAboriginal
      | let c: U32 if c <= 0x169C => ScriptOgham
      | let c: U32 if c <= 0x169F => ScriptUnknown
      | let c: U32 if c <= 0x16EA => ScriptRunic
      | let c: U32 if c <= 0x16ED => ScriptCommon
      | let c: U32 if c <= 0x16F8 => ScriptRunic
      | let c: U32 if c <= 0x16FF => ScriptUnknown
      | let c: U32 if c <= 0x1715 => ScriptTagalog
      | let c: U32 if c <= 0x171E => ScriptUnknown
      | let c: U32 if c <= 0x171F => ScriptTagalog
      | let c: U32 if c <= 0x1734 => ScriptHanunoo
      | let c: U32 if c <= 0x1736 => ScriptCommon
      | let c: U32 if c <= 0x173F => ScriptUnknown
      | let c: U32 if c <= 0x1753 => ScriptBuhid
      | let c: U32 if c <= 0x175F => ScriptUnknown
      | let c: U32 if c <= 0x176C => ScriptTagbanwa
      | let c: U32 if c <= 0x176D => ScriptUnknown
      | let c: U32 if c <= 0x1770 => ScriptTagbanwa
      | let c: U32 if c <= 0x1771 => ScriptUnknown
      | let c: U32 if c <= 0x1773 => ScriptTagbanwa
      | let c: U32 if c <= 0x177F => ScriptUnknown
      | let c: U32 if c <= 0x17DD => ScriptKhmer
      | let c: U32 if c <= 0x17DF => ScriptUnknown
      | let c: U32 if c <= 0x17E9 => ScriptKhmer
      | let c: U32 if c <= 0x17EF => ScriptUnknown
      | let c: U32 if c <= 0x17F9 => ScriptKhmer
      | let c: U32 if c <= 0x17FF => ScriptUnknown
      | let c: U32 if c <= 0x1801 => ScriptMongolian
      | let c: U32 if c <= 0x1803 => ScriptCommon
      | let c: U32 if c <= 0x1804 => ScriptMongolian
      | let c: U32 if c <= 0x1805 => ScriptCommon
      | let c: U32 if c <= 0x1819 => ScriptMongolian
      | let c: U32 if c <= 0x181F => ScriptUnknown
      | let c: U32 if c <= 0x1878 => ScriptMongolian
      | let c: U32 if c <= 0x187F => ScriptUnknown
      | let c: U32 if c <= 0x18AA => ScriptMongolian
      | let c: U32 if c <= 0x18AF => ScriptUnknown
      | let c: U32 if c <= 0x18F5 => ScriptCanadianAboriginal
      | let c: U32 if c <= 0x18FF => ScriptUnknown
      | let c: U32 if c <= 0x191E => ScriptLimbu
      | let c: U32 if c <= 0x191F => ScriptUnknown
      | let c: U32 if c <= 0x192B => ScriptLimbu
      | let c: U32 if c <= 0x192F => ScriptUnknown
      | let c: U32 if c <= 0x193B => ScriptLimbu
      | let c: U32 if c <= 0x193F => ScriptUnknown
      | let c: U32 if c <= 0x1940 => ScriptLimbu
      | let c: U32 if c <= 0x1943 => ScriptUnknown
      | let c: U32 if c <= 0x194F => ScriptLimbu
      | let c: U32 if c <= 0x196D => ScriptTaiLe
      | let c: U32 if c <= 0x196F => ScriptUnknown
      | let c: U32 if c <= 0x1974 => ScriptTaiLe
      | let c: U32 if c <= 0x197F => ScriptUnknown
      | let c: U32 if c <= 0x19AB => ScriptNewTaiLue
      | let c: U32 if c <= 0x19AF => ScriptUnknown
      | let c: U32 if c <= 0x19C9 => ScriptNewTaiLue
      | let c: U32 if c <= 0x19CF => ScriptUnknown
      | let c: U32 if c <= 0x19DA => ScriptNewTaiLue
      | let c: U32 if c <= 0x19DD => ScriptUnknown
      | let c: U32 if c <= 0x19DF => ScriptNewTaiLue
      | let c: U32 if c <= 0x19FF => ScriptKhmer
      | let c: U32 if c <= 0x1A1B => ScriptBuginese
      | let c: U32 if c <= 0x1A1D => ScriptUnknown
      | let c: U32 if c <= 0x1A1F => ScriptBuginese
      | let c: U32 if c <= 0x1A5E => ScriptTaiTham
      | let c: U32 if c <= 0x1A5F => ScriptUnknown
      | let c: U32 if c <= 0x1A7C => ScriptTaiTham
      | let c: U32 if c <= 0x1A7E => ScriptUnknown
      | let c: U32 if c <= 0x1A89 => ScriptTaiTham
      | let c: U32 if c <= 0x1A8F => ScriptUnknown
      | let c: U32 if c <= 0x1A99 => ScriptTaiTham
      | let c: U32 if c <= 0x1A9F => ScriptUnknown
      | let c: U32 if c <= 0x1AAD => ScriptTaiTham
      | let c: U32 if c <= 0x1AAF => ScriptUnknown
      | let c: U32 if c <= 0x1ACE => ScriptInherited
      | let c: U32 if c <= 0x1AFF => ScriptUnknown
      | let c: U32 if c <= 0x1B4C => ScriptBalinese
      | let c: U32 if c <= 0x1B4D => ScriptUnknown
      | let c: U32 if c <= 0x1B7F => ScriptBalinese
      | let c: U32 if c <= 0x1BBF => ScriptSundanese
      | let c: U32 if c <= 0x1BF3 => ScriptBatak
      | let c: U32 if c <= 0x1BFB => ScriptUnknown
      | let c: U32 if c <= 0x1BFF => ScriptBatak
      | let c: U32 if c <= 0x1C37 => ScriptLepcha
      | let c: U32 if c <= 0x1C3A => ScriptUnknown
      | let c: U32 if c <= 0x1C49 => ScriptLepcha
      | let c: U32 if c <= 0x1C4C => ScriptUnknown
      | let c: U32 if c <= 0x1C4F => ScriptLepcha
      | let c: U32 if c <= 0x1C7F => ScriptOlChiki
      | let c: U32 if c <= 0x1C8A => ScriptCyrillic
      | let c: U32 if c <= 0x1C8F => ScriptUnknown
      | let c: U32 if c <= 0x1CBA => ScriptGeorgian
      | let c: U32 if c <= 0x1CBC => ScriptUnknown
      | let c: U32 if c <= 0x1CBF => ScriptGeorgian
      | let c: U32 if c <= 0x1CC7 => ScriptSundanese
      | let c: U32 if c <= 0x1CCF => ScriptUnknown
      | let c: U32 if c <= 0x1CD2 => ScriptInherited
      | let c: U32 if c <= 0x1CD3 => ScriptCommon
      | let c: U32 if c <= 0x1CE0 => ScriptInherited
      | let c: U32 if c <= 0x1CE1 => ScriptCommon
      | let c: U32 if c <= 0x1CE8 => ScriptInherited
      | let c: U32 if c <= 0x1CEC => ScriptCommon
      | let c: U32 if c <= 0x1CED => ScriptInherited
      | let c: U32 if c <= 0x1CF3 => ScriptCommon
      | let c: U32 if c <= 0x1CF4 => ScriptInherited
      | let c: U32 if c <= 0x1CF7 => ScriptCommon
      | let c: U32 if c <= 0x1CF9 => ScriptInherited
      | let c: U32 if c <= 0x1CFA => ScriptCommon
      | let c: U32 if c <= 0x1CFF => ScriptUnknown
      | let c: U32 if c <= 0x1D25 => ScriptLatin
      | let c: U32 if c <= 0x1D2A => ScriptGreek
      | let c: U32 if c <= 0x1D2B => ScriptCyrillic
      | let c: U32 if c <= 0x1D5C => ScriptLatin
      | let c: U32 if c <= 0x1D61 => ScriptGreek
      | let c: U32 if c <= 0x1D65 => ScriptLatin
      | let c: U32 if c <= 0x1D6A => ScriptGreek
      | let c: U32 if c <= 0x1D77 => ScriptLatin
      | let c: U32 if c <= 0x1D78 => ScriptCyrillic
      | let c: U32 if c <= 0x1DBE => ScriptLatin
      | let c: U32 if c <= 0x1DBF => ScriptGreek
      | let c: U32 if c <= 0x1DFF => ScriptInherited
      | let c: U32 if c <= 0x1EFF => ScriptLatin
      | let c: U32 if c <= 0x1F15 => ScriptGreek
      | let c: U32 if c <= 0x1F17 => ScriptUnknown
      | let c: U32 if c <= 0x1F1D => ScriptGreek
      | let c: U32 if c <= 0x1F1F => ScriptUnknown
      | let c: U32 if c <= 0x1F45 => ScriptGreek
      | let c: U32 if c <= 0x1F47 => ScriptUnknown
      | let c: U32 if c <= 0x1F4D => ScriptGreek
      | let c: U32 if c <= 0x1F4F => ScriptUnknown
      | let c: U32 if c <= 0x1F57 => ScriptGreek
      | let c: U32 if c <= 0x1F58 => ScriptUnknown
      | let c: U32 if c <= 0x1F59 => ScriptGreek
      | let c: U32 if c <= 0x1F5A => ScriptUnknown
      | let c: U32 if c <= 0x1F5B => ScriptGreek
      | let c: U32 if c <= 0x1F5C => ScriptUnknown
      | let c: U32 if c <= 0x1F5D => ScriptGreek
      | let c: U32 if c <= 0x1F5E => ScriptUnknown
      | let c: U32 if c <= 0x1F7D => ScriptGreek
      | let c: U32 if c <= 0x1F7F => ScriptUnknown
      | let c: U32 if c <= 0x1FB4 => ScriptGreek
      | let c: U32 if c <= 0x1FB5 => ScriptUnknown
      | let c: U32 if c <= 0x1FC4 => ScriptGreek
      | let c: U32 if c <= 0x1FC5 => ScriptUnknown
      | let c: U32 if c <= 0x1FD3 => ScriptGreek
      | let c: U32 if c <= 0x1FD5 => ScriptUnknown
      | let c: U32 if c <= 0x1FDB => ScriptGreek
      | let c: U32 if c <= 0x1FDC => ScriptUnknown
      | let c: U32 if c <= 0x1FEF => ScriptGreek
      | let c: U32 if c <= 0x1FF1 => ScriptUnknown
      | let c: U32 if c <= 0x1FF4 => ScriptGreek
      | let c: U32 if c <= 0x1FF5 => ScriptUnknown
      | let c: U32 if c <= 0x1FFE => ScriptGreek
      else ScriptUnknown
      end
    | 0x0002 =>
      match cp
      | let c: U32 if c <= 0x200B => ScriptCommon
      | let c: U32 if c <= 0x200D => ScriptInherited
      | let c: U32 if c <= 0x2064 => ScriptCommon
      | let c: U32 if c <= 0x2065 => ScriptUnknown
      | let c: U32 if c <= 0x2070 => ScriptCommon
      | let c: U32 if c <= 0x2071 => ScriptLatin
      | let c: U32 if c <= 0x2073 => ScriptUnknown
      | let c: U32 if c <= 0x207E => ScriptCommon
      | let c: U32 if c <= 0x207F => ScriptLatin
      | let c: U32 if c <= 0x208E => ScriptCommon
      | let c: U32 if c <= 0x208F => ScriptUnknown
      | let c: U32 if c <= 0x209C => ScriptLatin
      | let c: U32 if c <= 0x209F => ScriptUnknown
      | let c: U32 if c <= 0x20C0 => ScriptCommon
      | let c: U32 if c <= 0x20CF => ScriptUnknown
      | let c: U32 if c <= 0x20F0 => ScriptInherited
      | let c: U32 if c <= 0x20FF => ScriptUnknown
      | let c: U32 if c <= 0x2125 => ScriptCommon
      | let c: U32 if c <= 0x2126 => ScriptGreek
      | let c: U32 if c <= 0x2129 => ScriptCommon
      | let c: U32 if c <= 0x212B => ScriptLatin
      | let c: U32 if c <= 0x2131 => ScriptCommon
      | let c: U32 if c <= 0x2132 => ScriptLatin
      | let c: U32 if c <= 0x214D => ScriptCommon
      | let c: U32 if c <= 0x214E => ScriptLatin
      | let c: U32 if c <= 0x215F => ScriptCommon
      | let c: U32 if c <= 0x2188 => ScriptLatin
      | let c: U32 if c <= 0x218B => ScriptCommon
      | let c: U32 if c <= 0x218F => ScriptUnknown
      | let c: U32 if c <= 0x2429 => ScriptCommon
      | let c: U32 if c <= 0x243F => ScriptUnknown
      | let c: U32 if c <= 0x244A => ScriptCommon
      | let c: U32 if c <= 0x245F => ScriptUnknown
      | let c: U32 if c <= 0x27FF => ScriptCommon
      | let c: U32 if c <= 0x28FF => ScriptBraille
      | let c: U32 if c <= 0x2B73 => ScriptCommon
      | let c: U32 if c <= 0x2B75 => ScriptUnknown
      | let c: U32 if c <= 0x2B95 => ScriptCommon
      | let c: U32 if c <= 0x2B96 => ScriptUnknown
      | let c: U32 if c <= 0x2BFF => ScriptCommon
      | let c: U32 if c <= 0x2C5F => ScriptGlagolitic
      | let c: U32 if c <= 0x2C7F => ScriptLatin
      | let c: U32 if c <= 0x2CF3 => ScriptCoptic
      | let c: U32 if c <= 0x2CF8 => ScriptUnknown
      | let c: U32 if c <= 0x2CFF => ScriptCoptic
      | let c: U32 if c <= 0x2D25 => ScriptGeorgian
      | let c: U32 if c <= 0x2D26 => ScriptUnknown
      | let c: U32 if c <= 0x2D27 => ScriptGeorgian
      | let c: U32 if c <= 0x2D2C => ScriptUnknown
      | let c: U32 if c <= 0x2D2D => ScriptGeorgian
      | let c: U32 if c <= 0x2D2F => ScriptUnknown
      | let c: U32 if c <= 0x2D67 => ScriptTifinagh
      | let c: U32 if c <= 0x2D6E => ScriptUnknown
      | let c: U32 if c <= 0x2D70 => ScriptTifinagh
      | let c: U32 if c <= 0x2D7E => ScriptUnknown
      | let c: U32 if c <= 0x2D7F => ScriptTifinagh
      | let c: U32 if c <= 0x2D96 => ScriptEthiopic
      | let c: U32 if c <= 0x2D9F => ScriptUnknown
      | let c: U32 if c <= 0x2DA6 => ScriptEthiopic
      | let c: U32 if c <= 0x2DA7 => ScriptUnknown
      | let c: U32 if c <= 0x2DAE => ScriptEthiopic
      | let c: U32 if c <= 0x2DAF => ScriptUnknown
      | let c: U32 if c <= 0x2DB6 => ScriptEthiopic
      | let c: U32 if c <= 0x2DB7 => ScriptUnknown
      | let c: U32 if c <= 0x2DBE => ScriptEthiopic
      | let c: U32 if c <= 0x2DBF => ScriptUnknown
      | let c: U32 if c <= 0x2DC6 => ScriptEthiopic
      | let c: U32 if c <= 0x2DC7 => ScriptUnknown
      | let c: U32 if c <= 0x2DCE => ScriptEthiopic
      | let c: U32 if c <= 0x2DCF => ScriptUnknown
      | let c: U32 if c <= 0x2DD6 => ScriptEthiopic
      | let c: U32 if c <= 0x2DD7 => ScriptUnknown
      | let c: U32 if c <= 0x2DDE => ScriptEthiopic
      | let c: U32 if c <= 0x2DDF => ScriptUnknown
      | let c: U32 if c <= 0x2DFF => ScriptCyrillic
      | let c: U32 if c <= 0x2E5D => ScriptCommon
      | let c: U32 if c <= 0x2E7F => ScriptUnknown
      | let c: U32 if c <= 0x2E99 => ScriptHan
      | let c: U32 if c <= 0x2E9A => ScriptUnknown
      | let c: U32 if c <= 0x2EF3 => ScriptHan
      | let c: U32 if c <= 0x2EFF => ScriptUnknown
      | let c: U32 if c <= 0x2FD5 => ScriptHan
      | let c: U32 if c <= 0x2FEF => ScriptUnknown
      | let c: U32 if c <= 0x2FFF => ScriptCommon
      else ScriptUnknown
      end
    | 0x0003 =>
      match cp
      | let c: U32 if c <= 0x3004 => ScriptCommon
      | let c: U32 if c <= 0x3005 => ScriptHan
      | let c: U32 if c <= 0x3006 => ScriptCommon
      | let c: U32 if c <= 0x3007 => ScriptHan
      | let c: U32 if c <= 0x3020 => ScriptCommon
      | let c: U32 if c <= 0x3029 => ScriptHan
      | let c: U32 if c <= 0x302D => ScriptInherited
      | let c: U32 if c <= 0x302F => ScriptHangul
      | let c: U32 if c <= 0x3037 => ScriptCommon
      | let c: U32 if c <= 0x303B => ScriptHan
      | let c: U32 if c <= 0x303F => ScriptCommon
      | let c: U32 if c <= 0x3040 => ScriptUnknown
      | let c: U32 if c <= 0x3096 => ScriptHiragana
      | let c: U32 if c <= 0x3098 => ScriptUnknown
      | let c: U32 if c <= 0x309A => ScriptInherited
      | let c: U32 if c <= 0x309C => ScriptCommon
      | let c: U32 if c <= 0x309F => ScriptHiragana
      | let c: U32 if c <= 0x30A0 => ScriptCommon
      | let c: U32 if c <= 0x30FA => ScriptKatakana
      | let c: U32 if c <= 0x30FC => ScriptCommon
      | let c: U32 if c <= 0x30FF => ScriptKatakana
      | let c: U32 if c <= 0x3104 => ScriptUnknown
      | let c: U32 if c <= 0x312F => ScriptBopomofo
      | let c: U32 if c <= 0x3130 => ScriptUnknown
      | let c: U32 if c <= 0x318E => ScriptHangul
      | let c: U32 if c <= 0x318F => ScriptUnknown
      | let c: U32 if c <= 0x319F => ScriptCommon
      | let c: U32 if c <= 0x31BF => ScriptBopomofo
      | let c: U32 if c <= 0x31E5 => ScriptCommon
      | let c: U32 if c <= 0x31EE => ScriptUnknown
      | let c: U32 if c <= 0x31EF => ScriptCommon
      | let c: U32 if c <= 0x31FF => ScriptKatakana
      | let c: U32 if c <= 0x321E => ScriptHangul
      | let c: U32 if c <= 0x321F => ScriptUnknown
      | let c: U32 if c <= 0x325F => ScriptCommon
      | let c: U32 if c <= 0x327E => ScriptHangul
      | let c: U32 if c <= 0x32CF => ScriptCommon
      | let c: U32 if c <= 0x32FE => ScriptKatakana
      | let c: U32 if c <= 0x32FF => ScriptCommon
      | let c: U32 if c <= 0x3357 => ScriptKatakana
      | let c: U32 if c <= 0x33FF => ScriptCommon
      | let c: U32 if c <= 0x3FFF => ScriptHan
      else ScriptUnknown
      end
    | 0x0004 =>
      match cp
      | let c: U32 if c <= 0x4DBF => ScriptHan
      | let c: U32 if c <= 0x4DFF => ScriptCommon
      | let c: U32 if c <= 0x4FFF => ScriptHan
      else ScriptUnknown
      end
    | 0x0005 =>
      match cp
      | let c: U32 if c <= 0x5FFF => ScriptHan
      else ScriptUnknown
      end
    | 0x0006 =>
      match cp
      | let c: U32 if c <= 0x6FFF => ScriptHan
      else ScriptUnknown
      end
    | 0x0007 =>
      match cp
      | let c: U32 if c <= 0x7FFF => ScriptHan
      else ScriptUnknown
      end
    | 0x0008 =>
      match cp
      | let c: U32 if c <= 0x8FFF => ScriptHan
      else ScriptUnknown
      end
    | 0x0009 =>
      match cp
      | let c: U32 if c <= 0x9FFF => ScriptHan
      else ScriptUnknown
      end
    | 0x000A =>
      match cp
      | let c: U32 if c <= 0xA48C => ScriptYi
      | let c: U32 if c <= 0xA48F => ScriptUnknown
      | let c: U32 if c <= 0xA4C6 => ScriptYi
      | let c: U32 if c <= 0xA4CF => ScriptUnknown
      | let c: U32 if c <= 0xA4FF => ScriptLisu
      | let c: U32 if c <= 0xA62B => ScriptVai
      | let c: U32 if c <= 0xA63F => ScriptUnknown
      | let c: U32 if c <= 0xA69F => ScriptCyrillic
      | let c: U32 if c <= 0xA6F7 => ScriptBamum
      | let c: U32 if c <= 0xA6FF => ScriptUnknown
      | let c: U32 if c <= 0xA721 => ScriptCommon
      | let c: U32 if c <= 0xA787 => ScriptLatin
      | let c: U32 if c <= 0xA78A => ScriptCommon
      | let c: U32 if c <= 0xA7CD => ScriptLatin
      | let c: U32 if c <= 0xA7CF => ScriptUnknown
      | let c: U32 if c <= 0xA7D1 => ScriptLatin
      | let c: U32 if c <= 0xA7D2 => ScriptUnknown
      | let c: U32 if c <= 0xA7D3 => ScriptLatin
      | let c: U32 if c <= 0xA7D4 => ScriptUnknown
      | let c: U32 if c <= 0xA7DC => ScriptLatin
      | let c: U32 if c <= 0xA7F1 => ScriptUnknown
      | let c: U32 if c <= 0xA7FF => ScriptLatin
      | let c: U32 if c <= 0xA82C => ScriptSylotiNagri
      | let c: U32 if c <= 0xA82F => ScriptUnknown
      | let c: U32 if c <= 0xA839 => ScriptCommon
      | let c: U32 if c <= 0xA83F => ScriptUnknown
      | let c: U32 if c <= 0xA877 => ScriptPhagsPa
      | let c: U32 if c <= 0xA87F => ScriptUnknown
      | let c: U32 if c <= 0xA8C5 => ScriptSaurashtra
      | let c: U32 if c <= 0xA8CD => ScriptUnknown
      | let c: U32 if c <= 0xA8D9 => ScriptSaurashtra
      | let c: U32 if c <= 0xA8DF => ScriptUnknown
      | let c: U32 if c <= 0xA8FF => ScriptDevanagari
      | let c: U32 if c <= 0xA92D => ScriptKayahLi
      | let c: U32 if c <= 0xA92E => ScriptCommon
      | let c: U32 if c <= 0xA92F => ScriptKayahLi
      | let c: U32 if c <= 0xA953 => ScriptRejang
      | let c: U32 if c <= 0xA95E => ScriptUnknown
      | let c: U32 if c <= 0xA95F => ScriptRejang
      | let c: U32 if c <= 0xA97C => ScriptHangul
      | let c: U32 if c <= 0xA97F => ScriptUnknown
      | let c: U32 if c <= 0xA9CD => ScriptJavanese
      | let c: U32 if c <= 0xA9CE => ScriptUnknown
      | let c: U32 if c <= 0xA9CF => ScriptCommon
      | let c: U32 if c <= 0xA9D9 => ScriptJavanese
      | let c: U32 if c <= 0xA9DD => ScriptUnknown
      | let c: U32 if c <= 0xA9DF => ScriptJavanese
      | let c: U32 if c <= 0xA9FE => ScriptMyanmar
      | let c: U32 if c <= 0xA9FF => ScriptUnknown
      | let c: U32 if c <= 0xAA36 => ScriptCham
      | let c: U32 if c <= 0xAA3F => ScriptUnknown
      | let c: U32 if c <= 0xAA4D => ScriptCham
      | let c: U32 if c <= 0xAA4F => ScriptUnknown
      | let c: U32 if c <= 0xAA59 => ScriptCham
      | let c: U32 if c <= 0xAA5B => ScriptUnknown
      | let c: U32 if c <= 0xAA5F => ScriptCham
      | let c: U32 if c <= 0xAA7F => ScriptMyanmar
      | let c: U32 if c <= 0xAAC2 => ScriptTaiViet
      | let c: U32 if c <= 0xAADA => ScriptUnknown
      | let c: U32 if c <= 0xAADF => ScriptTaiViet
      | let c: U32 if c <= 0xAAF6 => ScriptMeeteiMayek
      | let c: U32 if c <= 0xAB00 => ScriptUnknown
      | let c: U32 if c <= 0xAB06 => ScriptEthiopic
      | let c: U32 if c <= 0xAB08 => ScriptUnknown
      | let c: U32 if c <= 0xAB0E => ScriptEthiopic
      | let c: U32 if c <= 0xAB10 => ScriptUnknown
      | let c: U32 if c <= 0xAB16 => ScriptEthiopic
      | let c: U32 if c <= 0xAB1F => ScriptUnknown
      | let c: U32 if c <= 0xAB26 => ScriptEthiopic
      | let c: U32 if c <= 0xAB27 => ScriptUnknown
      | let c: U32 if c <= 0xAB2E => ScriptEthiopic
      | let c: U32 if c <= 0xAB2F => ScriptUnknown
      | let c: U32 if c <= 0xAB5A => ScriptLatin
      | let c: U32 if c <= 0xAB5B => ScriptCommon
      | let c: U32 if c <= 0xAB64 => ScriptLatin
      | let c: U32 if c <= 0xAB65 => ScriptGreek
      | let c: U32 if c <= 0xAB69 => ScriptLatin
      | let c: U32 if c <= 0xAB6B => ScriptCommon
      | let c: U32 if c <= 0xAB6F => ScriptUnknown
      | let c: U32 if c <= 0xABBF => ScriptCherokee
      | let c: U32 if c <= 0xABED => ScriptMeeteiMayek
      | let c: U32 if c <= 0xABEF => ScriptUnknown
      | let c: U32 if c <= 0xABF9 => ScriptMeeteiMayek
      | let c: U32 if c <= 0xABFF => ScriptUnknown
      | let c: U32 if c <= 0xAFFF => ScriptHangul
      else ScriptUnknown
      end
    | 0x000B =>
      match cp
      | let c: U32 if c <= 0xBFFF => ScriptHangul
      else ScriptUnknown
      end
    | 0x000C =>
      match cp
      | let c: U32 if c <= 0xCFFF => ScriptHangul
      else ScriptUnknown
      end
    | 0x000D =>
      match cp
      | let c: U32 if c <= 0xD7A3 => ScriptHangul
      | let c: U32 if c <= 0xD7AF => ScriptUnknown
      | let c: U32 if c <= 0xD7C6 => ScriptHangul
      | let c: U32 if c <= 0xD7CA => ScriptUnknown
      | let c: U32 if c <= 0xD7FB => ScriptHangul
      else ScriptUnknown
      end
    | 0x000F =>
      match cp
      | let c: U32 if c <= 0xF8FF => ScriptUnknown
      | let c: U32 if c <= 0xFA6D => ScriptHan
      | let c: U32 if c <= 0xFA6F => ScriptUnknown
      | let c: U32 if c <= 0xFAD9 => ScriptHan
      | let c: U32 if c <= 0xFAFF => ScriptUnknown
      | let c: U32 if c <= 0xFB06 => ScriptLatin
      | let c: U32 if c <= 0xFB12 => ScriptUnknown
      | let c: U32 if c <= 0xFB17 => ScriptArmenian
      | let c: U32 if c <= 0xFB1C => ScriptUnknown
      | let c: U32 if c <= 0xFB36 => ScriptHebrew
      | let c: U32 if c <= 0xFB37 => ScriptUnknown
      | let c: U32 if c <= 0xFB3C => ScriptHebrew
      | let c: U32 if c <= 0xFB3D => ScriptUnknown
      | let c: U32 if c <= 0xFB3E => ScriptHebrew
      | let c: U32 if c <= 0xFB3F => ScriptUnknown
      | let c: U32 if c <= 0xFB41 => ScriptHebrew
      | let c: U32 if c <= 0xFB42 => ScriptUnknown
      | let c: U32 if c <= 0xFB44 => ScriptHebrew
      | let c: U32 if c <= 0xFB45 => ScriptUnknown
      | let c: U32 if c <= 0xFB4F => ScriptHebrew
      | let c: U32 if c <= 0xFBC2 => ScriptArabic
      | let c: U32 if c <= 0xFBD2 => ScriptUnknown
      | let c: U32 if c <= 0xFD3D => ScriptArabic
      | let c: U32 if c <= 0xFD3F => ScriptCommon
      | let c: U32 if c <= 0xFD8F => ScriptArabic
      | let c: U32 if c <= 0xFD91 => ScriptUnknown
      | let c: U32 if c <= 0xFDC7 => ScriptArabic
      | let c: U32 if c <= 0xFDCE => ScriptUnknown
      | let c: U32 if c <= 0xFDCF => ScriptArabic
      | let c: U32 if c <= 0xFDEF => ScriptUnknown
      | let c: U32 if c <= 0xFDFF => ScriptArabic
      | let c: U32 if c <= 0xFE0F => ScriptInherited
      | let c: U32 if c <= 0xFE19 => ScriptCommon
      | let c: U32 if c <= 0xFE1F => ScriptUnknown
      | let c: U32 if c <= 0xFE2D => ScriptInherited
      | let c: U32 if c <= 0xFE2F => ScriptCyrillic
      | let c: U32 if c <= 0xFE52 => ScriptCommon
      | let c: U32 if c <= 0xFE53 => ScriptUnknown
      | let c: U32 if c <= 0xFE66 => ScriptCommon
      | let c: U32 if c <= 0xFE67 => ScriptUnknown
      | let c: U32 if c <= 0xFE6B => ScriptCommon
      | let c: U32 if c <= 0xFE6F => ScriptUnknown
      | let c: U32 if c <= 0xFE74 => ScriptArabic
      | let c: U32 if c <= 0xFE75 => ScriptUnknown
      | let c: U32 if c <= 0xFEFC => ScriptArabic
      | let c: U32 if c <= 0xFEFE => ScriptUnknown
      | let c: U32 if c <= 0xFEFF => ScriptCommon
      | let c: U32 if c <= 0xFF00 => ScriptUnknown
      | let c: U32 if c <= 0xFF20 => ScriptCommon
      | let c: U32 if c <= 0xFF3A => ScriptLatin
      | let c: U32 if c <= 0xFF40 => ScriptCommon
      | let c: U32 if c <= 0xFF5A => ScriptLatin
      | let c: U32 if c <= 0xFF65 => ScriptCommon
      | let c: U32 if c <= 0xFF6F => ScriptKatakana
      | let c: U32 if c <= 0xFF70 => ScriptCommon
      | let c: U32 if c <= 0xFF9D => ScriptKatakana
      | let c: U32 if c <= 0xFF9F => ScriptCommon
      | let c: U32 if c <= 0xFFBE => ScriptHangul
      | let c: U32 if c <= 0xFFC1 => ScriptUnknown
      | let c: U32 if c <= 0xFFC7 => ScriptHangul
      | let c: U32 if c <= 0xFFC9 => ScriptUnknown
      | let c: U32 if c <= 0xFFCF => ScriptHangul
      | let c: U32 if c <= 0xFFD1 => ScriptUnknown
      | let c: U32 if c <= 0xFFD7 => ScriptHangul
      | let c: U32 if c <= 0xFFD9 => ScriptUnknown
      | let c: U32 if c <= 0xFFDC => ScriptHangul
      | let c: U32 if c <= 0xFFDF => ScriptUnknown
      | let c: U32 if c <= 0xFFE6 => ScriptCommon
      | let c: U32 if c <= 0xFFE7 => ScriptUnknown
      | let c: U32 if c <= 0xFFEE => ScriptCommon
      | let c: U32 if c <= 0xFFF8 => ScriptUnknown
      | let c: U32 if c <= 0xFFFD => ScriptCommon
      else ScriptUnknown
      end
    | 0x0010 =>
      match cp
      | let c: U32 if c <= 0x1000B => ScriptLinearB
      | let c: U32 if c <= 0x1000C => ScriptUnknown
      | let c: U32 if c <= 0x10026 => ScriptLinearB
      | let c: U32 if c <= 0x10027 => ScriptUnknown
      | let c: U32 if c <= 0x1003A => ScriptLinearB
      | let c: U32 if c <= 0x1003B => ScriptUnknown
      | let c: U32 if c <= 0x1003D => ScriptLinearB
      | let c: U32 if c <= 0x1003E => ScriptUnknown
      | let c: U32 if c <= 0x1004D => ScriptLinearB
      | let c: U32 if c <= 0x1004F => ScriptUnknown
      | let c: U32 if c <= 0x1005D => ScriptLinearB
      | let c: U32 if c <= 0x1007F => ScriptUnknown
      | let c: U32 if c <= 0x100FA => ScriptLinearB
      | let c: U32 if c <= 0x100FF => ScriptUnknown
      | let c: U32 if c <= 0x10102 => ScriptCommon
      | let c: U32 if c <= 0x10106 => ScriptUnknown
      | let c: U32 if c <= 0x10133 => ScriptCommon
      | let c: U32 if c <= 0x10136 => ScriptUnknown
      | let c: U32 if c <= 0x1013F => ScriptCommon
      | let c: U32 if c <= 0x1018E => ScriptGreek
      | let c: U32 if c <= 0x1018F => ScriptUnknown
      | let c: U32 if c <= 0x1019C => ScriptCommon
      | let c: U32 if c <= 0x1019F => ScriptUnknown
      | let c: U32 if c <= 0x101A0 => ScriptGreek
      | let c: U32 if c <= 0x101CF => ScriptUnknown
      | let c: U32 if c <= 0x101FC => ScriptCommon
      | let c: U32 if c <= 0x101FD => ScriptInherited
      | let c: U32 if c <= 0x1027F => ScriptUnknown
      | let c: U32 if c <= 0x1029C => ScriptLycian
      | let c: U32 if c <= 0x1029F => ScriptUnknown
      | let c: U32 if c <= 0x102D0 => ScriptCarian
      | let c: U32 if c <= 0x102DF => ScriptUnknown
      | let c: U32 if c <= 0x102E0 => ScriptInherited
      | let c: U32 if c <= 0x102FB => ScriptCommon
      | let c: U32 if c <= 0x102FF => ScriptUnknown
      | let c: U32 if c <= 0x10323 => ScriptOldItalic
      | let c: U32 if c <= 0x1032C => ScriptUnknown
      | let c: U32 if c <= 0x1032F => ScriptOldItalic
      | let c: U32 if c <= 0x1034A => ScriptGothic
      | let c: U32 if c <= 0x1034F => ScriptUnknown
      | let c: U32 if c <= 0x1037A => ScriptOldPermic
      | let c: U32 if c <= 0x1037F => ScriptUnknown
      | let c: U32 if c <= 0x1039D => ScriptUgaritic
      | let c: U32 if c <= 0x1039E => ScriptUnknown
      | let c: U32 if c <= 0x1039F => ScriptUgaritic
      | let c: U32 if c <= 0x103C3 => ScriptOldPersian
      | let c: U32 if c <= 0x103C7 => ScriptUnknown
      | let c: U32 if c <= 0x103D5 => ScriptOldPersian
      | let c: U32 if c <= 0x103FF => ScriptUnknown
      | let c: U32 if c <= 0x1044F => ScriptDeseret
      | let c: U32 if c <= 0x1047F => ScriptShavian
      | let c: U32 if c <= 0x1049D => ScriptOsmanya
      | let c: U32 if c <= 0x1049F => ScriptUnknown
      | let c: U32 if c <= 0x104A9 => ScriptOsmanya
      | let c: U32 if c <= 0x104AF => ScriptUnknown
      | let c: U32 if c <= 0x104D3 => ScriptOsage
      | let c: U32 if c <= 0x104D7 => ScriptUnknown
      | let c: U32 if c <= 0x104FB => ScriptOsage
      | let c: U32 if c <= 0x104FF => ScriptUnknown
      | let c: U32 if c <= 0x10527 => ScriptElbasan
      | let c: U32 if c <= 0x1052F => ScriptUnknown
      | let c: U32 if c <= 0x10563 => ScriptCaucasianAlbanian
      | let c: U32 if c <= 0x1056E => ScriptUnknown
      | let c: U32 if c <= 0x1056F => ScriptCaucasianAlbanian
      | let c: U32 if c <= 0x1057A => ScriptVithkuqi
      | let c: U32 if c <= 0x1057B => ScriptUnknown
      | let c: U32 if c <= 0x1058A => ScriptVithkuqi
      | let c: U32 if c <= 0x1058B => ScriptUnknown
      | let c: U32 if c <= 0x10592 => ScriptVithkuqi
      | let c: U32 if c <= 0x10593 => ScriptUnknown
      | let c: U32 if c <= 0x10595 => ScriptVithkuqi
      | let c: U32 if c <= 0x10596 => ScriptUnknown
      | let c: U32 if c <= 0x105A1 => ScriptVithkuqi
      | let c: U32 if c <= 0x105A2 => ScriptUnknown
      | let c: U32 if c <= 0x105B1 => ScriptVithkuqi
      | let c: U32 if c <= 0x105B2 => ScriptUnknown
      | let c: U32 if c <= 0x105B9 => ScriptVithkuqi
      | let c: U32 if c <= 0x105BA => ScriptUnknown
      | let c: U32 if c <= 0x105BC => ScriptVithkuqi
      | let c: U32 if c <= 0x105BF => ScriptUnknown
      | let c: U32 if c <= 0x105F3 => ScriptTodhri
      | let c: U32 if c <= 0x105FF => ScriptUnknown
      | let c: U32 if c <= 0x10736 => ScriptLinearA
      | let c: U32 if c <= 0x1073F => ScriptUnknown
      | let c: U32 if c <= 0x10755 => ScriptLinearA
      | let c: U32 if c <= 0x1075F => ScriptUnknown
      | let c: U32 if c <= 0x10767 => ScriptLinearA
      | let c: U32 if c <= 0x1077F => ScriptUnknown
      | let c: U32 if c <= 0x10785 => ScriptLatin
      | let c: U32 if c <= 0x10786 => ScriptUnknown
      | let c: U32 if c <= 0x107B0 => ScriptLatin
      | let c: U32 if c <= 0x107B1 => ScriptUnknown
      | let c: U32 if c <= 0x107BA => ScriptLatin
      | let c: U32 if c <= 0x107FF => ScriptUnknown
      | let c: U32 if c <= 0x10805 => ScriptCypriot
      | let c: U32 if c <= 0x10807 => ScriptUnknown
      | let c: U32 if c <= 0x10808 => ScriptCypriot
      | let c: U32 if c <= 0x10809 => ScriptUnknown
      | let c: U32 if c <= 0x10835 => ScriptCypriot
      | let c: U32 if c <= 0x10836 => ScriptUnknown
      | let c: U32 if c <= 0x10838 => ScriptCypriot
      | let c: U32 if c <= 0x1083B => ScriptUnknown
      | let c: U32 if c <= 0x1083C => ScriptCypriot
      | let c: U32 if c <= 0x1083E => ScriptUnknown
      | let c: U32 if c <= 0x1083F => ScriptCypriot
      | let c: U32 if c <= 0x10855 => ScriptImperialAramaic
      | let c: U32 if c <= 0x10856 => ScriptUnknown
      | let c: U32 if c <= 0x1085F => ScriptImperialAramaic
      | let c: U32 if c <= 0x1087F => ScriptPalmyrene
      | let c: U32 if c <= 0x1089E => ScriptNabataean
      | let c: U32 if c <= 0x108A6 => ScriptUnknown
      | let c: U32 if c <= 0x108AF => ScriptNabataean
      | let c: U32 if c <= 0x108DF => ScriptUnknown
      | let c: U32 if c <= 0x108F2 => ScriptHatran
      | let c: U32 if c <= 0x108F3 => ScriptUnknown
      | let c: U32 if c <= 0x108F5 => ScriptHatran
      | let c: U32 if c <= 0x108FA => ScriptUnknown
      | let c: U32 if c <= 0x108FF => ScriptHatran
      | let c: U32 if c <= 0x1091B => ScriptPhoenician
      | let c: U32 if c <= 0x1091E => ScriptUnknown
      | let c: U32 if c <= 0x1091F => ScriptPhoenician
      | let c: U32 if c <= 0x10939 => ScriptLydian
      | let c: U32 if c <= 0x1093E => ScriptUnknown
      | let c: U32 if c <= 0x1093F => ScriptLydian
      | let c: U32 if c <= 0x1097F => ScriptUnknown
      | let c: U32 if c <= 0x1099F => ScriptMeroiticHieroglyphs
      | let c: U32 if c <= 0x109B7 => ScriptMeroiticCursive
      | let c: U32 if c <= 0x109BB => ScriptUnknown
      | let c: U32 if c <= 0x109CF => ScriptMeroiticCursive
      | let c: U32 if c <= 0x109D1 => ScriptUnknown
      | let c: U32 if c <= 0x109FF => ScriptMeroiticCursive
      | let c: U32 if c <= 0x10A03 => ScriptKharoshthi
      | let c: U32 if c <= 0x10A04 => ScriptUnknown
      | let c: U32 if c <= 0x10A06 => ScriptKharoshthi
      | let c: U32 if c <= 0x10A0B => ScriptUnknown
      | let c: U32 if c <= 0x10A13 => ScriptKharoshthi
      | let c: U32 if c <= 0x10A14 => ScriptUnknown
      | let c: U32 if c <= 0x10A17 => ScriptKharoshthi
      | let c: U32 if c <= 0x10A18 => ScriptUnknown
      | let c: U32 if c <= 0x10A35 => ScriptKharoshthi
      | let c: U32 if c <= 0x10A37 => ScriptUnknown
      | let c: U32 if c <= 0x10A3A => ScriptKharoshthi
      | let c: U32 if c <= 0x10A3E => ScriptUnknown
      | let c: U32 if c <= 0x10A48 => ScriptKharoshthi
      | let c: U32 if c <= 0x10A4F => ScriptUnknown
      | let c: U32 if c <= 0x10A58 => ScriptKharoshthi
      | let c: U32 if c <= 0x10A5F => ScriptUnknown
      | let c: U32 if c <= 0x10A7F => ScriptOldSouthArabian
      | let c: U32 if c <= 0x10A9F => ScriptOldNorthArabian
      | let c: U32 if c <= 0x10ABF => ScriptUnknown
      | let c: U32 if c <= 0x10AE6 => ScriptManichaean
      | let c: U32 if c <= 0x10AEA => ScriptUnknown
      | let c: U32 if c <= 0x10AF6 => ScriptManichaean
      | let c: U32 if c <= 0x10AFF => ScriptUnknown
      | let c: U32 if c <= 0x10B35 => ScriptAvestan
      | let c: U32 if c <= 0x10B38 => ScriptUnknown
      | let c: U32 if c <= 0x10B3F => ScriptAvestan
      | let c: U32 if c <= 0x10B55 => ScriptInscriptionalParthian
      | let c: U32 if c <= 0x10B57 => ScriptUnknown
      | let c: U32 if c <= 0x10B5F => ScriptInscriptionalParthian
      | let c: U32 if c <= 0x10B72 => ScriptInscriptionalPahlavi
      | let c: U32 if c <= 0x10B77 => ScriptUnknown
      | let c: U32 if c <= 0x10B7F => ScriptInscriptionalPahlavi
      | let c: U32 if c <= 0x10B91 => ScriptPsalterPahlavi
      | let c: U32 if c <= 0x10B98 => ScriptUnknown
      | let c: U32 if c <= 0x10B9C => ScriptPsalterPahlavi
      | let c: U32 if c <= 0x10BA8 => ScriptUnknown
      | let c: U32 if c <= 0x10BAF => ScriptPsalterPahlavi
      | let c: U32 if c <= 0x10BFF => ScriptUnknown
      | let c: U32 if c <= 0x10C48 => ScriptOldTurkic
      | let c: U32 if c <= 0x10C7F => ScriptUnknown
      | let c: U32 if c <= 0x10CB2 => ScriptOldHungarian
      | let c: U32 if c <= 0x10CBF => ScriptUnknown
      | let c: U32 if c <= 0x10CF2 => ScriptOldHungarian
      | let c: U32 if c <= 0x10CF9 => ScriptUnknown
      | let c: U32 if c <= 0x10CFF => ScriptOldHungarian
      | let c: U32 if c <= 0x10D27 => ScriptHanifiRohingya
      | let c: U32 if c <= 0x10D2F => ScriptUnknown
      | let c: U32 if c <= 0x10D39 => ScriptHanifiRohingya
      | let c: U32 if c <= 0x10D3F => ScriptUnknown
      | let c: U32 if c <= 0x10D65 => ScriptGaray
      | let c: U32 if c <= 0x10D68 => ScriptUnknown
      | let c: U32 if c <= 0x10D85 => ScriptGaray
      | let c: U32 if c <= 0x10D8D => ScriptUnknown
      | let c: U32 if c <= 0x10D8F => ScriptGaray
      | let c: U32 if c <= 0x10E5F => ScriptUnknown
      | let c: U32 if c <= 0x10E7E => ScriptArabic
      | let c: U32 if c <= 0x10E7F => ScriptUnknown
      | let c: U32 if c <= 0x10EA9 => ScriptYezidi
      | let c: U32 if c <= 0x10EAA => ScriptUnknown
      | let c: U32 if c <= 0x10EAD => ScriptYezidi
      | let c: U32 if c <= 0x10EAF => ScriptUnknown
      | let c: U32 if c <= 0x10EB1 => ScriptYezidi
      | let c: U32 if c <= 0x10EC1 => ScriptUnknown
      | let c: U32 if c <= 0x10EC4 => ScriptArabic
      | let c: U32 if c <= 0x10EFB => ScriptUnknown
      | let c: U32 if c <= 0x10EFF => ScriptArabic
      | let c: U32 if c <= 0x10F27 => ScriptOldSogdian
      | let c: U32 if c <= 0x10F2F => ScriptUnknown
      | let c: U32 if c <= 0x10F59 => ScriptSogdian
      | let c: U32 if c <= 0x10F6F => ScriptUnknown
      | let c: U32 if c <= 0x10F89 => ScriptOldUyghur
      | let c: U32 if c <= 0x10FAF => ScriptUnknown
      | let c: U32 if c <= 0x10FCB => ScriptChorasmian
      | let c: U32 if c <= 0x10FDF => ScriptUnknown
      | let c: U32 if c <= 0x10FF6 => ScriptElymaic
      else ScriptUnknown
      end
    | 0x0011 =>
      match cp
      | let c: U32 if c <= 0x1104D => ScriptBrahmi
      | let c: U32 if c <= 0x11051 => ScriptUnknown
      | let c: U32 if c <= 0x11075 => ScriptBrahmi
      | let c: U32 if c <= 0x1107E => ScriptUnknown
      | let c: U32 if c <= 0x1107F => ScriptBrahmi
      | let c: U32 if c <= 0x110C2 => ScriptKaithi
      | let c: U32 if c <= 0x110CC => ScriptUnknown
      | let c: U32 if c <= 0x110CD => ScriptKaithi
      | let c: U32 if c <= 0x110CF => ScriptUnknown
      | let c: U32 if c <= 0x110E8 => ScriptSoraSompeng
      | let c: U32 if c <= 0x110EF => ScriptUnknown
      | let c: U32 if c <= 0x110F9 => ScriptSoraSompeng
      | let c: U32 if c <= 0x110FF => ScriptUnknown
      | let c: U32 if c <= 0x11134 => ScriptChakma
      | let c: U32 if c <= 0x11135 => ScriptUnknown
      | let c: U32 if c <= 0x11147 => ScriptChakma
      | let c: U32 if c <= 0x1114F => ScriptUnknown
      | let c: U32 if c <= 0x11176 => ScriptMahajani
      | let c: U32 if c <= 0x1117F => ScriptUnknown
      | let c: U32 if c <= 0x111DF => ScriptSharada
      | let c: U32 if c <= 0x111E0 => ScriptUnknown
      | let c: U32 if c <= 0x111F4 => ScriptSinhala
      | let c: U32 if c <= 0x111FF => ScriptUnknown
      | let c: U32 if c <= 0x11211 => ScriptKhojki
      | let c: U32 if c <= 0x11212 => ScriptUnknown
      | let c: U32 if c <= 0x11241 => ScriptKhojki
      | let c: U32 if c <= 0x1127F => ScriptUnknown
      | let c: U32 if c <= 0x11286 => ScriptMultani
      | let c: U32 if c <= 0x11287 => ScriptUnknown
      | let c: U32 if c <= 0x11288 => ScriptMultani
      | let c: U32 if c <= 0x11289 => ScriptUnknown
      | let c: U32 if c <= 0x1128D => ScriptMultani
      | let c: U32 if c <= 0x1128E => ScriptUnknown
      | let c: U32 if c <= 0x1129D => ScriptMultani
      | let c: U32 if c <= 0x1129E => ScriptUnknown
      | let c: U32 if c <= 0x112A9 => ScriptMultani
      | let c: U32 if c <= 0x112AF => ScriptUnknown
      | let c: U32 if c <= 0x112EA => ScriptKhudawadi
      | let c: U32 if c <= 0x112EF => ScriptUnknown
      | let c: U32 if c <= 0x112F9 => ScriptKhudawadi
      | let c: U32 if c <= 0x112FF => ScriptUnknown
      | let c: U32 if c <= 0x11303 => ScriptGrantha
      | let c: U32 if c <= 0x11304 => ScriptUnknown
      | let c: U32 if c <= 0x1130C => ScriptGrantha
      | let c: U32 if c <= 0x1130E => ScriptUnknown
      | let c: U32 if c <= 0x11310 => ScriptGrantha
      | let c: U32 if c <= 0x11312 => ScriptUnknown
      | let c: U32 if c <= 0x11328 => ScriptGrantha
      | let c: U32 if c <= 0x11329 => ScriptUnknown
      | let c: U32 if c <= 0x11330 => ScriptGrantha
      | let c: U32 if c <= 0x11331 => ScriptUnknown
      | let c: U32 if c <= 0x11333 => ScriptGrantha
      | let c: U32 if c <= 0x11334 => ScriptUnknown
      | let c: U32 if c <= 0x11339 => ScriptGrantha
      | let c: U32 if c <= 0x1133A => ScriptUnknown
      | let c: U32 if c <= 0x1133B => ScriptInherited
      | let c: U32 if c <= 0x11344 => ScriptGrantha
      | let c: U32 if c <= 0x11346 => ScriptUnknown
      | let c: U32 if c <= 0x11348 => ScriptGrantha
      | let c: U32 if c <= 0x1134A => ScriptUnknown
      | let c: U32 if c <= 0x1134D => ScriptGrantha
      | let c: U32 if c <= 0x1134F => ScriptUnknown
      | let c: U32 if c <= 0x11350 => ScriptGrantha
      | let c: U32 if c <= 0x11356 => ScriptUnknown
      | let c: U32 if c <= 0x11357 => ScriptGrantha
      | let c: U32 if c <= 0x1135C => ScriptUnknown
      | let c: U32 if c <= 0x11363 => ScriptGrantha
      | let c: U32 if c <= 0x11365 => ScriptUnknown
      | let c: U32 if c <= 0x1136C => ScriptGrantha
      | let c: U32 if c <= 0x1136F => ScriptUnknown
      | let c: U32 if c <= 0x11374 => ScriptGrantha
      | let c: U32 if c <= 0x1137F => ScriptUnknown
      | let c: U32 if c <= 0x11389 => ScriptTuluTigalari
      | let c: U32 if c <= 0x1138A => ScriptUnknown
      | let c: U32 if c <= 0x1138B => ScriptTuluTigalari
      | let c: U32 if c <= 0x1138D => ScriptUnknown
      | let c: U32 if c <= 0x1138E => ScriptTuluTigalari
      | let c: U32 if c <= 0x1138F => ScriptUnknown
      | let c: U32 if c <= 0x113B5 => ScriptTuluTigalari
      | let c: U32 if c <= 0x113B6 => ScriptUnknown
      | let c: U32 if c <= 0x113C0 => ScriptTuluTigalari
      | let c: U32 if c <= 0x113C1 => ScriptUnknown
      | let c: U32 if c <= 0x113C2 => ScriptTuluTigalari
      | let c: U32 if c <= 0x113C4 => ScriptUnknown
      | let c: U32 if c <= 0x113C5 => ScriptTuluTigalari
      | let c: U32 if c <= 0x113C6 => ScriptUnknown
      | let c: U32 if c <= 0x113CA => ScriptTuluTigalari
      | let c: U32 if c <= 0x113CB => ScriptUnknown
      | let c: U32 if c <= 0x113D5 => ScriptTuluTigalari
      | let c: U32 if c <= 0x113D6 => ScriptUnknown
      | let c: U32 if c <= 0x113D8 => ScriptTuluTigalari
      | let c: U32 if c <= 0x113E0 => ScriptUnknown
      | let c: U32 if c <= 0x113E2 => ScriptTuluTigalari
      | let c: U32 if c <= 0x113FF => ScriptUnknown
      | let c: U32 if c <= 0x1145B => ScriptNewa
      | let c: U32 if c <= 0x1145C => ScriptUnknown
      | let c: U32 if c <= 0x11461 => ScriptNewa
      | let c: U32 if c <= 0x1147F => ScriptUnknown
      | let c: U32 if c <= 0x114C7 => ScriptTirhuta
      | let c: U32 if c <= 0x114CF => ScriptUnknown
      | let c: U32 if c <= 0x114D9 => ScriptTirhuta
      | let c: U32 if c <= 0x1157F => ScriptUnknown
      | let c: U32 if c <= 0x115B5 => ScriptSiddham
      | let c: U32 if c <= 0x115B7 => ScriptUnknown
      | let c: U32 if c <= 0x115DD => ScriptSiddham
      | let c: U32 if c <= 0x115FF => ScriptUnknown
      | let c: U32 if c <= 0x11644 => ScriptModi
      | let c: U32 if c <= 0x1164F => ScriptUnknown
      | let c: U32 if c <= 0x11659 => ScriptModi
      | let c: U32 if c <= 0x1165F => ScriptUnknown
      | let c: U32 if c <= 0x1166C => ScriptMongolian
      | let c: U32 if c <= 0x1167F => ScriptUnknown
      | let c: U32 if c <= 0x116B9 => ScriptTakri
      | let c: U32 if c <= 0x116BF => ScriptUnknown
      | let c: U32 if c <= 0x116C9 => ScriptTakri
      | let c: U32 if c <= 0x116CF => ScriptUnknown
      | let c: U32 if c <= 0x116E3 => ScriptMyanmar
      | let c: U32 if c <= 0x116FF => ScriptUnknown
      | let c: U32 if c <= 0x1171A => ScriptAhom
      | let c: U32 if c <= 0x1171C => ScriptUnknown
      | let c: U32 if c <= 0x1172B => ScriptAhom
      | let c: U32 if c <= 0x1172F => ScriptUnknown
      | let c: U32 if c <= 0x11746 => ScriptAhom
      | let c: U32 if c <= 0x117FF => ScriptUnknown
      | let c: U32 if c <= 0x1183B => ScriptDogra
      | let c: U32 if c <= 0x1189F => ScriptUnknown
      | let c: U32 if c <= 0x118F2 => ScriptWarangCiti
      | let c: U32 if c <= 0x118FE => ScriptUnknown
      | let c: U32 if c <= 0x118FF => ScriptWarangCiti
      | let c: U32 if c <= 0x11906 => ScriptDivesAkuru
      | let c: U32 if c <= 0x11908 => ScriptUnknown
      | let c: U32 if c <= 0x11909 => ScriptDivesAkuru
      | let c: U32 if c <= 0x1190B => ScriptUnknown
      | let c: U32 if c <= 0x11913 => ScriptDivesAkuru
      | let c: U32 if c <= 0x11914 => ScriptUnknown
      | let c: U32 if c <= 0x11916 => ScriptDivesAkuru
      | let c: U32 if c <= 0x11917 => ScriptUnknown
      | let c: U32 if c <= 0x11935 => ScriptDivesAkuru
      | let c: U32 if c <= 0x11936 => ScriptUnknown
      | let c: U32 if c <= 0x11938 => ScriptDivesAkuru
      | let c: U32 if c <= 0x1193A => ScriptUnknown
      | let c: U32 if c <= 0x11946 => ScriptDivesAkuru
      | let c: U32 if c <= 0x1194F => ScriptUnknown
      | let c: U32 if c <= 0x11959 => ScriptDivesAkuru
      | let c: U32 if c <= 0x1199F => ScriptUnknown
      | let c: U32 if c <= 0x119A7 => ScriptNandinagari
      | let c: U32 if c <= 0x119A9 => ScriptUnknown
      | let c: U32 if c <= 0x119D7 => ScriptNandinagari
      | let c: U32 if c <= 0x119D9 => ScriptUnknown
      | let c: U32 if c <= 0x119E4 => ScriptNandinagari
      | let c: U32 if c <= 0x119FF => ScriptUnknown
      | let c: U32 if c <= 0x11A47 => ScriptZanabazarSquare
      | let c: U32 if c <= 0x11A4F => ScriptUnknown
      | let c: U32 if c <= 0x11AA2 => ScriptSoyombo
      | let c: U32 if c <= 0x11AAF => ScriptUnknown
      | let c: U32 if c <= 0x11ABF => ScriptCanadianAboriginal
      | let c: U32 if c <= 0x11AF8 => ScriptPauCinHau
      | let c: U32 if c <= 0x11AFF => ScriptUnknown
      | let c: U32 if c <= 0x11B09 => ScriptDevanagari
      | let c: U32 if c <= 0x11BBF => ScriptUnknown
      | let c: U32 if c <= 0x11BE1 => ScriptSunuwar
      | let c: U32 if c <= 0x11BEF => ScriptUnknown
      | let c: U32 if c <= 0x11BF9 => ScriptSunuwar
      | let c: U32 if c <= 0x11BFF => ScriptUnknown
      | let c: U32 if c <= 0x11C08 => ScriptBhaiksuki
      | let c: U32 if c <= 0x11C09 => ScriptUnknown
      | let c: U32 if c <= 0x11C36 => ScriptBhaiksuki
      | let c: U32 if c <= 0x11C37 => ScriptUnknown
      | let c: U32 if c <= 0x11C45 => ScriptBhaiksuki
      | let c: U32 if c <= 0x11C4F => ScriptUnknown
      | let c: U32 if c <= 0x11C6C => ScriptBhaiksuki
      | let c: U32 if c <= 0x11C6F => ScriptUnknown
      | let c: U32 if c <= 0x11C8F => ScriptMarchen
      | let c: U32 if c <= 0x11C91 => ScriptUnknown
      | let c: U32 if c <= 0x11CA7 => ScriptMarchen
      | let c: U32 if c <= 0x11CA8 => ScriptUnknown
      | let c: U32 if c <= 0x11CB6 => ScriptMarchen
      | let c: U32 if c <= 0x11CFF => ScriptUnknown
      | let c: U32 if c <= 0x11D06 => ScriptMasaramGondi
      | let c: U32 if c <= 0x11D07 => ScriptUnknown
      | let c: U32 if c <= 0x11D09 => ScriptMasaramGondi
      | let c: U32 if c <= 0x11D0A => ScriptUnknown
      | let c: U32 if c <= 0x11D36 => ScriptMasaramGondi
      | let c: U32 if c <= 0x11D39 => ScriptUnknown
      | let c: U32 if c <= 0x11D3A => ScriptMasaramGondi
      | let c: U32 if c <= 0x11D3B => ScriptUnknown
      | let c: U32 if c <= 0x11D3D => ScriptMasaramGondi
      | let c: U32 if c <= 0x11D3E => ScriptUnknown
      | let c: U32 if c <= 0x11D47 => ScriptMasaramGondi
      | let c: U32 if c <= 0x11D4F => ScriptUnknown
      | let c: U32 if c <= 0x11D59 => ScriptMasaramGondi
      | let c: U32 if c <= 0x11D5F => ScriptUnknown
      | let c: U32 if c <= 0x11D65 => ScriptGunjalaGondi
      | let c: U32 if c <= 0x11D66 => ScriptUnknown
      | let c: U32 if c <= 0x11D68 => ScriptGunjalaGondi
      | let c: U32 if c <= 0x11D69 => ScriptUnknown
      | let c: U32 if c <= 0x11D8E => ScriptGunjalaGondi
      | let c: U32 if c <= 0x11D8F => ScriptUnknown
      | let c: U32 if c <= 0x11D91 => ScriptGunjalaGondi
      | let c: U32 if c <= 0x11D92 => ScriptUnknown
      | let c: U32 if c <= 0x11D98 => ScriptGunjalaGondi
      | let c: U32 if c <= 0x11D9F => ScriptUnknown
      | let c: U32 if c <= 0x11DA9 => ScriptGunjalaGondi
      | let c: U32 if c <= 0x11EDF => ScriptUnknown
      | let c: U32 if c <= 0x11EF8 => ScriptMakasar
      | let c: U32 if c <= 0x11EFF => ScriptUnknown
      | let c: U32 if c <= 0x11F10 => ScriptKawi
      | let c: U32 if c <= 0x11F11 => ScriptUnknown
      | let c: U32 if c <= 0x11F3A => ScriptKawi
      | let c: U32 if c <= 0x11F3D => ScriptUnknown
      | let c: U32 if c <= 0x11F5A => ScriptKawi
      | let c: U32 if c <= 0x11FAF => ScriptUnknown
      | let c: U32 if c <= 0x11FB0 => ScriptLisu
      | let c: U32 if c <= 0x11FBF => ScriptUnknown
      | let c: U32 if c <= 0x11FF1 => ScriptTamil
      | let c: U32 if c <= 0x11FFE => ScriptUnknown
      | let c: U32 if c <= 0x11FFF => ScriptTamil
      else ScriptUnknown
      end
    | 0x0012 =>
      match cp
      | let c: U32 if c <= 0x12399 => ScriptCuneiform
      | let c: U32 if c <= 0x123FF => ScriptUnknown
      | let c: U32 if c <= 0x1246E => ScriptCuneiform
      | let c: U32 if c <= 0x1246F => ScriptUnknown
      | let c: U32 if c <= 0x12474 => ScriptCuneiform
      | let c: U32 if c <= 0x1247F => ScriptUnknown
      | let c: U32 if c <= 0x12543 => ScriptCuneiform
      | let c: U32 if c <= 0x12F8F => ScriptUnknown
      | let c: U32 if c <= 0x12FF2 => ScriptCyproMinoan
      else ScriptUnknown
      end
    | 0x0013 =>
      match cp
      | let c: U32 if c <= 0x13455 => ScriptEgyptianHieroglyphs
      | let c: U32 if c <= 0x1345F => ScriptUnknown
      | let c: U32 if c <= 0x13FFF => ScriptEgyptianHieroglyphs
      else ScriptUnknown
      end
    | 0x0014 =>
      match cp
      | let c: U32 if c <= 0x143FA => ScriptEgyptianHieroglyphs
      | let c: U32 if c <= 0x143FF => ScriptUnknown
      | let c: U32 if c <= 0x14646 => ScriptAnatolianHieroglyphs
      else ScriptUnknown
      end
    | 0x0016 =>
      match cp
      | let c: U32 if c <= 0x160FF => ScriptUnknown
      | let c: U32 if c <= 0x16139 => ScriptGurungKhema
      | let c: U32 if c <= 0x167FF => ScriptUnknown
      | let c: U32 if c <= 0x16A38 => ScriptBamum
      | let c: U32 if c <= 0x16A3F => ScriptUnknown
      | let c: U32 if c <= 0x16A5E => ScriptMro
      | let c: U32 if c <= 0x16A5F => ScriptUnknown
      | let c: U32 if c <= 0x16A69 => ScriptMro
      | let c: U32 if c <= 0x16A6D => ScriptUnknown
      | let c: U32 if c <= 0x16A6F => ScriptMro
      | let c: U32 if c <= 0x16ABE => ScriptTangsa
      | let c: U32 if c <= 0x16ABF => ScriptUnknown
      | let c: U32 if c <= 0x16AC9 => ScriptTangsa
      | let c: U32 if c <= 0x16ACF => ScriptUnknown
      | let c: U32 if c <= 0x16AED => ScriptBassaVah
      | let c: U32 if c <= 0x16AEF => ScriptUnknown
      | let c: U32 if c <= 0x16AF5 => ScriptBassaVah
      | let c: U32 if c <= 0x16AFF => ScriptUnknown
      | let c: U32 if c <= 0x16B45 => ScriptPahawhHmong
      | let c: U32 if c <= 0x16B4F => ScriptUnknown
      | let c: U32 if c <= 0x16B59 => ScriptPahawhHmong
      | let c: U32 if c <= 0x16B5A => ScriptUnknown
      | let c: U32 if c <= 0x16B61 => ScriptPahawhHmong
      | let c: U32 if c <= 0x16B62 => ScriptUnknown
      | let c: U32 if c <= 0x16B77 => ScriptPahawhHmong
      | let c: U32 if c <= 0x16B7C => ScriptUnknown
      | let c: U32 if c <= 0x16B8F => ScriptPahawhHmong
      | let c: U32 if c <= 0x16D3F => ScriptUnknown
      | let c: U32 if c <= 0x16D79 => ScriptKiratRai
      | let c: U32 if c <= 0x16E3F => ScriptUnknown
      | let c: U32 if c <= 0x16E9A => ScriptMedefaidrin
      | let c: U32 if c <= 0x16EFF => ScriptUnknown
      | let c: U32 if c <= 0x16F4A => ScriptMiao
      | let c: U32 if c <= 0x16F4E => ScriptUnknown
      | let c: U32 if c <= 0x16F87 => ScriptMiao
      | let c: U32 if c <= 0x16F8E => ScriptUnknown
      | let c: U32 if c <= 0x16F9F => ScriptMiao
      | let c: U32 if c <= 0x16FDF => ScriptUnknown
      | let c: U32 if c <= 0x16FE0 => ScriptTangut
      | let c: U32 if c <= 0x16FE1 => ScriptNushu
      | let c: U32 if c <= 0x16FE3 => ScriptHan
      | let c: U32 if c <= 0x16FE4 => ScriptKhitanSmallScript
      | let c: U32 if c <= 0x16FEF => ScriptUnknown
      | let c: U32 if c <= 0x16FF1 => ScriptHan
      else ScriptUnknown
      end
    | 0x0017 =>
      match cp
      | let c: U32 if c <= 0x17FFF => ScriptTangut
      else ScriptUnknown
      end
    | 0x0018 =>
      match cp
      | let c: U32 if c <= 0x187F7 => ScriptTangut
      | let c: U32 if c <= 0x187FF => ScriptUnknown
      | let c: U32 if c <= 0x18AFF => ScriptTangut
      | let c: U32 if c <= 0x18CD5 => ScriptKhitanSmallScript
      | let c: U32 if c <= 0x18CFE => ScriptUnknown
      | let c: U32 if c <= 0x18CFF => ScriptKhitanSmallScript
      | let c: U32 if c <= 0x18D08 => ScriptTangut
      else ScriptUnknown
      end
    | 0x001A =>
      match cp
      | let c: U32 if c <= 0x1AFEF => ScriptUnknown
      | let c: U32 if c <= 0x1AFF3 => ScriptKatakana
      | let c: U32 if c <= 0x1AFF4 => ScriptUnknown
      | let c: U32 if c <= 0x1AFFB => ScriptKatakana
      | let c: U32 if c <= 0x1AFFC => ScriptUnknown
      | let c: U32 if c <= 0x1AFFE => ScriptKatakana
      else ScriptUnknown
      end
    | 0x001B =>
      match cp
      | let c: U32 if c <= 0x1B000 => ScriptKatakana
      | let c: U32 if c <= 0x1B11F => ScriptHiragana
      | let c: U32 if c <= 0x1B122 => ScriptKatakana
      | let c: U32 if c <= 0x1B131 => ScriptUnknown
      | let c: U32 if c <= 0x1B132 => ScriptHiragana
      | let c: U32 if c <= 0x1B14F => ScriptUnknown
      | let c: U32 if c <= 0x1B152 => ScriptHiragana
      | let c: U32 if c <= 0x1B154 => ScriptUnknown
      | let c: U32 if c <= 0x1B155 => ScriptKatakana
      | let c: U32 if c <= 0x1B163 => ScriptUnknown
      | let c: U32 if c <= 0x1B167 => ScriptKatakana
      | let c: U32 if c <= 0x1B16F => ScriptUnknown
      | let c: U32 if c <= 0x1B2FB => ScriptNushu
      | let c: U32 if c <= 0x1BBFF => ScriptUnknown
      | let c: U32 if c <= 0x1BC6A => ScriptDuployan
      | let c: U32 if c <= 0x1BC6F => ScriptUnknown
      | let c: U32 if c <= 0x1BC7C => ScriptDuployan
      | let c: U32 if c <= 0x1BC7F => ScriptUnknown
      | let c: U32 if c <= 0x1BC88 => ScriptDuployan
      | let c: U32 if c <= 0x1BC8F => ScriptUnknown
      | let c: U32 if c <= 0x1BC99 => ScriptDuployan
      | let c: U32 if c <= 0x1BC9B => ScriptUnknown
      | let c: U32 if c <= 0x1BC9F => ScriptDuployan
      | let c: U32 if c <= 0x1BCA3 => ScriptCommon
      else ScriptUnknown
      end
    | 0x001C =>
      match cp
      | let c: U32 if c <= 0x1CBFF => ScriptUnknown
      | let c: U32 if c <= 0x1CCF9 => ScriptCommon
      | let c: U32 if c <= 0x1CCFF => ScriptUnknown
      | let c: U32 if c <= 0x1CEB3 => ScriptCommon
      | let c: U32 if c <= 0x1CEFF => ScriptUnknown
      | let c: U32 if c <= 0x1CF2D => ScriptInherited
      | let c: U32 if c <= 0x1CF2F => ScriptUnknown
      | let c: U32 if c <= 0x1CF46 => ScriptInherited
      | let c: U32 if c <= 0x1CF4F => ScriptUnknown
      | let c: U32 if c <= 0x1CFC3 => ScriptCommon
      else ScriptUnknown
      end
    | 0x001D =>
      match cp
      | let c: U32 if c <= 0x1D0F5 => ScriptCommon
      | let c: U32 if c <= 0x1D0FF => ScriptUnknown
      | let c: U32 if c <= 0x1D126 => ScriptCommon
      | let c: U32 if c <= 0x1D128 => ScriptUnknown
      | let c: U32 if c <= 0x1D166 => ScriptCommon
      | let c: U32 if c <= 0x1D169 => ScriptInherited
      | let c: U32 if c <= 0x1D17A => ScriptCommon
      | let c: U32 if c <= 0x1D182 => ScriptInherited
      | let c: U32 if c <= 0x1D184 => ScriptCommon
      | let c: U32 if c <= 0x1D18B => ScriptInherited
      | let c: U32 if c <= 0x1D1A9 => ScriptCommon
      | let c: U32 if c <= 0x1D1AD => ScriptInherited
      | let c: U32 if c <= 0x1D1EA => ScriptCommon
      | let c: U32 if c <= 0x1D1FF => ScriptUnknown
      | let c: U32 if c <= 0x1D245 => ScriptGreek
      | let c: U32 if c <= 0x1D2BF => ScriptUnknown
      | let c: U32 if c <= 0x1D2D3 => ScriptCommon
      | let c: U32 if c <= 0x1D2DF => ScriptUnknown
      | let c: U32 if c <= 0x1D2F3 => ScriptCommon
      | let c: U32 if c <= 0x1D2FF => ScriptUnknown
      | let c: U32 if c <= 0x1D356 => ScriptCommon
      | let c: U32 if c <= 0x1D35F => ScriptUnknown
      | let c: U32 if c <= 0x1D378 => ScriptCommon
      | let c: U32 if c <= 0x1D3FF => ScriptUnknown
      | let c: U32 if c <= 0x1D454 => ScriptCommon
      | let c: U32 if c <= 0x1D455 => ScriptUnknown
      | let c: U32 if c <= 0x1D49C => ScriptCommon
      | let c: U32 if c <= 0x1D49D => ScriptUnknown
      | let c: U32 if c <= 0x1D49F => ScriptCommon
      | let c: U32 if c <= 0x1D4A1 => ScriptUnknown
      | let c: U32 if c <= 0x1D4A2 => ScriptCommon
      | let c: U32 if c <= 0x1D4A4 => ScriptUnknown
      | let c: U32 if c <= 0x1D4A6 => ScriptCommon
      | let c: U32 if c <= 0x1D4A8 => ScriptUnknown
      | let c: U32 if c <= 0x1D4AC => ScriptCommon
      | let c: U32 if c <= 0x1D4AD => ScriptUnknown
      | let c: U32 if c <= 0x1D4B9 => ScriptCommon
      | let c: U32 if c <= 0x1D4BA => ScriptUnknown
      | let c: U32 if c <= 0x1D4BB => ScriptCommon
      | let c: U32 if c <= 0x1D4BC => ScriptUnknown
      | let c: U32 if c <= 0x1D4C3 => ScriptCommon
      | let c: U32 if c <= 0x1D4C4 => ScriptUnknown
      | let c: U32 if c <= 0x1D505 => ScriptCommon
      | let c: U32 if c <= 0x1D506 => ScriptUnknown
      | let c: U32 if c <= 0x1D50A => ScriptCommon
      | let c: U32 if c <= 0x1D50C => ScriptUnknown
      | let c: U32 if c <= 0x1D514 => ScriptCommon
      | let c: U32 if c <= 0x1D515 => ScriptUnknown
      | let c: U32 if c <= 0x1D51C => ScriptCommon
      | let c: U32 if c <= 0x1D51D => ScriptUnknown
      | let c: U32 if c <= 0x1D539 => ScriptCommon
      | let c: U32 if c <= 0x1D53A => ScriptUnknown
      | let c: U32 if c <= 0x1D53E => ScriptCommon
      | let c: U32 if c <= 0x1D53F => ScriptUnknown
      | let c: U32 if c <= 0x1D544 => ScriptCommon
      | let c: U32 if c <= 0x1D545 => ScriptUnknown
      | let c: U32 if c <= 0x1D546 => ScriptCommon
      | let c: U32 if c <= 0x1D549 => ScriptUnknown
      | let c: U32 if c <= 0x1D550 => ScriptCommon
      | let c: U32 if c <= 0x1D551 => ScriptUnknown
      | let c: U32 if c <= 0x1D6A5 => ScriptCommon
      | let c: U32 if c <= 0x1D6A7 => ScriptUnknown
      | let c: U32 if c <= 0x1D7CB => ScriptCommon
      | let c: U32 if c <= 0x1D7CD => ScriptUnknown
      | let c: U32 if c <= 0x1D7FF => ScriptCommon
      | let c: U32 if c <= 0x1DA8B => ScriptSignWriting
      | let c: U32 if c <= 0x1DA9A => ScriptUnknown
      | let c: U32 if c <= 0x1DA9F => ScriptSignWriting
      | let c: U32 if c <= 0x1DAA0 => ScriptUnknown
      | let c: U32 if c <= 0x1DAAF => ScriptSignWriting
      | let c: U32 if c <= 0x1DEFF => ScriptUnknown
      | let c: U32 if c <= 0x1DF1E => ScriptLatin
      | let c: U32 if c <= 0x1DF24 => ScriptUnknown
      | let c: U32 if c <= 0x1DF2A => ScriptLatin
      else ScriptUnknown
      end
    | 0x001E =>
      match cp
      | let c: U32 if c <= 0x1E006 => ScriptGlagolitic
      | let c: U32 if c <= 0x1E007 => ScriptUnknown
      | let c: U32 if c <= 0x1E018 => ScriptGlagolitic
      | let c: U32 if c <= 0x1E01A => ScriptUnknown
      | let c: U32 if c <= 0x1E021 => ScriptGlagolitic
      | let c: U32 if c <= 0x1E022 => ScriptUnknown
      | let c: U32 if c <= 0x1E024 => ScriptGlagolitic
      | let c: U32 if c <= 0x1E025 => ScriptUnknown
      | let c: U32 if c <= 0x1E02A => ScriptGlagolitic
      | let c: U32 if c <= 0x1E02F => ScriptUnknown
      | let c: U32 if c <= 0x1E06D => ScriptCyrillic
      | let c: U32 if c <= 0x1E08E => ScriptUnknown
      | let c: U32 if c <= 0x1E08F => ScriptCyrillic
      | let c: U32 if c <= 0x1E0FF => ScriptUnknown
      | let c: U32 if c <= 0x1E12C => ScriptNyiakengPuachueHmong
      | let c: U32 if c <= 0x1E12F => ScriptUnknown
      | let c: U32 if c <= 0x1E13D => ScriptNyiakengPuachueHmong
      | let c: U32 if c <= 0x1E13F => ScriptUnknown
      | let c: U32 if c <= 0x1E149 => ScriptNyiakengPuachueHmong
      | let c: U32 if c <= 0x1E14D => ScriptUnknown
      | let c: U32 if c <= 0x1E14F => ScriptNyiakengPuachueHmong
      | let c: U32 if c <= 0x1E28F => ScriptUnknown
      | let c: U32 if c <= 0x1E2AE => ScriptToto
      | let c: U32 if c <= 0x1E2BF => ScriptUnknown
      | let c: U32 if c <= 0x1E2F9 => ScriptWancho
      | let c: U32 if c <= 0x1E2FE => ScriptUnknown
      | let c: U32 if c <= 0x1E2FF => ScriptWancho
      | let c: U32 if c <= 0x1E4CF => ScriptUnknown
      | let c: U32 if c <= 0x1E4F9 => ScriptNagMundari
      | let c: U32 if c <= 0x1E5CF => ScriptUnknown
      | let c: U32 if c <= 0x1E5FA => ScriptOlOnal
      | let c: U32 if c <= 0x1E5FE => ScriptUnknown
      | let c: U32 if c <= 0x1E5FF => ScriptOlOnal
      | let c: U32 if c <= 0x1E7DF => ScriptUnknown
      | let c: U32 if c <= 0x1E7E6 => ScriptEthiopic
      | let c: U32 if c <= 0x1E7E7 => ScriptUnknown
      | let c: U32 if c <= 0x1E7EB => ScriptEthiopic
      | let c: U32 if c <= 0x1E7EC => ScriptUnknown
      | let c: U32 if c <= 0x1E7EE => ScriptEthiopic
      | let c: U32 if c <= 0x1E7EF => ScriptUnknown
      | let c: U32 if c <= 0x1E7FE => ScriptEthiopic
      | let c: U32 if c <= 0x1E7FF => ScriptUnknown
      | let c: U32 if c <= 0x1E8C4 => ScriptMendeKikakui
      | let c: U32 if c <= 0x1E8C6 => ScriptUnknown
      | let c: U32 if c <= 0x1E8D6 => ScriptMendeKikakui
      | let c: U32 if c <= 0x1E8FF => ScriptUnknown
      | let c: U32 if c <= 0x1E94B => ScriptAdlam
      | let c: U32 if c <= 0x1E94F => ScriptUnknown
      | let c: U32 if c <= 0x1E959 => ScriptAdlam
      | let c: U32 if c <= 0x1E95D => ScriptUnknown
      | let c: U32 if c <= 0x1E95F => ScriptAdlam
      | let c: U32 if c <= 0x1EC70 => ScriptUnknown
      | let c: U32 if c <= 0x1ECB4 => ScriptCommon
      | let c: U32 if c <= 0x1ED00 => ScriptUnknown
      | let c: U32 if c <= 0x1ED3D => ScriptCommon
      | let c: U32 if c <= 0x1EDFF => ScriptUnknown
      | let c: U32 if c <= 0x1EE03 => ScriptArabic
      | let c: U32 if c <= 0x1EE04 => ScriptUnknown
      | let c: U32 if c <= 0x1EE1F => ScriptArabic
      | let c: U32 if c <= 0x1EE20 => ScriptUnknown
      | let c: U32 if c <= 0x1EE22 => ScriptArabic
      | let c: U32 if c <= 0x1EE23 => ScriptUnknown
      | let c: U32 if c <= 0x1EE24 => ScriptArabic
      | let c: U32 if c <= 0x1EE26 => ScriptUnknown
      | let c: U32 if c <= 0x1EE27 => ScriptArabic
      | let c: U32 if c <= 0x1EE28 => ScriptUnknown
      | let c: U32 if c <= 0x1EE32 => ScriptArabic
      | let c: U32 if c <= 0x1EE33 => ScriptUnknown
      | let c: U32 if c <= 0x1EE37 => ScriptArabic
      | let c: U32 if c <= 0x1EE38 => ScriptUnknown
      | let c: U32 if c <= 0x1EE39 => ScriptArabic
      | let c: U32 if c <= 0x1EE3A => ScriptUnknown
      | let c: U32 if c <= 0x1EE3B => ScriptArabic
      | let c: U32 if c <= 0x1EE41 => ScriptUnknown
      | let c: U32 if c <= 0x1EE42 => ScriptArabic
      | let c: U32 if c <= 0x1EE46 => ScriptUnknown
      | let c: U32 if c <= 0x1EE47 => ScriptArabic
      | let c: U32 if c <= 0x1EE48 => ScriptUnknown
      | let c: U32 if c <= 0x1EE49 => ScriptArabic
      | let c: U32 if c <= 0x1EE4A => ScriptUnknown
      | let c: U32 if c <= 0x1EE4B => ScriptArabic
      | let c: U32 if c <= 0x1EE4C => ScriptUnknown
      | let c: U32 if c <= 0x1EE4F => ScriptArabic
      | let c: U32 if c <= 0x1EE50 => ScriptUnknown
      | let c: U32 if c <= 0x1EE52 => ScriptArabic
      | let c: U32 if c <= 0x1EE53 => ScriptUnknown
      | let c: U32 if c <= 0x1EE54 => ScriptArabic
      | let c: U32 if c <= 0x1EE56 => ScriptUnknown
      | let c: U32 if c <= 0x1EE57 => ScriptArabic
      | let c: U32 if c <= 0x1EE58 => ScriptUnknown
      | let c: U32 if c <= 0x1EE59 => ScriptArabic
      | let c: U32 if c <= 0x1EE5A => ScriptUnknown
      | let c: U32 if c <= 0x1EE5B => ScriptArabic
      | let c: U32 if c <= 0x1EE5C => ScriptUnknown
      | let c: U32 if c <= 0x1EE5D => ScriptArabic
      | let c: U32 if c <= 0x1EE5E => ScriptUnknown
      | let c: U32 if c <= 0x1EE5F => ScriptArabic
      | let c: U32 if c <= 0x1EE60 => ScriptUnknown
      | let c: U32 if c <= 0x1EE62 => ScriptArabic
      | let c: U32 if c <= 0x1EE63 => ScriptUnknown
      | let c: U32 if c <= 0x1EE64 => ScriptArabic
      | let c: U32 if c <= 0x1EE66 => ScriptUnknown
      | let c: U32 if c <= 0x1EE6A => ScriptArabic
      | let c: U32 if c <= 0x1EE6B => ScriptUnknown
      | let c: U32 if c <= 0x1EE72 => ScriptArabic
      | let c: U32 if c <= 0x1EE73 => ScriptUnknown
      | let c: U32 if c <= 0x1EE77 => ScriptArabic
      | let c: U32 if c <= 0x1EE78 => ScriptUnknown
      | let c: U32 if c <= 0x1EE7C => ScriptArabic
      | let c: U32 if c <= 0x1EE7D => ScriptUnknown
      | let c: U32 if c <= 0x1EE7E => ScriptArabic
      | let c: U32 if c <= 0x1EE7F => ScriptUnknown
      | let c: U32 if c <= 0x1EE89 => ScriptArabic
      | let c: U32 if c <= 0x1EE8A => ScriptUnknown
      | let c: U32 if c <= 0x1EE9B => ScriptArabic
      | let c: U32 if c <= 0x1EEA0 => ScriptUnknown
      | let c: U32 if c <= 0x1EEA3 => ScriptArabic
      | let c: U32 if c <= 0x1EEA4 => ScriptUnknown
      | let c: U32 if c <= 0x1EEA9 => ScriptArabic
      | let c: U32 if c <= 0x1EEAA => ScriptUnknown
      | let c: U32 if c <= 0x1EEBB => ScriptArabic
      | let c: U32 if c <= 0x1EEEF => ScriptUnknown
      | let c: U32 if c <= 0x1EEF1 => ScriptArabic
      else ScriptUnknown
      end
    | 0x001F =>
      match cp
      | let c: U32 if c <= 0x1F02B => ScriptCommon
      | let c: U32 if c <= 0x1F02F => ScriptUnknown
      | let c: U32 if c <= 0x1F093 => ScriptCommon
      | let c: U32 if c <= 0x1F09F => ScriptUnknown
      | let c: U32 if c <= 0x1F0AE => ScriptCommon
      | let c: U32 if c <= 0x1F0B0 => ScriptUnknown
      | let c: U32 if c <= 0x1F0BF => ScriptCommon
      | let c: U32 if c <= 0x1F0C0 => ScriptUnknown
      | let c: U32 if c <= 0x1F0CF => ScriptCommon
      | let c: U32 if c <= 0x1F0D0 => ScriptUnknown
      | let c: U32 if c <= 0x1F0F5 => ScriptCommon
      | let c: U32 if c <= 0x1F0FF => ScriptUnknown
      | let c: U32 if c <= 0x1F1AD => ScriptCommon
      | let c: U32 if c <= 0x1F1E5 => ScriptUnknown
      | let c: U32 if c <= 0x1F1FF => ScriptCommon
      | let c: U32 if c <= 0x1F200 => ScriptHiragana
      | let c: U32 if c <= 0x1F202 => ScriptCommon
      | let c: U32 if c <= 0x1F20F => ScriptUnknown
      | let c: U32 if c <= 0x1F23B => ScriptCommon
      | let c: U32 if c <= 0x1F23F => ScriptUnknown
      | let c: U32 if c <= 0x1F248 => ScriptCommon
      | let c: U32 if c <= 0x1F24F => ScriptUnknown
      | let c: U32 if c <= 0x1F251 => ScriptCommon
      | let c: U32 if c <= 0x1F25F => ScriptUnknown
      | let c: U32 if c <= 0x1F265 => ScriptCommon
      | let c: U32 if c <= 0x1F2FF => ScriptUnknown
      | let c: U32 if c <= 0x1F6D7 => ScriptCommon
      | let c: U32 if c <= 0x1F6DB => ScriptUnknown
      | let c: U32 if c <= 0x1F6EC => ScriptCommon
      | let c: U32 if c <= 0x1F6EF => ScriptUnknown
      | let c: U32 if c <= 0x1F6FC => ScriptCommon
      | let c: U32 if c <= 0x1F6FF => ScriptUnknown
      | let c: U32 if c <= 0x1F776 => ScriptCommon
      | let c: U32 if c <= 0x1F77A => ScriptUnknown
      | let c: U32 if c <= 0x1F7D9 => ScriptCommon
      | let c: U32 if c <= 0x1F7DF => ScriptUnknown
      | let c: U32 if c <= 0x1F7EB => ScriptCommon
      | let c: U32 if c <= 0x1F7EF => ScriptUnknown
      | let c: U32 if c <= 0x1F7F0 => ScriptCommon
      | let c: U32 if c <= 0x1F7FF => ScriptUnknown
      | let c: U32 if c <= 0x1F80B => ScriptCommon
      | let c: U32 if c <= 0x1F80F => ScriptUnknown
      | let c: U32 if c <= 0x1F847 => ScriptCommon
      | let c: U32 if c <= 0x1F84F => ScriptUnknown
      | let c: U32 if c <= 0x1F859 => ScriptCommon
      | let c: U32 if c <= 0x1F85F => ScriptUnknown
      | let c: U32 if c <= 0x1F887 => ScriptCommon
      | let c: U32 if c <= 0x1F88F => ScriptUnknown
      | let c: U32 if c <= 0x1F8AD => ScriptCommon
      | let c: U32 if c <= 0x1F8AF => ScriptUnknown
      | let c: U32 if c <= 0x1F8BB => ScriptCommon
      | let c: U32 if c <= 0x1F8BF => ScriptUnknown
      | let c: U32 if c <= 0x1F8C1 => ScriptCommon
      | let c: U32 if c <= 0x1F8FF => ScriptUnknown
      | let c: U32 if c <= 0x1FA53 => ScriptCommon
      | let c: U32 if c <= 0x1FA5F => ScriptUnknown
      | let c: U32 if c <= 0x1FA6D => ScriptCommon
      | let c: U32 if c <= 0x1FA6F => ScriptUnknown
      | let c: U32 if c <= 0x1FA7C => ScriptCommon
      | let c: U32 if c <= 0x1FA7F => ScriptUnknown
      | let c: U32 if c <= 0x1FA89 => ScriptCommon
      | let c: U32 if c <= 0x1FA8E => ScriptUnknown
      | let c: U32 if c <= 0x1FAC6 => ScriptCommon
      | let c: U32 if c <= 0x1FACD => ScriptUnknown
      | let c: U32 if c <= 0x1FADC => ScriptCommon
      | let c: U32 if c <= 0x1FADE => ScriptUnknown
      | let c: U32 if c <= 0x1FAE9 => ScriptCommon
      | let c: U32 if c <= 0x1FAEF => ScriptUnknown
      | let c: U32 if c <= 0x1FAF8 => ScriptCommon
      | let c: U32 if c <= 0x1FAFF => ScriptUnknown
      | let c: U32 if c <= 0x1FB92 => ScriptCommon
      | let c: U32 if c <= 0x1FB93 => ScriptUnknown
      | let c: U32 if c <= 0x1FBF9 => ScriptCommon
      else ScriptUnknown
      end
    | 0x0020 =>
      match cp
      | let c: U32 if c <= 0x20FFF => ScriptHan
      else ScriptUnknown
      end
    | 0x0021 =>
      match cp
      | let c: U32 if c <= 0x21FFF => ScriptHan
      else ScriptUnknown
      end
    | 0x0022 =>
      match cp
      | let c: U32 if c <= 0x22FFF => ScriptHan
      else ScriptUnknown
      end
    | 0x0023 =>
      match cp
      | let c: U32 if c <= 0x23FFF => ScriptHan
      else ScriptUnknown
      end
    | 0x0024 =>
      match cp
      | let c: U32 if c <= 0x24FFF => ScriptHan
      else ScriptUnknown
      end
    | 0x0025 =>
      match cp
      | let c: U32 if c <= 0x25FFF => ScriptHan
      else ScriptUnknown
      end
    | 0x0026 =>
      match cp
      | let c: U32 if c <= 0x26FFF => ScriptHan
      else ScriptUnknown
      end
    | 0x0027 =>
      match cp
      | let c: U32 if c <= 0x27FFF => ScriptHan
      else ScriptUnknown
      end
    | 0x0028 =>
      match cp
      | let c: U32 if c <= 0x28FFF => ScriptHan
      else ScriptUnknown
      end
    | 0x0029 =>
      match cp
      | let c: U32 if c <= 0x29FFF => ScriptHan
      else ScriptUnknown
      end
    | 0x002A =>
      match cp
      | let c: U32 if c <= 0x2A6DF => ScriptHan
      | let c: U32 if c <= 0x2A6FF => ScriptUnknown
      | let c: U32 if c <= 0x2AFFF => ScriptHan
      else ScriptUnknown
      end
    | 0x002B =>
      match cp
      | let c: U32 if c <= 0x2B739 => ScriptHan
      | let c: U32 if c <= 0x2B73F => ScriptUnknown
      | let c: U32 if c <= 0x2B81D => ScriptHan
      | let c: U32 if c <= 0x2B81F => ScriptUnknown
      | let c: U32 if c <= 0x2BFFF => ScriptHan
      else ScriptUnknown
      end
    | 0x002C =>
      match cp
      | let c: U32 if c <= 0x2CEA1 => ScriptHan
      | let c: U32 if c <= 0x2CEAF => ScriptUnknown
      | let c: U32 if c <= 0x2CFFF => ScriptHan
      else ScriptUnknown
      end
    | 0x002D =>
      match cp
      | let c: U32 if c <= 0x2DFFF => ScriptHan
      else ScriptUnknown
      end
    | 0x002E =>
      match cp
      | let c: U32 if c <= 0x2EBE0 => ScriptHan
      | let c: U32 if c <= 0x2EBEF => ScriptUnknown
      | let c: U32 if c <= 0x2EE5D => ScriptHan
      else ScriptUnknown
      end
    | 0x002F =>
      match cp
      | let c: U32 if c <= 0x2F7FF => ScriptUnknown
      | let c: U32 if c <= 0x2FA1D => ScriptHan
      else ScriptUnknown
      end
    | 0x0030 =>
      match cp
      | let c: U32 if c <= 0x30FFF => ScriptHan
      else ScriptUnknown
      end
    | 0x0031 =>
      match cp
      | let c: U32 if c <= 0x3134A => ScriptHan
      | let c: U32 if c <= 0x3134F => ScriptUnknown
      | let c: U32 if c <= 0x31FFF => ScriptHan
      else ScriptUnknown
      end
    | 0x0032 =>
      match cp
      | let c: U32 if c <= 0x323AF => ScriptHan
      else ScriptUnknown
      end
    | 0x00E0 =>
      match cp
      | let c: U32 if c <= 0xE0000 => ScriptUnknown
      | let c: U32 if c <= 0xE0001 => ScriptCommon
      | let c: U32 if c <= 0xE001F => ScriptUnknown
      | let c: U32 if c <= 0xE007F => ScriptCommon
      | let c: U32 if c <= 0xE00FF => ScriptUnknown
      | let c: U32 if c <= 0xE01EF => ScriptInherited
      else ScriptUnknown
      end
    else
      ScriptUnknown
    end
