// Auto-generated by unicode-build. Do not edit by hand.
// Regenerate via:
//   make ucd-generate
//
// Source: UnicodeData.txt General_Category field.
// Codepoints outside any range default to Cn.
use @ucd_cat_lookup[U8](cp: U32)

primitive _UcdCategory
  fun of(cp: U32): Category =>
    Categories._from_byte(@ucd_cat_lookup(cp))
