// Auto-generated by unicode-build. Do not edit by hand.
// Regenerate via:
//   make ucd-generate
//
// Source: ScriptExtensions.txt + PropertyValueAliases.txt.
// Two-level `match cp >> 12` / `match cp` dispatch (see
// `_RangeMatchEmitter` in unicode_build/ for the broader
// pattern). Each non-empty range arm returns a fresh
// `Array[Script] val` literal; codepoints not listed here
// return `None` and the API layer falls back to
// `[script(cp)]`.

primitive _UcdScriptExtensions
  fun of(cp: U32): (Array[Script] val | None) =>
    match cp >> 12
    | 0x0000 =>
      match cp
      | let c: U32 if c <= 0x00B6 => None
      | let c: U32 if c <= 0x00B7 => recover val [as Script: ScriptAvestan; ScriptCarian; ScriptCoptic; ScriptDuployan; ScriptElbasan; ScriptGeorgian; ScriptGlagolitic; ScriptGunjalaGondi; ScriptGothic; ScriptGreek; ScriptHan; ScriptLatin; ScriptLydian; ScriptMahajani; ScriptOldPermic; ScriptShavian] end
      | let c: U32 if c <= 0x02BB => None
      | let c: U32 if c <= 0x02BC => recover val [as Script: ScriptBengali; ScriptCyrillic; ScriptDevanagari; ScriptLatin; ScriptLisu; ScriptThai; ScriptToto] end
      | let c: U32 if c <= 0x02C6 => None
      | let c: U32 if c <= 0x02C7 => recover val [as Script: ScriptBopomofo; ScriptLatin] end
      | let c: U32 if c <= 0x02C8 => None
      | let c: U32 if c <= 0x02CB => recover val [as Script: ScriptBopomofo; ScriptLatin] end
      | let c: U32 if c <= 0x02CC => None
      | let c: U32 if c <= 0x02CD => recover val [as Script: ScriptLatin; ScriptLisu] end
      | let c: U32 if c <= 0x02D6 => None
      | let c: U32 if c <= 0x02D7 => recover val [as Script: ScriptLatin; ScriptThai] end
      | let c: U32 if c <= 0x02D8 => None
      | let c: U32 if c <= 0x02D9 => recover val [as Script: ScriptBopomofo; ScriptLatin] end
      | let c: U32 if c <= 0x02FF => None
      | let c: U32 if c <= 0x0300 => recover val [as Script: ScriptCherokee; ScriptCoptic; ScriptCyrillic; ScriptGreek; ScriptLatin; ScriptOldPermic; ScriptSunuwar; ScriptTaiLe] end
      | let c: U32 if c <= 0x0301 => recover val [as Script: ScriptCherokee; ScriptCyrillic; ScriptGreek; ScriptLatin; ScriptOsage; ScriptSunuwar; ScriptTaiLe; ScriptTodhri] end
      | let c: U32 if c <= 0x0302 => recover val [as Script: ScriptCherokee; ScriptCyrillic; ScriptLatin; ScriptTifinagh] end
      | let c: U32 if c <= 0x0303 => recover val [as Script: ScriptGlagolitic; ScriptLatin; ScriptSunuwar; ScriptSyriac; ScriptThai] end
      | let c: U32 if c <= 0x0304 => recover val [as Script: ScriptCaucasianAlbanian; ScriptCherokee; ScriptCoptic; ScriptCyrillic; ScriptGothic; ScriptGreek; ScriptLatin; ScriptOsage; ScriptSyriac; ScriptTifinagh; ScriptTodhri] end
      | let c: U32 if c <= 0x0305 => recover val [as Script: ScriptCoptic; ScriptElbasan; ScriptGlagolitic; ScriptGothic; ScriptKatakana; ScriptLatin] end
      | let c: U32 if c <= 0x0306 => recover val [as Script: ScriptCyrillic; ScriptGreek; ScriptLatin; ScriptOldPermic] end
      | let c: U32 if c <= 0x0307 => recover val [as Script: ScriptCoptic; ScriptDuployan; ScriptHebrew; ScriptLatin; ScriptOldPermic; ScriptSyriac; ScriptTaiLe; ScriptTifinagh; ScriptTodhri] end
      | let c: U32 if c <= 0x0308 => recover val [as Script: ScriptArmenian; ScriptCyrillic; ScriptDuployan; ScriptGothic; ScriptGreek; ScriptHebrew; ScriptLatin; ScriptOldPermic; ScriptSyriac; ScriptTaiLe] end
      | let c: U32 if c <= 0x0309 => recover val [as Script: ScriptLatin; ScriptTifinagh] end
      | let c: U32 if c <= 0x030A => recover val [as Script: ScriptDuployan; ScriptLatin; ScriptSyriac] end
      | let c: U32 if c <= 0x030B => recover val [as Script: ScriptCherokee; ScriptCyrillic; ScriptLatin; ScriptOsage] end
      | let c: U32 if c <= 0x030C => recover val [as Script: ScriptCherokee; ScriptLatin; ScriptTaiLe] end
      | let c: U32 if c <= 0x030D => recover val [as Script: ScriptLatin; ScriptSunuwar] end
      | let c: U32 if c <= 0x030E => recover val [as Script: ScriptEthiopic; ScriptLatin] end
      | let c: U32 if c <= 0x030F => None
      | let c: U32 if c <= 0x0310 => recover val [as Script: ScriptLatin; ScriptSunuwar] end
      | let c: U32 if c <= 0x0311 => recover val [as Script: ScriptCyrillic; ScriptLatin; ScriptTodhri] end
      | let c: U32 if c <= 0x0312 => None
      | let c: U32 if c <= 0x0313 => recover val [as Script: ScriptGreek; ScriptLatin; ScriptOldPermic; ScriptTodhri] end
      | let c: U32 if c <= 0x031F => None
      | let c: U32 if c <= 0x0320 => recover val [as Script: ScriptLatin; ScriptSyriac] end
      | let c: U32 if c <= 0x0322 => None
      | let c: U32 if c <= 0x0323 => recover val [as Script: ScriptCherokee; ScriptDuployan; ScriptKatakana; ScriptLatin; ScriptSyriac] end
      | let c: U32 if c <= 0x0324 => recover val [as Script: ScriptCherokee; ScriptDuployan; ScriptLatin; ScriptSyriac] end
      | let c: U32 if c <= 0x0325 => recover val [as Script: ScriptLatin; ScriptSyriac] end
      | let c: U32 if c <= 0x032C => None
      | let c: U32 if c <= 0x032D => recover val [as Script: ScriptLatin; ScriptSunuwar; ScriptSyriac] end
      | let c: U32 if c <= 0x032E => recover val [as Script: ScriptLatin; ScriptSyriac] end
      | let c: U32 if c <= 0x032F => None
      | let c: U32 if c <= 0x0330 => recover val [as Script: ScriptCherokee; ScriptLatin; ScriptSyriac] end
      | let c: U32 if c <= 0x0331 => recover val [as Script: ScriptCaucasianAlbanian; ScriptCherokee; ScriptGothic; ScriptLatin; ScriptSunuwar; ScriptThai] end
      | let c: U32 if c <= 0x0341 => None
      | let c: U32 if c <= 0x0342 => recover val [as Script: ScriptGreek] end
      | let c: U32 if c <= 0x0344 => None
      | let c: U32 if c <= 0x0345 => recover val [as Script: ScriptGreek] end
      | let c: U32 if c <= 0x0357 => None
      | let c: U32 if c <= 0x0358 => recover val [as Script: ScriptLatin; ScriptOsage] end
      | let c: U32 if c <= 0x035D => None
      | let c: U32 if c <= 0x035E => recover val [as Script: ScriptCaucasianAlbanian; ScriptLatin; ScriptTodhri] end
      | let c: U32 if c <= 0x0362 => None
      | let c: U32 if c <= 0x036F => recover val [as Script: ScriptLatin] end
      | let c: U32 if c <= 0x0373 => None
      | let c: U32 if c <= 0x0374 => recover val [as Script: ScriptCoptic; ScriptGreek] end
      | let c: U32 if c <= 0x0375 => recover val [as Script: ScriptCoptic; ScriptGreek] end
      | let c: U32 if c <= 0x0482 => None
      | let c: U32 if c <= 0x0483 => recover val [as Script: ScriptCyrillic; ScriptOldPermic] end
      | let c: U32 if c <= 0x0484 => recover val [as Script: ScriptCyrillic; ScriptGlagolitic] end
      | let c: U32 if c <= 0x0486 => recover val [as Script: ScriptCyrillic; ScriptLatin] end
      | let c: U32 if c <= 0x0487 => recover val [as Script: ScriptCyrillic; ScriptGlagolitic] end
      | let c: U32 if c <= 0x0588 => None
      | let c: U32 if c <= 0x0589 => recover val [as Script: ScriptArmenian; ScriptGeorgian; ScriptGlagolitic] end
      | let c: U32 if c <= 0x060B => None
      | let c: U32 if c <= 0x060C => recover val [as Script: ScriptArabic; ScriptGaray; ScriptNko; ScriptHanifiRohingya; ScriptSyriac; ScriptThaana; ScriptYezidi] end
      | let c: U32 if c <= 0x061A => None
      | let c: U32 if c <= 0x061B => recover val [as Script: ScriptArabic; ScriptGaray; ScriptNko; ScriptHanifiRohingya; ScriptSyriac; ScriptThaana; ScriptYezidi] end
      | let c: U32 if c <= 0x061C => recover val [as Script: ScriptArabic; ScriptSyriac; ScriptThaana] end
      | let c: U32 if c <= 0x061E => None
      | let c: U32 if c <= 0x061F => recover val [as Script: ScriptAdlam; ScriptArabic; ScriptGaray; ScriptNko; ScriptHanifiRohingya; ScriptSyriac; ScriptThaana; ScriptYezidi] end
      | let c: U32 if c <= 0x063F => None
      | let c: U32 if c <= 0x0640 => recover val [as Script: ScriptAdlam; ScriptArabic; ScriptMandaic; ScriptManichaean; ScriptOldUyghur; ScriptPsalterPahlavi; ScriptHanifiRohingya; ScriptSogdian; ScriptSyriac] end
      | let c: U32 if c <= 0x064A => None
      | let c: U32 if c <= 0x0655 => recover val [as Script: ScriptArabic; ScriptSyriac] end
      | let c: U32 if c <= 0x065F => None
      | let c: U32 if c <= 0x0669 => recover val [as Script: ScriptArabic; ScriptThaana; ScriptYezidi] end
      | let c: U32 if c <= 0x066F => None
      | let c: U32 if c <= 0x0670 => recover val [as Script: ScriptArabic; ScriptSyriac] end
      | let c: U32 if c <= 0x06D3 => None
      | let c: U32 if c <= 0x06D4 => recover val [as Script: ScriptArabic; ScriptHanifiRohingya] end
      | let c: U32 if c <= 0x0950 => None
      | let c: U32 if c <= 0x0951 => recover val [as Script: ScriptBengali; ScriptDevanagari; ScriptGrantha; ScriptGujarati; ScriptGurmukhi; ScriptKannada; ScriptLatin; ScriptMalayalam; ScriptOriya; ScriptSharada; ScriptTamil; ScriptTelugu; ScriptTirhuta] end
      | let c: U32 if c <= 0x0952 => recover val [as Script: ScriptBengali; ScriptDevanagari; ScriptGrantha; ScriptGujarati; ScriptGurmukhi; ScriptKannada; ScriptLatin; ScriptMalayalam; ScriptOriya; ScriptTamil; ScriptTelugu; ScriptTirhuta] end
      | let c: U32 if c <= 0x0963 => None
      | let c: U32 if c <= 0x0964 => recover val [as Script: ScriptBengali; ScriptDevanagari; ScriptDogra; ScriptGunjalaGondi; ScriptMasaramGondi; ScriptGrantha; ScriptGujarati; ScriptGurmukhi; ScriptKannada; ScriptMahajani; ScriptMalayalam; ScriptNandinagari; ScriptOlOnal; ScriptOriya; ScriptKhudawadi; ScriptSinhala; ScriptSylotiNagri; ScriptTakri; ScriptTamil; ScriptTelugu; ScriptTirhuta] end
      | let c: U32 if c <= 0x0965 => recover val [as Script: ScriptBengali; ScriptDevanagari; ScriptDogra; ScriptGunjalaGondi; ScriptMasaramGondi; ScriptGrantha; ScriptGujarati; ScriptGurungKhema; ScriptGurmukhi; ScriptKannada; ScriptLimbu; ScriptMahajani; ScriptMalayalam; ScriptNandinagari; ScriptOlOnal; ScriptOriya; ScriptKhudawadi; ScriptSinhala; ScriptSylotiNagri; ScriptTakri; ScriptTamil; ScriptTelugu; ScriptTirhuta] end
      | let c: U32 if c <= 0x096F => recover val [as Script: ScriptDevanagari; ScriptDogra; ScriptKaithi; ScriptMahajani] end
      | let c: U32 if c <= 0x09E5 => None
      | let c: U32 if c <= 0x09EF => recover val [as Script: ScriptBengali; ScriptChakma; ScriptSylotiNagri] end
      | let c: U32 if c <= 0x0A65 => None
      | let c: U32 if c <= 0x0A6F => recover val [as Script: ScriptGurmukhi; ScriptMultani] end
      | let c: U32 if c <= 0x0AE5 => None
      | let c: U32 if c <= 0x0AEF => recover val [as Script: ScriptGujarati; ScriptKhojki] end
      | let c: U32 if c <= 0x0BE5 => None
      | let c: U32 if c <= 0x0BEF => recover val [as Script: ScriptGrantha; ScriptTamil] end
      | let c: U32 if c <= 0x0BF2 => recover val [as Script: ScriptGrantha; ScriptTamil] end
      | let c: U32 if c <= 0x0BF3 => recover val [as Script: ScriptGrantha; ScriptTamil] end
      | let c: U32 if c <= 0x0CE5 => None
      | let c: U32 if c <= 0x0CEF => recover val [as Script: ScriptKannada; ScriptNandinagari; ScriptTuluTigalari] end
      else None
      end
    | 0x0001 =>
      match cp
      | let c: U32 if c <= 0x103F => None
      | let c: U32 if c <= 0x1049 => recover val [as Script: ScriptChakma; ScriptMyanmar; ScriptTaiLe] end
      | let c: U32 if c <= 0x10FA => None
      | let c: U32 if c <= 0x10FB => recover val [as Script: ScriptGeorgian; ScriptGlagolitic; ScriptLatin] end
      | let c: U32 if c <= 0x16EA => None
      | let c: U32 if c <= 0x16ED => recover val [as Script: ScriptRunic] end
      | let c: U32 if c <= 0x1734 => None
      | let c: U32 if c <= 0x1736 => recover val [as Script: ScriptBuhid; ScriptHanunoo; ScriptTagbanwa; ScriptTagalog] end
      | let c: U32 if c <= 0x1801 => None
      | let c: U32 if c <= 0x1803 => recover val [as Script: ScriptMongolian; ScriptPhagsPa] end
      | let c: U32 if c <= 0x1804 => None
      | let c: U32 if c <= 0x1805 => recover val [as Script: ScriptMongolian; ScriptPhagsPa] end
      | let c: U32 if c <= 0x1CCF => None
      | let c: U32 if c <= 0x1CD0 => recover val [as Script: ScriptBengali; ScriptDevanagari; ScriptGrantha; ScriptKannada] end
      | let c: U32 if c <= 0x1CD1 => recover val [as Script: ScriptDevanagari] end
      | let c: U32 if c <= 0x1CD2 => recover val [as Script: ScriptBengali; ScriptDevanagari; ScriptGrantha; ScriptKannada] end
      | let c: U32 if c <= 0x1CD3 => recover val [as Script: ScriptDevanagari; ScriptGrantha; ScriptKannada] end
      | let c: U32 if c <= 0x1CD4 => recover val [as Script: ScriptDevanagari] end
      | let c: U32 if c <= 0x1CD6 => recover val [as Script: ScriptBengali; ScriptDevanagari] end
      | let c: U32 if c <= 0x1CD7 => recover val [as Script: ScriptDevanagari; ScriptSharada] end
      | let c: U32 if c <= 0x1CD8 => recover val [as Script: ScriptBengali; ScriptDevanagari] end
      | let c: U32 if c <= 0x1CD9 => recover val [as Script: ScriptDevanagari; ScriptSharada] end
      | let c: U32 if c <= 0x1CDA => recover val [as Script: ScriptDevanagari; ScriptKannada; ScriptMalayalam; ScriptOriya; ScriptTamil; ScriptTelugu] end
      | let c: U32 if c <= 0x1CDB => recover val [as Script: ScriptDevanagari] end
      | let c: U32 if c <= 0x1CDD => recover val [as Script: ScriptDevanagari; ScriptSharada] end
      | let c: U32 if c <= 0x1CDF => recover val [as Script: ScriptDevanagari] end
      | let c: U32 if c <= 0x1CE0 => recover val [as Script: ScriptDevanagari; ScriptSharada] end
      | let c: U32 if c <= 0x1CE1 => recover val [as Script: ScriptBengali; ScriptDevanagari] end
      | let c: U32 if c <= 0x1CE8 => recover val [as Script: ScriptDevanagari] end
      | let c: U32 if c <= 0x1CE9 => recover val [as Script: ScriptDevanagari; ScriptNandinagari] end
      | let c: U32 if c <= 0x1CEA => recover val [as Script: ScriptBengali; ScriptDevanagari] end
      | let c: U32 if c <= 0x1CEC => recover val [as Script: ScriptDevanagari] end
      | let c: U32 if c <= 0x1CED => recover val [as Script: ScriptBengali; ScriptDevanagari] end
      | let c: U32 if c <= 0x1CF1 => recover val [as Script: ScriptDevanagari] end
      | let c: U32 if c <= 0x1CF2 => recover val [as Script: ScriptBengali; ScriptDevanagari; ScriptGrantha; ScriptKannada; ScriptMalayalam; ScriptNandinagari; ScriptOriya; ScriptSinhala; ScriptTelugu; ScriptTirhuta; ScriptTuluTigalari] end
      | let c: U32 if c <= 0x1CF3 => recover val [as Script: ScriptDevanagari; ScriptGrantha] end
      | let c: U32 if c <= 0x1CF4 => recover val [as Script: ScriptDevanagari; ScriptGrantha; ScriptKannada; ScriptTuluTigalari] end
      | let c: U32 if c <= 0x1CF6 => recover val [as Script: ScriptBengali; ScriptDevanagari] end
      | let c: U32 if c <= 0x1CF7 => recover val [as Script: ScriptBengali] end
      | let c: U32 if c <= 0x1CF9 => recover val [as Script: ScriptDevanagari; ScriptGrantha] end
      | let c: U32 if c <= 0x1CFA => recover val [as Script: ScriptNandinagari] end
      | let c: U32 if c <= 0x1DBF => None
      | let c: U32 if c <= 0x1DC1 => recover val [as Script: ScriptGreek] end
      | let c: U32 if c <= 0x1DF7 => None
      | let c: U32 if c <= 0x1DF8 => recover val [as Script: ScriptCyrillic; ScriptLatin; ScriptSyriac] end
      | let c: U32 if c <= 0x1DF9 => None
      | let c: U32 if c <= 0x1DFA => recover val [as Script: ScriptSyriac] end
      else None
      end
    | 0x0002 =>
      match cp
      | let c: U32 if c <= 0x202E => None
      | let c: U32 if c <= 0x202F => recover val [as Script: ScriptLatin; ScriptMongolian; ScriptPhagsPa] end
      | let c: U32 if c <= 0x204E => None
      | let c: U32 if c <= 0x204F => recover val [as Script: ScriptAdlam; ScriptArabic] end
      | let c: U32 if c <= 0x2059 => None
      | let c: U32 if c <= 0x205A => recover val [as Script: ScriptCarian; ScriptGeorgian; ScriptGlagolitic; ScriptOldHungarian; ScriptLycian; ScriptOldTurkic] end
      | let c: U32 if c <= 0x205C => None
      | let c: U32 if c <= 0x205D => recover val [as Script: ScriptCarian; ScriptGreek; ScriptOldHungarian; ScriptMeroiticHieroglyphs] end
      | let c: U32 if c <= 0x20EF => None
      | let c: U32 if c <= 0x20F0 => recover val [as Script: ScriptDevanagari; ScriptGrantha; ScriptLatin] end
      | let c: U32 if c <= 0x2E16 => None
      | let c: U32 if c <= 0x2E17 => recover val [as Script: ScriptCoptic; ScriptLatin] end
      | let c: U32 if c <= 0x2E2F => None
      | let c: U32 if c <= 0x2E30 => recover val [as Script: ScriptAvestan; ScriptOldTurkic] end
      | let c: U32 if c <= 0x2E31 => recover val [as Script: ScriptAvestan; ScriptCarian; ScriptGeorgian; ScriptOldHungarian; ScriptKaithi; ScriptLydian; ScriptSamaritan] end
      | let c: U32 if c <= 0x2E3B => None
      | let c: U32 if c <= 0x2E3C => recover val [as Script: ScriptDuployan] end
      | let c: U32 if c <= 0x2E40 => None
      | let c: U32 if c <= 0x2E41 => recover val [as Script: ScriptAdlam; ScriptArabic; ScriptOldHungarian] end
      | let c: U32 if c <= 0x2E42 => None
      | let c: U32 if c <= 0x2E43 => recover val [as Script: ScriptCyrillic; ScriptGlagolitic] end
      | let c: U32 if c <= 0x2FEF => None
      | let c: U32 if c <= 0x2FFF => recover val [as Script: ScriptHan; ScriptTangut] end
      else None
      end
    | 0x0003 =>
      match cp
      | let c: U32 if c <= 0x3000 => None
      | let c: U32 if c <= 0x3001 => recover val [as Script: ScriptBopomofo; ScriptHangul; ScriptHan; ScriptHiragana; ScriptKatakana; ScriptMongolian; ScriptYi] end
      | let c: U32 if c <= 0x3002 => recover val [as Script: ScriptBopomofo; ScriptHangul; ScriptHan; ScriptHiragana; ScriptKatakana; ScriptMongolian; ScriptPhagsPa; ScriptYi] end
      | let c: U32 if c <= 0x3003 => recover val [as Script: ScriptBopomofo; ScriptHangul; ScriptHan; ScriptHiragana; ScriptKatakana] end
      | let c: U32 if c <= 0x3005 => None
      | let c: U32 if c <= 0x3006 => recover val [as Script: ScriptHan] end
      | let c: U32 if c <= 0x3007 => None
      | let c: U32 if c <= 0x3008 => recover val [as Script: ScriptBopomofo; ScriptHangul; ScriptHan; ScriptHiragana; ScriptKatakana; ScriptMongolian; ScriptTibetan; ScriptYi] end
      | let c: U32 if c <= 0x3009 => recover val [as Script: ScriptBopomofo; ScriptHangul; ScriptHan; ScriptHiragana; ScriptKatakana; ScriptMongolian; ScriptTibetan; ScriptYi] end
      | let c: U32 if c <= 0x300A => recover val [as Script: ScriptBopomofo; ScriptHangul; ScriptHan; ScriptHiragana; ScriptKatakana; ScriptLisu; ScriptMongolian; ScriptTibetan; ScriptYi] end
      | let c: U32 if c <= 0x300B => recover val [as Script: ScriptBopomofo; ScriptHangul; ScriptHan; ScriptHiragana; ScriptKatakana; ScriptLisu; ScriptMongolian; ScriptTibetan; ScriptYi] end
      | let c: U32 if c <= 0x300C => recover val [as Script: ScriptBopomofo; ScriptHangul; ScriptHan; ScriptHiragana; ScriptKatakana; ScriptYi] end
      | let c: U32 if c <= 0x300D => recover val [as Script: ScriptBopomofo; ScriptHangul; ScriptHan; ScriptHiragana; ScriptKatakana; ScriptYi] end
      | let c: U32 if c <= 0x300E => recover val [as Script: ScriptBopomofo; ScriptHangul; ScriptHan; ScriptHiragana; ScriptKatakana; ScriptYi] end
      | let c: U32 if c <= 0x300F => recover val [as Script: ScriptBopomofo; ScriptHangul; ScriptHan; ScriptHiragana; ScriptKatakana; ScriptYi] end
      | let c: U32 if c <= 0x3010 => recover val [as Script: ScriptBopomofo; ScriptHangul; ScriptHan; ScriptHiragana; ScriptKatakana; ScriptYi] end
      | let c: U32 if c <= 0x3011 => recover val [as Script: ScriptBopomofo; ScriptHangul; ScriptHan; ScriptHiragana; ScriptKatakana; ScriptYi] end
      | let c: U32 if c <= 0x3012 => None
      | let c: U32 if c <= 0x3013 => recover val [as Script: ScriptBopomofo; ScriptHangul; ScriptHan; ScriptHiragana; ScriptKatakana] end
      | let c: U32 if c <= 0x3014 => recover val [as Script: ScriptBopomofo; ScriptHangul; ScriptHan; ScriptHiragana; ScriptKatakana; ScriptYi] end
      | let c: U32 if c <= 0x3015 => recover val [as Script: ScriptBopomofo; ScriptHangul; ScriptHan; ScriptHiragana; ScriptKatakana; ScriptYi] end
      | let c: U32 if c <= 0x3016 => recover val [as Script: ScriptBopomofo; ScriptHangul; ScriptHan; ScriptHiragana; ScriptKatakana; ScriptYi] end
      | let c: U32 if c <= 0x3017 => recover val [as Script: ScriptBopomofo; ScriptHangul; ScriptHan; ScriptHiragana; ScriptKatakana; ScriptYi] end
      | let c: U32 if c <= 0x3018 => recover val [as Script: ScriptBopomofo; ScriptHangul; ScriptHan; ScriptHiragana; ScriptKatakana; ScriptYi] end
      | let c: U32 if c <= 0x3019 => recover val [as Script: ScriptBopomofo; ScriptHangul; ScriptHan; ScriptHiragana; ScriptKatakana; ScriptYi] end
      | let c: U32 if c <= 0x301A => recover val [as Script: ScriptBopomofo; ScriptHangul; ScriptHan; ScriptHiragana; ScriptKatakana; ScriptYi] end
      | let c: U32 if c <= 0x301B => recover val [as Script: ScriptBopomofo; ScriptHangul; ScriptHan; ScriptHiragana; ScriptKatakana; ScriptYi] end
      | let c: U32 if c <= 0x301C => recover val [as Script: ScriptBopomofo; ScriptHangul; ScriptHan; ScriptHiragana; ScriptKatakana] end
      | let c: U32 if c <= 0x301D => recover val [as Script: ScriptBopomofo; ScriptHangul; ScriptHan; ScriptHiragana; ScriptKatakana] end
      | let c: U32 if c <= 0x301F => recover val [as Script: ScriptBopomofo; ScriptHangul; ScriptHan; ScriptHiragana; ScriptKatakana] end
      | let c: U32 if c <= 0x3029 => None
      | let c: U32 if c <= 0x302D => recover val [as Script: ScriptBopomofo; ScriptHan] end
      | let c: U32 if c <= 0x302F => None
      | let c: U32 if c <= 0x3030 => recover val [as Script: ScriptBopomofo; ScriptHangul; ScriptHan; ScriptHiragana; ScriptKatakana] end
      | let c: U32 if c <= 0x3035 => recover val [as Script: ScriptHiragana; ScriptKatakana] end
      | let c: U32 if c <= 0x3036 => None
      | let c: U32 if c <= 0x3037 => recover val [as Script: ScriptBopomofo; ScriptHangul; ScriptHan; ScriptHiragana; ScriptKatakana] end
      | let c: U32 if c <= 0x303B => None
      | let c: U32 if c <= 0x303C => recover val [as Script: ScriptHan; ScriptHiragana; ScriptKatakana] end
      | let c: U32 if c <= 0x303D => recover val [as Script: ScriptHan; ScriptHiragana; ScriptKatakana] end
      | let c: U32 if c <= 0x303F => recover val [as Script: ScriptHan] end
      | let c: U32 if c <= 0x3098 => None
      | let c: U32 if c <= 0x309A => recover val [as Script: ScriptHiragana; ScriptKatakana] end
      | let c: U32 if c <= 0x309C => recover val [as Script: ScriptHiragana; ScriptKatakana] end
      | let c: U32 if c <= 0x309F => None
      | let c: U32 if c <= 0x30A0 => recover val [as Script: ScriptHiragana; ScriptKatakana] end
      | let c: U32 if c <= 0x30FA => None
      | let c: U32 if c <= 0x30FB => recover val [as Script: ScriptBopomofo; ScriptHangul; ScriptHan; ScriptHiragana; ScriptKatakana; ScriptYi] end
      | let c: U32 if c <= 0x30FC => recover val [as Script: ScriptHiragana; ScriptKatakana] end
      | let c: U32 if c <= 0x318F => None
      | let c: U32 if c <= 0x3191 => recover val [as Script: ScriptHan] end
      | let c: U32 if c <= 0x3195 => recover val [as Script: ScriptHan] end
      | let c: U32 if c <= 0x319F => recover val [as Script: ScriptHan] end
      | let c: U32 if c <= 0x31BF => None
      | let c: U32 if c <= 0x31E5 => recover val [as Script: ScriptHan] end
      | let c: U32 if c <= 0x31EE => None
      | let c: U32 if c <= 0x31EF => recover val [as Script: ScriptHan; ScriptTangut] end
      | let c: U32 if c <= 0x321F => None
      | let c: U32 if c <= 0x3229 => recover val [as Script: ScriptHan] end
      | let c: U32 if c <= 0x3247 => recover val [as Script: ScriptHan] end
      | let c: U32 if c <= 0x327F => None
      | let c: U32 if c <= 0x3289 => recover val [as Script: ScriptHan] end
      | let c: U32 if c <= 0x32B0 => recover val [as Script: ScriptHan] end
      | let c: U32 if c <= 0x32BF => None
      | let c: U32 if c <= 0x32CB => recover val [as Script: ScriptHan] end
      | let c: U32 if c <= 0x32FE => None
      | let c: U32 if c <= 0x32FF => recover val [as Script: ScriptHan] end
      | let c: U32 if c <= 0x3357 => None
      | let c: U32 if c <= 0x3370 => recover val [as Script: ScriptHan] end
      | let c: U32 if c <= 0x337A => None
      | let c: U32 if c <= 0x337F => recover val [as Script: ScriptHan] end
      | let c: U32 if c <= 0x33DF => None
      | let c: U32 if c <= 0x33FE => recover val [as Script: ScriptHan] end
      else None
      end
    | 0x000A =>
      match cp
      | let c: U32 if c <= 0xA66E => None
      | let c: U32 if c <= 0xA66F => recover val [as Script: ScriptCyrillic; ScriptGlagolitic] end
      | let c: U32 if c <= 0xA6FF => None
      | let c: U32 if c <= 0xA707 => recover val [as Script: ScriptHan; ScriptLatin] end
      | let c: U32 if c <= 0xA82F => None
      | let c: U32 if c <= 0xA832 => recover val [as Script: ScriptDevanagari; ScriptDogra; ScriptGujarati; ScriptGurmukhi; ScriptKhojki; ScriptKannada; ScriptKaithi; ScriptMahajani; ScriptMalayalam; ScriptModi; ScriptNandinagari; ScriptSharada; ScriptKhudawadi; ScriptTakri; ScriptTirhuta; ScriptTuluTigalari] end
      | let c: U32 if c <= 0xA835 => recover val [as Script: ScriptDevanagari; ScriptDogra; ScriptGujarati; ScriptGurmukhi; ScriptKhojki; ScriptKannada; ScriptKaithi; ScriptMahajani; ScriptModi; ScriptNandinagari; ScriptSharada; ScriptKhudawadi; ScriptTakri; ScriptTirhuta; ScriptTuluTigalari] end
      | let c: U32 if c <= 0xA837 => recover val [as Script: ScriptDevanagari; ScriptDogra; ScriptGujarati; ScriptGurmukhi; ScriptKhojki; ScriptKaithi; ScriptMahajani; ScriptModi; ScriptKhudawadi; ScriptTakri; ScriptTirhuta] end
      | let c: U32 if c <= 0xA838 => recover val [as Script: ScriptDevanagari; ScriptDogra; ScriptGujarati; ScriptGurmukhi; ScriptKhojki; ScriptKaithi; ScriptMahajani; ScriptModi; ScriptSharada; ScriptKhudawadi; ScriptTakri; ScriptTirhuta] end
      | let c: U32 if c <= 0xA839 => recover val [as Script: ScriptDevanagari; ScriptDogra; ScriptGujarati; ScriptGurmukhi; ScriptKhojki; ScriptKaithi; ScriptMahajani; ScriptModi; ScriptKhudawadi; ScriptTakri; ScriptTirhuta] end
      | let c: U32 if c <= 0xA8F0 => None
      | let c: U32 if c <= 0xA8F1 => recover val [as Script: ScriptBengali; ScriptDevanagari; ScriptTuluTigalari] end
      | let c: U32 if c <= 0xA8F2 => None
      | let c: U32 if c <= 0xA8F3 => recover val [as Script: ScriptDevanagari; ScriptTamil] end
      | let c: U32 if c <= 0xA92D => None
      | let c: U32 if c <= 0xA92E => recover val [as Script: ScriptKayahLi; ScriptLatin; ScriptMyanmar] end
      | let c: U32 if c <= 0xA9CE => None
      | let c: U32 if c <= 0xA9CF => recover val [as Script: ScriptBuginese; ScriptJavanese] end
      else None
      end
    | 0x000F =>
      match cp
      | let c: U32 if c <= 0xFD3D => None
      | let c: U32 if c <= 0xFD3E => recover val [as Script: ScriptArabic; ScriptNko] end
      | let c: U32 if c <= 0xFD3F => recover val [as Script: ScriptArabic; ScriptNko] end
      | let c: U32 if c <= 0xFDF1 => None
      | let c: U32 if c <= 0xFDF2 => recover val [as Script: ScriptArabic; ScriptThaana] end
      | let c: U32 if c <= 0xFDFC => None
      | let c: U32 if c <= 0xFDFD => recover val [as Script: ScriptArabic; ScriptThaana] end
      | let c: U32 if c <= 0xFE44 => None
      | let c: U32 if c <= 0xFE46 => recover val [as Script: ScriptBopomofo; ScriptHangul; ScriptHan; ScriptHiragana; ScriptKatakana] end
      | let c: U32 if c <= 0xFF60 => None
      | let c: U32 if c <= 0xFF61 => recover val [as Script: ScriptBopomofo; ScriptHangul; ScriptHan; ScriptHiragana; ScriptKatakana; ScriptYi] end
      | let c: U32 if c <= 0xFF62 => recover val [as Script: ScriptBopomofo; ScriptHangul; ScriptHan; ScriptHiragana; ScriptKatakana; ScriptYi] end
      | let c: U32 if c <= 0xFF63 => recover val [as Script: ScriptBopomofo; ScriptHangul; ScriptHan; ScriptHiragana; ScriptKatakana; ScriptYi] end
      | let c: U32 if c <= 0xFF65 => recover val [as Script: ScriptBopomofo; ScriptHangul; ScriptHan; ScriptHiragana; ScriptKatakana; ScriptYi] end
      | let c: U32 if c <= 0xFF6F => None
      | let c: U32 if c <= 0xFF70 => recover val [as Script: ScriptHiragana; ScriptKatakana] end
      | let c: U32 if c <= 0xFF9D => None
      | let c: U32 if c <= 0xFF9F => recover val [as Script: ScriptHiragana; ScriptKatakana] end
      else None
      end
    | 0x0010 =>
      match cp
      | let c: U32 if c <= 0x100FF => None
      | let c: U32 if c <= 0x10101 => recover val [as Script: ScriptCyproMinoan; ScriptCypriot; ScriptLinearB] end
      | let c: U32 if c <= 0x10102 => recover val [as Script: ScriptCypriot; ScriptLinearB] end
      | let c: U32 if c <= 0x10106 => None
      | let c: U32 if c <= 0x10133 => recover val [as Script: ScriptCypriot; ScriptLinearA; ScriptLinearB] end
      | let c: U32 if c <= 0x10136 => None
      | let c: U32 if c <= 0x1013F => recover val [as Script: ScriptCypriot; ScriptLinearB] end
      | let c: U32 if c <= 0x102DF => None
      | let c: U32 if c <= 0x102E0 => recover val [as Script: ScriptArabic; ScriptCoptic] end
      | let c: U32 if c <= 0x102FB => recover val [as Script: ScriptArabic; ScriptCoptic] end
      | let c: U32 if c <= 0x10AF1 => None
      | let c: U32 if c <= 0x10AF2 => recover val [as Script: ScriptManichaean; ScriptOldUyghur] end
      else None
      end
    | 0x0011 =>
      match cp
      | let c: U32 if c <= 0x11300 => None
      | let c: U32 if c <= 0x11301 => recover val [as Script: ScriptGrantha; ScriptTamil] end
      | let c: U32 if c <= 0x11302 => None
      | let c: U32 if c <= 0x11303 => recover val [as Script: ScriptGrantha; ScriptTamil] end
      | let c: U32 if c <= 0x1133A => None
      | let c: U32 if c <= 0x1133C => recover val [as Script: ScriptGrantha; ScriptTamil] end
      | let c: U32 if c <= 0x11FCF => None
      | let c: U32 if c <= 0x11FD1 => recover val [as Script: ScriptGrantha; ScriptTamil] end
      | let c: U32 if c <= 0x11FD2 => None
      | let c: U32 if c <= 0x11FD3 => recover val [as Script: ScriptGrantha; ScriptTamil] end
      else None
      end
    | 0x001B =>
      match cp
      | let c: U32 if c <= 0x1BC9F => None
      | let c: U32 if c <= 0x1BCA3 => recover val [as Script: ScriptDuployan] end
      else None
      end
    | 0x001D =>
      match cp
      | let c: U32 if c <= 0x1D35F => None
      | let c: U32 if c <= 0x1D371 => recover val [as Script: ScriptHan] end
      else None
      end
    | 0x001F =>
      match cp
      | let c: U32 if c <= 0x1F24F => None
      | let c: U32 if c <= 0x1F251 => recover val [as Script: ScriptHan] end
      else None
      end
    else
      None
    end
