// Auto-generated by unicode-build. Do not edit by hand.
// Regenerate via:
//   make ucd-generate
//
// Source: Scripts.txt. Codepoints outside any range
// default to ScriptUnknown (byte 0).
use @ucd_script_lookup[U8](cp: U32)

primitive _UcdScript
  fun of(cp: U32): Script =>
    _ScriptCodec.from_byte(@ucd_script_lookup(cp))

  fun byte_of(cp: U32): U8 =>
    // Raw script byte; lets byte-consuming callers skip the
    // from_byte/to_byte round trip (see Scripts.dominant etc).
    @ucd_script_lookup(cp)
