// Auto-generated by unicode-build. Do not edit by hand.
// Regenerate via:
//   make ucd-generate
//
// Sources: auxiliary/WordBreakProperty.txt +
// emoji/emoji-data.txt (Extended_Pictographic only).
// Codepoints outside any range default to WBOther.
use @ucd_wb_lookup[U8](cp: U32)

primitive _UcdWordBreak
  fun of(cp: U32): WordBreak =>
    WordBreaks._from_byte(@ucd_wb_lookup(cp))
