// Auto-generated by unicode-build. Do not edit by hand.
// Regenerate via:
//   make ucd-generate
//
// Source: CaseFolding.txt status C + S entries.
// Only non-identity mappings are stored (value 0 = identity);
// `of` returns `cp` for those so the API is identity-preserving.
use @ucd_scf_lookup[U32](cp: U32)

primitive _UcdSimpleCaseFold
  fun of(cp: U32): U32 =>
    let m = @ucd_scf_lookup(cp)
    if m == 0 then cp else m end
