// Auto-generated by unicode-build. Do not edit by hand.
// Regenerate via:
//   make ucd-generate
//
// Source: PropList.txt + DerivedCoreProperties.txt +
// emoji/emoji-data.txt. The `BinaryProperty` type is a
// closed union — exhaustive `match` is compile-checked.

primitive PropASCIIHexDigit
  fun code(): String val => "ASCII_Hex_Digit"
  fun string(): String iso^ => "ASCII_Hex_Digit".clone()

primitive PropAlphabetic
  fun code(): String val => "Alphabetic"
  fun string(): String iso^ => "Alphabetic".clone()

primitive PropBidiControl
  fun code(): String val => "Bidi_Control"
  fun string(): String iso^ => "Bidi_Control".clone()

primitive PropCaseIgnorable
  fun code(): String val => "Case_Ignorable"
  fun string(): String iso^ => "Case_Ignorable".clone()

primitive PropCased
  fun code(): String val => "Cased"
  fun string(): String iso^ => "Cased".clone()

primitive PropChangesWhenCasefolded
  fun code(): String val => "Changes_When_Casefolded"
  fun string(): String iso^ => "Changes_When_Casefolded".clone()

primitive PropChangesWhenCasemapped
  fun code(): String val => "Changes_When_Casemapped"
  fun string(): String iso^ => "Changes_When_Casemapped".clone()

primitive PropChangesWhenLowercased
  fun code(): String val => "Changes_When_Lowercased"
  fun string(): String iso^ => "Changes_When_Lowercased".clone()

primitive PropChangesWhenTitlecased
  fun code(): String val => "Changes_When_Titlecased"
  fun string(): String iso^ => "Changes_When_Titlecased".clone()

primitive PropChangesWhenUppercased
  fun code(): String val => "Changes_When_Uppercased"
  fun string(): String iso^ => "Changes_When_Uppercased".clone()

primitive PropDash
  fun code(): String val => "Dash"
  fun string(): String iso^ => "Dash".clone()

primitive PropDefaultIgnorableCodePoint
  fun code(): String val => "Default_Ignorable_Code_Point"
  fun string(): String iso^ => "Default_Ignorable_Code_Point".clone()

primitive PropDeprecated
  fun code(): String val => "Deprecated"
  fun string(): String iso^ => "Deprecated".clone()

primitive PropDiacritic
  fun code(): String val => "Diacritic"
  fun string(): String iso^ => "Diacritic".clone()

primitive PropEmoji
  fun code(): String val => "Emoji"
  fun string(): String iso^ => "Emoji".clone()

primitive PropEmojiComponent
  fun code(): String val => "Emoji_Component"
  fun string(): String iso^ => "Emoji_Component".clone()

primitive PropEmojiModifier
  fun code(): String val => "Emoji_Modifier"
  fun string(): String iso^ => "Emoji_Modifier".clone()

primitive PropEmojiModifierBase
  fun code(): String val => "Emoji_Modifier_Base"
  fun string(): String iso^ => "Emoji_Modifier_Base".clone()

primitive PropEmojiPresentation
  fun code(): String val => "Emoji_Presentation"
  fun string(): String iso^ => "Emoji_Presentation".clone()

primitive PropExtendedPictographic
  fun code(): String val => "Extended_Pictographic"
  fun string(): String iso^ => "Extended_Pictographic".clone()

primitive PropExtender
  fun code(): String val => "Extender"
  fun string(): String iso^ => "Extender".clone()

primitive PropGraphemeBase
  fun code(): String val => "Grapheme_Base"
  fun string(): String iso^ => "Grapheme_Base".clone()

primitive PropGraphemeExtend
  fun code(): String val => "Grapheme_Extend"
  fun string(): String iso^ => "Grapheme_Extend".clone()

primitive PropGraphemeLink
  fun code(): String val => "Grapheme_Link"
  fun string(): String iso^ => "Grapheme_Link".clone()

primitive PropHexDigit
  fun code(): String val => "Hex_Digit"
  fun string(): String iso^ => "Hex_Digit".clone()

primitive PropHyphen
  fun code(): String val => "Hyphen"
  fun string(): String iso^ => "Hyphen".clone()

primitive PropIDSBinaryOperator
  fun code(): String val => "IDS_Binary_Operator"
  fun string(): String iso^ => "IDS_Binary_Operator".clone()

primitive PropIDSTrinaryOperator
  fun code(): String val => "IDS_Trinary_Operator"
  fun string(): String iso^ => "IDS_Trinary_Operator".clone()

primitive PropIDContinue
  fun code(): String val => "ID_Continue"
  fun string(): String iso^ => "ID_Continue".clone()

primitive PropIDStart
  fun code(): String val => "ID_Start"
  fun string(): String iso^ => "ID_Start".clone()

primitive PropIdeographic
  fun code(): String val => "Ideographic"
  fun string(): String iso^ => "Ideographic".clone()

primitive PropJoinControl
  fun code(): String val => "Join_Control"
  fun string(): String iso^ => "Join_Control".clone()

primitive PropLogicalOrderException
  fun code(): String val => "Logical_Order_Exception"
  fun string(): String iso^ => "Logical_Order_Exception".clone()

primitive PropLowercase
  fun code(): String val => "Lowercase"
  fun string(): String iso^ => "Lowercase".clone()

primitive PropMath
  fun code(): String val => "Math"
  fun string(): String iso^ => "Math".clone()

primitive PropNoncharacterCodePoint
  fun code(): String val => "Noncharacter_Code_Point"
  fun string(): String iso^ => "Noncharacter_Code_Point".clone()

primitive PropOtherAlphabetic
  fun code(): String val => "Other_Alphabetic"
  fun string(): String iso^ => "Other_Alphabetic".clone()

primitive PropOtherDefaultIgnorableCodePoint
  fun code(): String val => "Other_Default_Ignorable_Code_Point"
  fun string(): String iso^ => "Other_Default_Ignorable_Code_Point".clone()

primitive PropOtherGraphemeExtend
  fun code(): String val => "Other_Grapheme_Extend"
  fun string(): String iso^ => "Other_Grapheme_Extend".clone()

primitive PropOtherIDContinue
  fun code(): String val => "Other_ID_Continue"
  fun string(): String iso^ => "Other_ID_Continue".clone()

primitive PropOtherIDStart
  fun code(): String val => "Other_ID_Start"
  fun string(): String iso^ => "Other_ID_Start".clone()

primitive PropOtherLowercase
  fun code(): String val => "Other_Lowercase"
  fun string(): String iso^ => "Other_Lowercase".clone()

primitive PropOtherMath
  fun code(): String val => "Other_Math"
  fun string(): String iso^ => "Other_Math".clone()

primitive PropOtherUppercase
  fun code(): String val => "Other_Uppercase"
  fun string(): String iso^ => "Other_Uppercase".clone()

primitive PropPatternSyntax
  fun code(): String val => "Pattern_Syntax"
  fun string(): String iso^ => "Pattern_Syntax".clone()

primitive PropPatternWhiteSpace
  fun code(): String val => "Pattern_White_Space"
  fun string(): String iso^ => "Pattern_White_Space".clone()

primitive PropPrependedConcatenationMark
  fun code(): String val => "Prepended_Concatenation_Mark"
  fun string(): String iso^ => "Prepended_Concatenation_Mark".clone()

primitive PropQuotationMark
  fun code(): String val => "Quotation_Mark"
  fun string(): String iso^ => "Quotation_Mark".clone()

primitive PropRadical
  fun code(): String val => "Radical"
  fun string(): String iso^ => "Radical".clone()

primitive PropRegionalIndicator
  fun code(): String val => "Regional_Indicator"
  fun string(): String iso^ => "Regional_Indicator".clone()

primitive PropSentenceTerminal
  fun code(): String val => "Sentence_Terminal"
  fun string(): String iso^ => "Sentence_Terminal".clone()

primitive PropSoftDotted
  fun code(): String val => "Soft_Dotted"
  fun string(): String iso^ => "Soft_Dotted".clone()

primitive PropTerminalPunctuation
  fun code(): String val => "Terminal_Punctuation"
  fun string(): String iso^ => "Terminal_Punctuation".clone()

primitive PropUnifiedIdeograph
  fun code(): String val => "Unified_Ideograph"
  fun string(): String iso^ => "Unified_Ideograph".clone()

primitive PropUppercase
  fun code(): String val => "Uppercase"
  fun string(): String iso^ => "Uppercase".clone()

primitive PropVariationSelector
  fun code(): String val => "Variation_Selector"
  fun string(): String iso^ => "Variation_Selector".clone()

primitive PropWhiteSpace
  fun code(): String val => "White_Space"
  fun string(): String iso^ => "White_Space".clone()

primitive PropXIDContinue
  fun code(): String val => "XID_Continue"
  fun string(): String iso^ => "XID_Continue".clone()

primitive PropXIDStart
  fun code(): String val => "XID_Start"
  fun string(): String iso^ => "XID_Start".clone()

type BinaryProperty is
  ( PropASCIIHexDigit
  | PropAlphabetic
  | PropBidiControl
  | PropCaseIgnorable
  | PropCased
  | PropChangesWhenCasefolded
  | PropChangesWhenCasemapped
  | PropChangesWhenLowercased
  | PropChangesWhenTitlecased
  | PropChangesWhenUppercased
  | PropDash
  | PropDefaultIgnorableCodePoint
  | PropDeprecated
  | PropDiacritic
  | PropEmoji
  | PropEmojiComponent
  | PropEmojiModifier
  | PropEmojiModifierBase
  | PropEmojiPresentation
  | PropExtendedPictographic
  | PropExtender
  | PropGraphemeBase
  | PropGraphemeExtend
  | PropGraphemeLink
  | PropHexDigit
  | PropHyphen
  | PropIDSBinaryOperator
  | PropIDSTrinaryOperator
  | PropIDContinue
  | PropIDStart
  | PropIdeographic
  | PropJoinControl
  | PropLogicalOrderException
  | PropLowercase
  | PropMath
  | PropNoncharacterCodePoint
  | PropOtherAlphabetic
  | PropOtherDefaultIgnorableCodePoint
  | PropOtherGraphemeExtend
  | PropOtherIDContinue
  | PropOtherIDStart
  | PropOtherLowercase
  | PropOtherMath
  | PropOtherUppercase
  | PropPatternSyntax
  | PropPatternWhiteSpace
  | PropPrependedConcatenationMark
  | PropQuotationMark
  | PropRadical
  | PropRegionalIndicator
  | PropSentenceTerminal
  | PropSoftDotted
  | PropTerminalPunctuation
  | PropUnifiedIdeograph
  | PropUppercase
  | PropVariationSelector
  | PropWhiteSpace
  | PropXIDContinue
  | PropXIDStart
  )

primitive BinaryProperties
  fun from_iso(s: String box): (BinaryProperty | None) =>
    match s
    | "ASCII_Hex_Digit" => PropASCIIHexDigit
    | "Alphabetic" => PropAlphabetic
    | "Bidi_Control" => PropBidiControl
    | "Case_Ignorable" => PropCaseIgnorable
    | "Cased" => PropCased
    | "Changes_When_Casefolded" => PropChangesWhenCasefolded
    | "Changes_When_Casemapped" => PropChangesWhenCasemapped
    | "Changes_When_Lowercased" => PropChangesWhenLowercased
    | "Changes_When_Titlecased" => PropChangesWhenTitlecased
    | "Changes_When_Uppercased" => PropChangesWhenUppercased
    | "Dash" => PropDash
    | "Default_Ignorable_Code_Point" => PropDefaultIgnorableCodePoint
    | "Deprecated" => PropDeprecated
    | "Diacritic" => PropDiacritic
    | "Emoji" => PropEmoji
    | "Emoji_Component" => PropEmojiComponent
    | "Emoji_Modifier" => PropEmojiModifier
    | "Emoji_Modifier_Base" => PropEmojiModifierBase
    | "Emoji_Presentation" => PropEmojiPresentation
    | "Extended_Pictographic" => PropExtendedPictographic
    | "Extender" => PropExtender
    | "Grapheme_Base" => PropGraphemeBase
    | "Grapheme_Extend" => PropGraphemeExtend
    | "Grapheme_Link" => PropGraphemeLink
    | "Hex_Digit" => PropHexDigit
    | "Hyphen" => PropHyphen
    | "IDS_Binary_Operator" => PropIDSBinaryOperator
    | "IDS_Trinary_Operator" => PropIDSTrinaryOperator
    | "ID_Continue" => PropIDContinue
    | "ID_Start" => PropIDStart
    | "Ideographic" => PropIdeographic
    | "Join_Control" => PropJoinControl
    | "Logical_Order_Exception" => PropLogicalOrderException
    | "Lowercase" => PropLowercase
    | "Math" => PropMath
    | "Noncharacter_Code_Point" => PropNoncharacterCodePoint
    | "Other_Alphabetic" => PropOtherAlphabetic
    | "Other_Default_Ignorable_Code_Point" => PropOtherDefaultIgnorableCodePoint
    | "Other_Grapheme_Extend" => PropOtherGraphemeExtend
    | "Other_ID_Continue" => PropOtherIDContinue
    | "Other_ID_Start" => PropOtherIDStart
    | "Other_Lowercase" => PropOtherLowercase
    | "Other_Math" => PropOtherMath
    | "Other_Uppercase" => PropOtherUppercase
    | "Pattern_Syntax" => PropPatternSyntax
    | "Pattern_White_Space" => PropPatternWhiteSpace
    | "Prepended_Concatenation_Mark" => PropPrependedConcatenationMark
    | "Quotation_Mark" => PropQuotationMark
    | "Radical" => PropRadical
    | "Regional_Indicator" => PropRegionalIndicator
    | "Sentence_Terminal" => PropSentenceTerminal
    | "Soft_Dotted" => PropSoftDotted
    | "Terminal_Punctuation" => PropTerminalPunctuation
    | "Unified_Ideograph" => PropUnifiedIdeograph
    | "Uppercase" => PropUppercase
    | "Variation_Selector" => PropVariationSelector
    | "White_Space" => PropWhiteSpace
    | "XID_Continue" => PropXIDContinue
    | "XID_Start" => PropXIDStart
    else None
    end
