// Auto-generated by unicode-build. Do not edit by hand.
// Regenerate via:
//   make ucd-generate
//
// Source: Scripts.txt. The `Script` type is a closed
// union — exhaustive `match` is compile-checked. Every
// new Unicode version that adds a script is a
// semver-significant breaking change by design.

primitive ScriptUnknown
  fun code(): String val => "Unknown"
  fun string(): String iso^ => "Unknown".clone()

primitive ScriptAdlam
  fun code(): String val => "Adlam"
  fun string(): String iso^ => "Adlam".clone()

primitive ScriptAhom
  fun code(): String val => "Ahom"
  fun string(): String iso^ => "Ahom".clone()

primitive ScriptAnatolianHieroglyphs
  fun code(): String val => "Anatolian_Hieroglyphs"
  fun string(): String iso^ => "Anatolian_Hieroglyphs".clone()

primitive ScriptArabic
  fun code(): String val => "Arabic"
  fun string(): String iso^ => "Arabic".clone()

primitive ScriptArmenian
  fun code(): String val => "Armenian"
  fun string(): String iso^ => "Armenian".clone()

primitive ScriptAvestan
  fun code(): String val => "Avestan"
  fun string(): String iso^ => "Avestan".clone()

primitive ScriptBalinese
  fun code(): String val => "Balinese"
  fun string(): String iso^ => "Balinese".clone()

primitive ScriptBamum
  fun code(): String val => "Bamum"
  fun string(): String iso^ => "Bamum".clone()

primitive ScriptBassaVah
  fun code(): String val => "Bassa_Vah"
  fun string(): String iso^ => "Bassa_Vah".clone()

primitive ScriptBatak
  fun code(): String val => "Batak"
  fun string(): String iso^ => "Batak".clone()

primitive ScriptBengali
  fun code(): String val => "Bengali"
  fun string(): String iso^ => "Bengali".clone()

primitive ScriptBhaiksuki
  fun code(): String val => "Bhaiksuki"
  fun string(): String iso^ => "Bhaiksuki".clone()

primitive ScriptBopomofo
  fun code(): String val => "Bopomofo"
  fun string(): String iso^ => "Bopomofo".clone()

primitive ScriptBrahmi
  fun code(): String val => "Brahmi"
  fun string(): String iso^ => "Brahmi".clone()

primitive ScriptBraille
  fun code(): String val => "Braille"
  fun string(): String iso^ => "Braille".clone()

primitive ScriptBuginese
  fun code(): String val => "Buginese"
  fun string(): String iso^ => "Buginese".clone()

primitive ScriptBuhid
  fun code(): String val => "Buhid"
  fun string(): String iso^ => "Buhid".clone()

primitive ScriptCanadianAboriginal
  fun code(): String val => "Canadian_Aboriginal"
  fun string(): String iso^ => "Canadian_Aboriginal".clone()

primitive ScriptCarian
  fun code(): String val => "Carian"
  fun string(): String iso^ => "Carian".clone()

primitive ScriptCaucasianAlbanian
  fun code(): String val => "Caucasian_Albanian"
  fun string(): String iso^ => "Caucasian_Albanian".clone()

primitive ScriptChakma
  fun code(): String val => "Chakma"
  fun string(): String iso^ => "Chakma".clone()

primitive ScriptCham
  fun code(): String val => "Cham"
  fun string(): String iso^ => "Cham".clone()

primitive ScriptCherokee
  fun code(): String val => "Cherokee"
  fun string(): String iso^ => "Cherokee".clone()

primitive ScriptChorasmian
  fun code(): String val => "Chorasmian"
  fun string(): String iso^ => "Chorasmian".clone()

primitive ScriptCommon
  fun code(): String val => "Common"
  fun string(): String iso^ => "Common".clone()

primitive ScriptCoptic
  fun code(): String val => "Coptic"
  fun string(): String iso^ => "Coptic".clone()

primitive ScriptCuneiform
  fun code(): String val => "Cuneiform"
  fun string(): String iso^ => "Cuneiform".clone()

primitive ScriptCypriot
  fun code(): String val => "Cypriot"
  fun string(): String iso^ => "Cypriot".clone()

primitive ScriptCyproMinoan
  fun code(): String val => "Cypro_Minoan"
  fun string(): String iso^ => "Cypro_Minoan".clone()

primitive ScriptCyrillic
  fun code(): String val => "Cyrillic"
  fun string(): String iso^ => "Cyrillic".clone()

primitive ScriptDeseret
  fun code(): String val => "Deseret"
  fun string(): String iso^ => "Deseret".clone()

primitive ScriptDevanagari
  fun code(): String val => "Devanagari"
  fun string(): String iso^ => "Devanagari".clone()

primitive ScriptDivesAkuru
  fun code(): String val => "Dives_Akuru"
  fun string(): String iso^ => "Dives_Akuru".clone()

primitive ScriptDogra
  fun code(): String val => "Dogra"
  fun string(): String iso^ => "Dogra".clone()

primitive ScriptDuployan
  fun code(): String val => "Duployan"
  fun string(): String iso^ => "Duployan".clone()

primitive ScriptEgyptianHieroglyphs
  fun code(): String val => "Egyptian_Hieroglyphs"
  fun string(): String iso^ => "Egyptian_Hieroglyphs".clone()

primitive ScriptElbasan
  fun code(): String val => "Elbasan"
  fun string(): String iso^ => "Elbasan".clone()

primitive ScriptElymaic
  fun code(): String val => "Elymaic"
  fun string(): String iso^ => "Elymaic".clone()

primitive ScriptEthiopic
  fun code(): String val => "Ethiopic"
  fun string(): String iso^ => "Ethiopic".clone()

primitive ScriptGeorgian
  fun code(): String val => "Georgian"
  fun string(): String iso^ => "Georgian".clone()

primitive ScriptGlagolitic
  fun code(): String val => "Glagolitic"
  fun string(): String iso^ => "Glagolitic".clone()

primitive ScriptGothic
  fun code(): String val => "Gothic"
  fun string(): String iso^ => "Gothic".clone()

primitive ScriptGrantha
  fun code(): String val => "Grantha"
  fun string(): String iso^ => "Grantha".clone()

primitive ScriptGreek
  fun code(): String val => "Greek"
  fun string(): String iso^ => "Greek".clone()

primitive ScriptGujarati
  fun code(): String val => "Gujarati"
  fun string(): String iso^ => "Gujarati".clone()

primitive ScriptGunjalaGondi
  fun code(): String val => "Gunjala_Gondi"
  fun string(): String iso^ => "Gunjala_Gondi".clone()

primitive ScriptGurmukhi
  fun code(): String val => "Gurmukhi"
  fun string(): String iso^ => "Gurmukhi".clone()

primitive ScriptHan
  fun code(): String val => "Han"
  fun string(): String iso^ => "Han".clone()

primitive ScriptHangul
  fun code(): String val => "Hangul"
  fun string(): String iso^ => "Hangul".clone()

primitive ScriptHanifiRohingya
  fun code(): String val => "Hanifi_Rohingya"
  fun string(): String iso^ => "Hanifi_Rohingya".clone()

primitive ScriptHanunoo
  fun code(): String val => "Hanunoo"
  fun string(): String iso^ => "Hanunoo".clone()

primitive ScriptHatran
  fun code(): String val => "Hatran"
  fun string(): String iso^ => "Hatran".clone()

primitive ScriptHebrew
  fun code(): String val => "Hebrew"
  fun string(): String iso^ => "Hebrew".clone()

primitive ScriptHiragana
  fun code(): String val => "Hiragana"
  fun string(): String iso^ => "Hiragana".clone()

primitive ScriptImperialAramaic
  fun code(): String val => "Imperial_Aramaic"
  fun string(): String iso^ => "Imperial_Aramaic".clone()

primitive ScriptInherited
  fun code(): String val => "Inherited"
  fun string(): String iso^ => "Inherited".clone()

primitive ScriptInscriptionalPahlavi
  fun code(): String val => "Inscriptional_Pahlavi"
  fun string(): String iso^ => "Inscriptional_Pahlavi".clone()

primitive ScriptInscriptionalParthian
  fun code(): String val => "Inscriptional_Parthian"
  fun string(): String iso^ => "Inscriptional_Parthian".clone()

primitive ScriptJavanese
  fun code(): String val => "Javanese"
  fun string(): String iso^ => "Javanese".clone()

primitive ScriptKaithi
  fun code(): String val => "Kaithi"
  fun string(): String iso^ => "Kaithi".clone()

primitive ScriptKannada
  fun code(): String val => "Kannada"
  fun string(): String iso^ => "Kannada".clone()

primitive ScriptKatakana
  fun code(): String val => "Katakana"
  fun string(): String iso^ => "Katakana".clone()

primitive ScriptKayahLi
  fun code(): String val => "Kayah_Li"
  fun string(): String iso^ => "Kayah_Li".clone()

primitive ScriptKharoshthi
  fun code(): String val => "Kharoshthi"
  fun string(): String iso^ => "Kharoshthi".clone()

primitive ScriptKhitanSmallScript
  fun code(): String val => "Khitan_Small_Script"
  fun string(): String iso^ => "Khitan_Small_Script".clone()

primitive ScriptKhmer
  fun code(): String val => "Khmer"
  fun string(): String iso^ => "Khmer".clone()

primitive ScriptKhojki
  fun code(): String val => "Khojki"
  fun string(): String iso^ => "Khojki".clone()

primitive ScriptKhudawadi
  fun code(): String val => "Khudawadi"
  fun string(): String iso^ => "Khudawadi".clone()

primitive ScriptLao
  fun code(): String val => "Lao"
  fun string(): String iso^ => "Lao".clone()

primitive ScriptLatin
  fun code(): String val => "Latin"
  fun string(): String iso^ => "Latin".clone()

primitive ScriptLepcha
  fun code(): String val => "Lepcha"
  fun string(): String iso^ => "Lepcha".clone()

primitive ScriptLimbu
  fun code(): String val => "Limbu"
  fun string(): String iso^ => "Limbu".clone()

primitive ScriptLinearA
  fun code(): String val => "Linear_A"
  fun string(): String iso^ => "Linear_A".clone()

primitive ScriptLinearB
  fun code(): String val => "Linear_B"
  fun string(): String iso^ => "Linear_B".clone()

primitive ScriptLisu
  fun code(): String val => "Lisu"
  fun string(): String iso^ => "Lisu".clone()

primitive ScriptLycian
  fun code(): String val => "Lycian"
  fun string(): String iso^ => "Lycian".clone()

primitive ScriptLydian
  fun code(): String val => "Lydian"
  fun string(): String iso^ => "Lydian".clone()

primitive ScriptMahajani
  fun code(): String val => "Mahajani"
  fun string(): String iso^ => "Mahajani".clone()

primitive ScriptMakasar
  fun code(): String val => "Makasar"
  fun string(): String iso^ => "Makasar".clone()

primitive ScriptMalayalam
  fun code(): String val => "Malayalam"
  fun string(): String iso^ => "Malayalam".clone()

primitive ScriptMandaic
  fun code(): String val => "Mandaic"
  fun string(): String iso^ => "Mandaic".clone()

primitive ScriptManichaean
  fun code(): String val => "Manichaean"
  fun string(): String iso^ => "Manichaean".clone()

primitive ScriptMarchen
  fun code(): String val => "Marchen"
  fun string(): String iso^ => "Marchen".clone()

primitive ScriptMasaramGondi
  fun code(): String val => "Masaram_Gondi"
  fun string(): String iso^ => "Masaram_Gondi".clone()

primitive ScriptMedefaidrin
  fun code(): String val => "Medefaidrin"
  fun string(): String iso^ => "Medefaidrin".clone()

primitive ScriptMeeteiMayek
  fun code(): String val => "Meetei_Mayek"
  fun string(): String iso^ => "Meetei_Mayek".clone()

primitive ScriptMendeKikakui
  fun code(): String val => "Mende_Kikakui"
  fun string(): String iso^ => "Mende_Kikakui".clone()

primitive ScriptMeroiticCursive
  fun code(): String val => "Meroitic_Cursive"
  fun string(): String iso^ => "Meroitic_Cursive".clone()

primitive ScriptMeroiticHieroglyphs
  fun code(): String val => "Meroitic_Hieroglyphs"
  fun string(): String iso^ => "Meroitic_Hieroglyphs".clone()

primitive ScriptMiao
  fun code(): String val => "Miao"
  fun string(): String iso^ => "Miao".clone()

primitive ScriptModi
  fun code(): String val => "Modi"
  fun string(): String iso^ => "Modi".clone()

primitive ScriptMongolian
  fun code(): String val => "Mongolian"
  fun string(): String iso^ => "Mongolian".clone()

primitive ScriptMro
  fun code(): String val => "Mro"
  fun string(): String iso^ => "Mro".clone()

primitive ScriptMultani
  fun code(): String val => "Multani"
  fun string(): String iso^ => "Multani".clone()

primitive ScriptMyanmar
  fun code(): String val => "Myanmar"
  fun string(): String iso^ => "Myanmar".clone()

primitive ScriptNabataean
  fun code(): String val => "Nabataean"
  fun string(): String iso^ => "Nabataean".clone()

primitive ScriptNandinagari
  fun code(): String val => "Nandinagari"
  fun string(): String iso^ => "Nandinagari".clone()

primitive ScriptNewTaiLue
  fun code(): String val => "New_Tai_Lue"
  fun string(): String iso^ => "New_Tai_Lue".clone()

primitive ScriptNewa
  fun code(): String val => "Newa"
  fun string(): String iso^ => "Newa".clone()

primitive ScriptNko
  fun code(): String val => "Nko"
  fun string(): String iso^ => "Nko".clone()

primitive ScriptNushu
  fun code(): String val => "Nushu"
  fun string(): String iso^ => "Nushu".clone()

primitive ScriptNyiakengPuachueHmong
  fun code(): String val => "Nyiakeng_Puachue_Hmong"
  fun string(): String iso^ => "Nyiakeng_Puachue_Hmong".clone()

primitive ScriptOgham
  fun code(): String val => "Ogham"
  fun string(): String iso^ => "Ogham".clone()

primitive ScriptOlChiki
  fun code(): String val => "Ol_Chiki"
  fun string(): String iso^ => "Ol_Chiki".clone()

primitive ScriptOldHungarian
  fun code(): String val => "Old_Hungarian"
  fun string(): String iso^ => "Old_Hungarian".clone()

primitive ScriptOldItalic
  fun code(): String val => "Old_Italic"
  fun string(): String iso^ => "Old_Italic".clone()

primitive ScriptOldNorthArabian
  fun code(): String val => "Old_North_Arabian"
  fun string(): String iso^ => "Old_North_Arabian".clone()

primitive ScriptOldPermic
  fun code(): String val => "Old_Permic"
  fun string(): String iso^ => "Old_Permic".clone()

primitive ScriptOldPersian
  fun code(): String val => "Old_Persian"
  fun string(): String iso^ => "Old_Persian".clone()

primitive ScriptOldSogdian
  fun code(): String val => "Old_Sogdian"
  fun string(): String iso^ => "Old_Sogdian".clone()

primitive ScriptOldSouthArabian
  fun code(): String val => "Old_South_Arabian"
  fun string(): String iso^ => "Old_South_Arabian".clone()

primitive ScriptOldTurkic
  fun code(): String val => "Old_Turkic"
  fun string(): String iso^ => "Old_Turkic".clone()

primitive ScriptOldUyghur
  fun code(): String val => "Old_Uyghur"
  fun string(): String iso^ => "Old_Uyghur".clone()

primitive ScriptOriya
  fun code(): String val => "Oriya"
  fun string(): String iso^ => "Oriya".clone()

primitive ScriptOsage
  fun code(): String val => "Osage"
  fun string(): String iso^ => "Osage".clone()

primitive ScriptOsmanya
  fun code(): String val => "Osmanya"
  fun string(): String iso^ => "Osmanya".clone()

primitive ScriptPahawhHmong
  fun code(): String val => "Pahawh_Hmong"
  fun string(): String iso^ => "Pahawh_Hmong".clone()

primitive ScriptPalmyrene
  fun code(): String val => "Palmyrene"
  fun string(): String iso^ => "Palmyrene".clone()

primitive ScriptPauCinHau
  fun code(): String val => "Pau_Cin_Hau"
  fun string(): String iso^ => "Pau_Cin_Hau".clone()

primitive ScriptPhagsPa
  fun code(): String val => "Phags_Pa"
  fun string(): String iso^ => "Phags_Pa".clone()

primitive ScriptPhoenician
  fun code(): String val => "Phoenician"
  fun string(): String iso^ => "Phoenician".clone()

primitive ScriptPsalterPahlavi
  fun code(): String val => "Psalter_Pahlavi"
  fun string(): String iso^ => "Psalter_Pahlavi".clone()

primitive ScriptRejang
  fun code(): String val => "Rejang"
  fun string(): String iso^ => "Rejang".clone()

primitive ScriptRunic
  fun code(): String val => "Runic"
  fun string(): String iso^ => "Runic".clone()

primitive ScriptSamaritan
  fun code(): String val => "Samaritan"
  fun string(): String iso^ => "Samaritan".clone()

primitive ScriptSaurashtra
  fun code(): String val => "Saurashtra"
  fun string(): String iso^ => "Saurashtra".clone()

primitive ScriptSharada
  fun code(): String val => "Sharada"
  fun string(): String iso^ => "Sharada".clone()

primitive ScriptShavian
  fun code(): String val => "Shavian"
  fun string(): String iso^ => "Shavian".clone()

primitive ScriptSiddham
  fun code(): String val => "Siddham"
  fun string(): String iso^ => "Siddham".clone()

primitive ScriptSignWriting
  fun code(): String val => "SignWriting"
  fun string(): String iso^ => "SignWriting".clone()

primitive ScriptSinhala
  fun code(): String val => "Sinhala"
  fun string(): String iso^ => "Sinhala".clone()

primitive ScriptSogdian
  fun code(): String val => "Sogdian"
  fun string(): String iso^ => "Sogdian".clone()

primitive ScriptSoraSompeng
  fun code(): String val => "Sora_Sompeng"
  fun string(): String iso^ => "Sora_Sompeng".clone()

primitive ScriptSoyombo
  fun code(): String val => "Soyombo"
  fun string(): String iso^ => "Soyombo".clone()

primitive ScriptSundanese
  fun code(): String val => "Sundanese"
  fun string(): String iso^ => "Sundanese".clone()

primitive ScriptSylotiNagri
  fun code(): String val => "Syloti_Nagri"
  fun string(): String iso^ => "Syloti_Nagri".clone()

primitive ScriptSyriac
  fun code(): String val => "Syriac"
  fun string(): String iso^ => "Syriac".clone()

primitive ScriptTagalog
  fun code(): String val => "Tagalog"
  fun string(): String iso^ => "Tagalog".clone()

primitive ScriptTagbanwa
  fun code(): String val => "Tagbanwa"
  fun string(): String iso^ => "Tagbanwa".clone()

primitive ScriptTaiLe
  fun code(): String val => "Tai_Le"
  fun string(): String iso^ => "Tai_Le".clone()

primitive ScriptTaiTham
  fun code(): String val => "Tai_Tham"
  fun string(): String iso^ => "Tai_Tham".clone()

primitive ScriptTaiViet
  fun code(): String val => "Tai_Viet"
  fun string(): String iso^ => "Tai_Viet".clone()

primitive ScriptTakri
  fun code(): String val => "Takri"
  fun string(): String iso^ => "Takri".clone()

primitive ScriptTamil
  fun code(): String val => "Tamil"
  fun string(): String iso^ => "Tamil".clone()

primitive ScriptTangsa
  fun code(): String val => "Tangsa"
  fun string(): String iso^ => "Tangsa".clone()

primitive ScriptTangut
  fun code(): String val => "Tangut"
  fun string(): String iso^ => "Tangut".clone()

primitive ScriptTelugu
  fun code(): String val => "Telugu"
  fun string(): String iso^ => "Telugu".clone()

primitive ScriptThaana
  fun code(): String val => "Thaana"
  fun string(): String iso^ => "Thaana".clone()

primitive ScriptThai
  fun code(): String val => "Thai"
  fun string(): String iso^ => "Thai".clone()

primitive ScriptTibetan
  fun code(): String val => "Tibetan"
  fun string(): String iso^ => "Tibetan".clone()

primitive ScriptTifinagh
  fun code(): String val => "Tifinagh"
  fun string(): String iso^ => "Tifinagh".clone()

primitive ScriptTirhuta
  fun code(): String val => "Tirhuta"
  fun string(): String iso^ => "Tirhuta".clone()

primitive ScriptToto
  fun code(): String val => "Toto"
  fun string(): String iso^ => "Toto".clone()

primitive ScriptUgaritic
  fun code(): String val => "Ugaritic"
  fun string(): String iso^ => "Ugaritic".clone()

primitive ScriptVai
  fun code(): String val => "Vai"
  fun string(): String iso^ => "Vai".clone()

primitive ScriptVithkuqi
  fun code(): String val => "Vithkuqi"
  fun string(): String iso^ => "Vithkuqi".clone()

primitive ScriptWancho
  fun code(): String val => "Wancho"
  fun string(): String iso^ => "Wancho".clone()

primitive ScriptWarangCiti
  fun code(): String val => "Warang_Citi"
  fun string(): String iso^ => "Warang_Citi".clone()

primitive ScriptYezidi
  fun code(): String val => "Yezidi"
  fun string(): String iso^ => "Yezidi".clone()

primitive ScriptYi
  fun code(): String val => "Yi"
  fun string(): String iso^ => "Yi".clone()

primitive ScriptZanabazarSquare
  fun code(): String val => "Zanabazar_Square"
  fun string(): String iso^ => "Zanabazar_Square".clone()

type Script is
  ( ScriptUnknown
  | ScriptAdlam
  | ScriptAhom
  | ScriptAnatolianHieroglyphs
  | ScriptArabic
  | ScriptArmenian
  | ScriptAvestan
  | ScriptBalinese
  | ScriptBamum
  | ScriptBassaVah
  | ScriptBatak
  | ScriptBengali
  | ScriptBhaiksuki
  | ScriptBopomofo
  | ScriptBrahmi
  | ScriptBraille
  | ScriptBuginese
  | ScriptBuhid
  | ScriptCanadianAboriginal
  | ScriptCarian
  | ScriptCaucasianAlbanian
  | ScriptChakma
  | ScriptCham
  | ScriptCherokee
  | ScriptChorasmian
  | ScriptCommon
  | ScriptCoptic
  | ScriptCuneiform
  | ScriptCypriot
  | ScriptCyproMinoan
  | ScriptCyrillic
  | ScriptDeseret
  | ScriptDevanagari
  | ScriptDivesAkuru
  | ScriptDogra
  | ScriptDuployan
  | ScriptEgyptianHieroglyphs
  | ScriptElbasan
  | ScriptElymaic
  | ScriptEthiopic
  | ScriptGeorgian
  | ScriptGlagolitic
  | ScriptGothic
  | ScriptGrantha
  | ScriptGreek
  | ScriptGujarati
  | ScriptGunjalaGondi
  | ScriptGurmukhi
  | ScriptHan
  | ScriptHangul
  | ScriptHanifiRohingya
  | ScriptHanunoo
  | ScriptHatran
  | ScriptHebrew
  | ScriptHiragana
  | ScriptImperialAramaic
  | ScriptInherited
  | ScriptInscriptionalPahlavi
  | ScriptInscriptionalParthian
  | ScriptJavanese
  | ScriptKaithi
  | ScriptKannada
  | ScriptKatakana
  | ScriptKayahLi
  | ScriptKharoshthi
  | ScriptKhitanSmallScript
  | ScriptKhmer
  | ScriptKhojki
  | ScriptKhudawadi
  | ScriptLao
  | ScriptLatin
  | ScriptLepcha
  | ScriptLimbu
  | ScriptLinearA
  | ScriptLinearB
  | ScriptLisu
  | ScriptLycian
  | ScriptLydian
  | ScriptMahajani
  | ScriptMakasar
  | ScriptMalayalam
  | ScriptMandaic
  | ScriptManichaean
  | ScriptMarchen
  | ScriptMasaramGondi
  | ScriptMedefaidrin
  | ScriptMeeteiMayek
  | ScriptMendeKikakui
  | ScriptMeroiticCursive
  | ScriptMeroiticHieroglyphs
  | ScriptMiao
  | ScriptModi
  | ScriptMongolian
  | ScriptMro
  | ScriptMultani
  | ScriptMyanmar
  | ScriptNabataean
  | ScriptNandinagari
  | ScriptNewTaiLue
  | ScriptNewa
  | ScriptNko
  | ScriptNushu
  | ScriptNyiakengPuachueHmong
  | ScriptOgham
  | ScriptOlChiki
  | ScriptOldHungarian
  | ScriptOldItalic
  | ScriptOldNorthArabian
  | ScriptOldPermic
  | ScriptOldPersian
  | ScriptOldSogdian
  | ScriptOldSouthArabian
  | ScriptOldTurkic
  | ScriptOldUyghur
  | ScriptOriya
  | ScriptOsage
  | ScriptOsmanya
  | ScriptPahawhHmong
  | ScriptPalmyrene
  | ScriptPauCinHau
  | ScriptPhagsPa
  | ScriptPhoenician
  | ScriptPsalterPahlavi
  | ScriptRejang
  | ScriptRunic
  | ScriptSamaritan
  | ScriptSaurashtra
  | ScriptSharada
  | ScriptShavian
  | ScriptSiddham
  | ScriptSignWriting
  | ScriptSinhala
  | ScriptSogdian
  | ScriptSoraSompeng
  | ScriptSoyombo
  | ScriptSundanese
  | ScriptSylotiNagri
  | ScriptSyriac
  | ScriptTagalog
  | ScriptTagbanwa
  | ScriptTaiLe
  | ScriptTaiTham
  | ScriptTaiViet
  | ScriptTakri
  | ScriptTamil
  | ScriptTangsa
  | ScriptTangut
  | ScriptTelugu
  | ScriptThaana
  | ScriptThai
  | ScriptTibetan
  | ScriptTifinagh
  | ScriptTirhuta
  | ScriptToto
  | ScriptUgaritic
  | ScriptVai
  | ScriptVithkuqi
  | ScriptWancho
  | ScriptWarangCiti
  | ScriptYezidi
  | ScriptYi
  | ScriptZanabazarSquare
  )

primitive Scripts
  fun from_iso(s: String box): (Script | None) =>
    match s
    | "Unknown" => ScriptUnknown
    | "Adlam" => ScriptAdlam
    | "Ahom" => ScriptAhom
    | "Anatolian_Hieroglyphs" => ScriptAnatolianHieroglyphs
    | "Arabic" => ScriptArabic
    | "Armenian" => ScriptArmenian
    | "Avestan" => ScriptAvestan
    | "Balinese" => ScriptBalinese
    | "Bamum" => ScriptBamum
    | "Bassa_Vah" => ScriptBassaVah
    | "Batak" => ScriptBatak
    | "Bengali" => ScriptBengali
    | "Bhaiksuki" => ScriptBhaiksuki
    | "Bopomofo" => ScriptBopomofo
    | "Brahmi" => ScriptBrahmi
    | "Braille" => ScriptBraille
    | "Buginese" => ScriptBuginese
    | "Buhid" => ScriptBuhid
    | "Canadian_Aboriginal" => ScriptCanadianAboriginal
    | "Carian" => ScriptCarian
    | "Caucasian_Albanian" => ScriptCaucasianAlbanian
    | "Chakma" => ScriptChakma
    | "Cham" => ScriptCham
    | "Cherokee" => ScriptCherokee
    | "Chorasmian" => ScriptChorasmian
    | "Common" => ScriptCommon
    | "Coptic" => ScriptCoptic
    | "Cuneiform" => ScriptCuneiform
    | "Cypriot" => ScriptCypriot
    | "Cypro_Minoan" => ScriptCyproMinoan
    | "Cyrillic" => ScriptCyrillic
    | "Deseret" => ScriptDeseret
    | "Devanagari" => ScriptDevanagari
    | "Dives_Akuru" => ScriptDivesAkuru
    | "Dogra" => ScriptDogra
    | "Duployan" => ScriptDuployan
    | "Egyptian_Hieroglyphs" => ScriptEgyptianHieroglyphs
    | "Elbasan" => ScriptElbasan
    | "Elymaic" => ScriptElymaic
    | "Ethiopic" => ScriptEthiopic
    | "Georgian" => ScriptGeorgian
    | "Glagolitic" => ScriptGlagolitic
    | "Gothic" => ScriptGothic
    | "Grantha" => ScriptGrantha
    | "Greek" => ScriptGreek
    | "Gujarati" => ScriptGujarati
    | "Gunjala_Gondi" => ScriptGunjalaGondi
    | "Gurmukhi" => ScriptGurmukhi
    | "Han" => ScriptHan
    | "Hangul" => ScriptHangul
    | "Hanifi_Rohingya" => ScriptHanifiRohingya
    | "Hanunoo" => ScriptHanunoo
    | "Hatran" => ScriptHatran
    | "Hebrew" => ScriptHebrew
    | "Hiragana" => ScriptHiragana
    | "Imperial_Aramaic" => ScriptImperialAramaic
    | "Inherited" => ScriptInherited
    | "Inscriptional_Pahlavi" => ScriptInscriptionalPahlavi
    | "Inscriptional_Parthian" => ScriptInscriptionalParthian
    | "Javanese" => ScriptJavanese
    | "Kaithi" => ScriptKaithi
    | "Kannada" => ScriptKannada
    | "Katakana" => ScriptKatakana
    | "Kayah_Li" => ScriptKayahLi
    | "Kharoshthi" => ScriptKharoshthi
    | "Khitan_Small_Script" => ScriptKhitanSmallScript
    | "Khmer" => ScriptKhmer
    | "Khojki" => ScriptKhojki
    | "Khudawadi" => ScriptKhudawadi
    | "Lao" => ScriptLao
    | "Latin" => ScriptLatin
    | "Lepcha" => ScriptLepcha
    | "Limbu" => ScriptLimbu
    | "Linear_A" => ScriptLinearA
    | "Linear_B" => ScriptLinearB
    | "Lisu" => ScriptLisu
    | "Lycian" => ScriptLycian
    | "Lydian" => ScriptLydian
    | "Mahajani" => ScriptMahajani
    | "Makasar" => ScriptMakasar
    | "Malayalam" => ScriptMalayalam
    | "Mandaic" => ScriptMandaic
    | "Manichaean" => ScriptManichaean
    | "Marchen" => ScriptMarchen
    | "Masaram_Gondi" => ScriptMasaramGondi
    | "Medefaidrin" => ScriptMedefaidrin
    | "Meetei_Mayek" => ScriptMeeteiMayek
    | "Mende_Kikakui" => ScriptMendeKikakui
    | "Meroitic_Cursive" => ScriptMeroiticCursive
    | "Meroitic_Hieroglyphs" => ScriptMeroiticHieroglyphs
    | "Miao" => ScriptMiao
    | "Modi" => ScriptModi
    | "Mongolian" => ScriptMongolian
    | "Mro" => ScriptMro
    | "Multani" => ScriptMultani
    | "Myanmar" => ScriptMyanmar
    | "Nabataean" => ScriptNabataean
    | "Nandinagari" => ScriptNandinagari
    | "New_Tai_Lue" => ScriptNewTaiLue
    | "Newa" => ScriptNewa
    | "Nko" => ScriptNko
    | "Nushu" => ScriptNushu
    | "Nyiakeng_Puachue_Hmong" => ScriptNyiakengPuachueHmong
    | "Ogham" => ScriptOgham
    | "Ol_Chiki" => ScriptOlChiki
    | "Old_Hungarian" => ScriptOldHungarian
    | "Old_Italic" => ScriptOldItalic
    | "Old_North_Arabian" => ScriptOldNorthArabian
    | "Old_Permic" => ScriptOldPermic
    | "Old_Persian" => ScriptOldPersian
    | "Old_Sogdian" => ScriptOldSogdian
    | "Old_South_Arabian" => ScriptOldSouthArabian
    | "Old_Turkic" => ScriptOldTurkic
    | "Old_Uyghur" => ScriptOldUyghur
    | "Oriya" => ScriptOriya
    | "Osage" => ScriptOsage
    | "Osmanya" => ScriptOsmanya
    | "Pahawh_Hmong" => ScriptPahawhHmong
    | "Palmyrene" => ScriptPalmyrene
    | "Pau_Cin_Hau" => ScriptPauCinHau
    | "Phags_Pa" => ScriptPhagsPa
    | "Phoenician" => ScriptPhoenician
    | "Psalter_Pahlavi" => ScriptPsalterPahlavi
    | "Rejang" => ScriptRejang
    | "Runic" => ScriptRunic
    | "Samaritan" => ScriptSamaritan
    | "Saurashtra" => ScriptSaurashtra
    | "Sharada" => ScriptSharada
    | "Shavian" => ScriptShavian
    | "Siddham" => ScriptSiddham
    | "SignWriting" => ScriptSignWriting
    | "Sinhala" => ScriptSinhala
    | "Sogdian" => ScriptSogdian
    | "Sora_Sompeng" => ScriptSoraSompeng
    | "Soyombo" => ScriptSoyombo
    | "Sundanese" => ScriptSundanese
    | "Syloti_Nagri" => ScriptSylotiNagri
    | "Syriac" => ScriptSyriac
    | "Tagalog" => ScriptTagalog
    | "Tagbanwa" => ScriptTagbanwa
    | "Tai_Le" => ScriptTaiLe
    | "Tai_Tham" => ScriptTaiTham
    | "Tai_Viet" => ScriptTaiViet
    | "Takri" => ScriptTakri
    | "Tamil" => ScriptTamil
    | "Tangsa" => ScriptTangsa
    | "Tangut" => ScriptTangut
    | "Telugu" => ScriptTelugu
    | "Thaana" => ScriptThaana
    | "Thai" => ScriptThai
    | "Tibetan" => ScriptTibetan
    | "Tifinagh" => ScriptTifinagh
    | "Tirhuta" => ScriptTirhuta
    | "Toto" => ScriptToto
    | "Ugaritic" => ScriptUgaritic
    | "Vai" => ScriptVai
    | "Vithkuqi" => ScriptVithkuqi
    | "Wancho" => ScriptWancho
    | "Warang_Citi" => ScriptWarangCiti
    | "Yezidi" => ScriptYezidi
    | "Yi" => ScriptYi
    | "Zanabazar_Square" => ScriptZanabazarSquare
    else None
    end

  fun _to_byte(sc: Script): U8 =>
    match sc
    | ScriptUnknown => 0
    | ScriptAdlam => 1
    | ScriptAhom => 2
    | ScriptAnatolianHieroglyphs => 3
    | ScriptArabic => 4
    | ScriptArmenian => 5
    | ScriptAvestan => 6
    | ScriptBalinese => 7
    | ScriptBamum => 8
    | ScriptBassaVah => 9
    | ScriptBatak => 10
    | ScriptBengali => 11
    | ScriptBhaiksuki => 12
    | ScriptBopomofo => 13
    | ScriptBrahmi => 14
    | ScriptBraille => 15
    | ScriptBuginese => 16
    | ScriptBuhid => 17
    | ScriptCanadianAboriginal => 18
    | ScriptCarian => 19
    | ScriptCaucasianAlbanian => 20
    | ScriptChakma => 21
    | ScriptCham => 22
    | ScriptCherokee => 23
    | ScriptChorasmian => 24
    | ScriptCommon => 25
    | ScriptCoptic => 26
    | ScriptCuneiform => 27
    | ScriptCypriot => 28
    | ScriptCyproMinoan => 29
    | ScriptCyrillic => 30
    | ScriptDeseret => 31
    | ScriptDevanagari => 32
    | ScriptDivesAkuru => 33
    | ScriptDogra => 34
    | ScriptDuployan => 35
    | ScriptEgyptianHieroglyphs => 36
    | ScriptElbasan => 37
    | ScriptElymaic => 38
    | ScriptEthiopic => 39
    | ScriptGeorgian => 40
    | ScriptGlagolitic => 41
    | ScriptGothic => 42
    | ScriptGrantha => 43
    | ScriptGreek => 44
    | ScriptGujarati => 45
    | ScriptGunjalaGondi => 46
    | ScriptGurmukhi => 47
    | ScriptHan => 48
    | ScriptHangul => 49
    | ScriptHanifiRohingya => 50
    | ScriptHanunoo => 51
    | ScriptHatran => 52
    | ScriptHebrew => 53
    | ScriptHiragana => 54
    | ScriptImperialAramaic => 55
    | ScriptInherited => 56
    | ScriptInscriptionalPahlavi => 57
    | ScriptInscriptionalParthian => 58
    | ScriptJavanese => 59
    | ScriptKaithi => 60
    | ScriptKannada => 61
    | ScriptKatakana => 62
    | ScriptKayahLi => 63
    | ScriptKharoshthi => 64
    | ScriptKhitanSmallScript => 65
    | ScriptKhmer => 66
    | ScriptKhojki => 67
    | ScriptKhudawadi => 68
    | ScriptLao => 69
    | ScriptLatin => 70
    | ScriptLepcha => 71
    | ScriptLimbu => 72
    | ScriptLinearA => 73
    | ScriptLinearB => 74
    | ScriptLisu => 75
    | ScriptLycian => 76
    | ScriptLydian => 77
    | ScriptMahajani => 78
    | ScriptMakasar => 79
    | ScriptMalayalam => 80
    | ScriptMandaic => 81
    | ScriptManichaean => 82
    | ScriptMarchen => 83
    | ScriptMasaramGondi => 84
    | ScriptMedefaidrin => 85
    | ScriptMeeteiMayek => 86
    | ScriptMendeKikakui => 87
    | ScriptMeroiticCursive => 88
    | ScriptMeroiticHieroglyphs => 89
    | ScriptMiao => 90
    | ScriptModi => 91
    | ScriptMongolian => 92
    | ScriptMro => 93
    | ScriptMultani => 94
    | ScriptMyanmar => 95
    | ScriptNabataean => 96
    | ScriptNandinagari => 97
    | ScriptNewTaiLue => 98
    | ScriptNewa => 99
    | ScriptNko => 100
    | ScriptNushu => 101
    | ScriptNyiakengPuachueHmong => 102
    | ScriptOgham => 103
    | ScriptOlChiki => 104
    | ScriptOldHungarian => 105
    | ScriptOldItalic => 106
    | ScriptOldNorthArabian => 107
    | ScriptOldPermic => 108
    | ScriptOldPersian => 109
    | ScriptOldSogdian => 110
    | ScriptOldSouthArabian => 111
    | ScriptOldTurkic => 112
    | ScriptOldUyghur => 113
    | ScriptOriya => 114
    | ScriptOsage => 115
    | ScriptOsmanya => 116
    | ScriptPahawhHmong => 117
    | ScriptPalmyrene => 118
    | ScriptPauCinHau => 119
    | ScriptPhagsPa => 120
    | ScriptPhoenician => 121
    | ScriptPsalterPahlavi => 122
    | ScriptRejang => 123
    | ScriptRunic => 124
    | ScriptSamaritan => 125
    | ScriptSaurashtra => 126
    | ScriptSharada => 127
    | ScriptShavian => 128
    | ScriptSiddham => 129
    | ScriptSignWriting => 130
    | ScriptSinhala => 131
    | ScriptSogdian => 132
    | ScriptSoraSompeng => 133
    | ScriptSoyombo => 134
    | ScriptSundanese => 135
    | ScriptSylotiNagri => 136
    | ScriptSyriac => 137
    | ScriptTagalog => 138
    | ScriptTagbanwa => 139
    | ScriptTaiLe => 140
    | ScriptTaiTham => 141
    | ScriptTaiViet => 142
    | ScriptTakri => 143
    | ScriptTamil => 144
    | ScriptTangsa => 145
    | ScriptTangut => 146
    | ScriptTelugu => 147
    | ScriptThaana => 148
    | ScriptThai => 149
    | ScriptTibetan => 150
    | ScriptTifinagh => 151
    | ScriptTirhuta => 152
    | ScriptToto => 153
    | ScriptUgaritic => 154
    | ScriptVai => 155
    | ScriptVithkuqi => 156
    | ScriptWancho => 157
    | ScriptWarangCiti => 158
    | ScriptYezidi => 159
    | ScriptYi => 160
    | ScriptZanabazarSquare => 161
    end

  fun _from_byte(b: U8): Script =>
    match b
    | 0 => ScriptUnknown
    | 1 => ScriptAdlam
    | 2 => ScriptAhom
    | 3 => ScriptAnatolianHieroglyphs
    | 4 => ScriptArabic
    | 5 => ScriptArmenian
    | 6 => ScriptAvestan
    | 7 => ScriptBalinese
    | 8 => ScriptBamum
    | 9 => ScriptBassaVah
    | 10 => ScriptBatak
    | 11 => ScriptBengali
    | 12 => ScriptBhaiksuki
    | 13 => ScriptBopomofo
    | 14 => ScriptBrahmi
    | 15 => ScriptBraille
    | 16 => ScriptBuginese
    | 17 => ScriptBuhid
    | 18 => ScriptCanadianAboriginal
    | 19 => ScriptCarian
    | 20 => ScriptCaucasianAlbanian
    | 21 => ScriptChakma
    | 22 => ScriptCham
    | 23 => ScriptCherokee
    | 24 => ScriptChorasmian
    | 25 => ScriptCommon
    | 26 => ScriptCoptic
    | 27 => ScriptCuneiform
    | 28 => ScriptCypriot
    | 29 => ScriptCyproMinoan
    | 30 => ScriptCyrillic
    | 31 => ScriptDeseret
    | 32 => ScriptDevanagari
    | 33 => ScriptDivesAkuru
    | 34 => ScriptDogra
    | 35 => ScriptDuployan
    | 36 => ScriptEgyptianHieroglyphs
    | 37 => ScriptElbasan
    | 38 => ScriptElymaic
    | 39 => ScriptEthiopic
    | 40 => ScriptGeorgian
    | 41 => ScriptGlagolitic
    | 42 => ScriptGothic
    | 43 => ScriptGrantha
    | 44 => ScriptGreek
    | 45 => ScriptGujarati
    | 46 => ScriptGunjalaGondi
    | 47 => ScriptGurmukhi
    | 48 => ScriptHan
    | 49 => ScriptHangul
    | 50 => ScriptHanifiRohingya
    | 51 => ScriptHanunoo
    | 52 => ScriptHatran
    | 53 => ScriptHebrew
    | 54 => ScriptHiragana
    | 55 => ScriptImperialAramaic
    | 56 => ScriptInherited
    | 57 => ScriptInscriptionalPahlavi
    | 58 => ScriptInscriptionalParthian
    | 59 => ScriptJavanese
    | 60 => ScriptKaithi
    | 61 => ScriptKannada
    | 62 => ScriptKatakana
    | 63 => ScriptKayahLi
    | 64 => ScriptKharoshthi
    | 65 => ScriptKhitanSmallScript
    | 66 => ScriptKhmer
    | 67 => ScriptKhojki
    | 68 => ScriptKhudawadi
    | 69 => ScriptLao
    | 70 => ScriptLatin
    | 71 => ScriptLepcha
    | 72 => ScriptLimbu
    | 73 => ScriptLinearA
    | 74 => ScriptLinearB
    | 75 => ScriptLisu
    | 76 => ScriptLycian
    | 77 => ScriptLydian
    | 78 => ScriptMahajani
    | 79 => ScriptMakasar
    | 80 => ScriptMalayalam
    | 81 => ScriptMandaic
    | 82 => ScriptManichaean
    | 83 => ScriptMarchen
    | 84 => ScriptMasaramGondi
    | 85 => ScriptMedefaidrin
    | 86 => ScriptMeeteiMayek
    | 87 => ScriptMendeKikakui
    | 88 => ScriptMeroiticCursive
    | 89 => ScriptMeroiticHieroglyphs
    | 90 => ScriptMiao
    | 91 => ScriptModi
    | 92 => ScriptMongolian
    | 93 => ScriptMro
    | 94 => ScriptMultani
    | 95 => ScriptMyanmar
    | 96 => ScriptNabataean
    | 97 => ScriptNandinagari
    | 98 => ScriptNewTaiLue
    | 99 => ScriptNewa
    | 100 => ScriptNko
    | 101 => ScriptNushu
    | 102 => ScriptNyiakengPuachueHmong
    | 103 => ScriptOgham
    | 104 => ScriptOlChiki
    | 105 => ScriptOldHungarian
    | 106 => ScriptOldItalic
    | 107 => ScriptOldNorthArabian
    | 108 => ScriptOldPermic
    | 109 => ScriptOldPersian
    | 110 => ScriptOldSogdian
    | 111 => ScriptOldSouthArabian
    | 112 => ScriptOldTurkic
    | 113 => ScriptOldUyghur
    | 114 => ScriptOriya
    | 115 => ScriptOsage
    | 116 => ScriptOsmanya
    | 117 => ScriptPahawhHmong
    | 118 => ScriptPalmyrene
    | 119 => ScriptPauCinHau
    | 120 => ScriptPhagsPa
    | 121 => ScriptPhoenician
    | 122 => ScriptPsalterPahlavi
    | 123 => ScriptRejang
    | 124 => ScriptRunic
    | 125 => ScriptSamaritan
    | 126 => ScriptSaurashtra
    | 127 => ScriptSharada
    | 128 => ScriptShavian
    | 129 => ScriptSiddham
    | 130 => ScriptSignWriting
    | 131 => ScriptSinhala
    | 132 => ScriptSogdian
    | 133 => ScriptSoraSompeng
    | 134 => ScriptSoyombo
    | 135 => ScriptSundanese
    | 136 => ScriptSylotiNagri
    | 137 => ScriptSyriac
    | 138 => ScriptTagalog
    | 139 => ScriptTagbanwa
    | 140 => ScriptTaiLe
    | 141 => ScriptTaiTham
    | 142 => ScriptTaiViet
    | 143 => ScriptTakri
    | 144 => ScriptTamil
    | 145 => ScriptTangsa
    | 146 => ScriptTangut
    | 147 => ScriptTelugu
    | 148 => ScriptThaana
    | 149 => ScriptThai
    | 150 => ScriptTibetan
    | 151 => ScriptTifinagh
    | 152 => ScriptTirhuta
    | 153 => ScriptToto
    | 154 => ScriptUgaritic
    | 155 => ScriptVai
    | 156 => ScriptVithkuqi
    | 157 => ScriptWancho
    | 158 => ScriptWarangCiti
    | 159 => ScriptYezidi
    | 160 => ScriptYi
    | 161 => ScriptZanabazarSquare
    else ScriptUnknown
    end
